// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'backButton': string;
  'description': string;
  'header': string;
  'inlineContainer': string;
  'provisionFPouter': string;
  'textarea': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
