@{
NestedModules =  'Core/PnP.PowerShell.dll'
ModuleVersion = '3.2.0'
Description = 'Microsoft 365 Patterns and Practices PowerShell Cmdlets'
GUID = '0b0430ce-d799-4f3b-a565-f0dca1f31e17'
Author = 'Microsoft 365 Patterns and Practices'
CompanyName = 'Microsoft 365 Patterns and Practices'
PowerShellVersion = '7.4.0'
ProcessorArchitecture = 'None'
FunctionsToExport = '*'
CmdletsToExport = @("Add-PnPAdaptiveScopeProperty","Add-PnPAzureADGroupMember","Add-PnPAzureADGroupOwner","Add-PnPAzureADServicePrincipalAppRole","Add-PnPAzureADServicePrincipalAppRoleAssignment","Add-PnPPropertyBagValue","Add-PnPSiteClassification","Clear-PnPAzureADGroupMember","Clear-PnPAzureADGroupOwner","Enable-PnPPriviledgedIdentityManagement","Get-PnPAzureADActivityReportDirectoryAudit","Get-PnPAzureADActivityReportSignIn","Get-PnPAzureADApp","Get-PnPAzureADAppPermission","Get-PnPAzureADAppSitePermission","Get-PnPAzureADGroup","Get-PnPAzureADGroupMember","Get-PnPAzureADGroupOwner","Get-PnPAzureADServicePrincipal","Get-PnPAzureADServicePrincipalAppRoleAssignment","Get-PnPAzureADServicePrincipalAssignedAppRole","Get-PnPAzureADServicePrincipalAvailableAppRole","Get-PnPAzureADUser","Get-PnPClientSidePage","Get-PnPMicrosoft365GroupMembers","Get-PnPMicrosoft365GroupOwners","Get-PnPPriviledgedIdentityManagementEligibleAssignment","Get-PnPPriviledgedIdentityManagementRole","Get-PnPSiteClassification","Get-PnPWebhookSubscriptions","Grant-PnPAzureADAppSitePermission","Invoke-PnPSearchQuery","Move-PnPClientSideComponent","New-PnPAzureADGroup","New-PnPAzureADUserTemporaryAccessPass","Register-PnPAzureADApp","Remove-PnPAzureADApp","Remove-PnPAzureADGroup","Remove-PnPAzureADGroupMember","Remove-PnPAzureADGroupOwner","Remove-PnPAzureADServicePrincipalAppRoleAssignment","Remove-PnPAzureADServicePrincipalAssignedAppRole","Remove-PnPAzureADUser","Remove-PnPClientSidePage","Revoke-PnPAzureADAppSitePermission","Set-PnPAzureADAppSitePermission","Set-PnPAzureADGroup","Set-PnPClientSidePage","Update-PnPVivaConnectionsDashboardACE","Update-SiteClassification","Add-PnPAlert","Add-PnPApp","Add-PnPApplicationCustomizer","Add-PnPAvailableSiteClassification","Add-PnPBrandCenterFont","Add-PnPBrandCenterFontPackage","Add-PnPContentType","Add-PnPContentTypesFromContentTypeHub","Add-PnPContentTypeToDocumentSet","Add-PnPContentTypeToList","Add-PnPCustomAction","Add-PnPDataRowsToSiteTemplate","Add-PnPDocumentSet","Add-PnPEntraIDGroupMember","Add-PnPEntraIDGroupOwner","Add-PnPEntraIDServicePrincipalAppRole","Add-PnPEntraIDServicePrincipalAppRoleAssignment","Add-PnPEventReceiver","Add-PnPField","Add-PnPFieldFromXml","Add-PnPFieldToContentType","Add-PnPFile","Add-PnPFileAnonymousSharingLink","Add-PnPFileOrganizationalSharingLink","Add-PnPFileSensitivityLabel","Add-PnPFileSharingInvite","Add-PnPFileToSiteTemplate","Add-PnPFileUserSharingLink","Add-PnPFlowOwner","Add-PnPFolder","Add-PnPFolderAnonymousSharingLink","Add-PnPFolderOrganizationalSharingLink","Add-PnPFolderSharingInvite","Add-PnPFolderUserSharingLink","Add-PnPGroupMember","Add-PnPHomeSite","Add-PnPHtmlPublishingPageLayout","Add-PnPHubSiteAssociation","Add-PnPHubToHubAssociation","Add-PnPIndexedProperty","Add-PnPJavaScriptBlock","Add-PnPJavaScriptLink","Add-PnPListDesign","Add-PnPListFoldersToSiteTemplate","Add-PnPListItem","Add-PnPListItemAttachment","Add-PnPListItemComment","Add-PnPMasterPage","Add-PnPMicrosoft365GroupMember","Add-PnPMicrosoft365GroupOwner","Add-PnPMicrosoft365GroupToSite","Add-PnPNavigationNode","Add-PnPOrgAssetsLibrary","Add-PnPOrgNewsSite","Add-PnPPage","Add-PnPPageImageWebPart","Add-PnPPageSection","Add-PnPPageTextPart","Add-PnPPageWebPart","Add-PnPPlannerBucket","Add-PnPPlannerRoster","Add-PnPPlannerRosterMember","Add-PnPPlannerTask","Add-PnPPublishingImageRendition","Add-PnPPublishingPage","Add-PnPPublishingPageLayout","Add-PnPRoleDefinition","Add-PnPSiteCollectionAdmin","Add-PnPSiteCollectionAppCatalog","Add-PnPSiteDesign","Add-PnPSiteDesignFromWeb","Add-PnPSiteDesignTask","Add-PnPSiteScript","Add-PnPSiteScriptPackage","Add-PnPSiteTemplate","Add-PnPStoredCredential","Add-PnPTaxonomyField","Add-PnPTeamsChannel","Add-PnPTeamsChannelUser","Add-PnPTeamsTab","Add-PnPTeamsTeam","Add-PnPTeamsUser","Add-PnPTenantCdnOrigin","Add-PnPTenantRestrictedSearchAllowedList","Add-PnPTenantSequence","Add-PnPTenantSequenceSite","Add-PnPTenantSequenceSubSite","Add-PnPTenantTheme","Add-PnPTermToTerm","Add-PnPView","Add-PnPViewsFromXML","Add-PnPVivaConnectionsDashboardACE","Add-PnPWebhookSubscription","Add-PnPWebPartToWebPartPage","Add-PnPWebPartToWikiPage","Add-PnPWikiPage","Approve-PnPTenantServicePrincipalPermissionRequest","Clear-PnPDefaultColumnValues","Clear-PnPEntraIDGroupMember","Clear-PnPEntraIDGroupOwner","Clear-PnPListItemAsRecord","Clear-PnPMicrosoft365GroupMember","Clear-PnPMicrosoft365GroupOwner","Clear-PnPRecycleBinItem","Clear-PnPTenantAppCatalogUrl","Clear-PnPTenantRecycleBinItem","Clear-PnPTraceLog","Connect-PnPOnline","Convert-PnPFile","Convert-PnPFolderToSiteTemplate","Convert-PnPSiteTemplate","Convert-PnPSiteTemplateToMarkdown","ConvertTo-PnPPage","Copy-PnPFile","Copy-PnPFileMetadata","Copy-PnPFolder","Copy-PnPItemProxy","Copy-PnPList","Copy-PnPPage","Copy-PnPTeamsTeam","Deny-PnPTenantServicePrincipalPermissionRequest","Disable-PnPFeature","Disable-PnPFlow","Disable-PnPPageScheduling","Disable-PnPPowerShellTelemetry","Disable-PnPSharingForNonOwnersOfSite","Disable-PnPSiteClassification","Disable-PnPTenantServicePrincipal","Disconnect-PnPOnline","Enable-PnPCommSite","Enable-PnPFeature","Enable-PnPFlow","Enable-PnPPageScheduling","Enable-PnPPowerShellTelemetry","Enable-PnPPrivilegedIdentityManagement","Enable-PnPSiteClassification","Enable-PnPTenantServicePrincipal","Export-PnPFlow","Export-PnPListToSiteTemplate","Export-PnPPage","Export-PnPPageMapping","Export-PnPPowerApp","Export-PnPTaxonomy","Export-PnPTermGroupToXml","Export-PnPUserInfo","Export-PnPUserProfile","Find-PnPFile","Format-PnPTraceLog","Get-PnPAccessToken","Get-PnPAlert","Get-PnPApp","Get-PnPAppErrors","Get-PnPAppInfo","Get-PnPApplicationCustomizer","Get-PnPAuditing","Get-PnPAuthenticationRealm","Get-PnPAvailableLanguage","Get-PnPAvailablePageComponents","Get-PnPAvailableSensitivityLabel","Get-PnPAvailableSiteClassification","Get-PnPAzureACSPrincipal","Get-PnPAzureCertificate","Get-PnPBrandCenterConfig","Get-PnPBrandCenterFont","Get-PnPBrandCenterFontPackage","Get-PnPBrowserIdleSignout","Get-PnPBuiltInDesignPackageVisibility","Get-PnPBuiltInSiteTemplateSettings","Get-PnPChangeLog","Get-PnPCompatibleHubContentTypes","Get-PnPConnection","Get-PnPContainer","Get-PnPContainerType","Get-PnPContainerTypeConfiguration","Get-PnPContentType","Get-PnPContentTypePublishingHubUrl","Get-PnPContentTypePublishingStatus","Get-PnPContext","Get-PnPCopilotAdminLimitedMode","Get-PnPCopilotAgent","Get-PnPCustomAction","Get-PnPDefaultColumnValues","Get-PnPDeletedContainer","Get-PnPDeletedFlow","Get-PnPDeletedMicrosoft365Group","Get-PnPDeletedTeam","Get-PnPDiagnostics","Get-PnPDisableSpacesActivation","Get-PnPDocumentSetTemplate","Get-PnPEnterpriseAppInsightsReport","Get-PnPEntraIDActivityReportDirectoryAudit","Get-PnPEntraIDActivityReportSignIn","Get-PnPEntraIDApp","Get-PnPEntraIDAppPermission","Get-PnPEntraIDAppSitePermission","Get-PnPEntraIDGroup","Get-PnPEntraIDGroupMember","Get-PnPEntraIDGroupOwner","Get-PnPEntraIDServicePrincipal","Get-PnPEntraIDServicePrincipalAppRoleAssignment","Get-PnPEntraIDServicePrincipalAssignedAppRole","Get-PnPEntraIDServicePrincipalAvailableAppRole","Get-PnPEntraIDUser","Get-PnPEventReceiver","Get-PnPException","Get-PnPExternalUser","Get-PnPFeature","Get-PnPField","Get-PnPFile","Get-PnPFileAnalyticsData","Get-PnPFileCheckedOut","Get-PnPFileInFolder","Get-PnPFileRetentionLabel","Get-PnPFileSensitivityLabel","Get-PnPFileSensitivityLabelInfo","Get-PnPFileSharingLink","Get-PnPFileVersion","Get-PnPFlow","Get-PnPFlowOwner","Get-PnPFlowRun","Get-PnPFolder","Get-PnPFolderInFolder","Get-PnPFolderItem","Get-PnPFolderSharingLink","Get-PnPFolderStorageMetric","Get-PnPFooter","Get-PnPGraphSubscription","Get-PnPGroup","Get-PnPGroupMember","Get-PnPGroupPermissions","Get-PnPHideDefaultThemes","Get-PnPHomePage","Get-PnPHomeSite","Get-PnPHubSite","Get-PnPHubSiteChild","Get-PnPIndexedPropertyKeys","Get-PnPInPlaceRecordsManagement","Get-PnPIsSiteAliasAvailable","Get-PnPJavaScriptLink","Get-PnPKnowledgeHubSite","Get-PnPLargeListOperationStatus","Get-PnPLibraryFileVersionBatchDeleteJobStatus","Get-PnPLibraryFileVersionExpirationReportJobStatus","Get-PnPList","Get-PnPListDesign","Get-PnPListInformationRightsManagement","Get-PnPListItem","Get-PnPListItemAttachment","Get-PnPListItemComment","Get-PnPListItemPermission","Get-PnPListItemVersion","Get-PnPListPermissions","Get-PnPListRecordDeclaration","Get-PnPListVersionPolicy","Get-PnPManagedAppId","Get-PnPMasterPage","Get-PnPMessageCenterAnnouncement","Get-PnPMicrosoft365ExpiringGroup","Get-PnPMicrosoft365Group","Get-PnPMicrosoft365GroupEndpoint","Get-PnPMicrosoft365GroupMember","Get-PnPMicrosoft365GroupOwner","Get-PnPMicrosoft365GroupSettings","Get-PnPMicrosoft365GroupSettingTemplates","Get-PnPMicrosoft365GroupTeam","Get-PnPMicrosoft365GroupYammerCommunity","Get-PnPMicrosoft365Roadmap","Get-PnPNavigationNode","Get-PnPOrgAssetsLibrary","Get-PnPOrgNewsSite","Get-PnPPage","Get-PnPPageComponent","Get-PnPPageCopyProgress","Get-PnPPageLikedByInformation","Get-PnPPageSchedulingEnabled","Get-PnPPlannerBucket","Get-PnPPlannerConfiguration","Get-PnPPlannerPlan","Get-PnPPlannerRosterMember","Get-PnPPlannerRosterPlan","Get-PnPPlannerTask","Get-PnPPlannerUserPolicy","Get-PnPPowerApp","Get-PnPPowerAppPermission","Get-PnPPowerPlatformCustomConnector","Get-PnPPowerPlatformEnvironment","Get-PnPPowerPlatformSolution","Get-PnPPowerShellTelemetryEnabled","Get-PnPPrivilegedIdentityManagementEligibleAssignment","Get-PnPPrivilegedIdentityManagementRole","Get-PnPProfileCardProperty","Get-PnPProperty","Get-PnPPropertyBag","Get-PnPPublishingImageRendition","Get-PnPRecycleBinItem","Get-PnPRequestAccessEmails","Get-PnPRetentionLabel","Get-PnPRoleDefinition","Get-PnPSearchConfiguration","Get-PnPSearchCrawlLog","Get-PnPSearchExternalConnection","Get-PnPSearchExternalItem","Get-PnPSearchExternalSchema","Get-PnPSearchResultType","Get-PnPSearchSettings","Get-PnPSearchSiteConnection","Get-PnPSearchVertical","Get-PnPServiceCurrentHealth","Get-PnPServiceHealthIssue","Get-PnPSharePointAddIn","Get-PnPSharingForNonOwnersOfSite","Get-PnPSite","Get-PnPSiteAnalyticsData","Get-PnPSiteClosure","Get-PnPSiteCollectionAdmin","Get-PnPSiteCollectionAppCatalog","Get-PnPSiteCollectionTermStore","Get-PnPSiteDesign","Get-PnPSiteDesignRights","Get-PnPSiteDesignRun","Get-PnPSiteDesignRunStatus","Get-PnPSiteDesignTask","Get-PnPSiteFileVersionBatchDeleteJobStatus","Get-PnPSiteFileVersionExpirationReportJobStatus","Get-PnPSiteGroup","Get-PnPSitePolicy","Get-PnPSiteScript","Get-PnPSiteScriptFromList","Get-PnPSiteScriptFromWeb","Get-PnPSiteSearchQueryResults","Get-PnPSiteSensitivityLabel","Get-PnPSiteTemplate","Get-PnPSiteUserInvitations","Get-PnPSiteVersionPolicy","Get-PnPSiteVersionPolicyStatus","Get-PnPStorageEntity","Get-PnPStoredCredential","Get-PnPStructuralNavigationCacheSiteState","Get-PnPStructuralNavigationCacheWebState","Get-PnPSubWeb","Get-PnPSyntexModel","Get-PnPSyntexModelPublication","Get-PnPTaxonomyItem","Get-PnPTaxonomySession","Get-PnPTeamsApp","Get-PnPTeamsChannel","Get-PnPTeamsChannelFilesFolder","Get-PnPTeamsChannelMessage","Get-PnPTeamsChannelMessageReply","Get-PnPTeamsChannelUser","Get-PnPTeamsPrimaryChannel","Get-PnPTeamsTab","Get-PnPTeamsTag","Get-PnPTeamsTeam","Get-PnPTeamsUser","Get-PnPTemporarilyDisableAppBar","Get-PnPTenant","Get-PnPTenantAppCatalogUrl","Get-PnPTenantCdnEnabled","Get-PnPTenantCdnOrigin","Get-PnPTenantCdnPolicies","Get-PnPTenantDeletedSite","Get-PnPTenantId","Get-PnPTenantInfo","Get-PnPTenantInstance","Get-PnPTenantInternalSetting","Get-PnPTenantPronounsSetting","Get-PnPTenantRecycleBinItem","Get-PnPTenantRestrictedSearchAllowedList","Get-PnPTenantRestrictedSearchMode","Get-PnPTenantRetentionLabel","Get-PnPTenantSequence","Get-PnPTenantSequenceSite","Get-PnPTenantServicePrincipal","Get-PnPTenantServicePrincipalPermissionGrants","Get-PnPTenantServicePrincipalPermissionRequests","Get-PnPTenantSite","Get-PnPTenantSyncClientRestriction","Get-PnPTenantTemplate","Get-PnPTenantTheme","Get-PnPTerm","Get-PnPTermGroup","Get-PnPTermLabel","Get-PnPTermSet","Get-PnPTheme","Get-PnPTimeZoneId","Get-PnPTodoList","Get-PnPTraceLog","Get-PnPUnfurlLink","Get-PnPUnifiedAuditLog","Get-PnPUPABulkImportStatus","Get-PnPUser","Get-PnPUserOneDriveQuota","Get-PnPUserProfilePhoto","Get-PnPUserProfileProperty","Get-PnPView","Get-PnPVivaConnectionsDashboardACE","Get-PnPVivaEngageCommunity","Get-PnPWeb","Get-PnPWebAlert","Get-PnPWebHeader","Get-PnPWebhookSubscription","Get-PnPWebPart","Get-PnPWebPartProperty","Get-PnPWebPartXml","Get-PnPWebPermission","Get-PnPWebTemplates","Get-PnPWikiPageContent","Grant-PnPEntraIDAppSitePermission","Grant-PnPHubSiteRights","Grant-PnPSiteDesignRights","Grant-PnPTenantServicePrincipalPermission","Import-PnPFlow","Import-PnPTaxonomy","Import-PnPTermGroupFromXml","Import-PnPTermSet","Install-PnPApp","Invoke-PnPBatch","Invoke-PnPGraphMethod","Invoke-PnPListDesign","Invoke-PnPQuery","Invoke-PnPSiteDesign","Invoke-PnPSiteScript","Invoke-PnPSiteSwap","Invoke-PnPSiteTemplate","Invoke-PnPSPRestMethod","Invoke-PnPTenantTemplate","Invoke-PnPWebAction","Measure-PnPList","Measure-PnPWeb","Merge-PnPTerm","Move-PnPFile","Move-PnPFolder","Move-PnPItemProxy","Move-PnPListItemToRecycleBin","Move-PnPPage","Move-PnPPageComponent","Move-PnPRecycleBinItem","Move-PnPTerm","Move-PnPTermSet","New-PnPAzureCertificate","New-PnPBatch","New-PnPContainerType","New-PnPEntraIDGroup","New-PnPEntraIDUserTemporaryAccessPass","New-PnPExtensibilityHandlerObject","New-PnPGraphSubscription","New-PnPGroup","New-PnPLibraryFileVersionBatchDeleteJob","New-PnPLibraryFileVersionExpirationReportJob","New-PnPList","New-PnPMicrosoft365Group","New-PnPMicrosoft365GroupSettings","New-PnPPersonalSite","New-PnPPlannerPlan","New-PnPProfileCardProperty","New-PnPSdnProvider","New-PnPSearchExternalConnection","New-PnPSearchResultType","New-PnPSearchResultTypeRule","New-PnPSearchVertical","New-PnPSite","New-PnPSiteCollectionTermStore","New-PnPSiteFileVersionBatchDeleteJob","New-PnPSiteFileVersionExpirationReportJob","New-PnPSiteGroup","New-PnPSiteManageVersionPolicyJob","New-PnPSiteTemplate","New-PnPSiteTemplateFromFolder","New-PnPTeamsApp","New-PnPTeamsTeam","New-PnPTenantSequence","New-PnPTenantSequenceCommunicationSite","New-PnPTenantSequenceTeamNoGroupSite","New-PnPTenantSequenceTeamNoGroupSubSite","New-PnPTenantSequenceTeamSite","New-PnPTenantSite","New-PnPTenantTemplate","New-PnPTerm","New-PnPTermGroup","New-PnPTermLabel","New-PnPTermSet","New-PnPTodoList","New-PnPUPABulkImportJob","New-PnPUser","New-PnPVivaEngageCommunity","New-PnPWeb","Publish-PnPApp","Publish-PnPContentType","Publish-PnPSyntexModel","Read-PnPSiteTemplate","Read-PnPTenantTemplate","Receive-PnPCopyMoveJobStatus","Register-PnPAppCatalogSite","Register-PnPEntraIDApp","Register-PnPEntraIDAppForInteractiveLogin","Register-PnPHubSite","Remove-PnPAdaptiveScopeProperty","Remove-PnPAlert","Remove-PnPApp","Remove-PnPApplicationCustomizer","Remove-PnPAvailableSiteClassification","Remove-PnPContainer","Remove-PnPContainerType","Remove-PnPContentType","Remove-PnPContentTypeFromDocumentSet","Remove-PnPContentTypeFromList","Remove-PnPCustomAction","Remove-PnPDeletedMicrosoft365Group","Remove-PnPEntraIDApp","Remove-PnPEntraIDGroup","Remove-PnPEntraIDGroupMember","Remove-PnPEntraIDGroupOwner","Remove-PnPEntraIDServicePrincipalAppRoleAssignment","Remove-PnPEntraIDServicePrincipalAssignedAppRole","Remove-PnPEntraIDUser","Remove-PnPEventReceiver","Remove-PnPExternalUser","Remove-PnPField","Remove-PnPFieldFromContentType","Remove-PnPFile","Remove-PnPFileFromSiteTemplate","Remove-PnPFileSharingLink","Remove-PnPFileVersion","Remove-PnPFlow","Remove-PnPFlowOwner","Remove-PnPFolder","Remove-PnPFolderSharingLink","Remove-PnPGraphSubscription","Remove-PnPGroup","Remove-PnPGroupMember","Remove-PnPHomeSite","Remove-PnPHubSiteAssociation","Remove-PnPHubToHubAssociation","Remove-PnPIndexedProperty","Remove-PnPJavaScriptLink","Remove-PnPKnowledgeHubSite","Remove-PnPLibraryFileVersionBatchDeleteJob","Remove-PnPList","Remove-PnPListDesign","Remove-PnPListItem","Remove-PnPListItemAttachment","Remove-PnPListItemComment","Remove-PnPListItemVersion","Remove-PnPManagedAppId","Remove-PnPMicrosoft365Group","Remove-PnPMicrosoft365GroupMember","Remove-PnPMicrosoft365GroupOwner","Remove-PnPMicrosoft365GroupPhoto","Remove-PnPMicrosoft365GroupSettings","Remove-PnPNavigationNode","Remove-PnPOrgAssetsLibrary","Remove-PnPOrgNewsSite","Remove-PnPPage","Remove-PnPPageComponent","Remove-PnPPlannerBucket","Remove-PnPPlannerPlan","Remove-PnPPlannerRoster","Remove-PnPPlannerRosterMember","Remove-PnPPlannerTask","Remove-PnPPowerAppPermission","Remove-PnPProfileCardProperty","Remove-PnPPropertyBagValue","Remove-PnPPublishingImageRendition","Remove-PnPRoleDefinition","Remove-PnPSdnProvider","Remove-PnPSearchConfiguration","Remove-PnPSearchExternalConnection","Remove-PnPSearchExternalItem","Remove-PnPSearchResultType","Remove-PnPSearchVertical","Remove-PnPSiteCollectionAdmin","Remove-PnPSiteCollectionAppCatalog","Remove-PnPSiteCollectionTermStore","Remove-PnPSiteDesign","Remove-PnPSiteDesignTask","Remove-PnPSiteFileVersionBatchDeleteJob","Remove-PnPSiteGroup","Remove-PnPSiteScript","Remove-PnPSiteSensitivityLabel","Remove-PnPSiteUserInvitations","Remove-PnPStorageEntity","Remove-PnPStoredCredential","Remove-PnPTaxonomyItem","Remove-PnPTeamsApp","Remove-PnPTeamsChannel","Remove-PnPTeamsChannelUser","Remove-PnPTeamsTab","Remove-PnPTeamsTag","Remove-PnPTeamsTeam","Remove-PnPTeamsUser","Remove-PnPTenantCdnOrigin","Remove-PnPTenantDeletedSite","Remove-PnPTenantRestrictedSearchAllowedList","Remove-PnPTenantSite","Remove-PnPTenantSyncClientRestriction","Remove-PnPTenantTheme","Remove-PnPTerm","Remove-PnPTermGroup","Remove-PnPTermLabel","Remove-PnPTodoList","Remove-PnPUser","Remove-PnPUserInfo","Remove-PnPUserProfile","Remove-PnPUserProfilePhoto","Remove-PnPView","Remove-PnPVivaConnectionsDashboardACE","Remove-PnPVivaEngageCommunity","Remove-PnPWeb","Remove-PnPWebAlert","Remove-PnPWebhookSubscription","Remove-PnPWebPart","Remove-PnPWikiPage","Rename-PnPFile","Rename-PnPFolder","Rename-PnPTenantSite","Repair-PnPSite","Request-PnPPersonalSite","Request-PnPReIndexList","Request-PnPReIndexWeb","Request-PnPSyntexClassifyAndExtract","Reset-PnPDocumentId","Reset-PnPFileVersion","Reset-PnPMicrosoft365GroupExpiration","Reset-PnPRetentionLabel","Reset-PnPUserOneDriveQuotaToDefault","Resolve-PnPFolder","Restart-PnPFlowRun","Restore-PnPDeletedContainer","Restore-PnPDeletedMicrosoft365Group","Restore-PnPFileVersion","Restore-PnPFlow","Restore-PnPListItemVersion","Restore-PnPRecycleBinItem","Restore-PnPTenantRecycleBinItem","Restore-PnPTenantSite","Revoke-PnPEntraIDAppSitePermission","Revoke-PnPHubSiteRights","Revoke-PnPSiteDesignRights","Revoke-PnPTenantServicePrincipalPermission","Revoke-PnPUserSession","Save-PnPPageConversionLog","Save-PnPSiteTemplate","Save-PnPTenantTemplate","Send-PnPMail","Set-PnPAdaptiveScopeProperty","Set-PnPApplicationCustomizer","Set-PnPAppSideLoading","Set-PnPAuditing","Set-PnPAvailablePageLayouts","Set-PnPBrowserIdleSignout","Set-PnPBuiltInDesignPackageVisibility","Set-PnPBuiltInSiteTemplateSettings","Set-PnPContentType","Set-PnPContext","Set-PnPCopilotAdminLimitedMode","Set-PnPDefaultColumnValues","Set-PnPDefaultContentTypeToList","Set-PnPDefaultPageLayout","Set-PnPDisableSpacesActivation","Set-PnPDocumentSetField","Set-PnPEntraIDAppSitePermission","Set-PnPEntraIDGroup","Set-PnPField","Set-PnPFileArchiveState","Set-PnPFileCheckedIn","Set-PnPFileCheckedOut","Set-PnPFileRetentionLabel","Set-PnPFileVersion","Set-PnPFolderArchiveState","Set-PnPFolderPermission","Set-PnPFooter","Set-PnPGraphSubscription","Set-PnPGroup","Set-PnPGroupPermissions","Set-PnPHideDefaultThemes","Set-PnPHomePage","Set-PnPHomeSite","Set-PnPHubSite","Set-PnPImageListItemColumn","Set-PnPIndexedProperties","Set-PnPInPlaceRecordsManagement","Set-PnPKnowledgeHubSite","Set-PnPList","Set-PnPListInformationRightsManagement","Set-PnPListItem","Set-PnPListItemAsRecord","Set-PnPListItemPermission","Set-PnPListPermission","Set-PnPListRecordDeclaration","Set-PnPListVersionPolicy","Set-PnPManagedAppId","Set-PnPMasterPage","Set-PnPMessageCenterAnnouncementAsArchived","Set-PnPMessageCenterAnnouncementAsFavorite","Set-PnPMessageCenterAnnouncementAsNotArchived","Set-PnPMessageCenterAnnouncementAsNotFavorite","Set-PnPMessageCenterAnnouncementAsRead","Set-PnPMessageCenterAnnouncementAsUnread","Set-PnPMicrosoft365Group","Set-PnPMicrosoft365GroupSettings","Set-PnPOrgAssetsLibrary","Set-PnPPage","Set-PnPPageTextPart","Set-PnPPageWebPart","Set-PnPPlannerBucket","Set-PnPPlannerConfiguration","Set-PnPPlannerPlan","Set-PnPPlannerTask","Set-PnPPlannerUserPolicy","Set-PnPPowerAppByPassConsent","Set-PnPPropertyBagValue","Set-PnPRequestAccessEmails","Set-PnPRetentionLabel","Set-PnPRoleDefinition","Set-PnPSearchConfiguration","Set-PnPSearchExternalConnection","Set-PnPSearchExternalItem","Set-PnPSearchExternalSchema","Set-PnPSearchResultType","Set-PnPSearchSettings","Set-PnPSearchVertical","Set-PnPSearchVerticalOrder","Set-PnPSite","Set-PnPSiteArchiveState","Set-PnPSiteClassification","Set-PnPSiteClosure","Set-PnPSiteDesign","Set-PnPSiteDocumentIdPrefix","Set-PnPSiteGroup","Set-PnPSitePolicy","Set-PnPSiteScript","Set-PnPSiteScriptPackage","Set-PnPSiteSensitivityLabel","Set-PnPSiteTemplateMetadata","Set-PnPSiteVersionPolicy","Set-PnPStorageEntity","Set-PnPStructuralNavigationCacheSiteState","Set-PnPStructuralNavigationCacheWebState","Set-PnPTaxonomyFieldValue","Set-PnPTeamifyPromptHidden","Set-PnPTeamsChannel","Set-PnPTeamsChannelUser","Set-PnPTeamsTab","Set-PnPTeamsTag","Set-PnPTeamsTeam","Set-PnPTeamsTeamArchivedState","Set-PnPTeamsTeamPicture","Set-PnPTemporarilyDisableAppBar","Set-PnPTenant","Set-PnPTenantAppCatalogUrl","Set-PnPTenantCdnEnabled","Set-PnPTenantCdnPolicy","Set-PnPTenantPronounsSetting","Set-PnPTenantRestrictedSearchMode","Set-PnPTenantSite","Set-PnPTenantSyncClientRestriction","Set-PnPTerm","Set-PnPTermGroup","Set-PnPTermSet","Set-PnPTheme","Set-PnPUserOneDriveQuota","Set-PnPUserProfilePhoto","Set-PnPUserProfileProperty","Set-PnPView","Set-PnPVivaConnectionsDashboardACE","Set-PnPVivaEngageCommunity","Set-PnPWeb","Set-PnPWebHeader","Set-PnPWebhookSubscription","Set-PnPWebPartProperty","Set-PnPWebPermission","Set-PnPWebTheme","Set-PnPWikiPageContent","Start-PnPEnterpriseAppInsightsReport","Start-PnPTenantRename","Start-PnPTraceLog","Stop-PnPFlowRun","Stop-PnPTraceLog","Submit-PnPSearchQuery","Submit-PnPTeamsChannelMessage","Sync-PnPAppToTeams","Sync-PnPSharePointUserProfilesFromAzureActiveDirectory","Test-PnPListItemIsRecord","Test-PnPMicrosoft365GroupAliasIsUsed","Test-PnPSite","Test-PnPTenantTemplate","Undo-PnPFileCheckedOut","Uninstall-PnPApp","Unlock-PnPSensitivityLabelEncryptedFile","Unpublish-PnPApp","Unpublish-PnPContentType","Unpublish-PnPSyntexModel","Unregister-PnPHubSite","Update-PnPApp","Update-PnPAvailableSiteClassification","Update-PnPSiteDesignFromWeb","Update-PnPTeamsApp","Update-PnPTeamsUser","Update-PnPTodoList","Update-PnPUserType","Use-PnPBrandCenterFontPackage","Write-PnPTraceLog")
VariablesToExport = '*'
AliasesToExport = '*'
FormatsToProcess = 'PnP.PowerShell.Format.ps1xml'
PrivateData = @{
	PSData = @{
		Tags = 'SharePoint','PnP','Teams','Planner'
		ProjectUri = 'https://aka.ms/sppnp'
		IconUri = 'https://raw.githubusercontent.com/pnp/media/40e7cd8952a9347ea44e5572bb0e49622a102a12/parker/ms/300w/parker-ms-300.png'
	}
}
}

# SIG # Begin signature block
# MIIvQQYJKoZIhvcNAQcCoIIvMjCCLy4CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBiYM4j5ghiKHO4
# zm4xlSsuMvrMgZ/6pH0IYvp8SQn8taCCE7AwggVkMIIDTKADAgECAhAGzuExvm1V
# yAf3wMf7ROYgMA0GCSqGSIb3DQEBDAUAMEwxCzAJBgNVBAYTAlVTMRcwFQYDVQQK
# Ew5EaWdpQ2VydCwgSW5jLjEkMCIGA1UEAxMbRGlnaUNlcnQgQ1MgUlNBNDA5NiBS
# b290IEc1MB4XDTIxMDExNTAwMDAwMFoXDTQ2MDExNDIzNTk1OVowTDELMAkGA1UE
# BhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMSQwIgYDVQQDExtEaWdpQ2Vy
# dCBDUyBSU0E0MDk2IFJvb3QgRzUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
# AoICAQC2M3OA2GIDcBQsERw5XnyufIOGHf4mL0wkrYvqg1+pvD1b/AuYTAJHMOzi
# /uzoNFtmXr871yymJf+MWbPf6tp8KdlGUHIIHW7RGwrdH82ZifoPD3PE4ZwddTLN
# b5faKmqVsmzJCdDqC3t9FwZJme/W3uDIU9SuxnfxhrsjHLjA31n3jn3R74LmJota
# OLX/ddWy2U8J8zeIUNoRpIoUFNFTBAB982pEGP5QcDIHHKiaDjodxQofbgsmabc8
# oldwLIb6TG6VqVhDuawS1v8/7ddDF2tMzp7EkKv/+hBQmqOQV9bnjBCunxYazzUd
# f9d27YqcNacouKddIfwwN93eCBlPFcbnptqQR473lFNMjlMCvv2Z5eqG0K8DAtOb
# qpPxqyiOIAH/TPvMtylA9YekEhMFH0Nu11FQnzi0IO0XCRKPzLkZr5/NvmkR069V
# EG0XhnmWUsayAJ3lrziwNfSIa48OBD187q/N02oQSsbNhsoiPaFKXPsO/4jfXGKn
# wLke2axsfjg3/neTJcKFik+1NwZaBoEU8c6UnZmR6jJazmc9bgRmrQxPLaMu9571
# eJ33Cv1+j+NCilWWvPGfNy38nl+V/owYG/yO/UuQr9cDaBJjrOKTp6LLBOVPZM4D
# +sYUn9mL6MzUYoxr5AAsGZ8aBsYxgVT7UySar1WZup11rrjC3QIDAQABo0IwQDAd
# BgNVHQ4EFgQUaAGTsdJKQEJplEYsHFqIqSW0R08wDgYDVR0PAQH/BAQDAgGGMA8G
# A1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEMBQADggIBAJL87rgCeRcCUX0hxUln
# p6TxqCQ46wxo6lpCa5z0c8FpSi2zNwVQQpiSngZ5LC4Gmfbv3yugzbOSAYO1oMsn
# tTwjGphJouwtmaVZQ6zSsZPWV9ccvJPWxkDhs28ZVbcT1+VDM6S1q8vawTFkDXTW
# LO3DjW7ru68ZR2FhLcD0BblveNw690JAZVORvZkNk5JUpqk3WSuby5nGvD33BITw
# lDMdD4JaOcsuRcMoGaOym5jI/DFrYI/26YYovOA8fXRdFolbaSTHEIvES7s2T9RZ
# P8OwpJGZ+C7RSgGd9YgS779aEWpZT1lrWmfzj7QTD8DYLz0ocqoZfxF9alufledf
# t5RP8T6hWv8tzJ3fJ3ePMnMcZwp28/pcsb+8Hb0MKJuyxxdnCzMPw7023Pu6Qgur
# 7YTDYtaEFqmxB2upbu7Gz+awRCnC8LNhgCqLb9IUXCWHVGTzpEzBofina+r+6jr8
# edsOj9zG88nUbN7pg6GOHSLsyTqyAHvcO6dCGn/ci6kRPY6nwCBvXQldQ0Tmj2bM
# qVsH8e+beg6zVOGU/Q4sxpPXVf1xmDW4CUr/xikoLPZSLdsUGJIn4hZ+jMrUYb6C
# h5HrmDc/v19ddz80rBs4Q6tocpkyHjoaGaWjOEwj16PnzNUqkheQC1pLvRa9+4Zq
# 4omZ7OSgVRjJowgfE+AyCHLQMIIGkDCCBHigAwIBAgIQCt4y6VCbRKo0sdrxvA7I
# czANBgkqhkiG9w0BAQsFADBMMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNl
# cnQsIEluYy4xJDAiBgNVBAMTG0RpZ2lDZXJ0IENTIFJTQTQwOTYgUm9vdCBHNTAe
# Fw0yMTA3MTUwMDAwMDBaFw0zMTA3MTQyMzU5NTlaMFsxCzAJBgNVBAYTAlVTMRgw
# FgYDVQQKEw8uTkVUIEZvdW5kYXRpb24xMjAwBgNVBAMTKS5ORVQgRm91bmRhdGlv
# biBQcm9qZWN0cyBDb2RlIFNpZ25pbmcgQ0EyMIICIjANBgkqhkiG9w0BAQEFAAOC
# Ag8AMIICCgKCAgEAznkpxwyD+QKdO6sSwPBJD5wtJL9ncyIlhHFM8rWvU5lCCoMp
# 9TcAiXvCIIaJCeOxjXFv0maraGhSr8SANVefC74HBfDTAl/JyoWmOfBxRY/30/0q
# ivfUtoxrw91SR3Gu3eucWxxb4b+hoIpTgbKU+//cnSvi8EmBTk7ntfFkAWw/6Lov
# +nMXU+qEzm/TuCT8qWX2IffLkdXIt4UqQS8Jqjxn7cGLhjqDA9w+5zXpSxSu/JhK
# OecY05XcdGlGnQBPc8RBzUD3ZzXMPoPBSFiH7UZs23iVmVXCJoU9IFaN3WSLD/jZ
# 3TXE8RxJxoY1DODwr4t6kTSQdDPrx3aPrtAcJFblh3JMP0SpZZpV8DHALVZkKKfF
# u2SOL9Wv57MJ6M/mhfyUot2vLVxVlWlplgwOhcHP7a40cVBczF/cAb+IBz+tuB1q
# wGGi4B3qnE2kpYju6xYz75hVcfFqXGmy3+NMZIF6oMJUSLUZmU7HUDCUyMgHt6SP
# 42r7vzRyPJEMXARiNwe5jI6oAWxyeX6dN4ZXiBDa1lVaVuK8yUd7ShbETPbTPaZ5
# BaV/yxcl1rqExPqKzIH+y/a6F33KXSYVGTSFcg/tSEd4vuXbBUuIf2UpPVkK+J2/
# 0J/o8sBSkF3nFZ/USwrvcMKEiINKokHvmivypLkhSfMIEismXSO6rke8ElECAwEA
# AaOCAV0wggFZMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFCgOTIkcmZfx
# gfCPCN5XEku8uHjPMB8GA1UdIwQYMBaAFGgBk7HSSkBCaZRGLBxaiKkltEdPMA4G
# A1UdDwEB/wQEAwIBhjATBgNVHSUEDDAKBggrBgEFBQcDAzB5BggrBgEFBQcBAQRt
# MGswJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBDBggrBgEF
# BQcwAoY3aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0Q1NSU0E0
# MDk2Um9vdEc1LmNydDBFBgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vY3JsMy5kaWdp
# Y2VydC5jb20vRGlnaUNlcnRDU1JTQTQwOTZSb290RzUuY3JsMBwGA1UdIAQVMBMw
# BwYFZ4EMAQMwCAYGZ4EMAQQBMA0GCSqGSIb3DQEBCwUAA4ICAQA66iJQhuBqWcn+
# rukrkzv8/2CGpyWTqoospvt+Nr2zsgl1xX97v588lngs94uqlTB90YLR4227PZQz
# HQAFEs0K0/UNUfoKPC9DZSn4xJxjPsLaK8N+l4d6oZBAb7AXglpxfk4ocrzM0KWY
# Tnaz3+lt0uGi8VgP8Wggh24FLxzxxiC5SqwZ7wfU7w1g7YugDn6xbcH4+yd6ZpCn
# MDcxYkGKqOtjM7V3bd3Rbl/PDySZ+chy/n6Q6ZNj9Oz/WFYlYOId7CMmI5SzbMWp
# qbdwvPNkrSYwFRtnRV9rwJo/q9jctfwrG9FQBkHMXiLHRQPw4oEoROk0AYCm26zv
# dEqc1pPCIEQHtXyOW+GqX2MORRdiePFfmG8b1xlIw8iBJOorlbEJA6tvOpDTb1I5
# +ph6tM4DwrMrS0LbGPJv0ah9fh26ZPta1xF0KC4/gdyqY7Bmij+X+atdrRZ0jdqc
# SHspWYc9U6SaXWKVXFwvkc0b19dkzECS7ebrPQuC0+euLpvDMzHIafzL21XHB1+g
# ncuwbt7/RknJoDbFKsx5x0qDQ6vfJmrajyNAMd5fGQdgcUHs75G+KWvg7M4RtGRq
# 6NHrXnBg1LHQlRbLDSCXbIoXkywzzksKuxxm9sn2gdz0/v4o4vPQHrxk8Mj6i23U
# 6h97uJQWVPhLWhQtcjc8MJmU2i5xlDCCB7AwggWYoAMCAQICEAeznI5xGX/9e0Sh
# g4fSo5cwDQYJKoZIhvcNAQELBQAwWzELMAkGA1UEBhMCVVMxGDAWBgNVBAoTDy5O
# RVQgRm91bmRhdGlvbjEyMDAGA1UEAxMpLk5FVCBGb3VuZGF0aW9uIFByb2plY3Rz
# IENvZGUgU2lnbmluZyBDQTIwHhcNMjYwNTA2MDAwMDAwWhcNMjcwODA3MjM1OTU5
# WjCB7zETMBEGCysGAQQBgjc8AgEDEwJVUzEbMBkGCysGAQQBgjc8AgECEwpXYXNo
# aW5ndG9uMR0wGwYDVQQPDBRQcml2YXRlIE9yZ2FuaXphdGlvbjEUMBIGA1UEBRML
# NjAzIDM4OSAwNjgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMSgwJgYDVQQKEx9QTlBQb3dlcnNoZWxsICguTmV0IEZv
# dW5kYXRpb24pMSgwJgYDVQQDEx9QTlBQb3dlcnNoZWxsICguTmV0IEZvdW5kYXRp
# b24pMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqZyiOReXlxKYzFsZ
# mqiuIK687ktpyou17CO/mC19vLxsgsTYoUOSpGtrere+Ufs15aqBHw4ROks4UMB3
# s1t9DJ3s+qn5QeCgCAfaZVFJ5w5KIcNR3qtalyTM3pjMjeRqYxRNoRCbwB8utUSP
# 6gEl2gWiN5iVs4uCjqU7EADPV8q24Plifgo/VnB74z4cSoYl1ZcH0cEE2qIVDUU1
# SDGfF3ivUJYY0BNujR6V5GI7Jtzi3Ogw3oE2eXphRl2EJZXfQJAHjEzW7rWWpFQa
# ChrPeR0OLPCiFAFGvkuP08u01jNBf44WQc0qrjesuVfvXC579vkGxREezEn1jzhZ
# EQe1xlwXqS1JZrc9oT1YZCqpWMmcyUqSVaFUNnH2RkTREN+66aeBG6eOGyyGrUtJ
# qUDSDuiw6mxjg5ixN/gu2rBGrX+qZ8Q+7ZjrLlEVIvdSEmn/ar/Bh9UR1ZxyDIEK
# //6CwLNBIB4ktg8PfOi3xyJSJ56KEYHW0Us+zY8WchIKGy6pANv3AKtSj1DIcQTj
# 1vPnSsHWow1BQFTt25uVqNbJTBxHkXSB5ZrFAwOtDw92KBeyD8vQjb0RMKZyueCA
# GTbp6sx21/gnAtL0mkbOnF91p6LNc/ascPlpU/VsNtgPg8/GlZbMK4F5srIpNUSx
# BI6WRkv7XF6bKapx37PFFDmjx9ECAwEAAaOCAdkwggHVMB8GA1UdIwQYMBaAFCgO
# TIkcmZfxgfCPCN5XEku8uHjPMB0GA1UdDgQWBBQRhEes+15qaWPFh5ZJqjhi1KSR
# HTA9BgNVHSAENjA0MDIGBWeBDAEDMCkwJwYIKwYBBQUHAgEWG2h0dHA6Ly93d3cu
# ZGlnaWNlcnQuY29tL0NQUzAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYB
# BQUHAwMwgZsGA1UdHwSBkzCBkDBGoESgQoZAaHR0cDovL2NybDMuZGlnaWNlcnQu
# Y29tL05FVEZvdW5kYXRpb25Qcm9qZWN0c0NvZGVTaWduaW5nQ0EyLmNybDBGoESg
# QoZAaHR0cDovL2NybDQuZGlnaWNlcnQuY29tL05FVEZvdW5kYXRpb25Qcm9qZWN0
# c0NvZGVTaWduaW5nQ0EyLmNybDCBhQYIKwYBBQUHAQEEeTB3MCQGCCsGAQUFBzAB
# hhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wTwYIKwYBBQUHMAKGQ2h0dHA6Ly9j
# YWNlcnRzLmRpZ2ljZXJ0LmNvbS9ORVRGb3VuZGF0aW9uUHJvamVjdHNDb2RlU2ln
# bmluZ0NBMi5jcnQwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAgEAmgQXKZlq
# gDFu62gUMSsjmyCyJ4bEJrNpIFJOtQ7WrjJT39LvA590dujW7qnyho5qoZQtFFu2
# KnWoP66OCOsG1vhlq6Up4Mk+ZQYlEK+HegiY0uCZIwOnzwxd3TbLV3e1AkJUtNgQ
# nv5GddBIgirwkJd5Ld1oo2jOx10wpf2GtDZRBgS2P0aocFsNgRFL/nVDPDSDX7i6
# D8pWp6krxqs3fzDiS6IzmnkwToBLLiKl6Glopm4wua1kqQslYuSv+k5HfKXGzrOo
# hHJvIX1Aw/t0khlvwZRDk6/0mXTfxs0rQxyxWQBl+IXnahhS4zbhSe9zX8haOxTW
# UOOpVeWVM3fvuQZEWPEHKfq59xc8VMV6WYZbSQ81UDRzZ0tVZbmjoXN8ae31rKPF
# mekWeMhm4UzFw+ERJ+JwjlMF/yIZ2nTbbtLTPoRLcIGd4m8/QLMzF91IO1ekCGJV
# MmLuVInpIvoPo8eb2UIH9IqY0cPaPmn/rQkiVaPqO8JqNsRrHk9Z2a9AjnhbEJLc
# UEyhchzYgEHqzZGo7ZLB6MPKDez09ml02VOBYKcp/WafHvZHV40vguEV2xDVi9uE
# wTnJSoRzWV3+2PNPhkfeyljwBMpK2/BBZe0OsVeY0HmseUCWRG+xeT5EMs3+x4hs
# dymt2fbq3fRMOT1Vi4Nnq0OLJIOLUjwlULMxghrnMIIa4wIBATBvMFsxCzAJBgNV
# BAYTAlVTMRgwFgYDVQQKEw8uTkVUIEZvdW5kYXRpb24xMjAwBgNVBAMTKS5ORVQg
# Rm91bmRhdGlvbiBQcm9qZWN0cyBDb2RlIFNpZ25pbmcgQ0EyAhAHs5yOcRl//XtE
# oYOH0qOXMA0GCWCGSAFlAwQCAQUAoIHQMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3
# AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJBDEi
# BCAKZ1SNzxADEdjnZSSgwE4kWR6ef/WBqcIo6wUtBNMiYDBkBgorBgEEAYI3AgEM
# MVYwVKAsgCoAUABuAFAAIABQAG8AdwBlAHIAUwBoAGUAbABsACAATQBvAGQAdQBs
# AGWhJIAiaHR0cHM6Ly9wbnAuZ2l0aHViLmlvL3Bvd2Vyc2hlbGwvIDANBgkqhkiG
# 9w0BAQEFAASCAgA033ukkMO7Enq3P34pmSTZDIhmVaslV3xJGXjJXI02VI8kdyus
# fBligKzVO1zByNyfqgbIkLcWzGUVv+j/Pcl1SurvhrhCFgACxMV+pXKeorlWuuLq
# 3+R8ALVXSmH3JMeT7pyeHwiITzWGpTGjPH3shVtu05HqrlvO1Qo9slPsS9nopzX7
# 03gTfdQ5fGTtwCNdaW6mmh4wjKCAkO1BR6LlDC41XVVsSRiiRp/OMVfftax0gUZH
# RRHnxNolIE0ck90AQhw2jBcewGjwOkD1Zn2kJJWXxyYyreiyz0oTuyB5QiEgdze8
# ICJ3X24M6uj/CswcrJaXbngaUXKWEHwUVTBIlgXxIC5/qctn0OPKDZT0ch/90Fsc
# tHTvRYxNG8h5gyxspmd5Tey3gsgPmjgiVRTUMklBAhXaoViQLkbCN8S4FUe8doTf
# aOtfzdENFUDaMNNRJyfMFEmRNVI+zyhAodG0IgP8W0c7cstpjjAieqbA1SZMsmLo
# kExxGX2xAnFGyLUTrMNMUaHV72ZSyDxbD7fu/UVt3afsbLbbkUut8xruRJpt0sea
# QvqAk71iiMKbwLOjnnOMT4iR1QZC/LulYOIkMs0nTye1ogBZv8blcRD4c5MF8Fa8
# sMP7cbDsYlG1tVI6baJKWIR1sl3PPUNobxjb85uFprp43/wJiPzMiBtxraGCF3Yw
# ghdyBgorBgEEAYI3AwMBMYIXYjCCF14GCSqGSIb3DQEHAqCCF08wghdLAgEDMQ8w
# DQYJYIZIAWUDBAIBBQAwdwYLKoZIhvcNAQkQAQSgaARmMGQCAQEGCWCGSAGG/WwH
# ATAxMA0GCWCGSAFlAwQCAQUABCD45pHPo7tb4wrmwdGE6exNPGitTZYfG5EFr87j
# 8b7DTAIQCYQtiNAkAs7o4/ig07Qp7hgPMjAyNjA1MTExNzQyMjdaoIITOjCCBu0w
# ggTVoAMCAQICEAqA7xhLjfEFgtHEdqeVdGgwDQYJKoZIhvcNAQELBQAwaTELMAkG
# A1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMUEwPwYDVQQDEzhEaWdp
# Q2VydCBUcnVzdGVkIEc0IFRpbWVTdGFtcGluZyBSU0E0MDk2IFNIQTI1NiAyMDI1
# IENBMTAeFw0yNTA2MDQwMDAwMDBaFw0zNjA5MDMyMzU5NTlaMGMxCzAJBgNVBAYT
# AlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjE7MDkGA1UEAxMyRGlnaUNlcnQg
# U0hBMjU2IFJTQTQwOTYgVGltZXN0YW1wIFJlc3BvbmRlciAyMDI1IDEwggIiMA0G
# CSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDQRqwtEsae0OquYFazK1e6b1H/hnAK
# Ad/KN8wZQjBjMqiZ3xTWcfsLwOvRxUwXcGx8AUjni6bz52fGTfr6PHRNv6T7zsf1
# Y/E3IU8kgNkeECqVQ+3bzWYesFtkepErvUSbf+EIYLkrLKd6qJnuzK8Vcn0DvbDM
# emQFoxQ2Dsw4vEjoT1FpS54dNApZfKY61HAldytxNM89PZXUP/5wWWURK+IfxiOg
# 8W9lKMqzdIo7VA1R0V3Zp3DjjANwqAf4lEkTlCDQ0/fKJLKLkzGBTpx6EYevvOi7
# XOc4zyh1uSqgr6UnbksIcFJqLbkIXIPbcNmA98Oskkkrvt6lPAw/p4oDSRZreiwB
# 7x9ykrjS6GS3NR39iTTFS+ENTqW8m6THuOmHHjQNC3zbJ6nJ6SXiLSvw4Smz8U07
# hqF+8CTXaETkVWz0dVVZw7knh1WZXOLHgDvundrAtuvz0D3T+dYaNcwafsVCGZKU
# hQPL1naFKBy1p6llN3QgshRta6Eq4B40h5avMcpi54wm0i2ePZD5pPIssoszQyF4
# //3DoK2O65Uck5Wggn8O2klETsJ7u8xEehGifgJYi+6I03UuT1j7FnrqVrOzaQoV
# JOeeStPeldYRNMmSF3voIgMFtNGh86w3ISHNm0IaadCKCkUe2LnwJKa8TIlwCUNV
# wppwn4D3/Pt5pwIDAQABo4IBlTCCAZEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU
# 5Dv88jHt/f3X85FxYxlQQ89hjOgwHwYDVR0jBBgwFoAU729TSunkBnx6yuKQVvYv
# 1Ensy04wDgYDVR0PAQH/BAQDAgeAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMIGV
# BggrBgEFBQcBAQSBiDCBhTAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNl
# cnQuY29tMF0GCCsGAQUFBzAChlFodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20v
# RGlnaUNlcnRUcnVzdGVkRzRUaW1lU3RhbXBpbmdSU0E0MDk2U0hBMjU2MjAyNUNB
# MS5jcnQwXwYDVR0fBFgwVjBUoFKgUIZOaHR0cDovL2NybDMuZGlnaWNlcnQuY29t
# L0RpZ2lDZXJ0VHJ1c3RlZEc0VGltZVN0YW1waW5nUlNBNDA5NlNIQTI1NjIwMjVD
# QTEuY3JsMCAGA1UdIAQZMBcwCAYGZ4EMAQQCMAsGCWCGSAGG/WwHATANBgkqhkiG
# 9w0BAQsFAAOCAgEAZSqt8RwnBLmuYEHs0QhEnmNAciH45PYiT9s1i6UKtW+FERp8
# FgXRGQ/YAavXzWjZhY+hIfP2JkQ38U+wtJPBVBajYfrbIYG+Dui4I4PCvHpQuPqF
# gqp1PzC/ZRX4pvP/ciZmUnthfAEP1HShTrY+2DE5qjzvZs7JIIgt0GCFD9ktx0Lx
# xtRQ7vllKluHWiKk6FxRPyUPxAAYH2Vy1lNM4kzekd8oEARzFAWgeW3az2xejEWL
# NN4eKGxDJ8WDl/FQUSntbjZ80FU3i54tpx5F/0Kr15zW/mJAxZMVBrTE2oi0fcI8
# VMbtoRAmaaslNXdCG1+lqvP4FbrQ6IwSBXkZagHLhFU9HCrG/syTRLLhAezu/3Lr
# 00GrJzPQFnCEH1Y58678IgmfORBPC1JKkYaEt2OdDh4GmO0/5cHelAK2/gTlQJIN
# qDr6JfwyYHXSd+V08X1JUPvB4ILfJdmL+66Gp3CSBXG6IwXMZUXBhtCyIaehr0Xk
# BoDIGMUG1dUtwq1qmcwbdUfcSYCn+OwncVUXf53VJUNOaMWMts0VlRYxe5nK+At+
# DI96HAlXHAL5SlfYxJ7La54i71McVWRP66bW+yERNpbJCjyCYG2j+bdpxo/1Cy4u
# PcU3AWVPGrbn5PhDBf3Froguzzhk++ami+r3Qrx5bIbY3TVzgiFI7Gq3zWcwgga0
# MIIEnKADAgECAhANx6xXBf8hmS5AQyIMOkmGMA0GCSqGSIb3DQEBCwUAMGIxCzAJ
# BgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5k
# aWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0IFRydXN0ZWQgUm9vdCBHNDAe
# Fw0yNTA1MDcwMDAwMDBaFw0zODAxMTQyMzU5NTlaMGkxCzAJBgNVBAYTAlVTMRcw
# FQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3Rl
# ZCBHNCBUaW1lU3RhbXBpbmcgUlNBNDA5NiBTSEEyNTYgMjAyNSBDQTEwggIiMA0G
# CSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC0eDHTCphBcr48RsAcrHXbo0ZodLRR
# F51NrY0NlLWZloMsVO1DahGPNRcybEKq+RuwOnPhof6pvF4uGjwjqNjfEvUi6wui
# m5bap+0lgloM2zX4kftn5B1IpYzTqpyFQ/4Bt0mAxAHeHYNnQxqXmRinvuNgxVBd
# Jkf77S2uPoCj7GH8BLuxBG5AvftBdsOECS1UkxBvMgEdgkFiDNYiOTx4OtiFcMSk
# qTtF2hfQz3zQSku2Ws3IfDReb6e3mmdglTcaarps0wjUjsZvkgFkriK9tUKJm/s8
# 0FiocSk1VYLZlDwFt+cVFBURJg6zMUjZa/zbCclF83bRVFLeGkuAhHiGPMvSGmhg
# aTzVyhYn4p0+8y9oHRaQT/aofEnS5xLrfxnGpTXiUOeSLsJygoLPp66bkDX1ZlAe
# SpQl92QOMeRxykvq6gbylsXQskBBBnGy3tW/AMOMCZIVNSaz7BX8VtYGqLt9MmeO
# reGPRdtBx3yGOP+rx3rKWDEJlIqLXvJWnY0v5ydPpOjL6s36czwzsucuoKs7Yk/e
# hb//Wx+5kMqIMRvUBDx6z1ev+7psNOdgJMoiwOrUG2ZdSoQbU2rMkpLiQ6bGRinZ
# bI4OLu9BMIFm1UUl9VnePs6BaaeEWvjJSjNm2qA+sdFUeEY0qVjPKOWug/G6X5uA
# iynM7Bu2ayBjUwIDAQABo4IBXTCCAVkwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNV
# HQ4EFgQU729TSunkBnx6yuKQVvYv1Ensy04wHwYDVR0jBBgwFoAU7NfjgtJxXWRM
# 3y5nP+e6mK4cD08wDgYDVR0PAQH/BAQDAgGGMBMGA1UdJQQMMAoGCCsGAQUFBwMI
# MHcGCCsGAQUFBwEBBGswaTAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNl
# cnQuY29tMEEGCCsGAQUFBzAChjVodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20v
# RGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNydDBDBgNVHR8EPDA6MDigNqA0hjJodHRw
# Oi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNybDAg
# BgNVHSAEGTAXMAgGBmeBDAEEAjALBglghkgBhv1sBwEwDQYJKoZIhvcNAQELBQAD
# ggIBABfO+xaAHP4HPRF2cTC9vgvItTSmf83Qh8WIGjB/T8ObXAZz8OjuhUxjaaFd
# leMM0lBryPTQM2qEJPe36zwbSI/mS83afsl3YTj+IQhQE7jU/kXjjytJgnn0hvrV
# 6hqWGd3rLAUt6vJy9lMDPjTLxLgXf9r5nWMQwr8Myb9rEVKChHyfpzee5kH0F8HA
# BBgr0UdqirZ7bowe9Vj2AIMD8liyrukZ2iA/wdG2th9y1IsA0QF8dTXqvcnTmpfe
# Qh35k5zOCPmSNq1UH410ANVko43+Cdmu4y81hjajV/gxdEkMx1NKU4uHQcKfZxAv
# BAKqMVuqte69M9J6A47OvgRaPs+2ykgcGV00TYr2Lr3ty9qIijanrUR3anzEwlvz
# ZiiyfTPjLbnFRsjsYg39OlV8cipDoq7+qNNjqFzeGxcytL5TTLL4ZaoBdqbhOhZ3
# ZRDUphPvSRmMThi0vw9vODRzW6AxnJll38F0cuJG7uEBYTptMSbhdhGQDpOXgpIU
# sWTjd6xpR6oaQf/DJbg3s6KCLPAlZ66RzIg9sC+NJpud/v4+7RWsWCiKi9EOLLHf
# MR2ZyJ/+xhCx9yHbxtl5TPau1j/1MIDpMPx0LckTetiSuEtQvLsNz3Qbp7wGWqbI
# iOWCnb5WqxL3/BAPvIXKUjPSxyZsq8WhbaM2tszWkPZPubdcMIIFjTCCBHWgAwIB
# AgIQDpsYjvnQLefv21DiCEAYWjANBgkqhkiG9w0BAQwFADBlMQswCQYDVQQGEwJV
# UzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQu
# Y29tMSQwIgYDVQQDExtEaWdpQ2VydCBBc3N1cmVkIElEIFJvb3QgQ0EwHhcNMjIw
# ODAxMDAwMDAwWhcNMzExMTA5MjM1OTU5WjBiMQswCQYDVQQGEwJVUzEVMBMGA1UE
# ChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSEwHwYD
# VQQDExhEaWdpQ2VydCBUcnVzdGVkIFJvb3QgRzQwggIiMA0GCSqGSIb3DQEBAQUA
# A4ICDwAwggIKAoICAQC/5pBzaN675F1KPDAiMGkz7MKnJS7JIT3yithZwuEppz1Y
# q3aaza57G4QNxDAf8xukOBbrVsaXbR2rsnnyyhHS5F/WBTxSD1Ifxp4VpX6+n6lX
# FllVcq9ok3DCsrp1mWpzMpTREEQQLt+C8weE5nQ7bXHiLQwb7iDVySAdYyktzuxe
# TsiT+CFhmzTrBcZe7FsavOvJz82sNEBfsXpm7nfISKhmV1efVFiODCu3T6cw2Vbu
# yntd463JT17lNecxy9qTXtyOj4DatpGYQJB5w3jHtrHEtWoYOAMQjdjUN6QuBX2I
# 9YI+EJFwq1WCQTLX2wRzKm6RAXwhTNS8rhsDdV14Ztk6MUSaM0C/CNdaSaTC5qmg
# Z92kJ7yhTzm1EVgX9yRcRo9k98FpiHaYdj1ZXUJ2h4mXaXpI8OCiEhtmmnTK3kse
# 5w5jrubU75KSOp493ADkRSWJtppEGSt+wJS00mFt6zPZxd9LBADMfRyVw4/3IbKy
# Ebe7f/LVjHAsQWCqsWMYRJUadmJ+9oCw++hkpjPRiQfhvbfmQ6QYuKZ3AeEPlAwh
# HbJUKSWJbOUOUlFHdL4mrLZBdd56rF+NP8m800ERElvlEFDrMcXKchYiCd98THU/
# Y+whX8QgUWtvsauGi0/C1kVfnSD8oR7FwI+isX4KJpn15GkvmB0t9dmpsh3lGwID
# AQABo4IBOjCCATYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU7NfjgtJxXWRM
# 3y5nP+e6mK4cD08wHwYDVR0jBBgwFoAUReuir/SSy4IxLVGLp6chnfNtyA8wDgYD
# VR0PAQH/BAQDAgGGMHkGCCsGAQUFBwEBBG0wazAkBggrBgEFBQcwAYYYaHR0cDov
# L29jc3AuZGlnaWNlcnQuY29tMEMGCCsGAQUFBzAChjdodHRwOi8vY2FjZXJ0cy5k
# aWdpY2VydC5jb20vRGlnaUNlcnRBc3N1cmVkSURSb290Q0EuY3J0MEUGA1UdHwQ+
# MDwwOqA4oDaGNGh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEFzc3Vy
# ZWRJRFJvb3RDQS5jcmwwEQYDVR0gBAowCDAGBgRVHSAAMA0GCSqGSIb3DQEBDAUA
# A4IBAQBwoL9DXFXnOF+go3QbPbYW1/e/Vwe9mqyhhyzshV6pGrsi+IcaaVQi7aSI
# d229GhT0E0p6Ly23OO/0/4C5+KH38nLeJLxSA8hO0Cre+i1Wz/n096wwepqLsl7U
# z9FDRJtDIeuWcqFItJnLnU+nBgMTdydE1Od/6Fmo8L8vC6bp8jQ87PcDx4eo0kxA
# GTVGamlUsLihVo7spNU96LHc/RzY9HdaXFSMb++hUD38dglohJ9vytsgjTVgHAID
# yyCwrFigDkBjxZgiwbJZ9VVrzyerbHbObyMt9H5xaiNrIv8SuFQtJ37YOtnwtoeW
# /VvRXKwYw02fc7cBqZ9Xql4o4rmUMYIDfDCCA3gCAQEwfTBpMQswCQYDVQQGEwJV
# UzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xQTA/BgNVBAMTOERpZ2lDZXJ0IFRy
# dXN0ZWQgRzQgVGltZVN0YW1waW5nIFJTQTQwOTYgU0hBMjU2IDIwMjUgQ0ExAhAK
# gO8YS43xBYLRxHanlXRoMA0GCWCGSAFlAwQCAQUAoIHRMBoGCSqGSIb3DQEJAzEN
# BgsqhkiG9w0BCRABBDAcBgkqhkiG9w0BCQUxDxcNMjYwNTExMTc0MjI3WjArBgsq
# hkiG9w0BCRACDDEcMBowGDAWBBTdYjCshgotMGvaOLFoeVIwB/tBfjAvBgkqhkiG
# 9w0BCQQxIgQgQ02DGuVuP4iPFAVBDF2piuH566XwX4a0jLtxrSEY+60wNwYLKoZI
# hvcNAQkQAi8xKDAmMCQwIgQgSqA/oizXXITFXJOPgo5na5yuyrM/420mmqM08UYR
# CjMwDQYJKoZIhvcNAQEBBQAEggIACHOJ6IXzNB5Cfxt4CD8ZZxyEExuAToNIK5Tk
# 80VwEU4cSy4hDQqnAbZg6LDclnHn7KmJS2MgAd1r8DaC1fOh3a/s/Mx4yv+xz8v9
# 5HXczZrkYxqDefy51DuY1BKqGCvUg5wGpB5hmbIL94UeyUyckOdvJ5Nab8Q7f2d4
# gcn7F+QDmTgwwHBWqUjU0lyGyu8olvcmjn1LAJnqtZzPCrqqmpptg52kc40467KL
# 9OBgfCzfiG8C0VBOEgA0EfGF57KfH8I1K8+f8CmrV3IQCv0RSwR2tJNPLL+Obilx
# 6x/oPKL0cwAlxu8LEJiuMA+ZQ4akdL8kaFFvX1TqZndY+hNvp2dPboTQBVX7be/D
# T90/q6e/wxEuCjskYTv0iI4euuPQberfRwBZEwybkKHNGQ9EdA0umk7DqTA3qGBe
# kGUxMOHyscTKOf0BfqZhpadXoTNk+7uA+qfDh6PCKsztCK9CiKhMrp49rk+rGcac
# GRmC/nIJxqZwUbKXODhTZymdylXwnBpr8sQAdOUeu9ay0wVzV+tBgbhc1z8ahZdw
# 1h2A0VukLgttPx1q4MA4FE27xSVotJm7A64NHo5EexgvMIU/kyG6XuEdv+ix5u0u
# 4v5lRbeEMxUqKkOvo11UMNq1LClFwBkbbGCHtNv9qpLxMS/JNxeGDSphSLLLULcR
# IgHVFiU=
# SIG # End signature block
