define([], function () {
  return {
    BarLabel: 'Bar',
    BudgetTotalLabel: 'Budget total',
    CategoryFieldLabel: 'Category',
    ColumnRenderOptionDate: 'Date',
    CostsTotalLabel: 'Total costs',
    CurrentPhaseLabel: 'Current phase',
    DescriptionFieldLabel: 'Description',
    DiamondLabel: 'Diamond',
    EndDateLabel: 'End date',
    FilterText: 'Filter',
    GroupByLabel: 'Group by',
    LastPublishedStatusreport: 'Go to the latest published status report',
    LoadingText: 'Loading...',
    MilestoneDateLabel: 'Milestone date',
    MilestoneLabel: 'Milestone',
    NameLabel: 'Name',
    PhaseLabel: 'Phase',
    ProjectLabel: 'Project',
    ProjectTimelineErrorTransformItemText: 'Error when associating items to the timeline.<br><br>This may be due to a problem with an item in the "Projects" list (duplicate, deleted project), or that a timeline element does not have a valid project association. <br><br>- SiteId: {0} <br> - Title: {1} <br> - Type: {2} <br><br>Error message: {3}',
    ProjectTimelineInfoText: 'All projects with start and end dates are listed here. The project timeline also supports phases, subphases and milestones. To zoom in/out in the timeline: ALT+Mouse wheel.',
    ProjectTimelineItemInfo: '{0} - the project\'s lifetime',
    SiteTitleLabel: 'Project',
    StartDateLabel: 'Start date',
    SubPhaseLabel: 'Sub phase',
    TagFieldLabel: 'Label',
    TriangleLabel: 'Triangle',
    TypeLabel: 'Type',
  }
})
