define([], function () {
  return {
    'BarLabel': 'Bar',
    'BudgetTotalLabel': 'Budget total',
    'CategoryFieldLabel': 'Category',
    'ColumnRenderOptionDate': 'Date',
    'CostsTotalLabel': 'Total costs',
    'CurrentPhaseLabel': 'Current phase',
    'DescriptionFieldLabel': 'Description',
    'DiamondLabel': 'Diamond',
    'EndDateLabel': 'End date',
    'FilterText': 'Filter',
    'GroupByLabel': 'Group by',
    'LastPublishedStatusreport': 'Go to the last published status report',
    'LoadingText': 'Loading...',
    'MilestoneDateLabel': 'Milestone date',
    'MilestoneLabel': 'Milestone',
    'NameLabel': 'Name',
    'PhaseLabel': 'Phase',
    'ProjectLabel': '  Project',
    'ProjectTimelineErrorTransformItemText': 'Error when linking items to timeline.<br><br>This may be due to a problem with an item in the "Projects" list (duplicate, deleted project), or that a timeline element does not have a valid connection. <br><br>- SiteId: {0} <br> - Title: {1} <br> - Type: {2} <br><br>Error message: {3}',
    'ProjectTimelineInfoText': 'All projects with start and end dates are listed here. The project timeline also supports phases, subphases and milestones, this is created in the <A HREF="../Lists/Tidslinjeinnhold/AllItems.aspx?Source={0}">central timeline content list</A>. Projects are shown in red, phases in blue, partial phases in blue-green, and milestones in yellow. To zoom in/out in timeline: ALT+Mouse wheel.',
    'ProjectTimelineItemInfo': '{0} - the project time course',
    'SiteTitleLabel': 'Project',
    'StartDateLabel': 'Start date',
    'SubPhaseLabel': 'Sub phase',
    'TagFieldLabel': 'Label',
    'TriangleLabel': 'Triangle',
    'TypeLabel': 'Type',
  }
})
