define([], function () {
  return {
    NoAccessToPortfolioErrorTitle: 'No access to portfolio',
    NoAccessToPortfolioErrorText: 'Du har ikke tilgangen til porteføljen for området {0}. Ta kontakt med en administrator.',
    GtModerationStatus_Choice_Draft: 'Draft',
    GtModerationStatus_Choice_Published: 'Published',
    SaveText: 'Save',
    CloseText: 'Close',
    Aria: {
      InfoLabelTitle: 'Information about {0}',
      MenuOverflowCount: '{0} more items',
      ProjectTitle: 'Logo for project: {0}',
      SaveTitle: 'Save',
      SaveDisabledTitle: 'There are required fields that are not filled out, fill these out to save'
    },
    Placeholder: {
      DatePicker: 'Enter a date',
      TextField: 'Enter value here',
      UrlField: 'Enter a URL',
      UrlFieldAlternative: 'Alternative text',
      TaxonomyPicker: 'Enter the term to be tagged',
      PeoplePicker: 'Enter a name or an email address',
      NumberField: 'Enter a number',
      ChoiceField: 'Select an option',
      MultiChoiceField: 'Select one or more options',
    },
    AllocationPercetageLabel: 'Allocation percentage',
    AllocationStatusLabel: 'Allocation status',
    BarLabel: 'Bar',
    BudgetTotalLabel: 'Total budget',
    CategoryFieldLabel: 'Category',
    ColumnRenderOptionDate: 'Date',
    CommentLabel: 'Comment',
    CostsTotalLabel: 'Total costs',
    CurrentPhaseLabel: 'Current phase',
    DescriptionFieldLabel: 'Description',
    DiamondLabel: 'Diamant',
    EndDateLabel: 'End date',
    ErrorTitle: 'An error occurred',
    FiltersString: 'Filters',
    FilterText: 'Filter',
    FilterPanelEmptyTitle: 'No data to filter',
    FilterPanelEmptyMessage: 'There is no data to filter. This may be because no filters are defined, or that there is no data to filter.',
    GroupByLabel: 'Group by',
    LastPublishedStatusreport: 'Go to last published status report',
    LoadingText: 'Loading...',
    MilestoneDateLabel: 'Date of milestone',
    MilestoneLabel: 'Milestone',
    NameLabel: 'Name',
    PhaseLabel: 'Phase',
    ProjectLabel: 'Project',
    ProjectTimelineErrorTransformItemText: 'Error when linking items to timeline.<br><br>This may be due to a problem with an item in the "Projects" list (duplicate, deleted project), or that a timeline item does not have a valid link. <br><br>- SiteId: {0} <br> - Title: {1} <br> - Type: {2} <br><br>Error message: {3}',
    ProjectTimelineInfoText: 'Here is a list of all projects with start and end date. The project timeline also supports phases, sub-phases and milestones. To zoom in/out in the timeline: ALT+Mouse wheel.',
    ProjectTimelineTitle: 'Project timeline',
    ProjectTimelineItemInfo: '{0} - project timeline',
    ResourceLabel: 'Resource',
    RoleLabel: 'Role',
    SiteTitleLabel: 'Project',
    StartDateLabel: 'Start date',
    SubPhaseLabel: 'Sub-phase',
    TagFieldLabel: 'Label',
    TimelineGroupDescription: 'Go to project timeline',
    TriangleLabel: 'Triangle',
    TypeLabel: 'Type',
    SyncListAddingField:'Adding field {0} to project properties...',
    BooleanYes: 'Yes',
    BooleanNo: 'No',
  }
})
