declare interface ISharedLibraryStrings {
  NoAccessToPortfolioErrorTitle: string
  NoAccessToPortfolioErrorText: string
  BooleanYes: string
  BooleanNo: string
  SaveText: string
  CloseText: string
  Aria: {
    InfoLabelTitle: string
    MenuOverflowCount: string
    ProjectTitle: string
    SaveTitle: string
    SaveDisabledTitle: string
  }
  Placeholder: {
    DatePicker: string
    TextField: string
    UrlField: string
    UrlFieldAlternative: string
    TaxonomyPicker: string
    PeoplePicker: string
    NumberField: string
    ChoiceField: string
    MultiChoiceField: string
  },
  Validation: {
    NumberFieldMin: string
    NumberFieldMax: string
    NumberFieldMinMax: string
    UrlFieldInvalidFormat: string
  },
  AllocationPercetageLabel: string
  AllocationStatusLabel: string
  BudgetTotalLabel: string
  CategoryFieldLabel: string
  ColumnRenderOptionDate: string
  CommentLabel: string
  CostsTotalLabel: string
  CurrentPhaseLabel: string
  DescriptionFieldLabel: string
  EndDateLabel: string
  ErrorTitle: string
  FiltersString: string
  FilterText: string
  FilterPanelEmptyTitle: string
  FilterPanelEmptyMessage: string
  GroupByLabel: string
  LastPublishedStatusreport: string
  LoadingText: string
  MilestoneDateLabel: string
  NameLabel: string
  ProjectTimelineErrorTransformItemText: string
  ProjectTimelineInfoText: string
  ProjectTimelineTitle: string
  ProjectTimelineItemInfo: string
  ProgramTimelineTitle: string
  ResourceLabel: string
  ResourceAbsenceLabel: string
  DepartmentLabel: string
  RoleLabel: string
  SiteTitleLabel: string
  StartDateLabel: string
  TagFieldLabel: string
  TimelineGroupDescription: string
  TypeLabel: string
  SyncListAddingField: string
  // ItemColumn strings
  ColumnPersistRenderGloballyFieldLabel: string
  ColumnPersistRenderGloballyFieldDescription: string
  ColumnRenderOptionText: string
  ColumnRenderOptionNote: string
  ColumnRenderOptionBoolean: string
  ColumnRenderOptionBooleanTrue: string
  ColumnRenderOptionBooleanFalse: string
  ColumnRenderOptionCurrency: string
  ColumnRenderOptionCurrencyFallbackValueLabel: string
  ColumnRenderOptionCurrencyMaximumFractionDigitsLabel: string
  ColumnRenderOptionCurrencyMinimumFractionDigitsLabel: string
  ColumnRenderOptionCurrencyPrefixLabel: string
  ColumnRenderOptionDateIncludeTimeLabel: string
  ColumnRenderOptionDialog: string
  ColumnRenderOptionDialogLinkTextLabel: string
  ColumnRenderOptionDialogShowInfoTextLabel: string
  ColumnRenderOptionDialogInfoTextTemplateLabel: string
  ColumnRenderOptionDialogInfoTextTemplateDescription: string
  ColumnRenderOptionFilename: string
  ColumnRenderOptionInstrument: string
  ColumnRenderOptionNumber: string
  ColumnRenderOptionPercentage: string
  ColumnRenderOptionProjectInfo: string
  ColumnRenderOptionStatusReport: string
  ColumnRenderOptionTags: string
  ColumnRenderOptionTagsValueSeparatorLabel: string
  ColumnRenderOptionTagsValueSeparatorDescription: string
  ColumnRenderOptionTrend: string
  ColumnRenderOptionTrendShowTrendIconLabel: string
  ColumnRenderOptionUrl: string
  ColumnRenderOptionUrlOpenInNewTabLabel: string
  ColumnRenderOptionUrlDescriptionLabel: string
  ColumnRenderOptionUrlDescriptionDescription: string
  ColumnRenderOptionUser: string
  ColumnRenderOptionCalculated: string
  HideDataTypePropertiesLabel: string
  ShowDataTypePropertiesLabel: string
  InstrumentUnitLabel: string
  MeasurementValueLabel: string
  MeasurementCommentLabel: string
  MeasurementAchievementLabel: string
  MeasurementDateLabel: string
  ModalColumnEmptyListTitle: string
  ModalColumnEmptyListMessage: string
  ShowAllMeasurementsLinkText: string
  ShowInstrumentLinkText: string
  ProjectInformationPanelButton: string
  MeasurementSheetName: string
}

declare module 'SharedLibraryStrings' {
  const strings: ISharedLibraryStrings
  export = strings
}
