define([], function () {
  return {
    NoAccessToPortfolioErrorTitle: 'Ingen tilgang til portefølje',
    NoAccessToPortfolioErrorText: 'Du har ikke tilgangen til porteføljen for området {0}. Ta kontakt med en administrator.',
    SaveText: 'Lagre',
    CloseText: 'Lukk',
    Aria: {
      InfoLabelTitle: 'Informasjon om {0}',
      MenuOverflowCount: '{0} flere elementer',
      ProjectTitle: 'Logo for prosjekt: {0}',
      SaveTitle: 'Lagre',
      SaveDisabledTitle: 'Det er påkrevde felter som ikke er utfylt, fyll ut disse for å lagre',
    },
    Placeholder: {
      DatePicker: 'Angi en dato',
      TextField: 'Angi verdi her',
      UrlField: 'Angi en nettadresse',
      UrlFieldAlternative: 'Alternativ tekst',
      TaxonomyPicker: 'Skriv inn termen som skal merkes',
      PeoplePicker: 'Angi et navn eller en e-postadresse',
      NumberField: 'Skriv inn et tall',
      ChoiceField: 'Velg et alternativ',
      MultiChoiceField: 'Velg ett eller flere alternativer',
    },
    AllocationPercetageLabel: 'Allokeringsprosent',
    AllocationStatusLabel: 'Allokeringsstatus',
    BudgetTotalLabel: 'Totalbudsjett',
    CategoryFieldLabel: 'Kategori',
    ColumnRenderOptionDate: 'Dato',
    CommentLabel: 'Kommentar',
    CostsTotalLabel: 'Totalkostnader',
    CurrentPhaseLabel: 'Gjeldende fase',
    DescriptionFieldLabel: 'Beskrivelse',
    EndDateLabel: 'Sluttdato',
    ErrorTitle: 'Det har oppstått en feil',
    FiltersString: 'Filtre',
    FilterText: 'Filtrer',
    FilterPanelEmptyTitle: 'Ingen data å filtrere på',
    FilterPanelEmptyMessage: 'Det er ingen data å filtrere på. Det kan være at ingen filtre er definert, eller at det ikke er noe data å filtrere på.',
    GroupByLabel: 'Grupper etter',
    LastPublishedStatusreport: 'Gå til siste statusrapport',
    LoadingText: 'Laster...',
    MilestoneDateLabel: 'Dato for milepæl',
    NameLabel: 'Navn',
    ProjectTimelineErrorTransformItemText: 'Feil ved knytning av elementer til tidslinje.<br><br>Dette kan være grunnet problem med et element i "Prosjekter" listen (duplikat, slettet prosjekt), eller at et tidslinjeelement ikke har gyldig tilknytning. <br><br>- SiteId: {0} <br> - Tittel: {1} <br> - Type: {2} <br><br>Feilmelding: {3}',
    ProjectTimelineInfoText: 'Her listes alle prosjektene med start- og sluttdato. Prosjekttidslinjen støtter også faser, delfaser og milepæler. For å zoome inn/ut i tidslinje: ALT+Musehjul.',
    ProjectTimelineTitle: 'Prosjekttidslinje',
    ProjectTimelineItemInfo: '{0} - prosjektets tidsforløp',
    ProgramTimelineTitle: 'Programtidslinje',
    ResourceLabel: 'Ressurs',
    ResourceAbsenceLabel: 'Ressurs (fravær)',
    DepartmentLabel: 'Avdeling',
    RoleLabel: 'Rolle',
    SiteTitleLabel: 'Prosjekt',
    StartDateLabel: 'Startdato',
    TagFieldLabel: 'Etikett',
    TimelineGroupDescription: 'Gå til tidslinje for prosjektet',
    TypeLabel: 'Type',
    SyncListAddingField: 'Legger til felt {0} i prosjektegenskaper...',
    BooleanYes: 'Ja',
    BooleanNo: 'Nei',
    // ItemColumn strings
    ColumnPersistRenderGloballyFieldLabel: 'Oppdater visningsmodus globalt',
    ColumnPersistRenderGloballyFieldDescription: 'Om du ønsker å endre visningsmodus for kolonnen globaly, for alle webdeler og visninger, huk av sjekkboksen over. (Dette gjelder kun visningsmodus)',
    ColumnRenderOptionText: 'Tekst',
    ColumnRenderOptionNote: 'Notat',
    ColumnRenderOptionBoolean: 'Ja/nei',
    ColumnRenderOptionBooleanTrue: 'Verdi for \'Ja\'',
    ColumnRenderOptionBooleanFalse: 'Verdi for \'Nei\'',
    ColumnRenderOptionCurrency: 'Valuta',
    ColumnRenderOptionCurrencyFallbackValueLabel: 'Standardverdi',
    ColumnRenderOptionCurrencyMaximumFractionDigitsLabel: 'Maksimalt antall desimaler',
    ColumnRenderOptionCurrencyMinimumFractionDigitsLabel: 'Minimum antall desimaler',
    ColumnRenderOptionCurrencyPrefixLabel: 'Valutaprefiks',
    ColumnRenderOptionDateIncludeTimeLabel: 'Inkluder tidspunkt',
    ColumnRenderOptionDialog: 'Modal',
    ColumnRenderOptionDialogLinkTextLabel: 'Tekst for lenke',
    ColumnRenderOptionDialogShowInfoTextLabel: 'Vis infotekst',
    ColumnRenderOptionDialogInfoTextTemplateLabel: 'Mal for infotekst',
    ColumnRenderOptionDialogInfoTextTemplateDescription: 'Mal for infotekst. Bruk {{GtMeasurementOWSCHCS}} for å vise måleindikatoren, {{GtStartValueOWSNMBR}} for å vise startverdien og {{GtDesiredValueOWSNMBR}} for å vise målet. Du kan også bruke andre kolonnenavn fra gevinstarbeidet.',
    ColumnRenderOptionFilename: 'Filnavn',
    ColumnRenderOptionInstrument: 'Instrument',
    ColumnRenderOptionNumber: 'Tall',
    ColumnRenderOptionPercentage: 'Prosent',
    ColumnRenderOptionProjectInfo: 'Prosjektinformasjon',
    ColumnRenderOptionStatusReport: 'Statusrapport',
    ColumnRenderOptionTags: 'Etiketter',
    ColumnRenderOptionTagsValueSeparatorLabel: 'Separator for verdier',
    ColumnRenderOptionTagsValueSeparatorDescription: 'Angi et tegn som skal brukes for å skille verdier i etikettfeltet. Standard er semikolon.',
    ColumnRenderOptionTrend: 'Trend',
    ColumnRenderOptionTrendShowTrendIconLabel: 'Vis ikon',
    ColumnRenderOptionUrl: 'URL',
    ColumnRenderOptionUrlOpenInNewTabLabel: 'Åpne i ny fane',
    ColumnRenderOptionUrlDescriptionLabel: 'Beskrivelse',
    ColumnRenderOptionUrlDescriptionDescription: 'Beskrivelse av lenken. Om du ikke angir en verdi, brukes eventuelt beskrivelse fra lenken.',
    ColumnRenderOptionUser: 'Person',
    HideDataTypePropertiesLabel: 'Skjul egenskaper for visningsmodus',
    ShowDataTypePropertiesLabel: 'Vis egenskaper for visningsmodus',
    InstrumentUnitLabel: 'Enhet: {0}',
    MeasurementValueLabel: 'Målt verdi',
    MeasurementCommentLabel: 'Kommentar til måling',
    MeasurementAchievementLabel: 'Måloppnåelse',
    MeasurementDateLabel: 'Dato for måling',
    ModalColumnEmptyListTitle: 'Ingen elementer funnet.',
    ModalColumnEmptyListMessage: 'Det ble ikke funnet noen elementer for denne dialogen.',
    ShowAllMeasurementsLinkText: 'Vis alle målinger',
    ShowInstrumentLinkText: '{0} (vis instrument)',
    ProjectInformationPanelButton: 'Åpne prosjektinformasjonspanel',
  }
})
