define([], function () {
  return {
    GtModerationStatus_Choice_Draft: 'Kladd',
    GtModerationStatus_Choice_Published: 'Publisert',
    SaveText: 'Lagre',
    CloseText: 'Lukk',
    Aria: {
      InfoLabelTitle: 'Informasjon om {0}',
      MenuOverflowCount: '{0} flere elementer',
      ProjectTitle: 'Logo for prosjekt: {0}',
      SaveTitle: 'Lagre',
      SaveDisabledTitle: 'Det er påkrevde felter som ikke er utfylt, fyll ut disse for å lagre',
    },
    Placeholder: {
      DatePicker: 'Angi en dato',
      TextField: 'Angi verdi her',
      UrlField: 'Angi en nettadresse',
      UrlFieldAlternative: 'Alternativ tekst',
      TaxonomyPicker: 'Skriv inn termen som skal merkes',
      PeoplePicker: 'Angi et navn eller en e-postadresse',
      NumberField: 'Skriv inn et tall',
      ChoiceField: 'Velg et alternativ',
      MultiChoiceField: 'Velg ett eller flere alternativer',
    },
    AllocationPercetageLabel: 'Allokeringsprosent',
    AllocationStatusLabel: 'Allokeringsstatus',
    BarLabel: 'Bar',
    BudgetTotalLabel: 'Totalbudsjett',
    CategoryFieldLabel: 'Kategori',
    ColumnRenderOptionDate: 'Dato',
    CommentLabel: 'Kommentar',
    CostsTotalLabel: 'Totalkostnader',
    CurrentPhaseLabel: 'Gjeldende fase',
    DescriptionFieldLabel: 'Beskrivelse',
    DiamondLabel: 'Diamant',
    EndDateLabel: 'Sluttdato',
    ErrorTitle: 'Det har oppstått en feil',
    FiltersString: 'Filtre',
    FilterText: 'Filtrer',
    FilterPanelEmptyTitle: 'Ingen data å filtrere på',
    FilterPanelEmptyMessage: 'Det er ingen data å filtrere på. Det kan være at ingen filtre er definert, eller at det ikke er noe data å filtrere på.',
    GroupByLabel: 'Grupper etter',
    LastPublishedStatusreport: 'Gå til siste statusrapport',
    LoadingText: 'Laster...',
    MilestoneDateLabel: 'Dato for milepæl',
    MilestoneLabel: 'Milepæl',
    NameLabel: 'Navn',
    PhaseLabel: 'Fase',
    ProjectLabel: 'Prosjekt',
    ProjectTimelineErrorTransformItemText: 'Feil ved knytning av elementer til tidslinje.<br><br>Dette kan være grunnet problem med et element i "Prosjekter" listen (duplikat, slettet prosjekt), eller at et tidslinjeelement ikke har gyldig tilknytning. <br><br>- SiteId: {0} <br> - Tittel: {1} <br> - Type: {2} <br><br>Feilmelding: {3}',
    ProjectTimelineInfoText: 'Her listes alle prosjektene med start- og sluttdato. Prosjekttidslinjen støtter også faser, delfaser og milepæler. For å zoome inn/ut i tidslinje: ALT+Musehjul.',
    ProjectTimelineTitle: 'Prosjekttidslinje',
    ProjectTimelineItemInfo: '{0} - prosjektets tidsforløp',
    ResourceLabel: 'Ressurs',
    RoleLabel: 'Rolle',
    SiteTitleLabel: 'Prosjekt',
    StartDateLabel: 'Startdato',
    SubPhaseLabel: 'Delfase',
    TagFieldLabel: 'Etikett',
    TimelineGroupDescription: 'Gå til tidslinje for prosjektet',
    TriangleLabel: 'Trekant',
    TypeLabel: 'Type',
  }
})
