define([], function () {
  return {
    SettingsGroupName: "Innstillinger",
    ViewsGroupName: "Visninger",
    LookAndFeelGroupName: "Utseende og funksjonalitet",
    PersistedPhasePropertyBagKey: "persisted_phase",
    PhaseFieldFieldLabel: "Felt",
    AutomaticReloadFieldLabel: "Automatisk oppdatering",
    ReloadTimeoutFieldLabel: "Forsinkelse (s)",
    FontSizeFieldLabel: "Skriftstørrelse",
    GutterFieldLabel: "Avstand mellom fasene",
    UpdateViewsDocumentsFieldLabel: "Opppdater Dokumenter",
    UpdateViewsRisksFieldLabel: "Oppdater Usikkerhet",
    CurrentPhaseViewNameFieldLabel: "Visningsnavn for gjeldende fase",
    ConfirmPhaseChangeFieldLabel: "Bekreft faseenendring",
    PhaseSubTextPropertyFieldLabel: "Egenskap for undertekst",
    ConfirmPhaseDialogTitle: "Endre fase",
    ConfirmPhaseDialogSubText: "Endring av fasen til {0} vil endre dette for alle, vil du fortsette?",
    PageReloadMessage: "Oppdater siden for å få oppdaterte listevisninger.",
    WebPartNotConfiguredMessage: "Webdelen er ikke konfigurert riktig. Du må angi webpartegenskaper riktig.",
    DocumentsListName: "Dokumenter",
    PhaseChecklistName: 'Fasesjekkliste',
    Yes: "Ja",
    No: "Nei",
    MoveOn: "Gå videre",
    Close: "Lukk",
    Skip: "Hopp over alle",
    CheckPointsMarkedAsText: "sjekkpunkter markert som",
    GoToPhaseChecklist: "Gå til fasesjekklisten",
    ChangePhaseText: "Endre til denne fasen",
    ConfirmChangePhase: "Vil du endre fase til {0}?",
    PhaseChecklistViewUrl: "Lists/Fasesjekkliste/AllItems.aspx",
    CheckpointNotRelevantTooltipCommentEmpty: "Du kan ikke sette sjekkpunktet som 'Ikke relevant' uten å legge inn enn kommentar.",
    CheckpointNotRelevantTooltip: "Sjekkpunktet er ikke relevant",
    CheckpointStillOpenTooltipCommentEmpty: "Du kan ikke sette sjekkpunktet som 'Fortsatt åpen' uten å legge inn enn kommentar.",
    CheckpointStillOpenTooltip: "Sjekkpunktet er forsatt åpent",
    CheckpointDoneTooltip: "Sjekkpunktet er utført",
    StatusNotRelevant: "Ikke relevant",
    StatusOpen: "Åpen",
    StatusStillOpen: "Forsatt åpen",
    StatusClosed: "Utført",
    CommentLabel: "Kommentar",
    ChangingPhaseLabel: "Vennligst vent",
    ChangingPhaseDescription: "Endrer fase til {0}",
    LoadingText: "Laster fasevelger...",
  }
});