define([], function () {
    return {
        ApplyExtensionHooks: 'Running hooks defined in project extension',
        ApplyExtensionText: 'Applying project extension {0}',
        ApplyingExtensionsText: 'Applying project extensions',
        ApplyTemplateClientSidePages: 'Applying files and web parts',
        ApplyTemplateComposedLook: 'Applying color and fonts',
        ApplyTemplateContentTypes: 'Applying content types',
        ApplyTemplateErrorMessage: 'An error occurred in step {0} during configuration of the site',
        ApplyTemplateFiles: 'Appyling files and web parts',
        ApplyTemplateHooks: 'Running hooks defined in the project template',
        ApplyTemplateLists: 'Appyling lists with fields, content types and views',
        ApplyTemplateNavigation: 'Appyling navigation',
        ApplyTemplateSiteFields: 'Appyling fields',
        ApplyTemplateText: 'Applying template {0}',
        ApplyTemplateWebSettings: 'Appyling web settings',
        CloseModalText: 'Close',
        CmdSelectionCountText: '{0} are selected',
        CmdSelectionCountTooltipText: 'The following items have been selected:',
        ConfiguredSpecifiedTaskMessage: 'Configured to run only the following steps: {0}',
        ContentConfigLockedTooltipText: 'The default content element is locked and cannot be unselected.',
        ContentConfigSectionHeaderText: 'Default content',
        ContentConfigSectionSearchPlaceholder: 'Search default content...',
        ContinueToProjectText: 'Continue to project',
        CopyFilesText: 'Copying {0} documents/folders from {1} to {2}',
        CopyHereText: 'Copy here',
        CopyListDataErrorMessage: 'An error occurred while copying list data',
        CopyListItemsText: 'Copying {0} list items from {1} to {2}',
        CopyProgressLabel: 'Copying selected document(s) to the project...',
        CreatingLocalProjectPropertiesListItemText: 'Creating list item for project properties',
        CreatingPlannerTaskText: 'Creating tasks for {0}',
        CustomActionsSubText: 'Adjusting custom actions for the project...',
        CustomActionsText: 'Custom actions',
        DescriptionLabel: 'Description',
        DocumentTemplateDialogScreenEditCopyInfoMessage: 'Here you can set **Filename** and **Title** for the documents to be copied over.<br /><br />When you are finished, press **Start copy** to start copying.',
        DocumentTemplateDialogScreenSelectInfoMessage: 'Select the document templates you want to copy to the project.<br /><br />The templates are retrieved from <a href="{0}" target="_blank">{1}</a> and the **latest version** is retrieved.<br /><br />When you press **Select** you are forwarded to a screen where you select the destination you wish to copy to.',
        DocumentTemplateDialogScreenTargetFolderInfoMessage: 'Select the target for the selected templates. If there is more than one document library, you can press **Library** to select another library.<br /><br />When you press **Copy here**, you are forwarded to a screen where you can set a title and file names for the templates that are copied over.',
        ExtensionLockedTooltipText: 'The project extention is locked and cannot be unselected.',
        ExtensionsSectionHeaderText: 'Project extentions',
        ExtensionsSectionSearchPlaceholder: 'Search project extentions...',
        FilenameAlreadyInUseErrorText: 'The filename is already in use.',
        FilenameInValidErrorText: 'The filename is invalid.',
        FileNameLabel: 'Filename',
        GetMoreText: 'Get more',
        GetSetupDataErrorMessage: 'An error occured',
        GetSetupDataErrorStack: 'An error occurred while retrieving data from the hub site. If the Project Portal has recently been installed, this may be the reason. Try again a little later.',
        InvalidLanguageErrorMessage: 'Invalid language for the site. The site must be the same language as the hub site.',
        InvalidLanguageErrorStack: 'The language set for the site is not supported. The site must be created with Norwegian language.',
        IsHubSiteErrorMessage: 'Cannot apply the project template on a hub site',
        IsHubSiteErrorStack: 'It is not possible to add site designs for projects to a hub site. Operation aborted.',
        Library: 'Library',
        LibraryDropdownLabel: 'Library',
        ModifiedLabel: 'Modified',
        NameLabel: 'Name',
        NoHubSiteErrorMessage: 'The SharePoint site is not connected to a hub site',
        NoHubSiteErrorStack: 'The SharePoint site cannot be set up without being connected to a hub site. Link the site to a portfolio hub site and reload the page.<br/><br/>Go to `Settings`, find `Site Information` and select hub/portfolio under `Link to hub site`.',
        OnGoBackText: 'Go back',
        OnStartCopyText: 'Start copy',
        OnSubmitSelectionText: 'Select',
        PermissionConfigurationList: 'Permission configuration',
        PhaseLabel: 'Phase',
        PlannerConfigurationErrorMessage: 'An error occurred while creating default tasks in Planner. Try again by reloading the page.',
        PlannerConfigurationText: 'Creating default tasks in planner',
        PlannerTagsLimitLogText: 'Unable to add more than 25 labels to planner "{0}", removing excess labels.',
        PlannerTaskAttachmentLimitLogText: 'Unable to add more than 10 attachments to task "{0}", removing excess attachments.',
        PlannerTaskChecklistLimitLogText: 'Unable to add more than 20 items to checklist for task "{0}", removing excess items.',
        PreTaskContentTypeValidationErrorMessage: 'Content type validation failed. check that the project properties and project status content types are correct in the template setup.',
        PreTaskErrorMessage: 'An error occured',
        PreTaskTermSetIdValidationErrorMessage: 'Phase term set validation failed.',
        ProcessFileText: 'Copying file {0} of {1}',
        ProcessFolderText: 'Copying folder {0} of {1}',
        ProcessListItemText: 'Processing batch {0} with {1} list items',
        ProgressDialogDescription: 'Please wait. Do not close the browser window - then the project will not be set up correctly.',
        ProgressDialogLabel: 'Preparing the project',
        ProgressDialogSubText: 'Please wait. Do not close the browser window - then the project will not be set up correctly.',
        ProgressDialogTitle: 'Setter opp prosjektområdet',
        ProjectAlreadySetupMessage: 'The project is already set up',
        ProjectAlreadySetupStack: 'It seems that the project is already set up. Do you want to apply a template (not recommended) or skip setup?',
        ProjectPropertiesListName: 'Prosjektegenskaper',
        ProjectProvisioningStartLogText: 'Starting provisioning of the project {0}.',
        ProjectProvisioningSuccessLogText: 'The project {0} was provisioned without error.',
        ProjectTemplateFilesListName: 'Prosjektmaler',
        ProvisionSiteFieldsErrorMessage: 'An error occurred while provisioning site columns',
        ProvisionSiteFieldsText: 'Creating site columns',
        ProvisionSiteFieldText: 'Created field {0} on site',
        ProvisionTemplateText: 'Go to setup',
        RecycleBinText: 'Recycle bin',
        RunHooksText: 'Run hooks',
        SetTaxonomyFieldsErrorMessage: 'An error occurred while configuring taxonomy fields',
        SetupAbortedText: 'Installation abortet by user',
        SetupProjectInformationErrorMessage: 'An error occurred while initializing project properties',
        SetupProjectInformationText: 'Setting up project properties',
        SitePermissionsSubText: 'Copying permission configuration from hub site.',
        SitePermissionsText: 'Setting up permissions for the site',
        SummaryMessage: '{0} document(s) were copied to the project.',
        SyncLocalProjectPropertiesListText: 'Synchronizing list for project properties',
        TemplateConfigMessage: 'The selected project template **{0}** contains configuration for {1}. These are selected by default.',
        PlannerMemberWarningMessage: 'You must be a member of the Microsoft 365 group to configure Planner. Please add yourself as a member or ask an administrator and try again.',
        TemplateLibrarySelectModalTitle: 'Hent dokumentmal',
        TemplateSelectDialogInfoText: 'Setting up the project takes about 10 minutes. Do not close the browser window while the site is being set up. It is not recommended to set up several sites at the same time.',
        TemplateSelectDialogSubmitButtonText: 'Set up the site',
        TemplateSelectDialogTitle: 'Setup of the project',
        TemplateSelectorSearchClearText: 'Reset project template selection',
        TemplateSelectorSearchPlaceholder: 'Search project templates...',
        TemplateSelectorTitle: 'Project template',
        TermSetDoesNotExistError: 'Cannot find term set ID. Check that the term set ID is correct in the template setup.',
        TitleLabel: 'Title'
    }
})
