declare interface IProjectExtensionsStrings {
  RiskActionFieldValueNoTasks: string
  NewRiskActionPanelUpdateTaskStatus: string
  RiskActionPopoverInfoText: string
  RiskActionPopoverInfoTextNoPlanner: string
  StartDateLabel: string
  DueDateLabel: string
  NewRiskActionPanelTitle: string
  NewRiskActionPanelAddNewRiskAction: string 
  ResponsibleFieldNoResults: string
  ResponsibleFieldLabel: string
  ApplyExtensionHooks: string
  ApplyExtensionText: string
  ApplyingExtensionsText: string
  ApplyTemplateClientSidePages: string
  ApplyTemplateComposedLook: string
  ApplyTemplateContentTypes: string
  ApplyTemplateErrorMessage: string
  ApplyTemplateFiles: string
  ApplyTemplateHooks: string
  ApplyTemplateLists: string
  ApplyTemplateNavigation: string
  ApplyTemplateSiteFields: string
  ApplyTemplateText: string
  ApplyTemplateWebSettings: string
  CloseModalText: string
  CmdSelectionCountText: string
  CmdSelectionCountTooltipText: string
  ConfiguredSpecifiedTaskMessage: string
  ContentConfigLockedTooltipText: string
  ContentConfigSectionHeaderText: string
  ContentConfigSectionSearchPlaceholder: string
  ContinueToProjectText: string
  CopyFilesText: string
  CopyHereText: string
  CopyListDataErrorMessage: string
  CopyListItemsText: string
  CopyProgressLabel: string
  CreatingLocalProjectPropertiesListItemText: string
  CreatingPlannerTaskText: string
  CustomActionsSubText: string
  CustomActionsText: string
  DescriptionLabel: string
  DocumentTemplateDialogScreenEditCopyInfoText: string
  DocumentTemplateDialogScreenSelectInfoText: string
  DocumentTemplateDialogScreenTargetFolderInfoText: string
  ExtensionLockedTooltipText: string
  ExtensionsSectionHeaderText: string
  ExtensionsSectionSearchPlaceholder: string
  FilenameAlreadyInUseErrorText: string
  FilenameInValidErrorText: string
  FileNameLabel: string
  GetMoreText: string
  GetSetupDataErrorMessage: string
  GetSetupDataErrorStack: string
  IdeaDecisionStatusApprovedAndSynced: string
  InvalidLanguageErrorMessage: string
  InvalidLanguageErrorStack: string
  IsHubSiteErrorMessage: string
  IsHubSiteErrorStack: string
  Library: string
  LibraryDropdownLabel: string
  ModifiedLabel: string
  NameLabel: string
  NoHubSiteErrorMessage: string
  NoHubSiteErrorStack: string
  OnGoBackText: string
  OnStartCopyText: string
  OnSubmitSelectionText: string
  PermissionConfigurationList: string
  PhaseLabel: string
  PlannerConfigurationErrorMessage: string
  PlannerConfigurationText: string
  PlannerTagsLimitLogText: string
  PlannerTaskAttachmentLimitLogText: string
  PlannerTaskChecklistLimitLogText: string
  PreTaskContentTypeValidationErrorMessage: string
  PreTaskErrorMessage: string
  PreTaskTermSetIdValidationErrorMessage: string
  ProcessFileText: string
  ProcessFolderText: string
  ProcessListItemText: string
  ProgressDialogDescription: string
  ProgressDialogLabel: string
  ProgressDialogSubText: string
  ProgressDialogTitle: string
  ProjectAlreadySetupMessage: string
  ProjectAlreadySetupStack: string
  ProjectIdeaFoundText: string
  ProjectPropertiesListName: string
  ProjectProvisioningStartLogText: string
  ProjectProvisioningSuccessLogText: string
  ProjectTemplateFilesListName: string,
  ProvisionSiteFieldsErrorMessage: string
  ProvisionSiteFieldsText: string
  ProvisionSiteFieldText: string
  ProvisionTemplateText: string
  RecycleBinText: string
  RunHooksText: string
  SetTaxonomyFieldsErrorMessage: string
  SetupAbortedText: string
  SetupProjectInformationErrorMessage: string
  SetupProjectInformationText: string
  SitePermissionsSubText: string
  SitePermissionsText: string
  SummaryText: string
  SyncLocalProjectPropertiesListText: string
  TemplateConfigText: string
  TemplateLibrarySelectModalTitle: string
  TemplateSelectDialogInfoText: string
  TemplateSelectDialogSubmitButtonText: string
  TemplateSelectDialogTitle: string
  TemplateSelectorSearchClearText: string
  TemplateSelectorSearchPlaceholder: string
  TemplateSelectorTitle: string
  TermSetDoesNotExistError: string
  TitleLabel: string
}

declare module 'ProjectExtensionsStrings' {
  const strings: IProjectExtensionsStrings
  export = strings
}
