declare interface IProjectExtensionsStrings {
    ApplyExtensionText: any;
    ProcessListItemText: any;
    CreatingPlannerTaskText: any;
    ProvisionSiteFieldText: any;
  ProgressDialogSubText: string;
  ApplyTemplateText: string;
  ApplyingExtensionsText: string;
  ApplyTemplateClientSidePages: string;
  ApplyTemplateComposedLook: string;
  ApplyTemplateContentTypes: string;
  ApplyTemplateErrorMessage: string;
  ApplyTemplateFiles: string;
  ApplyTemplateLists: string;
  ApplyTemplateNavigation: string;
  ApplyTemplateSiteFields: string;
  ApplyTemplateWebSettings: string;
  CloseModalText: string;
  CopyListDataErrorMessage: string;
  CopyListDataText: string;
  CopyPlannerTasksLabel: string;
  CopyProgressLabel: string;
  EditPropertiesLinkText: string;
  ErrorDialogTitle: string;
  ExtensionsTitle: string;
  GetMoreText: string;
  GetSetupDataErrorMessage: string;
  GetSetupDataErrorStack: string;
  IncludeStandardFoldersLabel: string;
  InvalidLanguageErrorMessage: string;
  InvalidLanguageErrorStack: string;
  DocumentLibraryDropdownLabel: string;
  ListContentTitle: string;
  ModifiedLabel: string;
  NameLabel: string;
  NoHubSiteErrorMessage: string;
  NoHubSiteErrorStack: string;
  OnGoBackText: string;
  OnStartCopyText: string;
  OnSubmitSelectionText: string;
  PlannerConfigurationErrorMessage: string;
  PlannerConfigurationText: string;
  PreTaskErrorMessage: string;
  ProgressDialogDescription: string;
  ProgressDialogLabel: string;
  ProgressDialogTitle: string;
  ProjectPropertiesListName: string;
  ProvisionSiteFieldsErrorMessage: string;
  ProvisionSiteFieldsText: string;
  SetTaxonomyFieldsErrorMessage: string;
  SettingsTitle: string;
  SetupProjectInformationErrorMessage: string;
  SetupProjectInformationText: string;
  SiteFieldsGroupName: string;
  SiteNotReadyErrorMessage: string;
  SiteNotReadyErrorStack: string;
  SummaryText: string;
  TemplateLibrarySelectModalTitle: string;
  TemplateSelectDialogInfoText: string;
  TemplateSelectDialogSubmitButtonText: string;
  TemplateSelectDialogTitle: string;
  TemplateSelectorTitle: string;
  TitleLabel: string;
  DocumentTemplateDialogScreenSelectInfoText: string;
  DocumentTemplateDialogScreenEditCopyInfoText: string;
  FilenameAlreadyInUseErrorText: string;
  FilenameInValidErrorText: string;
  SyncLocalProjectPropertiesListText: string;
  CreatingLocalProjectPropertiesListItemText: string;
  PhaseLabel: string;
}

declare module 'ProjectExtensionsStrings' {
  const strings: IProjectExtensionsStrings;
  export = strings;
}