declare interface IProjectExtensionsStrings {
  CopyHereText: string
  DocumentTemplateDialogScreenEditCopyRootLevelText: string
  ApplyExtensionText: string;
  ProcessListItemText: string;
  ProcessFileText: string;
  ProcessFolderText: string;
  CreatingPlannerTaskText: string;
  ProvisionSiteFieldText: string;
  ProgressDialogSubText: string;
  ApplyTemplateText: string;
  ApplyingExtensionsText: string;
  ApplyTemplateClientSidePages: string;
  ApplyTemplateComposedLook: string;
  ApplyTemplateContentTypes: string;
  ApplyTemplateErrorMessage: string;
  ApplyTemplateFiles: string;
  ApplyTemplateLists: string;
  ApplyTemplateNavigation: string;
  ApplyTemplateSiteFields: string;
  ApplyTemplateWebSettings: string;
  CloseModalText: string;
  CopyListDataErrorMessage: string;
  CopyListItemsText: string;
  CopyFilesText: string;
  CopyProgressLabel: string;
  EditPropertiesLinkText: string;
  ErrorDialogTitle: string;
  ExtensionsTitle: string;
  GetMoreText: string;
  GetSetupDataErrorMessage: string;
  GetSetupDataErrorStack: string;
  IncludeStandardFoldersLabel: string;
  IncludeStandardFoldersDescription: string;
  IncludePortfolioAdministratorsLabel: string;
  IncludePortfolioAdministratorsDescription: string;
  InvalidLanguageErrorMessage: string;
  InvalidLanguageErrorStack: string;
  DocumentLibraryDropdownLabel: string;
  FolderDropdownLabel: string;
  ListContentTitle: string;
  ModifiedLabel: string;
  NameLabel: string;
  NoHubSiteErrorMessage: string;
  NoHubSiteErrorStack: string;
  OnGoBackText: string;
  OnStartCopyText: string;
  OnSubmitSelectionText: string;
  PlannerConfigurationErrorMessage: string;
  PlannerConfigurationText: string;
  PreTaskErrorMessage: string;
  ProgressDialogDescription: string;
  ProgressDialogLabel: string;
  ProgressDialogTitle: string;
  ProjectPropertiesListName: string;
  ProvisionSiteFieldsErrorMessage: string;
  SitePermissionsErrorMessage: string;
  ProvisionSiteFieldsText: string;
  SetTaxonomyFieldsErrorMessage: string;
  SettingsSectionTitle: string;
  SetupProjectInformationErrorMessage: string;
  SetupProjectInformationText: string;
  SummaryText: string;
  TemplateLibrarySelectModalTitle: string;
  TemplateSelectDialogInfoText: string;
  TemplateSelectDialogSubmitButtonText: string;
  TemplateSelectDialogTitle: string;
  TemplateSelectorTitle: string;
  TitleLabel: string;
  DocumentTemplateDialogScreenSelectInfoText: string;
  DocumentTemplateDialogScreenEditCopyInfoText: string;
  FilenameAlreadyInUseErrorText: string;
  FilenameInValidErrorText: string;
  SyncLocalProjectPropertiesListText: string;
  CreatingLocalProjectPropertiesListItemText: string;
  PhaseLabel: string;
  SetupAbortedText: string;
  UnknownErrorText: string;
  TemplateListContentConfigText: string;
}

declare module 'ProjectExtensionsStrings' {
  const strings: IProjectExtensionsStrings
  export = strings
}
