define([], function () {
  return {
    CopyHereText: 'Kopier hit',
    ApplyTemplateText: 'Legger på mal {0}',
    ApplyingExtensionsText: 'Legger på prosjekttilegg',
    ApplyExtensionText: 'Legger på prosjekttilegg {0}',
    ApplyTemplateClientSidePages: 'Legger inn filer og webdeler',
    ApplyTemplateComposedLook: 'Legger på farge og fonter',
    ApplyTemplateContentTypes: 'Legger inn innholdstyper',
    ApplyTemplateErrorMessage: 'Det skjedde en feil under konfigurering av området',
    ApplyTemplateFiles: 'Legger inn filer og webdeler',
    ApplyTemplateLists: 'Legger inn lister med felter, innholdstyper og visninger',
    ApplyTemplateNavigation: 'Legger inn navigasjon',
    ApplyTemplateSiteFields: 'Legger inn felter',
    ApplyTemplateWebSettings: 'Legger inn webinstillinger',
    CloseModalText: 'Lukk',
    CopyListDataErrorMessage: 'Det skjedde en feil under kopiering av listeinnhold',
    CopyListItemsText: 'Kopierer {0} listeelementer fra {1} til {2}',
    CopyFilesText: 'Kopierer {0} dokumenter/mapper fra {1} til {2}',
    IncludePortfolioAdministratorsLabel: 'Gi tilgang til porteføljeadministratorer',
    IncludePortfolioAdministratorsDescription: 'Porteføljeadministratorer (brukerne i gruppen Porteføljeadministratorer) får tilgang til prosjektområdet.',
    CopyProgressLabel: 'Kopierer valgt(e) dokument(er) til prosjektområdet...',
    EditPropertiesLinkText: 'Du kan allerede nå<A HREF=\'{0}\' TARGET=\'_BLANK\'>redigere egenskaper</A> for prosjektet (åpnes i ny fane).',
    ErrorDialogTitle: 'Noe er galt',
    ExtensionsTitle: 'Prosjekttillegg',
    GetMoreText: 'Hent flere',
    GetSetupDataErrorMessage: 'Det skjedde en feil',
    GetSetupDataErrorStack: 'Det skjedde en feil under uthenting av data fra hubområdet.',
    IncludeStandardFoldersLabel: 'Inkluder standardmapper',
    InvalidLanguageErrorMessage: 'Ugyldig språk for området',
    InvalidLanguageErrorStack: 'Språket som er satt for området støttes ikke. Området må være opprettet med norsk språk.',
    LibraryDropdownLabel: 'Bibliotek',
    ListContentTitle: 'Standardinnhold',
    ModifiedLabel: 'Endret',
    NameLabel: 'Filnavn',
    NoHubSiteErrorMessage: 'Området er ikke koblet til en hub',
    NoHubSiteErrorStack: 'Området kan ikke settes opp uten å være koblet til en hub. Koble området til ett hubområde, og last siden på nytt.<br/><br/>Gå til `Innstillinger` (tannhjulet i øvre høyre hjørne), finn `Nettstedsinformasjon` og velg hub/portefølje under `Tilknytning til hubområde`.',
    OnGoBackText: 'Gå tilbake',
    OnStartCopyText: 'Start kopiering',
    OnSubmitSelectionText: 'Velg',
    PlannerConfigurationErrorMessage: 'Det skjedde en feil under opprettelse av standardoppgaver i Planner. Prøv igjen ved å laste siden på nytt.',
    PlannerConfigurationText: 'Oppretter standardoppgaver i Planner',
    PreTaskErrorMessage: 'Det skjedde en feil',
    ProgressDialogDescription: 'Vennligst vent. Ikke lukk nettleservinduet.',
    ProgressDialogLabel: 'Klargjør prosjektområdet',
    ProgressDialogTitle: 'Setter opp prosjektområdet',
    ProjectPropertiesListName: 'Prosjektegenskaper',
    ProvisionSiteFieldsErrorMessage: 'Det skjedde en feil under provisjonering av områdekolonner',
    SitePermissionsErrorMessage: 'Det skjedde en feil under oppsett av områdetilganger',
    ProvisionSiteFieldsText: 'Oppretter områdekolonner',
    SetTaxonomyFieldsErrorMessage: 'Det skjedde en feil under konfigurering av taksonomifelter',
    SettingsSectionTitle: 'Innstillinger',
    SetupProjectInformationErrorMessage: 'Det skjedde en feil under initialisering av prosjektegenskaper',
    SetupProjectInformationText: 'Setter opp prosjektegenskaper',
    SummaryText: '{0} dokument(er) ble kopiert til prosjektområdet.',
    TemplateLibrarySelectModalTitle: 'Hent dokumentmal',
    TemplateSelectDialogInfoText: 'Oppsettet av prosjektområdet tar omtrent 10 minutter.\n\nIkke lukk nettleservinduet mens området settes opp.',
    TemplateSelectDialogSubmitButtonText: 'Sett opp området',
    TemplateSelectDialogTitle: 'Oppsett av prosjektområde',
    TemplateSelectorTitle: 'Prosjektmal',
    TitleLabel: 'Tittel',
    ProgressDialogSubText: 'Vennligst vent. Ikke lukk nettleservinduet.',
    DocumentTemplateDialogScreenSelectInfoText: 'Velg dokumentmalene du vil kopiere til prosjektområdet.<br /><br />Malene hentes fra<a href="{0}" target="_blank">{1}</a> og det hentes _siste versjon_ av malene.<br /><br />Når du trykker \'Velg\' sendes du videre til et skjermbilde hvor du kan sette _tittel_ og _filnavn_ for dokumentene som kopieres over.',
    DocumentTemplateDialogScreenEditCopyInfoText: 'Her kan du sette _Filnavn_ og _Tittel_ for dokumentene som kopieres over.<br /><br />Når du er ferdig, trykk \'Start kopering\' for å starte kopieringen.',
    FilenameAlreadyInUseErrorText: 'Filnavnet er allerede i bruk.',
    FilenameInValidErrorText: 'Filnavnet er ugyldig.',
    SyncLocalProjectPropertiesListText: 'Synkroniserer liste for prosjektegenskaper',
    CreatingLocalProjectPropertiesListItemText: 'Oppretter element for prosjektegenskaper',
    ProvisionSiteFieldText: 'Opprettet feltet {0} på området',
    CreatingPlannerTaskText: 'Oppretter oppgaver for {0}',
    ProcessListItemText: 'Prosesserer batch {0} med {1} listeelementer',
    ProcessFileText: 'Kopierer fil {0} av {1}',
    ProcessFolderText: 'Kopierer mappe {0} av {1}',
    PhaseLabel: 'Fase',
    IncludeStandardFoldersDescription: 'Inkluder standardmapper for dokumentbiblioteket. Det opprettes en mappe per prosjetktfase.',
    SetupAbortedText: 'Installasjon avbrutt av bruker',
    UnknownErrorText: 'Ukjent feil',
    TemplateListContentConfigText: 'Den valgte prosjektmalen inneholder konfigurasjon for standardinnhold.',
    FolderDropdownLabel: 'Velg mappe',
    DocumentLibraryDropdownLabel: 'Velg dokumentbibliotek',
    DocumentTemplateDialogScreenEditCopyRootLevelText: 'Øverste nivå'
  }
});