define([], function () {
  return {
    ApplyTemplateText: 'Legger på mal {0}',
    ApplyExtensionText: 'Legger på prosjekttilegg',
    ApplyTemplateClientSidePages: 'Legger inn filer og webdeler',
    ApplyTemplateComposedLook: 'Legger på farge og fonter',
    ApplyTemplateContentTypes: 'Legger inn innholdstyper',
    ApplyTemplateErrorMessage: 'Det skjedde en feil under konfigurering av området',
    ApplyTemplateFiles: 'Legger inn filer og webdeler',
    ApplyTemplateLists: 'Legger inn lister med felter, innholdstyper og visninger',
    ApplyTemplateNavigation: 'Legger inn navigasjon',
    ApplyTemplateSiteFields: 'Legger inn felter',
    ApplyTemplateWebSettings: 'Legger inn webinstillinger',
    CloseModalText: 'Lukk',
    CopyListDataErrorMessage: 'Det skjedde en feil under kopiering av listeinnhold',
    CopyListDataText: 'Kopierer {0} listeelementer fra {1} til {2}',
    CopyPlannerTasksLabel: 'Kopier standardoppgaver til Planner',
    CopyProgressLabel: 'Kopierer valgt(e) dokument(er) til prosjektområdet...',
    EditPropertiesLinkText: 'Du kan allerede nå<A HREF=\'{0}\' TARGET=\'_BLANK\'>redigere egenskaper</A> for prosjektet (åpnes i ny fane).',
    ErrorDialogTitle: 'Noe er galt',
    ExtensionsTitle: 'Velg prosjekttillegg',
    GetMoreText: 'Hent flere',
    GetSetupDataErrorMessage: 'Det skjedde en feil',
    GetSetupDataErrorStack: 'Det skjedde en feil under uthenting av data fra hubområdet.',
    IncludeStandardFoldersLabel: 'Inkluder standardmapper',
    InvalidLanguageErrorMessage: 'Ugyldig språk for området',
    InvalidLanguageErrorStack: 'Språket som er satt for området støttes ikke. Området må være opprettet med norsk språk.',
    LibraryDropdownLabel: 'Bibliotek',
    ListContentTitle: 'Velg standardinnhold',
    ModifiedLabel: 'Endret',
    NameLabel: 'Filnavn',
    NoHubSiteErrorMessage: 'Området er ikke koblet til en hub',
    NoHubSiteErrorStack: 'Området kan ikke settes opp uten å være koblet til en hub. Koble området til ett hubområde, og last siden på nytt.',
    OnGoBackText: 'Gå tilbake',
    OnStartCopyText: 'Start kopiering',
    OnSubmitSelectionText: 'Kopier valgt(e) dokument(er) til prosjektområdet',
    PlannerConfigurationErrorMessage: 'Det skjedde en feil under konfigurering av området',
    PlannerConfigurationText: 'Oppretter standardoppgaver i Planner',
    PreTaskErrorMessage: 'Det skjedde en feil',
    ProgressDialogDescription: 'Vennligst vent. Ikke lukk nettleservinduet.',
    ProgressDialogLabel: 'Klargjør prosjektområdet',
    ProgressDialogTitle: 'Setter opp prosjektområdet',
    ProjectPropertiesListName: 'Prosjektegenskaper',
    ProvisionSiteFieldsErrorMessage: 'Det skjedde en feil under provisjonering av områdekolonner',
    ProvisionSiteFieldsText: 'Oppretter områdekolonner',
    SetTaxonomyFieldsErrorMessage: 'Det skjedde en feil under konfigurering av taksonomifelter',
    SettingsTitle: 'Innstillinger',
    SetupProjectInformationErrorMessage: 'Det skjedde en feil under initialisering av prosjektegenskaper',
    SetupProjectInformationText: 'Setter opp prosjektegenskaper',
    SiteFieldsGroupName: 'Kolonner for Prosjektportalen (Prosjekt)',
    SiteNotReadyErrorMessage: 'Området er ikke klart',
    SiteNotReadyErrorStack: 'Området er ikke klart. Prøv igjen senere.',
    SummaryText: '{0} dokument(er) ble kopiert til prosjektområdet.',
    TemplateLibrarySelectModalTitle: 'Hent dokumentmal',
    TemplateSelectDialogInfoText: 'Oppsettet av prosjektområdet tar omtrent 10 minutter. Ikke lukk nettleservinduet mens området settes opp.',
    TemplateSelectDialogSubmitButtonText: 'Sett opp området',
    TemplateSelectDialogTitle: 'Oppsett av prosjektområde',
    TemplateSelectTitle: 'Velg prosjektmal',
    TitleLabel: 'Tittel',
    ProgressDialogSubText: 'Vennligst vent. Ikke lukk nettleservinduet.'
  }
});