/**
 * @fileoverview This file generates temporary package solution file and component manifest files
 * with the solution ID and component IDs generated by the solution config file. This is required
 * to deploy a unique solution to the tenant app catalog.
 * 
 * The script is run as a pre-build script when the serve channel is not main. This is to avoid
 * generating temporary files when the main channel is being served. The script is also run as a
 * post-watch script to revert the package solution file and component manifest files to the
 * backup files.
 * 
 * The script can be run with the following parameters:
 * `--revert` - Reverts the package solution file and component manifest files to the backup files
 * `--force` - Forces the script to run even if no serve channel is specified
 */
const argv = require('yargs').argv
const fs = require('fs')
const glob = require('glob').sync
const isRevert = argv.revert
const isForce = argv.force
const { getFileContent, joinPath, log } = require('./util')
require('dotenv').config()

// Config folder path
const configFolder = joinPath(process.cwd(), `config`)

// Generated solution config file path
const solutionConfigFile = joinPath(configFolder, `.generated-solution-config.json`)

// Package solution file path
const packageSolutionFile = joinPath(configFolder, `package-solution.json`)

// Backup package solution file path
const packageSolutionFileCopy = joinPath(configFolder, `package-solution.json.bak`)

// Running as part of post watch script
const isPostWatch = process.env.npm_lifecycle_event === 'postwatch'

/**
 * Revert package solution file to the backup file and delete the backup file. Also deletes
 * the generated solution config file.
 */
function revertPackageSolutionFile() {
    log('Reverting package solution file to the backup file and deleting the backup file', 'modifySolutionFiles')
    fs.copyFileSync(packageSolutionFileCopy, packageSolutionFile)
    fs.unlinkSync(packageSolutionFileCopy)
    fs.unlinkSync(solutionConfigFile)
}

/**
 * Revert component manifest files to the backup files and delete the backup files.
 * 
 * @param {*} componentManifestFiles Component manifest files
 */
function revertComponentManifestFiles(componentManifestFiles) {
    log('Reverting component manifest files to the backup files and deleting the backup files', 'modifySolutionFiles')
    for (let i = 0; i < componentManifestFiles.length; i++) {
        const componentManifestFile = componentManifestFiles[i]
        const componentManifestFileCopy = componentManifestFile + '.bak'
        fs.copyFileSync(componentManifestFileCopy, componentManifestFile)
        fs.unlinkSync(componentManifestFileCopy)
    }
}

/**
 * Copy existing package solution file to a backup file
 */
function copyExistingPackageSolutionFile() {
    log('Copying existing package solution file to a backup file', 'modifySolutionFiles')
    fs.copyFileSync(packageSolutionFile, packageSolutionFileCopy)
}

/**
 * Generate package solution file with the given parameters
 * 
 * @param {*} id ID of the solution
 * @param {*} name Name of the solution
 * @param {*} zippedPackage Zipped package path
 */
function generatePackageSolutionFile(id, name, zippedPackage) {
    log('Generating package solution file with the given parameters', 'modifySolutionFiles')
    const packageSolution = getFileContent(packageSolutionFile)
    packageSolution.solution.id = id
    packageSolution.solution.name = name
    packageSolution.paths.zippedPackage = zippedPackage
    stampVersion(packageSolution)
    fs.writeFileSync(packageSolutionFile, JSON.stringify(packageSolution, null, 2), { encoding: 'utf8', overwrite: true })
}

/**
 * Stamps the build number into the fourth segment of the solution's version (and of every
 * feature's, which SharePoint upgrades with it) when `PP365_BUILD_NUMBER` is set - the CI run
 * number in the channel workflows. Channel builds otherwise all carry the version from
 * `package-solution.json`, and SharePoint clients keep the manifests they cached for a version they
 * have seen, so a deployment that did not bump it could leave a site serving the previous bundle.
 * Only channel builds come through here; the release build has its own stamping.
 *
 * @param {*} packageSolution Package solution config, modified in place
 */
function stampVersion(packageSolution) {
    const buildNumber = process.env.PP365_BUILD_NUMBER
    if (!buildNumber || !/^\d+$/.test(buildNumber)) return
    const stamp = (version) => {
        const [major = '1', minor = '0', patch = '0'] = String(version || '').split('.')
        return `${major}.${minor}.${patch}.${buildNumber}`
    }
    packageSolution.solution.version = stamp(packageSolution.solution.version)
    for (const feature of packageSolution.solution.features || []) {
        feature.version = stamp(feature.version)
    }
    log(`Stamped solution version ${packageSolution.solution.version}`, 'modifySolutionFiles')
}

/**
 * Copy existing manifest files to backup files.
 * 
 * @param {*} componentManifestFiles Component manifest files
 */
function copyExistingComponentManifestFiles(componentManifestFiles) {
    log('Copying existing manifest files to backup files', 'modifySolutionFiles')
    for (let i = 0; i < componentManifestFiles.length; i++) {
        const componentManifestFile = componentManifestFiles[i]
        const componentManifestFileCopy = componentManifestFile + '.bak'
        fs.copyFileSync(componentManifestFile, componentManifestFileCopy)
    }
}

/**
 * Generate component manifest files with a new ID based on the solution config file.
 * 
 * @param {*} solutionConfig Solution config
 * @param {*} componentManifestFiles Component manifest files
 */
function generateComponentManifestFiles(solutionConfig, componentManifestFiles) {
    log('Generating component manifest files with a new ID based on the solution config file', 'modifySolutionFiles')
    for (let i = 0; i < componentManifestFiles.length; i++) {
        const componentManifestFile = componentManifestFiles[i]
        const componentManifest = getFileContent(componentManifestFile)
        componentManifest.id = solutionConfig.components[componentManifest.alias]
        switch (componentManifest.componentType) {
            /**
             * For web parts, hide them from the toolbox by default. This is to avoid
             * confusion with duplicate web parts in the toolbox when several channels
             * are deployed to the same tenant.
             */
            case 'WebPart':
                {
                    componentManifest.hiddenFromToolbox = true
                }
                break
        }
        fs.writeFileSync(componentManifestFile, JSON.stringify(componentManifest, null, 2), { encoding: 'utf8', overwrite: true })
    }
}



/**
 * Runs the script. If revert flag is set (or if the script is run as post-watch), reverts
 * the package solution file and component manifest files to the backup files. Otherwise,
 * generates temporary package solution file and component manifest files with the solution
 * ID and component IDs generated by the solution config file.
 */
(async () => {
    if (process.env.SERVE_CHANNEL === 'main' || (!process.env.SERVE_CHANNEL && !isForce)) {
        return
    }
    const componentManifestFiles = glob(joinPath(process.cwd(), `src/**/manifest.json`))
    if (isRevert || isPostWatch) {
        revertPackageSolutionFile()
        revertComponentManifestFiles(componentManifestFiles)
    } else {
        const solutionConfig = getFileContent(solutionConfigFile)
        copyExistingPackageSolutionFile()
        generatePackageSolutionFile(solutionConfig.id, solutionConfig.name, solutionConfig.zippedPackage)
        copyExistingComponentManifestFiles(componentManifestFiles)
        generateComponentManifestFiles(solutionConfig, componentManifestFiles)
    }
})()