define([], function () {
  return {
    AddColumnLabel: 'Add a column',
    AllocationPercetageLabel: 'Allocation percentage',
    AllocationStatusLabel: 'Allocation status',
    AllProjectsHeaderText: 'All projects/programs',
    AllProjectsSearchBoxPlaceholderText: 'Search all {0} projects...',
    BarLabel: 'Bar',
    BooleanNo: 'No',
    BooleanYes: 'Yes',
    BooleanOff: 'Off',
    BooleanOn: 'On',
    CancelButtonLabel: 'Cancel',
    ChartConfigurationListNameLabel: 'Graph configuration',
    ChartErrorText: 'The graph is invalidly configured.',
    ColumnConfigListNameLabel: 'Column configuration',
    ColumnPersistRenderGloballyFieldDescription: 'If you want to change the display mode for the columns as for all web parts and views, tick the check box above.',
    ColumnPersistRenderGloballyFieldLabel: 'Update globally',
    ColumnRenderDataTypePropertiesHeaderText: 'Properties for display type',
    ColumnRenderDescription: 'Choose how the column should be displayed. If there are text fields to be displayed over several lines, select Note.',
    ColumnRenderLabel: 'Show as',
    ColumnRenderOptionBoolean: 'Yes/no',
    ColumnRenderOptionBooleanFalse: 'Value for \'No\'',
    ColumnRenderOptionBooleanTrue: 'Value for \'Yes\'',
    ColumnRenderOptionCurrency: 'Currency',
    ColumnRenderOptionCurrencyFallbackValueLabel: 'Default value',
    ColumnRenderOptionCurrencyMaximumFractionDigitsLabel: 'Maximum number of decimals',
    ColumnRenderOptionCurrencyMinimumFractionDigitsLabel: 'Minimum number of decimals',
    ColumnRenderOptionCurrencyPrefixLabel: 'Currency prefix',
    ColumnRenderOptionDate: 'Date',
    ColumnRenderOptionDateIncludeTimeLabel: 'Include time',
    ColumnRenderOptionFilename: 'File name',
    ColumnRenderOptionDialog: 'Modal',
    ColumnRenderOptionDialogInfoTextTemplateDescription: 'Template for info text. Use {{GtMeasurementOWSCHCS}} to display the measurement indicator, {{GtStartValueOWSNMBR}} to display the starting value, and {{GtDesiredValueOWSNMBR}} to display the target. You can also use other column names from the benefit overview.',
    ColumnRenderOptionDialogInfoTextTemplateLabel: 'Template for infotext',
    ColumnRenderOptionDialogLinkTextLabel: 'Linktext',
    ColumnRenderOptionDialogShowInfoTextLabel: 'Show infotext',
    ColumnRenderOptionNote: 'Note',
    ColumnRenderOptionNumber: 'Number',
    ColumnRenderOptionPercentage: 'Percentage',
    ColumnRenderOptionProjectInfo: 'Projectinformation',
    ColumnRenderOptionTags: 'Labels',
    ColumnRenderOptionTagsValueSeparatorDescription: 'Enter a character to be used to separate values in the label field. Default is semicolon.',
    ColumnRenderOptionTagsValueSeparatorLabel: 'Separator for values',
    ColumnRenderOptionText: 'Text',
    ColumnRenderOptionTrend: 'Trend',
    ColumnRenderOptionTrendShowTrendIconLabel: 'Show icon',
    ColumnRenderOptionUrl: 'URL',
    ColumnRenderOptionUrlDescriptionDescription: 'Link description. If you do not enter a value, any description from the link is used.',
    ColumnRenderOptionUrlDescriptionLabel: 'Description',
    ColumnRenderOptionUrlOpenInNewTabLabel: 'Open in new tab',
    ColumnRenderOptionUser: 'Person',
    ColumnSettingsDisabledTooltip: 'Column settings are only available when the site is in edit mode.',
    ColumnSettingsLabel: 'Column settings',
    ColumnsListNameLabel: 'Columns',
    ColumnVisibilityDescription: 'Specify where the column should appear. Project frontpage, the project status page, the portfolio overview or everywhere.',
    ColumnVisibilityLabel: 'Column visibility',
    CommandBarGroupName: 'Commandline',
    CommentLabel: 'Comment',
    CompactViewText: 'Compact list',
    ConfigItemTitleFieldDescription: 'If there is a specified element with this given title in the timelineconfiguration list, this will be displayed on the timeline.',
    ConfigItemTitleFieldLabel: 'Element title (Configuration)',
    ConfigurationGroupName: 'Configuration',
    ConfirmDeleteProjectColumnSubText: 'This column is removed from the Project Columns list and thus from all views that use it. Are you sure you want to delete this column? If you only want to remove the column from this display, you can use \'Show or hide columns\'.',
    ConfirmDeleteProjectColumnTitle: 'Do you want to delete?',
    ConfirmDeleteProjectContentColumnSubText: 'This column is removed from the Project Content Columns list and thus from all views that use it. Are you sure you want to delete this column? If you only want to remove the column from this display, you can use \'Show or hide columns\'.',
    ConfirmDeleteProjectContentColumnTitle: 'Do you want to delete?',
    ConfirmDeleteResponseAbort: 'Cancel',
    ConfirmDeleteResponseConfirm: 'Delete',
    CreatedTooltipText: 'Created {0}',
    CustomSortsText: 'Custom sorting',
    DataSourceCategoryDescription: 'Enter a data source category to be able to choose between multiple data sources in the web part.',
    DataSourceCategoryError: 'An error occurred while retrieving data sources with category **{0}**.',
    DataSourceCategoryLabel: 'Category for data sources',
    DataSourceError: 'An error occurred while retrieving data from the data source named **{0}**.',
    DataSourceGroupName: 'Data sources',
    DataSourceItemNotFound: 'Data source not found',
    DataSourceLabel: 'Data source',
    DataSourceLevelDescription: 'Set the level for the data source. This is used to filter data sources in the web part based on where data is obtained from. This can be changed afterwards in the \'Data sources\' list if you want to make the query/view available elsewhere.',
    DataSourceLevelLabel: 'Data source level',
    DataSourceLevelPortfolio: 'Portfolio',
    DataSourceLevelProject: 'Project',
    DataSourceListName: 'Datakilder',
    DataSourceNotFound: 'Cannot find any data source with name **{0}**.',
    DefaultDataSourceViewLabel: 'Default view (data source)',
    DefaultRenderModeLabel: 'Default display mode',
    DefaultVerticalLabel: 'Default vertical',
    DefaultViewDescription: 'Choose whether this is the default view for the Portfolio overview.',
    DefaultViewLabel: 'Default view',
    DefaultViewSetWarningMessage: 'There is already a view set as the default. You must first change this view before you can set a new one as the default. Personal views cannot be set as the default.',
    DeleteButtonLabel: 'Delete',
    DisplayNameDescription: 'Displayname for this column, for this web part only. If you want to change the display name for all web parts, you must change it in the Project Content Columns list.',
    DisplayNameLabel: 'Displayname',
    EditColumnHeaderText: 'Edit column',
    EditColumnLabel: 'Edit',
    EditViewColumnsPanelHeaderText: 'Edit displaycolumns',
    EditViewColumnsPanelHelpText: 'Select the columns to display for the current view. To change the order, you can drag and drop or use the arrows next to each column.',
    EditViewHeaderText: 'Edit view',
    EditViewText: 'Edit the view',
    EmptyMessageDescription: 'No new projects found.',
    EndDateLabel: 'End date',
    ExcelExportButtonLabel: 'Eksporter til Excel',
    ErrorFetchingProjectsTitle: 'An error occurred while retrieving projects.',
    FiltersString: 'Filters',
    FilterText: 'Filter',
    GeneralGroupName: 'General',
    GroupByColumnLabel: 'Group by {0}',
    HideVerticalsLabel: 'Hide verticals',
    IconNameDescription: 'Name of the icon from UI Fabric. See https://uifabricicons.azurewebsites.net/.',
    IconNameLabel: 'Icon name',
    IncludeViewNameInExcelExportFilenameLabel: 'Include view-name in excel filename',
    InternalNameDescription: 'Internal field name for this column.',
    InternalNameLabel: 'Internal field name',
    IsGroupableDescription: 'Users can group this column.',
    IsGroupableLabel: 'Groupable',
    IsRefinableDescription: 'Users can filter this column.',
    IsRefinableLabel: 'Specify',
    IsResizableLabel: 'Resizable',
    ListLayoutModeJustifiedLabel: 'Adjust columns by screen width',
    ListViewGroupName: 'List view',
    ListViewText: 'List',
    LoadingText: 'Loading {0}...',
    LoadingTextDescription: 'Text displayed while the web part is loading.',
    LoadingTextLabel: 'Loading text',
    MaxWidthDescription: 'Maximum width for the column. Cannot be less than the minimum width.',
    MaxWidthLabel: 'Max width',
    MeasurementAchievementLabel: 'Measurement achievement',
    MeasurementCommentLabel: 'Comment on measurement',
    MeasurementDateLabel: 'Date of measurement',
    MeasurementValueLabel: 'Measured value',
    MinWidthDescription: 'Minimum width for the column. Cannot exceed maximum width.',
    MinWidthLabel: 'Min width',
    ModalColumnEmptyListText: 'No elements found.',
    MoveLeftLabel: 'Move left',
    MoveRightLabel: 'Move right',
    MyProjectsHeaderText: 'My projects',
    MyProjectsSearchBoxPlaceholderText: 'Search {0} projects you are a member of...',
    NameLabel: 'Name',
    NewColumnHeaderText: 'New column',
    NewLabel: 'New',
    NewViewHeaderText: 'Create view',
    NewViewText: 'Create new view',
    NoAccessMessage: 'You do not have access to this project',
    NoDefaultViewMessage: 'No default display has been set.',
    NoProjectData: 'Unable to retrieve all data from the project. It may be that you do not have access to the project itself. It may also be that the project has recently been created or that project properties have not been filled in.',
    NoProjectsFoundMessage: 'No projects found.',
    NotSet: 'Not set',
    ParentProjectsHeaderText: 'Parent projects',
    ParentProjectsSearchBoxPlaceholderText: 'Search {0} parent projects...',
    PersonalViewDescription: 'Choose whether this is a personal view. Personal views can only be edited by you.',
    PersonalViewLabel: 'Personal view',
    PersonalViewsHeaderText: 'Personal views',
    PhaseLabel: 'Phase',
    PortfolioAggregationNotConfiguredMessage: 'The web part must be configured with a data source. Edit the web part and enter the name of the data source you want to use.',
    PortfolioAggregationViewSearchQueryDescription: 'The query to retrieve data. DepartmentId refers to the Project Portal hub and should not be changed. ContentTypeId refers to the content type of the data element you want to retrieve. Go to the Data Sources list to see examples.',
    PortfolioManagerGroupName: 'Porteføljeinnsyn',
    PortfolioOverviewColumnRenderDescription: 'Choose how the column should be displayed. If there are text fields to be displayed over several lines, select Note.',
    PortfolioOverviewDataFetchError: 'An error occurred while retrieving data for the portfolio overview. Please try again later.<br/><br/> **Error:**<br/> `{0}`',
    PortfolioOverviewDataFetchErrorView: 'An error occurred while retrieving data for the portfolio overview for view **{0}**. Please try again later, or try a different view.<br/><br/> **Error:**<br/> `{1}`',
    PortfolioOverviewShowEditViewColumnsPanelHelpText: 'Select the columns to display for the current view. To change the order, you can drag and drop or use the arrows next to each column. Use the \'Reset Order\' button to reset the order to the default order specified in the Project Columns list.',
    PortfolioViewSearchQueryDescription: 'The search query to retrieve projects in the portfolio. DepartmentId refers to the Project Portal hub and should not be changed.',
    PortfolioViewsListName: 'Porteføljevisninger',
    ProgramProjectsHeaderText: 'Program',
    ProgramSearchBoxPlaceholderText: 'Search {0} programs...',
    ProgramsHeaderText: 'Programs',
    ProjectColumnsListName: 'Prosjektkolonner',
    ProjectContentColumnItemNotFound: 'Project content column not found',
    ProjectContentColumnsListName: 'Prosjektinnholdskolonner',
    ProjectDeliveriesGroupName: 'Project deliveries (beta)',
    ProjectInformationGroupName: 'Settings for Project information panel',
    ProjectLabel: 'Project',
    ProjectListEmptyMessage: 'The search returned no results',
    ProjectManager: 'Project Manager',
    ProjectOwner: 'Project owner',
    ProjectsAccessHeaderText: 'Access to',
    ProjectsAccessSearchBoxPlaceholderText: 'Search {0} projects you have access to...',
    ProjectsListName: 'Prosjekter',
    RenderModeCompactListText: 'Compact list',
    RenderModeListText: 'List',
    RenderModeTilesText: 'Tiles',
    ResourceAllocationInfoText: 'Resource allocations or absences that apply across projects are entered into the <A HREF="../Lists/Ressursallokering/AllItems.aspx?Source={0}">resource allocation hub list</A>. These entries will be shown in blue and red (absence) color in the table below. Project allocations are shown in green. The color strength of the allocation is based on the allocation percentage.',
    ResourceLabel: 'Resource',
    RevertCustomOrderButtonText: 'Reset order',
    RevertCustomOrderButtonTooltip: 'Reset order to default order for columns specified in the Project Columns list.',
    RoleLabel: 'Role',
    RowLimitLabel: 'Number of elements',
    SaveButtonLabel: 'Save',
    SearchBoxGroupName: 'Search box',
    SearchBoxPlaceholderFallbackText: 'Search...',
    SearchBoxPlaceholderText: 'Search {0}...',
    SearchBoxPlaceholderTextDescription: 'Text that appears in the search box when it is empty. If no value is set, the text is based on the selected data source.',
    SearchBoxPlaceholderTextLabel: 'Search box text',
    SearchPropertyDescription: 'The name of the managed property for this column.',
    SearchPropertyFoundMessage: 'Found a managed property `{0}` that matches the internal field name `{1}`.',
    SearchPropertyLabel: 'Search property',
    SearchPropertyPlaceholder: 'Search managed properties...',
    SearchQueryLabel: 'Search query',
    SelectProgramText: 'Select a program',
    ShowAllMeasurementsLinkText: 'Show all measurements',
    ShowCommandBarLabel: 'Show commandline',
    ShowExcelExportButtonLabel: 'Show export to Excel button',
    ShowFieldFrontpageLabel: 'Project frontpage',
    ShowFieldPortfolioLabel: 'Portfolio overview',
    ShowFieldProjectStatusLabel: 'Project status',
    ShowFiltersLabel: 'Show filters',
    ShowGroupByLabel: 'Show grouping options',
    ShowHideColumnsLabel: 'Show/hide columns',
    ShowProgramViewsLabel: 'Show program views',
    ShowProjectLogoFieldLabel: 'Show logo',
    ShowRenderModeSelectorLabel: 'Show view selector',
    ShowSearchBoxLabel: 'Show search box',
    ShowViewSelectorLabel: 'Show view selector',
    SiteTitleLabel: 'Project',
    SortAscLabel: 'Z to A',
    SortByFieldLabel: 'Sorting property',
    SortDescLabel: 'A to Z',
    SortOrderDescription: 'The sort order determines the order in which the views are displayed. The lowest value is displayed first.',
    SortOrderLabel: 'Sort order',
    StartDateLabel: 'Start date',
    StatusReportsCountLabel: 'Number of statusreports to display',
    TileViewGroupName: 'Tile view',
    TimelineConfigurationListName: 'Tidslinjekonfigurasjon',
    TimelineContentListName: 'Tidslinjeinnhold',
    TitleLabel: 'Title',
    ToggleColumnFormPanelLabel: 'Add column',
    UseChangesButtonText: 'Use',
    ViewNotFoundMessage: 'Cannot find the specified view.',
    ViewsListNameLabel: 'Views',
    Provision: {
      DrawerLevel0HeaderText: 'Order area',
      DrawerLevel0DescriptionText: 'Here you can order a new area. Select one of the area types below, and fill in the information below.',
      DrawerLevel1HeaderText: 'Classification',
      DrawerLevel1DescriptionText: 'Here you can select classification for the area. Activate teams, sensitivity label and retention label.',
      DrawerLevel2HeaderText: 'Other information',
      DrawerLevel2DescriptionText: 'Here you can specify other information for the area. Area image and overview of language, time zone and hub connection.',
      SiteTypeFieldLabel: 'Area type',
      SiteNameFieldLabel: 'Area name',
      SiteNameFieldDescription: 'Choose a unique name that follows the organization\'s naming standards.',
      SiteNamePrefixTooltipText: 'This is a prefix that is added in front of the area name.',
      SiteNameSuffixTooltipText: 'This is a suffix that is added at the end of the area name.',
      SiteNameValidationErrorMessage: 'The name specified is not available. Try changing the name.',
      SiteNameValidationSuccessMessage: 'The name is available',
      SiteDescriptionFieldLabel: 'Description',
      SiteDescriptionFieldDescription: 'Provide a description, this is useful for people to understand what your area is for.',
      BusinessJustificationFieldLabel: 'Business justification',
      BusinessJustificationFieldDescription: 'Describe why you need this area? What is the purpose?',
      AliasFieldLabel: 'Alias/name',
      UrlFieldLabel: 'Area address',
      OwnerFieldLabel: 'Owner(s)',
      OwnerFieldDescription: 'Owner(s) have full access to the area and can add and remove members. You can add more owners later.',
      MemberFieldLabel: 'Member(s)',
      MemberFieldDescription: 'Member(s) have access to the area based on the permissions that are set. You can add more members later.',
      RequestedByFieldLabel: 'Ordered on behalf of',
      RequestedByFieldDescription: 'If you order the area on behalf of someone, you can enter the name of that person here. If you order the area for yourself, you can leave the field empty.',
      UserFieldNoOptionsText: 'No matches...',
      TeamifyFieldLabel: 'Activate Teams for the area?',
      TeamifyFieldDescription: 'If you activate Teams for the area, a Teams area will be created and linked to the area.',
      TeamTemplateFieldLabel: 'Teams template',
      TeamTemplateFieldDescription: 'Which teams template do you want to use for the area?',
      ConfidentialFieldLabel: 'Confidential/sensitive data',
      ConfidentialFieldDescription: 'Will confidential or sensitive data be stored in this room? If yes, you must ensure that you have set the correct permissions.',
      PrivacyFieldLabel: 'Access settings',
      PrivacyFieldDescription: 'Specify which access setting you want for the area.',
      PrivacyFieldOptionPrivate: 'Private - Users need permission to join',
      PrivacyFieldOptionPublic: 'Public - Everyone in the organization can join',
      ExternalSharingFieldLabel: 'Allow external guests',
      ExternalSharingFieldDescription: 'If this is enabled, you will be able to invite and share individual files, folders, libraries, etc. with external guest users. Note! Invitation of external guest users will only be possible after the group/area has been created.',
      GuestFieldLabel: 'Guest(s)',
      GuestFieldDescription: 'Guests have limited access to the area. You can add more guests later. Please enter a valid email address.',
      GuestFieldNoOptionsText: 'Cannot add...',
      SensitivityLabelFieldLabel: 'Sensitivity label',
      SensitivityLabelFieldDescription: 'Which sensitivity label do you want to apply for the area?',
      SensitivityLabelLibraryFieldLabel: 'Sensitivity label for library',
      SensitivityLabelLibraryFieldDescription: 'Which sensitivity label do you want to apply for the document library for the area?',
      RetentionLabelFieldLabel: 'Retention label',
      RetentionLabelFieldDescription: 'Which retention label do you want to apply for the area?',
      ExpirationDateFieldLabel: 'Expiration date',
      ExpirationDateFieldDescription: 'When does the area expire? Note! The area will not be deleted after this date.',
      ReadOnlyGroupFieldLabel: 'Activate read access group',
      ReadOnlyGroupFieldDescription: 'Activate a read access group for the area. This will give users in the group read access to the area.',
      InternalChannelFieldLabel: 'Activate internal channel',
      InternalChannelFieldDescription: 'When this option is enabled, an internal channel will be created in Teams.',
      LanguageFieldLabel: 'Language',
      TimeZoneFieldLabel: 'Time zone',
      HubSiteFieldLabel: 'Hub connection',
      ImageFieldLabel: 'Specify area image',
      ImageFieldDescription: 'Here you can upload an image to be used as an area image.',
      ImageDropZoneText: 'Drag and drop image here, or click to select image file (png, jpeg/jpg) Note! Cannot exceed 1 MB.',
      DrawerFooterDescriptionText: 'Your area will be linked to a Microsoft 365 group, which gives your website a shared OneNote notebook, group email address and shared calendar.',
      PreviousButtonLabel: 'Previous',
      NextButtonLabel: 'Next',
      ProvisionButtonLabel: 'Order area',
      ToastCreatedTitle: 'The area is ordered',
      ToastCreatedBody: 'The area is now ordered and sent for processing.',
      ToastCreatedErrorTitle: 'Error when ordering',
      ToastCreatedErrorBody: 'An error occurred when ordering the area. Please try again, or contact administrator.',
      StatusMenuLabel: 'My orders',
      SettingsMenuLabel: 'Settings',
      IdeaMenuLabel: 'Register idea',
      SettingsSearchLabel: 'Search in settings',
      SettingsDialogTitle: 'Settings for the Ordering portal',
      SettingsDialogDescription: 'Here you have an overview of all settings for the Ordering portal.',
      SettingsDialogSpinnerLabel: 'Updating and retrieving settings...',
      SettingsDialogNoSearchResultsLabel: 'No settings match the search.',
      SettingsDialogNoResultsLabel: 'There are no settings for the Ordering portal.',
      SettingLabel: 'Setting',
      DescriptionLabel: 'Description',
      ValueLabel: 'Value',
      EditLabel: 'Edit',
      StatusSearchLabel: 'Search in orders',
      UpdateLabel: 'Update',
      StatusDialogTitle: 'My orders',
      StatusDialogDescription: 'Here you can see the status of your orders, which area type, status and date for the order. It is also possible to delete orders that have not been submitted or that have been rejected.',
      StatusDialogSpinnerLabel: 'Updating and retrieving orders...',
      StatusDialogNoSearchResultsLabel: 'No orders match the search.',
      StatusDialogNoResultsLabel: 'You have no orders, create a new order to see status here.',
      StatusLabel: 'Status',
      SubmittedLabel: 'Submitted',
      ApprovedLabel: 'Approved',
      RejectedLabel: 'Rejected',
      PendingApprovalLabel: 'Pending approval',
      SpaceCreationFailedLabel: 'Area creation failed',
      SpaceAlreadyExistsLabel: 'The area already exists',
      TeamRequestedLabel: 'Team requested',
      SpaceCreationLabel: 'The area is being created',
      SpaceCreatedLabel: 'The area has been created',
      NotSubmittedLabel: 'Not submitted',
      SubmittedDateLabel: 'Order date',
      DeleteLabel: 'Delete',
      DeleteSubmissionLabel: 'Delete order',
      DeleteSubmissionConfirmationLabel: 'Are you sure you want to delete the order?',
      DeletedSubmissionToastTitle: 'Deleted order',
      DeletedSubmissionToastBody: 'The order, {0}, is now deleted.',
      DeletedSubmissionErrorToastTitle: 'Error when deleting',
      DeletedSubmissionErrorToastBody: 'An error occurred when deleting the order. Please try again, or contact administrator.',
      RequestedSource: 'Project Portal - Order form',
      NotConfiguredTitle: 'Not configured',
      NotConfiguredText: 'There is no configured url to the Ordering portal. Please specify this in the web part.',
      ExpirationDateNoneOption: 'No expiration date',
      ExpirationDateMonthOption: '{0} month(s)',
      NoProvisionAccessMessage: 'You do not have access to the Ordering portal.',
      DefaultTeamTemplate: 'Standard',
      DefaultLanguage: 'English',
      DefaultTimeZone: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna'
    },
  }
})
