define([], function () {
    return {
        Add: 'Add',
        AddProjectDialogSearchBoxPlaceholder: 'Search projects...',
        BarLabel: 'Bar',
        Cancel: 'Cancel',
        CmdSelectionCountText: '{0} is marked',
        CmdSelectionCountTooltipText: 'The following projects have been selected:',
        CommandBarGroupName: 'Commandline',
        ConfigItemTitleFieldDescription: 'If an element with the title specified here is specified in the timeline configuration list, this will be displayed on the timeline.',
        ConfigItemTitleFieldLabel: 'Element title (configuration)',
        DataSourceCategoryDescription: 'Enter a data source category to be able to choose between multiple data sources in the web part.',
        DataSourceCategoryError: 'An error occurred while retrieving data sources with category **{0}**.',
        DataSourceCategoryLabel: 'Category for data sources',
        DataSourceError: 'An error occurred while retrieving data from the data source named **{0}**.',
        DataSourceGroupName: 'Data sources',
        DataSourceLabel: 'Data source',
        DataSourceLevelDescription: 'Select level for the data source. Only data sources with this level will be available in the web part.',
        DataSourceLevelLabel: 'Data source level',
        DataSourceNotFound: 'Cannot find any data source with name **{0}**.',
        DefaultDataSourceViewLabel: 'Default view (data source)',
        DefaultViewLabel: 'Default view',
        GeneralGroupName: 'General',
        ListViewText: 'List',
        PortfolioManagerGroupName: 'Portfolio insight',
        ProgramAdministrationAddChildsButtonLabel: 'Add projects',
        ProgramAdministrationEmptyMessage: 'No sites are connected to the program.',
        ProgramAdministrationHeader: 'Administration of child projects',
        ProgramAdministrationInfoMessage: 'Select one or more projects you want to associate to the site. The site will appear as a parent for the projects that have been selected under Project Information.',
        ProgramAdministrationSearchBoxPlaceholder: 'Search the program site...',
        ProgramRemoveChildsButtonLabel: 'Remove child projects',
        ProgramTimelineInfoText: 'All the projects with start and end dates associated with the site are listed here. To zoom in/out in timeline: ALT+Mouse wheel.',
        ProjectContentColumnsListName: 'Prosjektinnholdskolonner',
        ProjectDeliveriesGroupName: 'Project deliveries (beta)',
        ProjectLabel: 'Project',
        ProjectPropertiesListName: 'Prosjektegenskaper',
        ProjectsListName: 'Prosjekter',
        SearchBoxGroupName: 'Search box',
        SearchBoxPlaceholderText: 'Search {0}...',
        SearchBoxPlaceholderTextDescription: 'Text that appears in the search box when it is empty. If no value is set, the text is based on the selected data source.',
        SearchBoxPlaceholderTextLabel: 'Search box text',
        ShowCommandBarLabel: 'Show commandline',
        ShowExcelExportButtonLabel: 'Show export to Excel button',
        ShowFiltersLabel: 'Show filters',
        ShowGroupByLabel: 'Show grouping options',
        ShowSearchBoxLabel: 'Show search box',
        ShowViewSelectorLabel: 'Show view selector',
        TimelineConfigurationListName: 'Tidslinjekonfigurasjon',
        TimelineContentListName: 'Tidslinjeinnhold',
    }
})
