define([], function () {
  return {
    Aria: {
      MenuOverflowCount: '{0} more items',
      MoveDisabled: 'Move disabled',
      MoveUp: 'Move up',
      MoveUpDisabled: 'Move up disabled',
      MoveDown: 'Move down',
      MoveDownDisabled: 'Move down disabled'
    },
    Placeholder: {
      TextField: "Enter text here",
      Icon: "Enter an icon",
      MultiChoiceField: "Select one or more options"
    },
    ColumnCategoryDescription: 'The category of the column. This is used to group columns in the web part.',
    ColumnCategoryLabel: 'Column category',
    DefaultRenderModeDescription: 'The default display mode for the web part. This can be changed in the web part properties.',
    DefaultTimeframeEndLabel: 'Default end date',
    DefaultTimeframeEndValue: 'Default end date value',
    DefaultTimeframeStartLabel: 'Default start date',
    DefaultTimeframeStartValue: 'Default start date value',
    DefaultVerticalDescription: 'The default vertical for the web part. This can be changed in the web part properties.',
    DisplayNamePortfolioOverviewDescription: 'Display name for the portfolio overview.',
    EditProjectListQuickLaunch: 'Edit project list',
    ErrorBoundaryFallbackDescription: 'An error occurred while retrieving data. Please try again later.',
    ErrorBoundaryFallbackText: 'An error occurred while retrieving data. Please try again later.',
    ErrorTitle: 'An error occurred',
    OpenInNewTabLabel: 'Open in new tab',
    ProjectListQuickLaunch: 'Project list',
    ProjectMetadataFieldLabel: 'Project metadata field',
    ProjectCard: {
      WebPartDescription: 'Project card',
      ProjectSiteIdFieldLabel: 'Site ID',
      ProjectSiteIdFieldDescription: 'ID for the SharePoint site (Project)'
    },
    ProjectServiceArea: 'Project service area',
    ProjectType: 'Project type',
    RelativeUrl: 'Relative URL',
    RenderModeLabel: 'Display mode',
    ResourceAllocationGroupName: 'Resource allocation',
    SearchPropertyFoundTitle: 'Found a managed property',
    ShowRenderModeSelectorDescription: 'Show the display mode selector.',
    ShowSortByDescription: 'Show the sorting options.',
    ShowSortByLabel: 'Show sorting options',
    SortByFieldDescription: 'The field to sort by.',
    TitleDescription: 'The title of the web part.',
    UseDynamicColorsDescription: 'Use dynamic colors for the web part.',
    UseDynamicColorsLabel: 'Use dynamic colors',
    ViewLessText: 'View less',
    ViewMoreText: 'View more',
    ResultsCountLabel: 'Displaying {0} of {1} projects',
    FilterPanelGroupProjectInformation: 'Project information',
    ColumnRenderOptionStatusReport: 'Status report',
    ColumnRenderOptionProjectInfo: 'Project information',
    ColumnRenderOptionHub: 'Hub',
    ColumnRenderOptionCalculated: 'Calculated column',
    PortfolioSelectorLabel: 'Portfolio selector',
    MergedViewLabel: 'Show all hubs',
    PortfoliosFieldDescription: 'Select the portfolios to be displayed in the portfolio selector.',
    SelectedPortfolioDescription: 'The portfolio selected in the portfolio selector.',
    ShowPortfolioSelectorDescription: 'Show the portfolio selector.',
    IconNameFieldPlaceholder: 'Enter icon name',
    IconNameFieldLabel: 'Icon name',
    LanguageFieldLabel: 'Language',
    IncludeInMergedViewFieldLabel: 'Include in merged view',
    PortfolioSelectorDescription: 'Select the portfolio to be displayed in the portfolio selector.',
    ShowPortfolioSelectorOnText: 'Show portfolio selector',
    ShowPortfolioSelectorOffText: 'Hide portfolio selector',
    ShowPortfolioSelectorLabel: 'Show portfolio selector',
    ShowMergedViewInViewSelectorLabel: 'Show merged view in view selector',
    ShowMergedViewInViewSelectorDescription: 'Add an option in the view selector to display merged data from all configured hubs simultaneously.',
    SelectedPortfolioLabel: 'Selected portfolio',
    PortfoliosFieldLabel: 'Portfolios',
    PortfoliosPanelHeader: 'Portfolios',
    PortfoliosManageBtnLabel: 'Manage portfolios',
    UrlFieldLabel: 'URL',
    ProjectListNameFieldLabel: 'Projects list name',
    ProjectStatusListNameFieldLabel: 'Project status list name',
    ProjectContentColumnsListNameFieldLabel: 'Project Content Columns list name',
    ViewsListNameFieldLabel: 'Views list name',
    ColumnsListNameFieldLabel: 'Columns list name',
    ColumnConfigListNameFieldLabel: 'Column configuration list name',
    GetPortfolioConfigErrorTitle: 'Error retrieving portfolio configuration',
    GetPortfolioConfigErrorText: 'An error occurred while retrieving the portfolio configuration. Please try again later.',
    AdvancedGroupName: 'Advanced',
    AddColumnLabel: 'Add a column',
    AllocationPercetageLabel: 'Allocation percentage',
    AllocationStatusLabel: 'Allocation status',
    AllProjectsHeaderText: 'All projects/programs',
    AllProjectsSearchBoxPlaceholderText: 'Search all {0} projects...',
    BooleanNo: 'No',
    BooleanYes: 'Yes',
    BooleanOff: 'Off',
    BooleanOn: 'On',
    CancelButtonLabel: 'Cancel',
    ColumnRenderDataTypePropertiesHeaderText: 'Properties for display type',
    ColumnRenderDescription: 'Choose how the column should be displayed. If there are text fields to be displayed over several lines, select Note.',
    ColumnRenderLabel: 'Show as',
    ColumnSettingsDisabledTooltip: 'Column settings are only available when the site is in edit mode.',
    ColumnSettingsLabel: 'Column settings',
    ColumnVisibilityDescription: 'Specify where the column should appear. Project frontpage, the project status page, the portfolio overview or everywhere.',
    ColumnVisibilityLabel: 'Column visibility',
    CommandBarGroupName: 'Commandline',
    CommentLabel: 'Comment',
    CompactViewText: 'Compact list',
    ConfigItemTitleFieldDescription: 'If there is a specified element with this given title in the timelineconfiguration list, this will be displayed on the timeline.',
    ConfigItemTitleFieldLabel: 'Element title (Configuration)',
    ConfigurationGroupName: 'Configuration',
    ConfirmDeleteProjectColumnSubText: 'This column is removed from the Project Columns list and thus from all views that use it. Are you sure you want to delete this column? If you only want to remove the column from this display, you can use \'Show or hide columns\'.',
    ConfirmDeleteProjectColumnTitle: 'Do you want to delete?',
    ConfirmDeleteProjectContentColumnSubText: 'This column is removed from the Project Content Columns list and thus from all views that use it. Are you sure you want to delete this column? If you only want to remove the column from this display, you can use \'Show or hide columns\'.',
    ConfirmDeleteProjectContentColumnTitle: 'Do you want to delete?',
    ConfirmDeleteResponseAbort: 'Cancel',
    ConfirmDeleteResponseConfirm: 'Delete',
    CreatedTooltipText: 'Created {0}',
    CustomSortsText: 'Custom sorting',
    DataSourceCategoryDescription: 'Enter a data source category to be able to choose between multiple data sources in the web part.',
    DataSourceCategoryError: 'An error occurred while retrieving data sources with category **{0}**.',
    DataSourceCategoryLabel: 'Category for data sources',
    DataSourceError: 'An error occurred while retrieving data from the data source named **{0}**.',
    DataSourceGroupName: 'Data sources',
    DataSourceItemNotFound: 'Data source not found',
    DataSourceLabel: 'Data source',
    DataSourceLevelDescription: 'Set the level for the data source. This is used to filter data sources in the web part based on where data is obtained from. This can be changed afterwards in the \'Data sources\' list if you want to make the query/view available elsewhere.',
    DataSourceLevelLabel: 'Data source level',
    DataSourceNotFound: 'Cannot find any data source with name **{0}**.',
    DefaultDataSourceViewLabel: 'Default view (data source)',
    DefaultRenderModeLabel: 'Default display mode',
    DefaultVerticalLabel: 'Default vertical',
    VerticalConfigLabel: 'Vertical configuration',
    VerticalConfigPanelHeader: 'Manage verticals',
    VerticalConfigManageBtnLabel: 'Manage verticals',
    VerticalConfigKeyTitle: 'Key',
    VerticalConfigTitleTitle: 'Title',
    VerticalConfigIconTitle: 'Icon',
    VerticalConfigSortOrderTitle: 'Sort order',
    VerticalConfigClientFilterTitle: 'Client filter (JSON)',
    VerticalConfigFieldFilterTitle: 'Field filter (JSON)',
    VerticalConfigVisibilityRuleTitle: 'Visibility rule (JSON)',
    VerticalConfigRequiresAccessTitle: 'Requires access',
    VerticalConfigIsDefaultTitle: 'Is default',
    VerticalConfigSearchBoxPlaceholderTitle: 'Search box placeholder',
    DefaultViewDescription: 'Choose whether this is the default view for the Portfolio overview.',
    DefaultViewLabel: 'Default view',
    DefaultViewSetWarningMessage: 'There is already a view set as the default. You must first change this view before you can set a new one as the default. Personal views cannot be set as the default.',
    DeleteButtonLabel: 'Delete',
    DisplayNameDescription: 'Displayname for this column, for this web part only. If you want to change the display name for all web parts, you must change it in the Project Content Columns list.',
    DisplayNameLabel: 'Displayname',
    EditColumnHeaderText: 'Edit column',
    EditColumnLabel: 'Edit',
    EditViewColumnsPanelHeaderText: 'Edit displaycolumns',
    EditViewColumnsPanelHelpText: 'Select the columns to display for the current view. To change the order, you can drag and drop or use the arrows next to each column.',
    EditViewHeaderText: 'Edit view',
    EditViewText: 'Edit the view',
    EmptyMessageDescription: 'No new projects found.',
    EndDateLabel: 'End date',
    ExcelExportButtonLabel: 'Export to excel',
    ErrorFetchingProjectsTitle: 'An error occurred while retrieving projects.',
    FiltersString: 'Filters',
    FilterText: 'Filter',
    GeneralGroupName: 'General',
    GroupByColumnLabel: 'Group by {0}',
    HideVerticalsLabel: 'Hide verticals',
    HideVerticalsDescription: 'Hide verticals from the vertical selector.',
    IconNameDescription: 'Name of the icon from UI Fabric. See https://uifabricicons.azurewebsites.net/.',
    IconNameLabel: 'Icon name',
    IncludeViewNameInExcelExportFilenameLabel: 'Include view-name in excel filename',
    InternalNameDescription: 'Internal field name for this column.',
    InternalNameLabel: 'Internal field name',
    IsGroupableDescription: 'Users can group this column.',
    IsGroupableLabel: 'Groupable',
    IsRefinableDescription: 'Users can filter this column.',
    IsRefinableLabel: 'Specify',
    IsResizableLabel: 'Resizable',
    ListLayoutModeJustifiedLabel: 'Adjust columns by screen width',
    ListViewGroupName: 'List view',
    ListViewText: 'List',
    LoadingText: 'Loading {0}...',
    LoadingTextDescription: 'Text displayed while the web part is loading.',
    LoadingTextLabel: 'Loading text',
    MaxWidthDescription: 'Maximum width for the column. Cannot be less than the minimum width.',
    MaxWidthLabel: 'Max width',
    MinWidthDescription: 'Minimum width for the column. Cannot exceed maximum width.',
    MinWidthLabel: 'Min width',
    MoveLeftLabel: 'Move left',
    MoveRightLabel: 'Move right',
    MyProjectsHeaderText: 'My projects',
    MyProjectsSearchBoxPlaceholderText: 'Search {0} projects you are a member of...',
    NameLabel: 'Name',
    NewColumnHeaderText: 'New column',
    NewLabel: 'New',
    NewViewHeaderText: 'Create view',
    NewViewText: 'Create new view',
    NoAccessMessage: 'You do not have access to this project',
    NoDefaultViewMessage: 'No default display has been set.',
    NoProjectsFoundMessage: 'There\'s no projects that have been created yet or have shown up in the search.',
    NoProjectsFoundTitle: 'No projects found',
    NotSet: 'Not set',
    ParentProjectsHeaderText: 'Parent projects',
    ParentProjectsSearchBoxPlaceholderText: 'Search {0} parent projects...',
    PersonalViewDescription: 'Choose whether this is a personal view. Personal views can only be edited by you.',
    PersonalViewLabel: 'Personal view',
    PersonalViewsHeaderText: 'Personal views',
    PhaseLabel: 'Phase',
    PortfolioAggregationNotConfiguredMessage: 'The web part must be configured with a data source. Edit the web part and enter the name of the data source you want to use.',
    PortfolioAggregationViewSearchQueryDescription: 'The query to retrieve data. DepartmentId refers to the Project Portal hub and should not be changed. ContentTypeId refers to the content type of the data element you want to retrieve. Go to the Data Sources list to see examples.',
    PortfolioOverviewColumnRenderDescription: 'Choose how the column should be displayed. If there are text fields to be displayed over several lines, select Note.',
    PortfolioOverviewDataFetchError: 'An error occurred while retrieving data for the portfolio overview. Please try again later.<br/><br/> **Error:**<br/> `{0}`',
    PortfolioOverviewDataFetchErrorView: 'An error occurred while retrieving data for the portfolio overview for view **{0}**. Please try again later, or try a different view.<br/><br/> **Error:**<br/> `{1}`',
    PortfolioOverviewShowEditViewColumnsPanelHelpText: 'Select the columns to display for the current view. To change the order, you can drag and drop or use the arrows next to each column. Use the \'Reset Order\' button to reset the order to the default order specified in the Project Columns list.',
    PortfolioViewSearchQueryDescription: 'The search query to retrieve projects in the portfolio. DepartmentId refers to the Project Portal hub and should not be changed.',
    ProgramProjectsHeaderText: 'Program',
    ProgramSearchBoxPlaceholderText: 'Search {0} programs...',
    ProgramsHeaderText: 'Programs',
    ProjectContentColumnItemNotFound: 'Project content column not found',
    ProjectDeliveriesGroupName: 'Project deliveries (beta)',
    ProjectInformationGroupName: 'Settings for Project information panel',
    ProjectInformationPanelButton: 'Open Project Information Panel',
    ProjectListEmptyMessage: 'The search returned no results',
    ProjectsAccessHeaderText: 'Access to',
    ProjectsAccessSearchBoxPlaceholderText: 'Search {0} projects you have access to...',
    RenderModeCompactListText: 'Compact list',
    RenderModeListText: 'List',
    RenderModeTilesText: 'Tiles',
    ResourceAllocationInfoText: 'Resource allocations or absences that apply across projects are entered into the <a href="../{0}">resource allocation hub list</a>. These entries will be shown in blue and red (absence) color in the table below. Project allocations are shown in green. The color strength of the allocation is based on the allocation percentage.<br/><br/>Note: The view is based on search, so the content of the view does not update immediately after changes are made.<br/><br/>Tip: To zoom in/out on the timeline, use ALT+Mouse Wheel or CTRL+Mouse Wheel. To navigate back and forth in time, you can use SHIFT+Mouse Wheel.',
    ResourceLabel: 'Resource',
    ResourceAbsenceLabel: 'Resource (absence)',
    DepartmentLabel: 'Department',
    RevertCustomOrderButtonText: 'Reset order',
    RevertCustomOrderButtonTooltip: 'Reset order to default order for columns specified in the Project Columns list.',
    RoleLabel: 'Role',
    RowLimitLabel: 'Number of elements',
    SaveButtonLabel: 'Save',
    SearchBoxGroupName: 'Search box',
    SearchBoxPlaceholderFallbackText: 'Search...',
    SearchBoxPlaceholderText: 'Search {0}...',
    SearchBoxPlaceholderTextDescription: 'Text that appears in the search box when it is empty. If no value is set, the text is based on the selected data source.',
    SearchBoxPlaceholderTextLabel: 'Search box text',
    SearchPropertyDescription: 'The name of the managed property for this column.',
    SearchPropertyFoundMessage: 'Found a managed property `{0}` that matches the internal field name `{1}`.',
    SearchPropertyLabel: 'Search property',
    SearchPropertyPlaceholder: 'Search managed properties...',
    SearchQueryLabel: 'Search query',
    SelectProgramText: 'Select a program',
    ShowCommandBarLabel: 'Show commandline',
    ShowExcelExportButtonLabel: 'Show export to Excel button',
    ShowFieldFrontpageLabel: 'Project frontpage',
    ShowFieldPortfolioLabel: 'Portfolio overview',
    ShowFieldProjectStatusLabel: 'Project status',
    ShowFiltersLabel: 'Show filters',
    ShowHideColumnsLabel: 'Show/hide columns',
    ShowProgramViewsLabel: 'Show program views',
    ShowProjectLogoFieldLabel: 'Show logo',
    ShowRenderModeSelectorLabel: 'Show view selector',
    ShowSearchBoxDescription: 'Here you can choose whether the search box should be shown or not.',
    ShowSearchBoxLabel: 'Show search box',
    ShowClosedProjectsLabel: "Show closed projects",
    ShowClosedProjectsDescription: "Includes projects with lifecycle status Closed. These are excluded by default. When enabled, each vertical's filters decide whether they are shown \u2014 add {\"GtProjectLifecycleStatus\": {\"$ne\": \"Closed\"}} to the field filter on the tabs that should stay free of them.",
    ShowViewSelectorLabel: 'Show view selector',
    SiteTitleLabel: 'Project',
    SortAscLabel: 'Z to A',
    SortByFieldLabel: 'Sorting property',
    SortCardsByLabel: 'Sort the tiles by: {0}',
    SortDescLabel: 'A to Z',
    SortOrderDescription: 'The sort order determines the order in which the views are displayed. The lowest value is displayed first.',
    SortOrderLabel: 'Sort order',
    StartDateLabel: 'Start date',
    StatusReportsCountLabel: 'Number of statusreports to display',
    TileViewGroupName: 'Tile view',
    TitleLabel: 'Title',
    ToggleColumnFormPanelLabel: 'Add column',
    UseChangesButtonText: 'Use',
    ViewNotFoundMessage: 'Cannot find the specified view.',
    ViewNotFoundMessage_WebPartProperty: 'Cannot find the specified view **{0}**. Please check the view name and try again.',
    ViewNotFoundMessage_Id: ' Cannot find a view with ID **{0}**.',
    NotSpecifiedText: 'Not specified',
    Idea: {
      MenuLabel: "Submit idea",
      ModuleTitle: 'Idea Module',
      ModuleLoadingText: 'Loading idea module',
      OverviewTitle: 'Ideas overview',
      RegistrationSectionTitle: 'Registration',
      RegisteredIdeasTitle: 'Registered ideas',
      ProcessingSectionTitle: 'Processing',
      ProcessingIdeasTitle: 'Ideas in processing',
      NewButtonText: 'New idea',
      NewButtonDescription: 'Create a new idea',
      EditButtonText: 'Edit',
      EditButtonDescription: 'Edit the idea',
      ApproveButtonText: 'Approve',
      ApproveButtonDescription: 'Approve the idea',
      DeleteButtonText: 'Delete',
      DeleteButtonDescription: 'Delete the idea',
      NoRegisteredIdeasText: 'There are currently no registered ideas, registered ideas will appear here',
      NoProcessingIdeasText: 'There are currently no ideas being processed, ideas in processing will appear here',
      RegisteredIdeaTitle: 'Registered idea',
      NoViewFoundErrorMessage: 'No view was found. It may be that the view specified in the address field does not exist, try removing this. Alternatively, create a new view (Data source).',
      NoIdeaFoundErrorMessage: 'No idea was found. It may be that the idea specified in the address field does not exist, try removing this. Alternatively, create a new idea.',
      ProvisionAreaTitle: 'Provision area',
      ConfigurationListFieldLabel: 'Configuration list',
      ConfigurationListFieldDescription: 'Name of the Idea configuration list',
      ConfigurationNameFieldLabel: 'Configuration name',
      ConfigurationNameFieldDescription: 'Name of the configuration to use',
      HiddenRegistrationFieldsLabel: 'Hidden fields (registration)',
      HiddenRegistrationFieldsDescription: 'Fields to hide from the idea module (Idea registration)',
      HiddenProcessingFieldsLabel: 'Hidden fields (processing)',
      HiddenProcessingFieldsDescription: 'Fields to hide from the idea module (Idea processing)',
    },
    NoViewFoundTitle: 'No view found',
    ProjectNotFound: 'Project not specified...',
    PrimaryFieldLabel: 'Primary field',
    SecondaryFieldLabel: 'Secondary field',
    PrimaryUserFieldLabel: 'Primary user',
    SecondaryUserFieldLabel: 'Secondary user',
    RefreshRequiredDescription: 'Requires refresh after changes',
    LifecycleStatus_Completed: 'Completed',
    LifecycleStatus_Closed: 'Closed',
    ProjectLevel: 'Project level',
    ColumnRenderOptionText: 'Text',
    NoProjectData: 'Unable to retrieve all data from the project. It may be that you do not have access to the project itself. It may also be that the project has recently been created or that project properties have not been filled in.',
    MeasurementSheetTitleKey: 'Measurement'
  }
})
