 define([], function () {
  return {
    Provision: {
      DrawerLevel1HeaderText: 'Create a new project',
      DrawerLevel1DescriptionText: 'Create a new project in the selected portfolio.',
      DrawerLevel2HeaderText: 'Create a new project',
      DrawerLevel2DescriptionText: 'Create a new project in the selected portfolio.',
      SiteTypeFieldLabel: 'Site type',
      SiteNameFieldLabel: 'Project name',
      SiteNameFieldDescription: 'Enter the name of the project. The name must be unique within the site collection.',
      SiteNameFieldPrefixLabel: 'Prefix',
      SiteNameFieldSuffixLabel: 'Suffix',
      SiteNamePrefixTooltipText: 'The prefix is used to identify the project in the site collection.',
      SiteNameSuffixTooltipText: 'The suffix is used to identify the project in the site collection.',
      SiteNameValidationErrorMessage: 'The project name must be unique within the site collection.',
      SiteNameValidationSuccessMessage: 'The project name is valid.',
      SiteDescriptionFieldLabel: 'Project description',
      SiteDescriptionFieldDescription: 'Enter a description of the project.',
      BusinessJustificationFieldLabel: 'Business justification',
      BusinessJustificationFieldDescription: 'Enter a business justification for the project.',
      AliasFieldLabel: 'Alias',
      UrlFieldLabel: 'URL',
      OwnerFieldLabel: 'Project owner',
      OwnerFieldDescription: 'Select the project owner.',
      OwnerFieldNoOptionsText: 'No options available',
      MemberFieldLabel: 'Project members',
      MemberFieldDescription: 'Select the project members.',
      MemberFieldNoOptionsText: 'No options available',
      TeamifyFieldLabel: 'Teamify',
      TeamifyFieldDescription: 'Create a Microsoft 365 group for the project.',
      TeamTemplateFieldLabel: 'Team template',
      TeamTemplateFieldDescription: 'Select the team template to use for the project.',
      ConfidentialFieldLabel: 'Confidential',
      ConfidentialFieldDescription: 'Select whether the project is confidential.',
      PrivacyFieldLabel: 'Privacy',
      PrivacyFieldDescription: 'Select the privacy level for the project.',
      PrivacyFieldOptionPrivate: 'Private',
      PrivacyFieldOptionPublic: 'Public',
      ExternalSharingFieldLabel: 'External sharing',
      ExternalSharingFieldDescription: 'Select whether the project can be shared externally.',
      GuestFieldLabel: 'Guest access',
      GuestFieldDescription: 'Select whether guests can access the project.',
      GuestFieldNoOptionsText: 'No options available',
      LanguageFieldLabel: 'Language',
      TimeZoneFieldLabel: 'Time zone',
      HubSiteFieldLabel: 'Hub site',
      DrawerFooterDescriptionText: 'By clicking "Create", you agree to the terms and conditions.',
      PreviousButtonLabel: 'Previous',
      NextButtonLabel: 'Next',
      ProvisionButtonLabel: 'Create',
      ToastCreatedTitle: 'Project created',
      ToastCreatedBody: 'The project has been created successfully.',
      ToastCreatedErrorTitle: 'Project creation failed',
      ToastCreatedErrorBody: 'The project could not be created. Please try again later.',
      StatusMenuLabel: 'Status',
      SettingsMenuLabel: 'Settings',
      IdeaMenuLabel: 'Ideas',
      SettingsSearchLabel: 'Search settings',
      SettingsDialogTitle: 'Settings',
      SettingsDialogDescription: 'Configure the settings for the project.',
      SettingsDialogSpinnerLabel: 'Loading settings...',
      SettingsDialogNoSearchResultsLabel: 'No search results',
      SettingsDialogNoResultsLabel: 'No results',
      SettingLabel: 'Setting',
      DescriptionLabel: 'Description',
      ValueLabel: 'Value',
      EditLabel: 'Edit',
      StatusSearchLabel: 'Search status',
      UpdateLabel: 'Update',
      StatusDialogTitle: 'Status',
      StatusDialogDescription: 'Configure the status for the project.',
      StatusDialogSpinnerLabel: 'Loading status...',
      StatusDialogNoSearchResultsLabel: 'No search results',
      StatusDialogNoResultsLabel: 'No results',
      StatusLabel: 'Status',
      SubmittedLabel: 'Submitted',
      ApprovedLabel: 'Approved',
      RejectedLabel: 'Rejected',
      PendingApprovalLabel: 'Pending approval',
      SpaceCreationFailedLabel: 'Space creation failed',
      SpaceAlreadyExistsLabel: 'Space already exists',
      TeamRequestedLabel: 'Team requested',
      SpaceCreationLabel: 'Space creation',
      SpaceCreatedLabel: 'Space created',
      NotSubmittedLabel: 'Not submitted',
      SubmittedDateLabel: 'Submitted date',
      DeleteLabel: 'Delete',
      DeleteSubmissionLabel: 'Delete submission',
      DeleteSubmissionConfirmationLabel: 'Are you sure you want to delete this submission?',
      DeletedSubmissionToastTitle: 'Submission deleted',
      DeletedSubmissionToastBody: 'The submission has been deleted successfully.',
      DeletedSubmissionErrorToastTitle: 'Submission deletion failed',
      DeletedSubmissionErrorToastBody: 'The submission could not be deleted. Please try again later.',
    },
    Aria: {
      MenuOverflowCount: '{0} more items',
      MoveDisabled: 'Move disabled',
      MoveUp: 'Move up',
      MoveUpDisabled: 'Move up disabled',
      MoveDown: 'Move down',
      MoveDownDisabled: 'Move down disabled',
      Back: 'Back',
      Settings: 'Settings',
      Close: 'Close'
    },
    Placeholder: {
      TextField: 'Enter text',
      SiteName: 'Project name',
      SiteDescription: 'Project description',
      Icon: 'Icon name',
      ChoiceField: 'Choice field',
      MultiChoiceField: 'Multi choice field',
      GuestField: 'Guest field',
      UserField: 'User field',
      BusinessJustificationField: 'Business justification field'
    },
    ColumnCategoryDescription: 'The category of the column. This is used to group columns in the web part.',
    ColumnCategoryLabel: 'Column category',
    ColumnRenderOptionInstrument: 'Instrument',
    DefaultRenderModeDescription: 'The default display mode for the web part. This can be changed in the web part properties.',
    DefaultTimeframeEndLabel: 'Default end date',
    DefaultTimeframeEndValue: 'Default end date value',
    DefaultTimeframeStartLabel: 'Default start date',
    DefaultTimeframeStartValue: 'Default start date value',
    DefaultVerticalDescription: 'The default vertical for the web part. This can be changed in the web part properties.',
    DisplayNamePortfolioOverviewDescription: 'Display name for the portfolio overview.',
    EditProjectListQuickLaunch: 'Edit project list',
    ErrorBoundaryFallbackDescription: 'An error occurred while retrieving data. Please try again later.',
    ErrorBoundaryFallbackText: 'An error occurred while retrieving data. Please try again later.',
    ErrorTitle: 'An error occurred',
    ModalColumnEmptyListMessage: 'No elements found.',
    ModalColumnEmptyListTitle: 'No elements found',
    OpenInNewTabLabel: 'Open in new tab',
    ProjectInformationPanelButton: 'Project information panel',
    ProjectListQuickLaunch: 'Project list',
    ProjectMetadataFieldLabel: 'Project metadata field',
    ProjectServiceArea: 'Project service area',
    ProjectType: 'Project type',
    RelativeUrl: 'Relative URL',
    RenderModeLabel: 'Display mode',
    ResourceAllocationGroupName: 'Resource allocation',
    SearchPropertyFoundTitle: 'Found a managed property',
    ShowInstrumentLinkText: 'Show instrument',
    ShowRenderModeSelectorDescription: 'Show the display mode selector.',
    ShowRenderModeSelectorLabel: 'Show display mode selector',
    ShowSearchBoxDescription: 'Show the search box.',
    ShowSortByDescription: 'Show the sorting options.',
    ShowSortByLabel: 'Show sorting options',
    SortByFieldDescription: 'The field to sort by.',
    TitleDescription: 'The title of the web part.',
    UseDynamicColorsDescription: 'Use dynamic colors for the web part.',
    UseDynamicColorsLabel: 'Use dynamic colors',
    ViewLessText: 'View less',
    ViewMoreText: 'View more',


    ResultsCountLabel: 'Displaying {0} of {1} projects',
    ColumnRenderOptionStatusReport: 'Status report',
    PortfolioSelectorLabel: 'Portfolio selector',
    PortfoliosFieldDescription: 'Select the portfolios to be displayed in the portfolio selector.',
    SelectedPortfolioDescription: 'The portfolio selected in the portfolio selector.',
    ShowPortfolioSelectorDescription: 'Show the portfolio selector.',
    IconNameFieldPlaceholder: 'Enter icon name',
    IconNameFieldLabel: 'Icon name',
    PortfolioSelectorDescription: 'Select the portfolio to be displayed in the portfolio selector.',
    ShowPortfolioSelectorOnText: 'Show portfolio selector',
    ShowPortfolioSelectorOffText: 'Hide portfolio selector',
    ShowPortfolioSelectorLabel: 'Show portfolio selector',
    SelectedPortfolioLabel: 'Selected portfolio',
    PortfoliosFieldLabel: 'Portfolios',
    PortfoliosPanelHeader: 'Portfolios',
    PortfoliosManageBtnLabel: 'Manage portfolios',
    UrlFieldLabel: 'URL',
    ViewsListNameFieldLabel: 'Views list name',
    ColumnsListNameFieldLabel: 'Columns list name',
    ColumnConfigListNameFieldLabel: 'Column configuration list name',
    GetPortfolioConfigErrorTitle: 'Error retrieving portfolio configuration',
    GetPortfolioConfigErrorText: 'An error occurred while retrieving the portfolio configuration. Please try again later.',
    AdvancedGroupName: 'Advanced',
    AddColumnLabel: 'Add a column',
    AllocationPercetageLabel: 'Allocation percentage',
    AllocationStatusLabel: 'Allocation status',
    AllProjectsHeaderText: 'All projects/programs',
    AllProjectsSearchBoxPlaceholderText: 'Search all {0} projects...',
    BarLabel: 'Bar',
    BooleanNo: 'No',
    BooleanYes: 'Yes',
    BooleanOff: 'Off',
    BooleanOn: 'On',
    CancelButtonLabel: 'Cancel',
    ChartConfigurationListNameLabel: 'Graph configuration',
    ChartErrorText: 'The graph is invalidly configured.',
    ColumnConfigListNameLabel: 'Column configuration',
    ColumnPersistRenderGloballyFieldDescription: 'If you want to change the display mode for the columns as for all web parts and views, tick the check box above.',
    ColumnPersistRenderGloballyFieldLabel: 'Update globally',
    ColumnRenderDataTypePropertiesHeaderText: 'Properties for display type',
    ColumnRenderDescription: 'Choose how the column should be displayed. If there are text fields to be displayed over several lines, select Note.',
    ColumnRenderLabel: 'Show as',
    ColumnRenderOptionBoolean: 'Yes/no',
    ColumnRenderOptionBooleanFalse: 'Value for \'No\'',
    ColumnRenderOptionBooleanTrue: 'Value for \'Yes\'',
    ColumnRenderOptionCurrency: 'Currency',
    ColumnRenderOptionCurrencyFallbackValueLabel: 'Default value',
    ColumnRenderOptionCurrencyMaximumFractionDigitsLabel: 'Maximum number of decimals',
    ColumnRenderOptionCurrencyMinimumFractionDigitsLabel: 'Minimum number of decimals',
    ColumnRenderOptionCurrencyPrefixLabel: 'Currency prefix',
    ColumnRenderOptionDate: 'Date',
    ColumnRenderOptionDateIncludeTimeLabel: 'Include time',
    ColumnRenderOptionFilename: 'File name',
    ColumnRenderOptionDialog: 'Modal',
    ColumnRenderOptionDialogInfoTextTemplateDescription: 'Template for info text. Use {{GtMeasurementOWSCHCS}} to display the measurement indicator, {{GtStartValueOWSNMBR}} to display the starting value, and {{GtDesiredValueOWSNMBR}} to display the target. You can also use other column names from the benefit overview.',
    ColumnRenderOptionDialogInfoTextTemplateLabel: 'Template for infotext',
    ColumnRenderOptionDialogLinkTextLabel: 'Linktext',
    ColumnRenderOptionDialogShowInfoTextLabel: 'Show infotext',
    ColumnRenderOptionNote: 'Note',
    ColumnRenderOptionNumber: 'Number',
    ColumnRenderOptionPercentage: 'Percentage',
    ColumnRenderOptionProjectInfo: 'Projectinformation',
    ColumnRenderOptionTags: 'Labels',
    ColumnRenderOptionTagsValueSeparatorDescription: 'Enter a character to be used to separate values in the label field. Default is semicolon.',
    ColumnRenderOptionTagsValueSeparatorLabel: 'Separator for values',
    ColumnRenderOptionText: 'Text',
    ColumnRenderOptionTrend: 'Trend',
    ColumnRenderOptionTrendShowTrendIconLabel: 'Show icon',
    ColumnRenderOptionUrl: 'URL',
    ColumnRenderOptionUrlDescriptionDescription: 'Link description. If you do not enter a value, any description from the link is used.',
    ColumnRenderOptionUrlDescriptionLabel: 'Description',
    ColumnRenderOptionUrlOpenInNewTabLabel: 'Open in new tab',
    ColumnRenderOptionUser: 'Person',
    ColumnSettingsDisabledTooltip: 'Column settings are only available when the site is in edit mode.',
    ColumnSettingsLabel: 'Column settings',
    ColumnsListNameLabel: 'Columns',
    ColumnVisibilityDescription: 'Specify where the column should appear. Project frontpage, the project status page, the portfolio overview or everywhere.',
    ColumnVisibilityLabel: 'Column visibility',
    CommandBarGroupName: 'Commandline',
    CommentLabel: 'Comment',
    CompactViewText: 'Compact list',
    ConfigItemTitleFieldDescription: 'If there is a specified element with this given title in the timelineconfiguration list, this will be displayed on the timeline.',
    ConfigItemTitleFieldLabel: 'Element title (Configuration)',
    ConfigurationGroupName: 'Configuration',
    ConfirmDeleteProjectColumnSubText: 'This column is removed from the Project Columns list and thus from all views that use it. Are you sure you want to delete this column? If you only want to remove the column from this display, you can use \'Show or hide columns\'.',
    ConfirmDeleteProjectColumnTitle: 'Do you want to delete?',
    ConfirmDeleteProjectContentColumnSubText: 'This column is removed from the Project Content Columns list and thus from all views that use it. Are you sure you want to delete this column? If you only want to remove the column from this display, you can use \'Show or hide columns\'.',
    ConfirmDeleteProjectContentColumnTitle: 'Do you want to delete?',
    ConfirmDeleteResponseAbort: 'Cancel',
    ConfirmDeleteResponseConfirm: 'Delete',
    CreatedTooltipText: 'Created {0}',
    CustomSortsText: 'Custom sorting',
    DataSourceCategoryDescription: 'Enter a data source category to be able to choose between multiple data sources in the web part.',
    DataSourceCategoryError: 'An error occurred while retrieving data sources with category **{0}**.',
    DataSourceCategoryLabel: 'Category for data sources',
    DataSourceError: 'An error occurred while retrieving data from the data source named **{0}**.',
    DataSourceGroupName: 'Data sources',
    DataSourceItemNotFound: 'Data source not found',
    DataSourceLabel: 'Data source',
    DataSourceLevelDescription: 'Set the level for the data source. This is used to filter data sources in the web part based on where data is obtained from. This can be changed afterwards in the \'Data sources\' list if you want to make the query/view available elsewhere.',
    DataSourceLevelLabel: 'Data source level',
    DataSourceNotFound: 'Cannot find any data source with name **{0}**.',
    DefaultDataSourceViewLabel: 'Default view (data source)',
    DefaultRenderModeLabel: 'Default display mode',
    DefaultVerticalLabel: 'Default vertical',
    DefaultViewDescription: 'Choose whether this is the default view for the Portfolio overview.',
    DefaultViewLabel: 'Default view',
    DefaultViewSetWarningMessage: 'There is already a view set as the default. You must first change this view before you can set a new one as the default. Personal views cannot be set as the default.',
    DeleteButtonLabel: 'Delete',
    DisplayNameDescription: 'Displayname for this column, for this web part only. If you want to change the display name for all web parts, you must change it in the Project Content Columns list.',
    DisplayNameLabel: 'Displayname',
    EditColumnHeaderText: 'Edit column',
    EditColumnLabel: 'Edit',
    EditViewColumnsPanelHeaderText: 'Edit displaycolumns',
    EditViewColumnsPanelHelpText: 'Select the columns to display for the current view. To change the order, you can drag and drop or use the arrows next to each column.',
    EditViewHeaderText: 'Edit view',
    EditViewText: 'Edit the view',
    EmptyMessageDescription: 'No new projects found.',
    EndDateLabel: 'End date',
    ExcelExportButtonLabel: 'Eksporter til Excel',
    ErrorFetchingProjectsTitle: 'An error occurred while retrieving projects.',
    FiltersString: 'Filters',
    FilterText: 'Filter',
    GeneralGroupName: 'General',
    GroupByColumnLabel: 'Group by {0}',
    HideVerticalsLabel: 'Hide verticals',
    IconNameDescription: 'Name of the icon from UI Fabric. See https://uifabricicons.azurewebsites.net/.',
    IconNameLabel: 'Icon name',
    IncludeViewNameInExcelExportFilenameLabel: 'Include view-name in excel filename',
    InternalNameDescription: 'Internal field name for this column.',
    InternalNameLabel: 'Internal field name',
    IsGroupableDescription: 'Users can group this column.',
    IsGroupableLabel: 'Groupable',
    IsRefinableDescription: 'Users can filter this column.',
    IsRefinableLabel: 'Specify',
    IsResizableLabel: 'Resizable',
    ListLayoutModeJustifiedLabel: 'Adjust columns by screen width',
    ListViewGroupName: 'List view',
    ListViewText: 'List',
    LoadingText: 'Loading {0}...',
    LoadingTextDescription: 'Text displayed while the web part is loading.',
    LoadingTextLabel: 'Loading text',
    MaxWidthDescription: 'Maximum width for the column. Cannot be less than the minimum width.',
    MaxWidthLabel: 'Max width',
    MeasurementAchievementLabel: 'Measurement achievement',
    MeasurementCommentLabel: 'Comment on measurement',
    MeasurementDateLabel: 'Date of measurement',
    MeasurementValueLabel: 'Measured value',
    MinWidthDescription: 'Minimum width for the column. Cannot exceed maximum width.',
    MinWidthLabel: 'Min width',
    ModalColumnEmptyListText: 'No elements found.',
    MoveLeftLabel: 'Move left',
    MoveRightLabel: 'Move right',
    MyProjectsHeaderText: 'My projects',
    MyProjectsSearchBoxPlaceholderText: 'Search {0} projects you are a member of...',
    NameLabel: 'Name',
    NewColumnHeaderText: 'New column',
    NewLabel: 'New',
    NewViewHeaderText: 'Create view',
    NewViewText: 'Create new view',
    NoAccessMessage: 'You do not have access to this project',
    NoDefaultViewMessage: 'No default display has been set.',
    NoProjectData: 'Unable to retrieve all data from the project. It may be that you do not have access to the project itself. It may also be that the project has recently been created or that project properties have not been filled in.',
    NoProjectsFoundMessage: 'There\'s no projects that have been created yet or have shown up in the search.',
    NoProjectsFoundTitle: 'No projects found',
    NotSet: 'Not set',
    ParentProjectsHeaderText: 'Parent projects',
    ParentProjectsSearchBoxPlaceholderText: 'Search {0} parent projects...',
    PersonalViewDescription: 'Choose whether this is a personal view. Personal views can only be edited by you.',
    PersonalViewLabel: 'Personal view',
    PersonalViewsHeaderText: 'Personal views',
    PhaseLabel: 'Phase',
    PortfolioAggregationNotConfiguredMessage: 'The web part must be configured with a data source. Edit the web part and enter the name of the data source you want to use.',
    PortfolioAggregationViewSearchQueryDescription: 'The query to retrieve data. DepartmentId refers to the Project Portal hub and should not be changed. ContentTypeId refers to the content type of the data element you want to retrieve. Go to the Data Sources list to see examples.',
    PortfolioManagerGroupName: 'Porteføljeinnsyn',
    PortfolioOverviewColumnRenderDescription: 'Choose how the column should be displayed. If there are text fields to be displayed over several lines, select Note.',
    PortfolioOverviewDataFetchError: 'An error occurred while retrieving data for the portfolio overview. Please try again later.<br/><br/> **Error:**<br/> `{0}`',
    PortfolioOverviewDataFetchErrorView: 'An error occurred while retrieving data for the portfolio overview for view **{0}**. Please try again later, or try a different view.<br/><br/> **Error:**<br/> `{1}`',
    PortfolioOverviewShowEditViewColumnsPanelHelpText: 'Select the columns to display for the current view. To change the order, you can drag and drop or use the arrows next to each column. Use the \'Reset Order\' button to reset the order to the default order specified in the Project Columns list.',
    PortfolioViewSearchQueryDescription: 'The search query to retrieve projects in the portfolio. DepartmentId refers to the Project Portal hub and should not be changed.',
    PortfolioViewsListName: 'Porteføljevisninger',
    ProgramProjectsHeaderText: 'Program',
    ProgramSearchBoxPlaceholderText: 'Search {0} programs...',
    ProgramsHeaderText: 'Programs',
    ProjectColumnsListName: 'Prosjektkolonner',
    ProjectContentColumnItemNotFound: 'Project content column not found',
    ProjectContentColumnsListName: 'Prosjektinnholdskolonner',
    ProjectDeliveriesGroupName: 'Project deliveries (beta)',
    ProjectInformationGroupName: 'Settings for Project information panel',
    ProjectLabel: 'Project',
    ProjectListEmptyMessage: 'The search returned no results',
    ProjectManager: 'Project Manager',
    ProjectOwner: 'Project owner',
    ProjectsAccessHeaderText: 'Access to',
    ProjectsAccessSearchBoxPlaceholderText: 'Search {0} projects you have access to...',
    ProjectsListName: 'Prosjekter',
    RenderModeCompactListText: 'Compact list',
    RenderModeListText: 'List',
    RenderModeTilesText: 'Tiles',
    ResourceAllocationInfoText: 'Resource allocations or absences that apply across projects are entered into the <A HREF="../Lists/Ressursallokering/AllItems.aspx?Source={0}">resource allocation hub list</A>. These entries will be shown in blue and red (absence) color in the table below. Project allocations are shown in green. The color strength of the allocation is based on the allocation percentage.',
    ResourceLabel: 'Resource',
    RevertCustomOrderButtonText: 'Reset order',
    RevertCustomOrderButtonTooltip: 'Reset order to default order for columns specified in the Project Columns list.',
    RoleLabel: 'Role',
    RowLimitLabel: 'Number of elements',
    SaveButtonLabel: 'Save',
    SearchBoxGroupName: 'Search box',
    SearchBoxPlaceholderFallbackText: 'Search...',
    SearchBoxPlaceholderText: 'Search {0}...',
    SearchBoxPlaceholderTextDescription: 'Text that appears in the search box when it is empty. If no value is set, the text is based on the selected data source.',
    SearchBoxPlaceholderTextLabel: 'Search box text',
    SearchPropertyDescription: 'The name of the managed property for this column.',
    SearchPropertyFoundMessage: 'Found a managed property `{0}` that matches the internal field name `{1}`.',
    SearchPropertyLabel: 'Search property',
    SearchPropertyPlaceholder: 'Search managed properties...',
    SearchQueryLabel: 'Search query',
    SelectProgramText: 'Select a program',
    ShowAllMeasurementsLinkText: 'Show all measurements',
    ShowCommandBarLabel: 'Show commandline',
    ShowExcelExportButtonLabel: 'Show export to Excel button',
    ShowFieldFrontpageLabel: 'Project frontpage',
    ShowFieldPortfolioLabel: 'Portfolio overview',
    ShowFieldProjectStatusLabel: 'Project status',
    ShowFiltersLabel: 'Show filters',
    ShowGroupByLabel: 'Show grouping options',
    ShowHideColumnsLabel: 'Show/hide columns',
    ShowProgramViewsLabel: 'Show program views',
    ShowProjectLogoFieldLabel: 'Show logo',
    ShowRenderModeSelectorLabel: 'Show view selector',
    ShowSearchBoxLabel: 'Show search box',
    ShowViewSelectorLabel: 'Show view selector',
    SiteTitleLabel: 'Project',
    SortAscLabel: 'Z to A',
    SortByFieldLabel: 'Sorting property',
    SortCardsByLabel: 'Sort the tiles by: {0}',
    SortDescLabel: 'A to Z',
    SortOrderDescription: 'The sort order determines the order in which the views are displayed. The lowest value is displayed first.',
    SortOrderLabel: 'Sort order',
    StartDateLabel: 'Start date',
    StatusReportsCountLabel: 'Number of statusreports to display',
    TileViewGroupName: 'Tile view',
    TimelineConfigurationListName: 'Tidslinjekonfigurasjon',
    TimelineContentListName: 'Tidslinjeinnhold',
    TitleLabel: 'Title',
    ToggleColumnFormPanelLabel: 'Add column',
    UseChangesButtonText: 'Use',
    ViewNotFoundMessage: 'Cannot find the specified view.',
    ViewNotFoundMessage_WebPartProperty: 'Cannot find the specified view **{0}**. Please check the view name and try again.',
    ViewNotFoundMessage_Id:' Cannot find a view with ID **{0}**.',
    ViewsListNameLabel: 'Views'
  }
})
