define([], function () {
  return {
    Provision: {
      DrawerLevel0HeaderText: "Request site",
      DrawerLevel0DescriptionText: "Here you can request a new site. Choose one of the site types below and fill in the required information.",
      DrawerLevel1HeaderText: "Classification",
      DrawerLevel1DescriptionText: "Here you can select classification for the site, activate Teams, sensitivity label, and retention label.",
      DrawerLevel2HeaderText: "Additional information",
      DrawerLevel2DescriptionText: "Here you can provide other information for the site, such as site image, language, time zone, and hub connection.",
      SiteTypeFieldLabel: "Site type",
      SiteNameFieldLabel: "Site name",
      SiteNameFieldDescription: "Choose a unique name that follows your organization's naming conventions.",
      SiteNamePrefixTooltipText: "This is a prefix added to the beginning of the site name.",
      SiteNameSuffixTooltipText: "This is a suffix added to the end of the site name.",
      SiteNameValidationErrorMessage: "The name is already taken. Please try a different name.",
      SiteNameValidationSuccessMessage: "The name is available",
      SiteDescriptionFieldLabel: "Description",
      SiteDescriptionFieldDescription: "Providing a description is optional but helps others understand the purpose of your site.",
      BusinessJustificationFieldLabel: "Business justification",
      BusinessJustificationFieldDescription: "Why do you need this site? What is the purpose?",
      AdditionalInfoFieldLabel: "Additional information",
      AdditionalInfoFieldDescription: "Provide additional information regarding the request.",
      AliasFieldLabel: "Alias/Name",
      UrlFieldLabel: "Site address",
      OwnerFieldLabel: "Owner(s)",
      OwnerFieldDescription: "Owners have full access and can manage members. You can add more owners later.",
      MemberFieldLabel: "Member(s)",
      MemberFieldDescription: "Members have access based on permissions. You can add more members later.",
      RequestedByFieldLabel: "Requested on behalf of",
      RequestedByFieldDescription: "If you're requesting on someone's behalf, enter their name here. Leave blank if it's for yourself.",
      UserFieldNoOptionsText: "No results...",
      TeamifyFieldLabel: "Enable Teams for this site?",
      TeamifyFieldDescription: "If enabled, a Teams workspace will be created and linked to this site.",
      TeamTemplateFieldLabel: "Teams template",
      TeamTemplateFieldDescription: "Which Teams template do you want to use for this site?",
      ConfidentialFieldLabel: "Confidential/Sensitive data",
      ConfidentialFieldDescription: "Will confidential or sensitive data be stored here? If yes, ensure proper permissions are set.",
      PrivacyFieldLabel: "Privacy settings",
      PrivacyFieldDescription: "Set the desired privacy level for the site.",
      PrivacyFieldOptionPrivate: "Private – Users need permission to join",
      PrivacyFieldOptionPublic: "Public – Anyone in the organization can join",
      ExternalSharingFieldLabel: "Allow external guests",
      ExternalSharingFieldDescription: "If enabled, you can invite and share content (files, folders, libraries, etc.) with external guests. Note: You can only invite guests after the group/site is created.",
      CommunityNameFieldLabel: "Community name",
      CommunityNameFieldDescription: "Enter the name for the community",
      CommunityNameFieldPlaceholder: "Enter community name",
      CommunityDescriptionFieldLabel: "Community description",
      CommunityDescriptionFieldDescription: "Enter a description for the community",
      CommunityDescriptionFieldPlaceholder: "Enter community description",
      CommunityJustificationFieldLabel: "Community justification",
      CommunityJustificationFieldDescription: "Provide justification for the community",
      CommunityJustificationFieldPlaceholder: "Enter community justification",
      CommunityOwnerFieldLabel: "Community owner(s)",
      CommunityOwnerFieldDescription: "Select the owner(s) for the community",
      CommunityOwnerFieldPlaceholder: "Select community owners",
      CommunityMemberFieldLabel: "Community member(s)",
      CommunityMemberFieldDescription: "Select the member(s) for the community",
      CommunityMemberFieldPlaceholder: "Select community members",
      CommunityPrivacyFieldLabel: "Community privacy",
      CommunityPrivacyFieldDescription: "Set the privacy level for the community",
      CommunityPrivacyFieldPlaceholder: "Select privacy level",
      TeamNameFieldLabel: "Team name",
      TeamNameFieldDescription: "Enter the name for the team",
      TeamNameFieldPlaceholder: "Enter team name",
      TeamDescriptionFieldLabel: "Team description",
      TeamDescriptionFieldDescription: "Enter a description for the team",
      TeamDescriptionFieldPlaceholder: "Enter team description",
      TeamOwnerFieldLabel: "Team owner(s)",
      TeamOwnerFieldDescription: "Select the owner(s) for the team",
      TeamOwnerFieldPlaceholder: "Select team owners",
      TeamMemberFieldLabel: "Team member(s)",
      TeamMemberFieldDescription: "Select the member(s) for the team",
      TeamMemberFieldPlaceholder: "Select team members",
      TeamJustificationFieldLabel: "Team justification",
      TeamJustificationFieldDescription: "Provide justification for the team",
      TeamJustificationFieldPlaceholder: "Enter team justification",
      TeamPrivacyFieldLabel: "Team privacy",
      TeamPrivacyFieldDescription: "Set the privacy level for the team",
      TeamPrivacyFieldPlaceholder: "Select privacy level",
      ButtonLabelFieldLabel: "Button label",
      ButtonLabelFieldDescription: "Set the label for the button",
      AutoOwnerFieldLabel: "Set current user as owner",
      AutoOwnerFieldDescription: "Automatically set the current user as owner",
      AutoOwnerOnText: "Yes",
      AutoOwnerOffText: "No",
      AppearanceGroupName: "Appearance",
      SiteTypeRenderModeFieldLabel: "Site type display mode",
      SiteTypeRenderModeCardNormal: "Card (with image)",
      SiteTypeRenderModeCardMinimal: "Card (without image and description)",
      SiteTypeRenderModeDropdown: "Dropdown",
      ExpirationDateModeFieldLabel: "Expiration date mode",
      ExpirationDateModeDate: "Date",
      ExpirationDateModeMonthDropdown: "Month dropdown",
      TitlesAndDescriptionsGroupName: "Titles and descriptions",
      Level0HeaderFieldLabel: "Level 0 title",
      Level0HeaderFieldDescription: "Set the title for level 0",
      Level0DescriptionFieldLabel: "Level 0 description",
      Level0DescriptionFieldDescription: "Set the description for level 0",
      Level1HeaderFieldLabel: "Level 1 title",
      Level1HeaderFieldDescription: "Set the title for level 1",
      Level1DescriptionFieldLabel: "Level 1 description",
      Level1DescriptionFieldDescription: "Set the description for level 1",
      Level2HeaderFieldLabel: "Level 2 title",
      Level2HeaderFieldDescription: "Set the title for level 2",
      Level2DescriptionFieldLabel: "Level 2 description",
      Level2DescriptionFieldDescription: "Set the description for level 2",
      FooterDescriptionFieldLabel: "Footer description",
      FooterDescriptionFieldDescription: "Set the footer description",
      ShowHideGroupName: "Show/Hide",
      HideStatusMenuFieldLabel: "Hide status menu",
      HideSettingsMenuFieldLabel: "Hide settings menu",
      ProvisionUrlFieldLabel: "Provision URL",
      ProvisionUrlFieldDescription: "Set the URL for provisioning",
      FieldsConfigurationLabel: "Fields configuration",
      FieldsConfigurationPanelHeader: "Fields configuration panel",
      FieldsConfigurationManageBtnLabel: "Manage fields configuration",
      FieldOrderLabel: "Default order",
      FieldNameLabel: "Field name (internal)",
      FieldDisplayNameLabel: "Display name",
      FieldDescriptionLabel: "Field description",
      FieldPlaceholderLabel: "Field placeholder",
      FieldDataTypeLabel: "Field data type",
      FieldDataTypeText: "Text",
      FieldDataTypeNote: "Note",
      FieldDataTypeNumber: "Number",
      FieldDataTypeChoice: "Choice",
      FieldDataTypeUserMulti: "Multiple users",
      FieldDataTypeGuest: "Guest",
      FieldDataTypeDate: "Date",
      FieldDataTypeTags: "Tags",
      FieldDataTypeBoolean: "Boolean",
      FieldDataTypePercentage: "Percentage",
      FieldDataTypeSite: "Site",
      FieldDataTypeImage: "Image",
      FieldRequiredLabel: "Field required",
      FieldHiddenLabel: "Field hidden",
      FieldLevelLabel: "Field level",
      WebPartDescription: "Web part description",
      MissingFieldsTitle: "Missing required fields",
      GuestFieldLabel: "Guest(s)",
      GuestFieldDescription: "Guests have limited access. You can add more guests later. Please enter a valid email address.",
      GuestFieldNoOptionsText: "Cannot add...",
      SensitivityLabelFieldLabel: "Sensitivity label",
      SensitivityLabelFieldDescription: "Which sensitivity label do you want to apply to this site?",
      RetentionLabelFieldLabel: "Retention label",
      RetentionLabelFieldDescription: "Which retention label do you want to apply to this site?",
      ExpirationDateFieldLabel: "Expiration date",
      ExpirationDateFieldDescription: "When should the site expire? Note: The site will not be deleted automatically after this date.",
      ReadOnlyGroupFieldLabel: "Enable read-only access group",
      ReadOnlyGroupFieldDescription: "Enable a read-only group for the site. Members of this group will have read-only access.",
      InternalChannelFieldLabel: "Enable internal channel",
      InternalChannelFieldDescription: "When enabled, an internal channel will be created in Teams.",
      LanguageFieldLabel: "Language",
      TimeZoneFieldLabel: "Time zone",
      DefaultLanguage: "English (United States)",
      DefaultTimeZone: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
      HubSiteFieldLabel: "Hub association",
      ImageFieldLabel: "Set site image",
      ImageFieldDescription: "Upload an image to use as the site image.",
      ImageDropZoneText: "Drag and drop image here, or click to select a file (png, jpeg/jpg)",
      DrawerFooterDescriptionText: "Your site will be linked to a Microsoft 365 Group, which provides a shared OneNote notebook, group email address, and shared calendar.",
      PreviousButtonLabel: "Previous",
      NextButtonLabel: "Next",
      ProvisionButtonLabel: "Request site",
      ToastCreatedTitle: "Site requested",
      ToastCreatedBody: "The site has been requested and is being processed.",
      ToastCreatedErrorTitle: "Request error",
      ToastCreatedErrorBody: "An error occurred while requesting the site. Please try again or contact an administrator.",
      StatusMenuLabel: "My requests",
      SettingsMenuLabel: "Settings",
      SettingsSearchLabel: "Search settings",
      SettingsDialogTitle: "Provisioning Portal Settings",
      SettingsDialogDescription: "Here you can see all settings for the provisioning portal.",
      SettingsDialogSpinnerLabel: "Updating and retrieving settings...",
      SettingsDialogNoSearchResultsLabel: "No settings match your search.",
      SettingsDialogNoResultsLabel: "There are no settings for the provisioning portal.",
      SettingLabel: "Setting",
      DescriptionLabel: "Description",
      ValueLabel: "Value",
      EditLabel: "Edit",
      StatusSearchLabel: "Search requests",
      UpdateLabel: "Update",
      StatusDialogTitle: "My requests",
      StatusDialogDescription: "View the status of your site requests, including type, status, and submission date. You can also delete unsubmitted or rejected requests.",
      StatusDialogSpinnerLabel: "Updating and retrieving requests...",
      StatusDialogNoSearchResultsLabel: "No requests match your search.",
      StatusDialogNoResultsLabel: "You have no site requests. Submit a new one to track its status here.",
      StatusLabel: "Status",
      SubmittedLabel: "Submitted",
      ApprovedLabel: "Approved",
      RejectedLabel: "Rejected",
      PendingApprovalLabel: "Pending approval",
      SpaceCreationFailedLabel: "Site creation failed",
      SpaceAlreadyExistsLabel: "Site already exists",
      TeamRequestedLabel: "Team requested",
      SpaceCreationLabel: "Creating site",
      SpaceCreatedLabel: "Site created",
      NotSubmittedLabel: "Not submitted",
      SubmittedDateLabel: "Submission date",
      DeleteLabel: "Delete",
      DeleteSubmissionLabel: "Delete request",
      DeleteSubmissionConfirmationLabel: "Are you sure you want to delete this request?",
      DeletedSubmissionToastTitle: "Request deleted",
      DeletedSubmissionToastBody: "The request, {0}, has been deleted.",
      DeletedSubmissionErrorToastTitle: "Deletion error",
      DeletedSubmissionErrorToastBody: "An error occurred while deleting the request. Please try again or contact an administrator.",
      RequestedSource: "Project Portal – Request form"
    },
    Aria: {
      MenuOverflowCount: '{0} more items',
      MoveDisabled: 'Move disabled',
      MoveUp: 'Move up',
      MoveUpDisabled: 'Move up disabled',
      MoveDown: 'Move down',
      MoveDownDisabled: 'Move down disabled',
      Back: 'Back',
      Settings: 'Settings',
      Close: 'Close'
    },
    Placeholder: {
      TextField: "Enter text here",
      SiteName: "Enter a name for the site",
      SiteDescription: "Enter a description for the site",
      Icon: "Enter an icon",
      ChoiceField: "Select an option",
      MultiChoiceField: "Select one or more options",
      GuestField: "Enter guests",
      UserField: "Enter users",
      BusinessJustificationField: "Enter a business justification",
      AdditionalInfoField: "Enter additional information",
      DatePicker: "Pick a date"
    },
    ColumnCategoryDescription: 'The category of the column. This is used to group columns in the web part.',
    ColumnCategoryLabel: 'Column category',
    ColumnRenderOptionInstrument: 'Instrument',
    InstrumentUnitLabel: 'Unit: {0}',
    DefaultRenderModeDescription: 'The default display mode for the web part. This can be changed in the web part properties.',
    DefaultTimeframeEndLabel: 'Default end date',
    DefaultTimeframeEndValue: 'Default end date value',
    DefaultTimeframeStartLabel: 'Default start date',
    DefaultTimeframeStartValue: 'Default start date value',
    DefaultVerticalDescription: 'The default vertical for the web part. This can be changed in the web part properties.',
    DisplayNamePortfolioOverviewDescription: 'Display name for the portfolio overview.',
    EditProjectListQuickLaunch: 'Edit project list',
    ErrorBoundaryFallbackDescription: 'An error occurred while retrieving data. Please try again later.',
    ErrorBoundaryFallbackText: 'An error occurred while retrieving data. Please try again later.',
    ErrorTitle: 'An error occurred',
    ModalColumnEmptyListMessage: 'No elements found.',
    ModalColumnEmptyListTitle: 'No elements found',
    OpenInNewTabLabel: 'Open in new tab',
    ProjectInformationPanelButton: 'Project information panel',
    ProjectListQuickLaunch: 'Project list',
    ProjectMetadataFieldLabel: 'Project metadata field',
    ProjectCard: {
      WebPartDescription: 'Project card',
      ProjectSiteIdFieldLabel: 'Site ID',
      ProjectSiteIdFieldDescription: 'ID for the SharePoint site (Project)'
    },
    ProjectServiceArea: 'Project service area',
    ProjectType: 'Project type',
    RelativeUrl: 'Relative URL',
    RenderModeLabel: 'Display mode',
    ResourceAllocationGroupName: 'Resource allocation',
    SearchPropertyFoundTitle: 'Found a managed property',
    ShowInstrumentLinkText: 'Show instrument',
    ShowRenderModeSelectorDescription: 'Show the display mode selector.',
    ShowRenderModeSelectorLabel: 'Show display mode selector',
    ShowSearchBoxDescription: 'Show the search box.',
    ShowSortByDescription: 'Show the sorting options.',
    ShowSortByLabel: 'Show sorting options',
    SortByFieldDescription: 'The field to sort by.',
    TitleDescription: 'The title of the web part.',
    UseDynamicColorsDescription: 'Use dynamic colors for the web part.',
    UseDynamicColorsLabel: 'Use dynamic colors',
    ViewLessText: 'View less',
    ViewMoreText: 'View more',
    ResultsCountLabel: 'Displaying {0} of {1} projects',
    ColumnRenderOptionStatusReport: 'Status report',
    PortfolioSelectorLabel: 'Portfolio selector',
    PortfoliosFieldDescription: 'Select the portfolios to be displayed in the portfolio selector.',
    SelectedPortfolioDescription: 'The portfolio selected in the portfolio selector.',
    ShowPortfolioSelectorDescription: 'Show the portfolio selector.',
    IconNameFieldPlaceholder: 'Enter icon name',
    IconNameFieldLabel: 'Icon name',
    PortfolioSelectorDescription: 'Select the portfolio to be displayed in the portfolio selector.',
    ShowPortfolioSelectorOnText: 'Show portfolio selector',
    ShowPortfolioSelectorOffText: 'Hide portfolio selector',
    ShowPortfolioSelectorLabel: 'Show portfolio selector',
    SelectedPortfolioLabel: 'Selected portfolio',
    PortfoliosFieldLabel: 'Portfolios',
    PortfoliosPanelHeader: 'Portfolios',
    PortfoliosManageBtnLabel: 'Manage portfolios',
    UrlFieldLabel: 'URL',
    ViewsListNameFieldLabel: 'Views list name',
    ColumnsListNameFieldLabel: 'Columns list name',
    ColumnConfigListNameFieldLabel: 'Column configuration list name',
    GetPortfolioConfigErrorTitle: 'Error retrieving portfolio configuration',
    GetPortfolioConfigErrorText: 'An error occurred while retrieving the portfolio configuration. Please try again later.',
    AdvancedGroupName: 'Advanced',
    AddColumnLabel: 'Add a column',
    AllocationPercetageLabel: 'Allocation percentage',
    AllocationStatusLabel: 'Allocation status',
    AllProjectsHeaderText: 'All projects/programs',
    AllProjectsSearchBoxPlaceholderText: 'Search all {0} projects...',
    BooleanNo: 'No',
    BooleanYes: 'Yes',
    BooleanOff: 'Off',
    BooleanOn: 'On',
    CancelButtonLabel: 'Cancel',
    ChartErrorText: 'The graph is invalidly configured.',
    ColumnPersistRenderGloballyFieldDescription: 'If you want to change the display mode for the columns as for all web parts and views, tick the check box above.',
    ColumnPersistRenderGloballyFieldLabel: 'Update globally',
    ColumnRenderDataTypePropertiesHeaderText: 'Properties for display type',
    ColumnRenderDescription: 'Choose how the column should be displayed. If there are text fields to be displayed over several lines, select Note.',
    ColumnRenderLabel: 'Show as',
    ColumnRenderOptionBoolean: 'Yes/no',
    ColumnRenderOptionBooleanFalse: 'Value for \'No\'',
    ColumnRenderOptionBooleanTrue: 'Value for \'Yes\'',
    ColumnRenderOptionCurrency: 'Currency',
    ColumnRenderOptionCurrencyFallbackValueLabel: 'Default value',
    ColumnRenderOptionCurrencyMaximumFractionDigitsLabel: 'Maximum number of decimals',
    ColumnRenderOptionCurrencyMinimumFractionDigitsLabel: 'Minimum number of decimals',
    ColumnRenderOptionCurrencyPrefixLabel: 'Currency prefix',
    ColumnRenderOptionDate: 'Date',
    ColumnRenderOptionDateIncludeTimeLabel: 'Include time',
    ColumnRenderOptionFilename: 'File name',
    ColumnRenderOptionDialog: 'Modal',
    ColumnRenderOptionDialogInfoTextTemplateDescription: 'Template for info text. Use {{GtMeasurementOWSCHCS}} to display the measurement indicator, {{GtStartValueOWSNMBR}} to display the starting value, and {{GtDesiredValueOWSNMBR}} to display the target. You can also use other column names from the benefit overview.',
    ColumnRenderOptionDialogInfoTextTemplateLabel: 'Template for infotext',
    ColumnRenderOptionDialogLinkTextLabel: 'Linktext',
    ColumnRenderOptionDialogShowInfoTextLabel: 'Show infotext',
    ColumnRenderOptionNote: 'Note',
    ColumnRenderOptionNumber: 'Number',
    ColumnRenderOptionPercentage: 'Percentage',
    ColumnRenderOptionProjectInfo: 'Projectinformation',
    ColumnRenderOptionTags: 'Labels',
    ColumnRenderOptionTagsValueSeparatorDescription: 'Enter a character to be used to separate values in the label field. Default is semicolon.',
    ColumnRenderOptionTagsValueSeparatorLabel: 'Separator for values',
    ColumnRenderOptionText: 'Text',
    ColumnRenderOptionTrend: 'Trend',
    ColumnRenderOptionTrendShowTrendIconLabel: 'Show icon',
    ColumnRenderOptionUrl: 'URL',
    ColumnRenderOptionUrlDescriptionDescription: 'Link description. If you do not enter a value, any description from the link is used.',
    ColumnRenderOptionUrlDescriptionLabel: 'Description',
    ColumnRenderOptionUrlOpenInNewTabLabel: 'Open in new tab',
    ColumnRenderOptionUser: 'Person',
    ColumnSettingsDisabledTooltip: 'Column settings are only available when the site is in edit mode.',
    ColumnSettingsLabel: 'Column settings',
    ColumnVisibilityDescription: 'Specify where the column should appear. Project frontpage, the project status page, the portfolio overview or everywhere.',
    ColumnVisibilityLabel: 'Column visibility',
    CommandBarGroupName: 'Commandline',
    CommentLabel: 'Comment',
    CompactViewText: 'Compact list',
    ConfigItemTitleFieldDescription: 'If there is a specified element with this given title in the timelineconfiguration list, this will be displayed on the timeline.',
    ConfigItemTitleFieldLabel: 'Element title (Configuration)',
    ConfigurationGroupName: 'Configuration',
    ConfirmDeleteProjectColumnSubText: 'This column is removed from the Project Columns list and thus from all views that use it. Are you sure you want to delete this column? If you only want to remove the column from this display, you can use \'Show or hide columns\'.',
    ConfirmDeleteProjectColumnTitle: 'Do you want to delete?',
    ConfirmDeleteProjectContentColumnSubText: 'This column is removed from the Project Content Columns list and thus from all views that use it. Are you sure you want to delete this column? If you only want to remove the column from this display, you can use \'Show or hide columns\'.',
    ConfirmDeleteProjectContentColumnTitle: 'Do you want to delete?',
    ConfirmDeleteResponseAbort: 'Cancel',
    ConfirmDeleteResponseConfirm: 'Delete',
    CreatedTooltipText: 'Created {0}',
    CustomSortsText: 'Custom sorting',
    DataSourceCategoryDescription: 'Enter a data source category to be able to choose between multiple data sources in the web part.',
    DataSourceCategoryError: 'An error occurred while retrieving data sources with category **{0}**.',
    DataSourceCategoryLabel: 'Category for data sources',
    DataSourceError: 'An error occurred while retrieving data from the data source named **{0}**.',
    DataSourceGroupName: 'Data sources',
    DataSourceItemNotFound: 'Data source not found',
    DataSourceLabel: 'Data source',
    DataSourceLevelDescription: 'Set the level for the data source. This is used to filter data sources in the web part based on where data is obtained from. This can be changed afterwards in the \'Data sources\' list if you want to make the query/view available elsewhere.',
    DataSourceLevelLabel: 'Data source level',
    DataSourceNotFound: 'Cannot find any data source with name **{0}**.',
    DefaultDataSourceViewLabel: 'Default view (data source)',
    DefaultRenderModeLabel: 'Default display mode',
    DefaultVerticalLabel: 'Default vertical',
    DefaultViewDescription: 'Choose whether this is the default view for the Portfolio overview.',
    DefaultViewLabel: 'Default view',
    DefaultViewSetWarningMessage: 'There is already a view set as the default. You must first change this view before you can set a new one as the default. Personal views cannot be set as the default.',
    DeleteButtonLabel: 'Delete',
    DisplayNameDescription: 'Displayname for this column, for this web part only. If you want to change the display name for all web parts, you must change it in the Project Content Columns list.',
    DisplayNameLabel: 'Displayname',
    EditColumnHeaderText: 'Edit column',
    EditColumnLabel: 'Edit',
    EditViewColumnsPanelHeaderText: 'Edit displaycolumns',
    EditViewColumnsPanelHelpText: 'Select the columns to display for the current view. To change the order, you can drag and drop or use the arrows next to each column.',
    EditViewHeaderText: 'Edit view',
    EditViewText: 'Edit the view',
    EmptyMessageDescription: 'No new projects found.',
    EndDateLabel: 'End date',
    ExcelExportButtonLabel: 'Export to excel',
    ErrorFetchingProjectsTitle: 'An error occurred while retrieving projects.',
    FiltersString: 'Filters',
    FilterText: 'Filter',
    GeneralGroupName: 'General',
    GroupByColumnLabel: 'Group by {0}',
    HideVerticalsLabel: 'Hide verticals',
    IconNameDescription: 'Name of the icon from UI Fabric. See https://uifabricicons.azurewebsites.net/.',
    IconNameLabel: 'Icon name',
    IncludeViewNameInExcelExportFilenameLabel: 'Include view-name in excel filename',
    InternalNameDescription: 'Internal field name for this column.',
    InternalNameLabel: 'Internal field name',
    IsGroupableDescription: 'Users can group this column.',
    IsGroupableLabel: 'Groupable',
    IsRefinableDescription: 'Users can filter this column.',
    IsRefinableLabel: 'Specify',
    IsResizableLabel: 'Resizable',
    ListLayoutModeJustifiedLabel: 'Adjust columns by screen width',
    ListViewGroupName: 'List view',
    ListViewText: 'List',
    LoadingText: 'Loading {0}...',
    LoadingTextDescription: 'Text displayed while the web part is loading.',
    LoadingTextLabel: 'Loading text',
    MaxWidthDescription: 'Maximum width for the column. Cannot be less than the minimum width.',
    MaxWidthLabel: 'Max width',
    MeasurementAchievementLabel: 'Measurement achievement',
    MeasurementCommentLabel: 'Comment on measurement',
    MeasurementDateLabel: 'Date of measurement',
    MeasurementValueLabel: 'Measured value',
    MinWidthDescription: 'Minimum width for the column. Cannot exceed maximum width.',
    MinWidthLabel: 'Min width',
    ModalColumnEmptyListText: 'No elements found.',
    MoveLeftLabel: 'Move left',
    MoveRightLabel: 'Move right',
    MyProjectsHeaderText: 'My projects',
    MyProjectsSearchBoxPlaceholderText: 'Search {0} projects you are a member of...',
    NameLabel: 'Name',
    NewColumnHeaderText: 'New column',
    NewLabel: 'New',
    NewViewHeaderText: 'Create view',
    NewViewText: 'Create new view',
    NoAccessMessage: 'You do not have access to this project',
    NoDefaultViewMessage: 'No default display has been set.',
    NoProjectData: 'Unable to retrieve all data from the project. It may be that you do not have access to the project itself. It may also be that the project has recently been created or that project properties have not been filled in.',
    NoProjectsFoundMessage: 'There\'s no projects that have been created yet or have shown up in the search.',
    NoProjectsFoundTitle: 'No projects found',
    NotSet: 'Not set',
    ParentProjectsHeaderText: 'Parent projects',
    ParentProjectsSearchBoxPlaceholderText: 'Search {0} parent projects...',
    PersonalViewDescription: 'Choose whether this is a personal view. Personal views can only be edited by you.',
    PersonalViewLabel: 'Personal view',
    PersonalViewsHeaderText: 'Personal views',
    PhaseLabel: 'Phase',
    PortfolioAggregationNotConfiguredMessage: 'The web part must be configured with a data source. Edit the web part and enter the name of the data source you want to use.',
    PortfolioAggregationViewSearchQueryDescription: 'The query to retrieve data. DepartmentId refers to the Project Portal hub and should not be changed. ContentTypeId refers to the content type of the data element you want to retrieve. Go to the Data Sources list to see examples.',
    PortfolioOverviewColumnRenderDescription: 'Choose how the column should be displayed. If there are text fields to be displayed over several lines, select Note.',
    PortfolioOverviewDataFetchError: 'An error occurred while retrieving data for the portfolio overview. Please try again later.<br/><br/> **Error:**<br/> `{0}`',
    PortfolioOverviewDataFetchErrorView: 'An error occurred while retrieving data for the portfolio overview for view **{0}**. Please try again later, or try a different view.<br/><br/> **Error:**<br/> `{1}`',
    PortfolioOverviewShowEditViewColumnsPanelHelpText: 'Select the columns to display for the current view. To change the order, you can drag and drop or use the arrows next to each column. Use the \'Reset Order\' button to reset the order to the default order specified in the Project Columns list.',
    PortfolioViewSearchQueryDescription: 'The search query to retrieve projects in the portfolio. DepartmentId refers to the Project Portal hub and should not be changed.',
    ProgramProjectsHeaderText: 'Program',
    ProgramSearchBoxPlaceholderText: 'Search {0} programs...',
    ProgramsHeaderText: 'Programs',
    ProjectContentColumnItemNotFound: 'Project content column not found',
    ProjectDeliveriesGroupName: 'Project deliveries (beta)',
    ProjectInformationGroupName: 'Settings for Project information panel',
    ProjectListEmptyMessage: 'The search returned no results',
    ProjectsAccessHeaderText: 'Access to',
    ProjectsAccessSearchBoxPlaceholderText: 'Search {0} projects you have access to...',
    RenderModeCompactListText: 'Compact list',
    RenderModeListText: 'List',
    RenderModeTilesText: 'Tiles',
    ResourceAllocationInfoText: 'Resource allocations or absences that apply across projects are entered into the <a href="../{0}">resource allocation hub list</a>. These entries will be shown in blue and red (absence) color in the table below. Project allocations are shown in green. The color strength of the allocation is based on the allocation percentage.<br/><br/>Note: The view is based on search, so the content of the view does not update immediately after changes are made.<br/><br/>Tip: To zoom in/out on the timeline, use ALT+Mouse Wheel or CTRL+Mouse Wheel. To navigate back and forth in time, you can use SHIFT+Mouse Wheel.',
    ResourceLabel: 'Resource',
    ResourceAbsenceLabel: 'Resource (absence)',
    DepartmentLabel: 'Department',
    RevertCustomOrderButtonText: 'Reset order',
    RevertCustomOrderButtonTooltip: 'Reset order to default order for columns specified in the Project Columns list.',
    RoleLabel: 'Role',
    RowLimitLabel: 'Number of elements',
    SaveButtonLabel: 'Save',
    SearchBoxGroupName: 'Search box',
    SearchBoxPlaceholderFallbackText: 'Search...',
    SearchBoxPlaceholderText: 'Search {0}...',
    SearchBoxPlaceholderTextDescription: 'Text that appears in the search box when it is empty. If no value is set, the text is based on the selected data source.',
    SearchBoxPlaceholderTextLabel: 'Search box text',
    SearchPropertyDescription: 'The name of the managed property for this column.',
    SearchPropertyFoundMessage: 'Found a managed property `{0}` that matches the internal field name `{1}`.',
    SearchPropertyLabel: 'Search property',
    SearchPropertyPlaceholder: 'Search managed properties...',
    SearchQueryLabel: 'Search query',
    SelectProgramText: 'Select a program',
    ShowAllMeasurementsLinkText: 'Show all measurements',
    ShowCommandBarLabel: 'Show commandline',
    ShowExcelExportButtonLabel: 'Show export to Excel button',
    ShowFieldFrontpageLabel: 'Project frontpage',
    ShowFieldPortfolioLabel: 'Portfolio overview',
    ShowFieldProjectStatusLabel: 'Project status',
    ShowFiltersLabel: 'Show filters',
    ShowGroupByLabel: 'Show grouping options',
    ShowHideColumnsLabel: 'Show/hide columns',
    ShowProgramViewsLabel: 'Show program views',
    ShowProjectLogoFieldLabel: 'Show logo',
    ShowRenderModeSelectorLabel: 'Show view selector',
    ShowSearchBoxLabel: 'Show search box',
    ShowViewSelectorLabel: 'Show view selector',
    SiteTitleLabel: 'Project',
    SortAscLabel: 'Z to A',
    SortByFieldLabel: 'Sorting property',
    SortCardsByLabel: 'Sort the tiles by: {0}',
    SortDescLabel: 'A to Z',
    SortOrderDescription: 'The sort order determines the order in which the views are displayed. The lowest value is displayed first.',
    SortOrderLabel: 'Sort order',
    StartDateLabel: 'Start date',
    StatusReportsCountLabel: 'Number of statusreports to display',
    TileViewGroupName: 'Tile view',
    TitleLabel: 'Title',
    ToggleColumnFormPanelLabel: 'Add column',
    UseChangesButtonText: 'Use',
    ViewNotFoundMessage: 'Cannot find the specified view.',
    ViewNotFoundMessage_WebPartProperty: 'Cannot find the specified view **{0}**. Please check the view name and try again.',
    ViewNotFoundMessage_Id: ' Cannot find a view with ID **{0}**.',
    Provision: {
      DrawerLevel0HeaderText: 'Provision area',
      DrawerLevel0DescriptionText: 'Here you can provision a new area. Select one of the area types below, and fill in the information below.',
      DrawerLevel1HeaderText: 'Classification',
      DrawerLevel1DescriptionText: 'Here you can select classification for the area. Activate teams, sensitivity label and retention label.',
      DrawerLevel2HeaderText: 'Other information',
      DrawerLevel2DescriptionText: 'Here you can specify other information for the area. Area image and overview of language, time zone and hub connection.',
      SiteTypeFieldLabel: 'Area type',
      SiteNameFieldLabel: 'Area name',
      SiteNameFieldDescription: 'Choose a unique name that follows the organization\'s naming standards.',
      SiteNamePrefixTooltipText: 'This is a prefix that is added in front of the area name.',
      SiteNameSuffixTooltipText: 'This is a suffix that is added at the end of the area name.',
      SiteNameValidationErrorMessage: 'The name specified is not available. Try changing the name.',
      SiteNameValidationSuccessMessage: 'The name is available',
      SiteDescriptionFieldLabel: 'Description',
      SiteDescriptionFieldDescription: 'Provide a description, this is useful for people to understand what your area is for.',
      BusinessJustificationFieldLabel: 'Business justification',
      BusinessJustificationFieldDescription: 'Describe why you need this area? What is the purpose?',
      AliasFieldLabel: 'Alias/name',
      UrlFieldLabel: 'Area address',
      OwnerFieldLabel: 'Owner(s)',
      OwnerFieldDescription: 'Owner(s) have full access to the area and can add and remove members. You can add more owners later.',
      MemberFieldLabel: 'Member(s)',
      MemberFieldDescription: 'Member(s) have access to the area based on the permissions that are set. You can add more members later.',
      RequestedByFieldLabel: 'Requested on behalf of',
      RequestedByFieldDescription: 'If you request the area on behalf of someone, you can enter the name of that person here. If you request the area for yourself, you can leave the field empty.',
      UserFieldNoOptionsText: 'No matches...',
      TeamifyFieldLabel: 'Activate Teams for the area?',
      TeamifyFieldDescription: 'If you activate Teams for the area, a Teams area will be created and linked to the area.',
      TeamTemplateFieldLabel: 'Teams template',
      TeamTemplateFieldDescription: 'Which teams template do you want to use for the area?',
      ConfidentialFieldLabel: 'Confidential/sensitive data',
      ConfidentialFieldDescription: 'Will confidential or sensitive data be stored in this room? If yes, you must ensure that you have set the correct permissions.',
      PrivacyFieldLabel: 'Access settings',
      PrivacyFieldDescription: 'Specify which access setting you want for the area.',
      PrivacyFieldOptionPrivate: 'Private - Users need permission to join',
      PrivacyFieldOptionPublic: 'Public - Everyone in the organization can join',
      ExternalSharingFieldLabel: 'Allow external guests',
      ExternalSharingFieldDescription: 'If this is enabled, you will be able to invite and share individual files, folders, libraries, etc. with external guest users. Note! Invitation of external guest users will only be possible after the group/area has been created.',
      GuestFieldLabel: 'Guest(s)',
      GuestFieldDescription: 'Guests have limited access to the area. You can add more guests later. Please enter a valid email address.',
      GuestFieldNoOptionsText: 'Cannot add...',
      SensitivityLabelFieldLabel: 'Sensitivity label',
      SensitivityLabelFieldDescription: 'Which sensitivity label do you want to apply for the area?',
      SensitivityLabelLibraryFieldLabel: 'Sensitivity label for library',
      SensitivityLabelLibraryFieldDescription: 'Which sensitivity label do you want to apply for the document library for the area?',
      RetentionLabelFieldLabel: 'Retention label',
      RetentionLabelFieldDescription: 'Which retention label do you want to apply for the area?',
      ExpirationDateFieldLabel: 'Expiration date',
      ExpirationDateFieldDescription: 'When does the area expire? Note! The area will not be deleted after this date.',
      ReadOnlyGroupFieldLabel: 'Activate read-only group',
      ReadOnlyGroupFieldDescription: 'Activate a read-only group for the area. This will give users in the group read-only access to the area.',
      InternalChannelFieldLabel: 'Activate internal channel',
      InternalChannelFieldDescription: 'When this option is enabled, an internal channel will be created in Teams.',
      LanguageFieldLabel: 'Language',
      TimeZoneFieldLabel: 'Time zone',
      HubSiteFieldLabel: 'Hub connection',
      ImageFieldLabel: 'Specify area image',
      ImageFieldDescription: 'Here you can upload an image to be used as an area image.',
      ImageDropZoneText: 'Drag and drop image here, or click to select image file (png, jpeg/jpg) Note! Cannot exceed 800 KB.',
      DrawerFooterDescriptionText: 'Your area will be linked to a Microsoft 365 group, which gives your website a shared OneNote notebook, group email address and shared calendar.',
      PreviousButtonLabel: 'Previous',
      NextButtonLabel: 'Next',
      ProvisionButtonLabel: 'Request area',
      ToastCreatedTitle: 'The area is requested',
      ToastCreatedBody: 'The area is now requested and sent for processing.',
      ToastCreatedErrorTitle: 'Error when requesting',
      ToastCreatedErrorBody: 'An error occurred when requesting the area. Please try again, or contact administrator.',
      StatusMenuLabel: 'My requests',
      SettingsMenuLabel: 'Settings',
      IdeaMenuLabel: 'Register idea',
      SettingsSearchLabel: 'Search in settings',
      SettingsDialogTitle: 'Settings for the Provisioning portal',
      SettingsDialogDescription: 'Here you have an overview of all settings for the Provisioning portal.',
      SettingsDialogSpinnerLabel: 'Updating and retrieving settings...',
      SettingsDialogNoSearchResultsLabel: 'No settings match the search.',
      SettingsDialogNoResultsLabel: 'There are no settings for the Provisioning portal.',
      SettingLabel: 'Setting',
      DescriptionLabel: 'Description',
      ValueLabel: 'Value',
      EditLabel: 'Edit',
      StatusSearchLabel: 'Search in requests',
      UpdateLabel: 'Update',
      StatusDialogTitle: 'My requests',
      StatusDialogDescription: 'Here you can see the status of your requests, which area type, status and date for the request. It is also possible to delete requests that have not been submitted or that have been rejected.',
      StatusDialogSpinnerLabel: 'Updating and retrieving requests...',
      StatusDialogNoSearchResultsLabel: 'No requests match the search.',
      StatusDialogNoResultsLabel: 'You have no requests, create a new request to see status here.',
      StatusLabel: 'Status',
      SubmittedLabel: 'Submitted',
      ApprovedLabel: 'Approved',
      RejectedLabel: 'Rejected',
      PendingApprovalLabel: 'Pending approval',
      SpaceCreationFailedLabel: 'Area creation failed',
      SpaceAlreadyExistsLabel: 'The area already exists',
      TeamRequestedLabel: 'Team requested',
      SpaceCreationLabel: 'The area is being created',
      SpaceCreatedLabel: 'The area has been created',
      NotSubmittedLabel: 'Not submitted',
      SubmittedDateLabel: 'Request date',
      DeleteLabel: 'Delete',
      DeleteSubmissionLabel: 'Delete request',
      DeleteSubmissionConfirmationLabel: 'Are you sure you want to delete the request?',
      DeletedSubmissionToastTitle: 'Deleted request',
      DeletedSubmissionToastBody: 'The request, {0}, is now deleted.',
      DeletedSubmissionErrorToastTitle: 'Error when deleting',
      DeletedSubmissionErrorToastBody: 'An error occurred when deleting the request. Please try again, or contact administrator.',
      RequestedSource: 'Project Portal - Request form',
      NotConfiguredTitle: 'Not configured',
      NotConfiguredText: 'There is no configured url to the Provisioning portal. Please specify this in the web part.',
      ExpirationDateNoneOption: 'No expiration date',
      ExpirationDateMonthOption: '{0} month(s)',
      NoProvisionAccessMessage: 'You do not have access to the Provisioning portal.',
      DefaultTeamTemplate: 'Standard',
      TypeConfigurationLabel: 'Type configuration',
      TypeConfigurationPanelHeader: 'Type configuration',
      TypeConfigurationManageBtnLabel: 'Configure types',
      TypeNameLabel: 'Type',
      HiddenFieldsForTypeLabel: 'Hidden fields for this type',
      HiddenFieldsForTypePlaceholder: 'Select fields to hide...',
      RequiredFieldsForTypeLabel: 'Required fields for this type',
      RequiredFieldsForTypePlaceholder: 'Select fields to make required...',
      FieldConfigurationJsonLabel: 'Field configuration (JSON)',
      FieldConfigurationJsonPlaceholder: 'Enter JSON configuration for fields...',
      PropertyEditorLabel: 'Edit web part properties (JSON)',
      PropertyEditorDescription: 'Here you can edit the web part properties in JSON format. Export and import of properties is also possible so that setup can be reused and imported into other web parts.',
      RequireProvisionAccessFieldLabel: 'Require access to provision portal',
      DebugModeLabel: 'Debug Mode',
      DebugModeOnText: 'On',
      DebugModeOffText: 'Off',
      ProvisionError: 'Could not retrieve data from list \'{0}\', please check that the web part is configured correctly and that the list exists on the provisioning portal. Error: {1}',
      StandardTeamTemplate: 'Default team template',
      FieldLogicGroupName: 'Field Logic',
      AdvancedGroupName: 'Advanced',
      DefaultExpirationDateFieldLabel: 'Default expiration Date',
      ReadOnlyGroupLogicFieldLabel: 'Require read-only group for internal channel',
      ProjectAreaType: 'Project Area',
      VivaEngageCommunityType: 'Viva Engage Community',
      MicrosoftTeamsTeamType: 'Microsoft Teams Team',
    },
    NotSpecifiedText: 'Not specified',
    Idea: {
      MenuLabel: "Submit idea",
      ModuleTitle: 'Idea Module',
      ModuleLoadingText: 'Loading idea module',
      OverviewTitle: 'Ideas overview',
      RegistrationSectionTitle: 'Registration',
      RegisteredIdeasTitle: 'Registered ideas',
      ProcessingSectionTitle: 'Processing',
      ProcessingIdeasTitle: 'Ideas in processing',
      NewButtonText: 'New idea',
      NewButtonDescription: 'Create a new idea',
      EditButtonText: 'Edit',
      EditButtonDescription: 'Edit the idea',
      ApproveButtonText: 'Approve',
      ApproveButtonDescription: 'Approve the idea',
      DeleteButtonText: 'Delete',
      DeleteButtonDescription: 'Delete the idea',
      NoRegisteredIdeasText: 'There are currently no registered ideas, registered ideas will appear here',
      NoProcessingIdeasText: 'There are currently no ideas being processed, ideas in processing will appear here',
      RegisteredIdeaTitle: 'Registered idea',
      NoViewFoundErrorMessage: 'No view was found. It may be that the view specified in the address field does not exist, try removing this. Alternatively, create a new view (Data source).',
      NoIdeaFoundErrorMessage: 'No idea was found. It may be that the idea specified in the address field does not exist, try removing this. Alternatively, create a new idea.',
      ProvisionAreaTitle: 'Provision area',
      ConfigurationListFieldLabel: 'Configuration list',
      ConfigurationListFieldDescription: 'Name of the Idea configuration list',
      ConfigurationNameFieldLabel: 'Configuration name',
      ConfigurationNameFieldDescription: 'Name of the configuration to use',
      HiddenRegistrationFieldsLabel: 'Hidden fields (registration)',
      HiddenRegistrationFieldsDescription: 'Fields to hide from the idea module (Idea registration)',
      HiddenProcessingFieldsLabel: 'Hidden fields (processing)',
      HiddenProcessingFieldsDescription: 'Fields to hide from the idea module (Idea processing)',
      ProvisionUrlFieldLabel: 'Provisioning area',
      ProvisionUrlFieldDescription: 'URL to the area that handles requests'
    },
    HideDataTypePropertiesLabel: 'Hide properties for display mode',
    ShowDataTypePropertiesLabel: 'Show properties for display mode',
    NoViewFoundTitle: 'No view found',
    AccessTitle: 'No access',
    ProjectNotFound: 'Project not specified...',
    PrimaryFieldLabel: 'Primary field',
    SecondaryFieldLabel: 'Secondary field',
    PrimaryUserFieldLabel: 'Primary user',
    SecondaryUserFieldLabel: 'Secondary user',
    RefreshRequiredDescription: 'Requires refresh after changes',
    LifecycleStatus_Completed: 'Completed',
    LifecycleStatus_Closed: 'Closed',
    ProjectLevel: 'Project level'
  }
})
