declare interface IPortfolioWebPartsStrings {
  Aria: {
    MenuOverflowCount: string
    MoveDisabled: string
    MoveUp: string
    MoveUpDisabled: string
    MoveDown: string
    MoveDownDisabled: string
    Back: string
    Close: string
  },
  Placeholder: {
    TextField: string
    SiteName: string
    SiteDescription: string
    Icon: string,
    ChoiceField: string,
    MultiChoiceField: string,
    GuestField: string,
    UserField: string,
    BusinessJustificationField: string
  },
  Provision: {
    DrawerLevel1HeaderText: string,
    DrawerLevel1DescriptionText: string,
    SiteTypeFieldLabel: string,
    SiteNameFieldLabel: string,
    SiteNameFieldDescription: string,
    SiteNamePrefixTooltipText: string,
    SiteNameSuffixTooltipText: string,
    SiteDescriptionFieldLabel: string,
    SiteDescriptionFieldDescription: string,
    BusinessJustificationFieldLabel: string,
    BusinessJustificationFieldDescription: string,
    OwnerFieldLabel: string,
    OwnerFieldDescription: string,
    OwnerFieldNoOptionsText: string,
    MemberFieldLabel: string,
    MemberFieldDescription: string,
    DrawerLevel2HeaderText: string,
    DrawerLevel2DescriptionText: string,
    ConfidentialFieldLabel: string,
    ConfidentialFieldDescription: string,
    PrivacyFieldLabel: string,
    PrivacyFieldDescription: string,
    PrivacyFieldOptionPrivate: string,
    PrivacyFieldOptionPublic: string,
    ExternalSharingFieldLabel: string,
    ExternalSharingFieldDescription: string,
    GuestFieldLabel: string,
    GuestFieldDescription: string,
    GuestFieldNoOptionsText: string,
    LanguageFieldLabel: string,
    TimeZoneFieldLabel: string,
    HubSiteFieldLabel: string,
    DrawerFooterDescriptionText: string,
    PreviousButtonLabel: string,
    NextButtonLabel: string,
    ProvisionButtonLabel: string
    ToastCreatedTitle: string
    ToastCreatedBody: string
    ToastCreatedErrorTitle: string
    ToastCreatedErrorBody: string
    StatusMenuLabel: string
    IdeaMenuLabel: string
  },
  AddColumnLabel: string
  AllProjectsHeaderText: string
  AllProjectsSearchBoxPlaceholderText: string
  BarLabel: string
  BooleanNo: string
  BooleanOff: string
  BooleanOn: string
  BooleanYes: string
  CancelButtonLabel: string
  ChartConfigurationListNameLabel: string
  ChartErrorText: string
  ColumnCategoryDescription: string
  ColumnCategoryLabel: string
  ColumnConfigListNameLabel: string
  ColumnPersistRenderGloballyFieldDescription: string
  ColumnPersistRenderGloballyFieldLabel: string
  ColumnRenderDataTypePropertiesHeaderText: string
  ColumnRenderDescription: string
  ColumnRenderLabel: string
  ColumnRenderOptionBoolean: string
  ColumnRenderOptionBooleanFalse: string
  ColumnRenderOptionBooleanTrue: string
  ColumnRenderOptionCurrency: string
  ColumnRenderOptionCurrencyFallbackValueLabel: string
  ColumnRenderOptionCurrencyMaximumFractionDigitsLabel: string
  ColumnRenderOptionCurrencyMinimumFractionDigitsLabel: string
  ColumnRenderOptionCurrencyPrefixLabel: string
  ColumnRenderOptionDate: string
  ColumnRenderOptionDateIncludeTimeLabel: string
  ColumnRenderOptionDialog: string
  ColumnRenderOptionDialogInfoTextTemplateDescription: string
  ColumnRenderOptionDialogInfoTextTemplateLabel: string
  ColumnRenderOptionDialogLinkTextLabel: string
  ColumnRenderOptionDialogShowInfoTextLabel: string
  ColumnRenderOptionFilename: string
  ColumnRenderOptionNote: string
  ColumnRenderOptionNumber: string
  ColumnRenderOptionPercentage: string
  ColumnRenderOptionProjectInfo: string
  ColumnRenderOptionTags: string
  ColumnRenderOptionTagsValueSeparatorDescription: string
  ColumnRenderOptionTagsValueSeparatorLabel: string
  ColumnRenderOptionText: string
  ColumnRenderOptionTrend: string
  ColumnRenderOptionTrendShowTrendIconLabel: string
  ColumnRenderOptionUrl: string
  ColumnRenderOptionUrlDescriptionDescription: string
  ColumnRenderOptionUrlDescriptionLabel: string
  ColumnRenderOptionUrlOpenInNewTabLabel: string
  ColumnRenderOptionUser: string
  ColumnSettingsDisabledTooltip: string
  ColumnSettingsLabel: string
  ColumnsListNameLabel: string
  ColumnVisibilityDescription: string
  ColumnVisibilityLabel: string
  CommandBarGroupName: string
  CompactViewText: string
  ConfigItemTitleFieldDescription: string
  ConfigItemTitleFieldLabel: string
  ConfigurationGroupName: string
  ConfirmDeleteProjectColumnSubText: string
  ConfirmDeleteProjectColumnTitle: string
  ConfirmDeleteProjectContentColumnSubText: string
  ConfirmDeleteProjectContentColumnTitle: string
  ConfirmDeleteResponseAbort: string
  ConfirmDeleteResponseConfirm: string
  CreatedTooltipText: string
  CustomSortsText: string
  DataSourceCategoryDescription: string
  DataSourceCategoryError: string
  DataSourceCategoryLabel: string
  DataSourceError: string
  DataSourceGroupName: string
  DataSourceItemNotFound: string
  DataSourceLabel: string
  DataSourceLevelDescription: string
  DataSourceLevelLabel: string
  DataSourceLevelPortfolio: string
  DataSourceLevelProject: string
  DataSourceListName: string
  DataSourceNotFound: string
  DefaultDataSourceViewLabel: string
  DefaultRenderModeDescription: string
  DefaultRenderModeLabel: string
  DefaultTimeframeEndLabel: string
  DefaultTimeframeEndValue: string
  DefaultTimeframeStartLabel: string
  DefaultTimeframeStartValue: string
  DefaultVerticalDescription: string
  DefaultVerticalLabel: string
  DefaultViewDescription: string
  DefaultViewLabel: string
  DefaultViewSetWarningMessage: string
  DeleteButtonLabel: string
  DisplayNameDescription: string
  DisplayNameLabel: string
  DisplayNamePortfolioOverviewDescription: string
  EditColumnHeaderText: string
  EditColumnLabel: string
  EditProjectListQuickLaunch: string
  EditViewColumnsPanelHeaderText: string
  EditViewColumnsPanelHelpText: string
  EditViewHeaderText: string
  EditViewText: string
  EmptyMessageDescription: string
  EndDateLabel: string
  ErrorBoundaryFallbackDescription: string
  ErrorBoundaryFallbackText: string
  ErrorFetchingProjectsTitle: string
  ErrorTitle: string
  ExcelExportButtonLabel: string
  FiltersString: string
  FilterText: string
  GeneralGroupName: string
  GroupByColumnLabel: string
  HideVerticalsLabel: string
  IconNameDescription: string
  IconNameLabel: string
  IncludeViewNameInExcelExportFilenameLabel: string
  InternalNameDescription: string
  InternalNameLabel: string
  IsGroupableDescription: string
  IsGroupableLabel: string
  IsRefinableDescription: string
  IsRefinableLabel: string
  IsResizableLabel: string
  ListLayoutModeJustifiedLabel: string
  ListViewGroupName: string
  ListViewText: string
  LoadingText: string
  MaxWidthDescription: string
  MaxWidthLabel: string
  MeasurementAchievementLabel: string
  MeasurementCommentLabel: string
  MeasurementDateLabel: string
  MeasurementValueLabel: string
  MinWidthDescription: string
  MinWidthLabel: string
  ModalColumnEmptyListMessage: string
  ModalColumnEmptyListTitle: string
  MoveLeftLabel: string
  MoveRightLabel: string
  MyProjectsHeaderText: string
  MyProjectsSearchBoxPlaceholderText: string
  NameLabel: string
  NewColumnHeaderText: string
  NewLabel: string
  NewViewHeaderText: string
  NewViewText: string
  NoAccessMessage: string
  NoDefaultViewMessage: string
  NoProjectData: string
  NoProjectsFoundMessage: string
  NoProjectsFoundTitle: string
  NotSet: string
  OpenInNewTabLabel: string
  ParentProjectsHeaderText: string
  ParentProjectsSearchBoxPlaceholderText: string
  PersonalViewDescription: string
  PersonalViewLabel: string
  PersonalViewsHeaderText: string
  PhaseLabel: string
  PortfolioAggregationNotConfiguredMessage: string
  PortfolioAggregationViewSearchQueryDescription: string
  PortfolioManagerGroupName: string
  PortfolioOverviewColumnRenderDescription: string
  PortfolioOverviewDataFetchError: string
  PortfolioOverviewDataFetchErrorView: string
  PortfolioOverviewShowEditViewColumnsPanelHelpText: string
  PortfolioViewSearchQueryDescription: string
  PortfolioViewsListName: string
  ProgramProjectsHeaderText: string
  ProgramSearchBoxPlaceholderText: string
  ProgramsHeaderText: string
  ProjectColumnsListName: string
  ProjectContentColumnItemNotFound: string
  ProjectContentColumnsListName: string
  ProjectDeliveriesGroupName: string
  ProjectInformationGroupName: string
  ProjectInformationPanelButton: string
  ProjectLabel: string
  ProjectListEmptyMessage: string
  ProjectListQuickLaunch: string
  ProjectManager: string
  ProjectMetadataFieldLabel: string
  ProjectOwner: string
  ProjectsAccessHeaderText: string
  ProjectsAccessSearchBoxPlaceholderText: string
  ProjectServiceArea: string
  ProjectsListName: string
  ProjectType: string
  RelativeUrl: string,
  RenderModeCompactListText: string
  RenderModeLabel: string
  RenderModeListText: string
  RenderModeTilesText: string
  ResourceAllocationGroupName: string
  ResourceAllocationInfoText: string
  ResourceLabel: string
  RevertCustomOrderButtonText: string
  RevertCustomOrderButtonTooltip: string
  RoleLabel: string
  RowLimitLabel: string
  SaveButtonLabel: string
  SearchBoxGroupName: string
  SearchBoxPlaceholderFallbackText: string
  SearchBoxPlaceholderText: string
  SearchBoxPlaceholderTextDescription: string
  SearchBoxPlaceholderTextLabel: string
  SearchPropertyDescription: string
  SearchPropertyFoundMessage: string
  SearchPropertyFoundTitle: string
  SearchPropertyLabel: string
  SearchPropertyPlaceholder: string
  SearchQueryLabel: string
  SelectProgramText: string
  ShowAllMeasurementsLinkText: string
  ShowCommandBarLabel: string
  ShowExcelExportButtonLabel: string
  ShowFieldFrontpageLabel: string
  ShowFieldPortfolioLabel: string
  ShowFieldProjectStatusLabel: string
  ShowFiltersLabel: string
  ShowGroupByLabel: string
  ShowHideColumnsLabel: string
  ShowProgramViewsLabel: string
  ShowProjectLogoFieldLabel: string
  ShowRenderModeSelectorDescription: string
  ShowRenderModeSelectorLabel: string
  ShowSearchBoxDescription: string
  ShowSearchBoxLabel: string
  ShowSortByDescription: string
  ShowSortByLabel: string
  ShowViewSelectorLabel: string
  SiteTitleLabel: string
  SortAscLabel: string
  SortByFieldDescription: string
  SortByFieldLabel: string
  SortCardsByLabel: string
  SortDescLabel: string
  SortOrderDescription: string
  SortOrderLabel: string
  StartDateLabel: string
  StatusReportsCountLabel: string
  TileViewGroupName: string
  TimelineConfigurationListName: string
  TimelineContentListName: string
  TitleLabel: string
  TitleDescription: string
  ToggleColumnFormPanelLabel: string
  ToggleEditViewColumnsLabel: string
  UseChangesButtonText: string
  UseDynamicColorsDescription: string
  UseDynamicColorsLabel: string
  ViewLessText: string
  ViewMoreText: string
  ViewNotFoundMessage: string
  ViewsListNameLabel: string
}

declare module 'PortfolioWebPartsStrings' {
  const strings: IPortfolioWebPartsStrings
  export = strings
}
