define([], function () {
  return {
    ResultsCountLabel: 'Viser {0} av {1} prosjekter',
    FilterPanelGroupProjectInformation: 'Prosjektinformasjon',
    ColumnRenderOptionStatusReport: 'Statusrapport',
    ColumnRenderOptionProjectInfo: 'Prosjektinformasjon',
    ColumnRenderOptionHub: 'Hub',
    ColumnRenderOptionCalculated: 'Beregnet kolonne',
    PortfolioSelectorLabel: 'Portefølje',
    MergedViewLabel: 'Vis alle hubber',
    IconNameFieldLabel: 'Ikonnavn',
    IconNameFieldPlaceholder: 'Skriv inn et ikonnavn fra UI Fabric (f.eks. "Page")',
    LanguageFieldLabel: 'Språk',
    IncludeInMergedViewFieldLabel: 'Inkluder i sammenslått visning',
    PortfolioSelectorDescription: 'Velg en portefølje for å vise prosjekter fra denne porteføljen.',
    ShowPortfolioSelectorOnText: 'Ja',
    ShowPortfolioSelectorOffText: 'Nei',
    ShowPortfolioSelectorLabel: 'Vis porteføljevelger',
    ShowPortfolioSelectorDescription: 'Porteføljevelgeren vil vises på kommandolinjen om det er flere enn én portefølje tilgjengelig.',
    ShowMergedViewInViewSelectorLabel: 'Vis sammenslått visning i visningsvelger',
    ShowMergedViewInViewSelectorDescription: 'Legg til et alternativ i visningsvelgeren for å vise sammenslått data fra alle konfigurerte hubber samtidig.',
    SelectedPortfolioLabel: 'Standardportefølje',
    SelectedPortfolioDescription: 'Velg en portefølje for å vise prosjekter fra denne porteføljen. Tilgjengelige porteføljer administreres over. Om ingen standardportefølje er valgt, vil den første porteføljen i listen bli brukt.',
    PortfoliosFieldLabel: 'Porteføljer',
    PortfoliosFieldDescription: 'Administrer porteføljer for å vise prosjekter fra disse porteføljene. Du kan også velge en standardportefølje som skal vises i webdelen, dette velger under. Dette brukes som regel om du bruker webdelen utenfor en Prosjektportalen-hub.',
    PortfoliosPanelHeader: 'Administrer porteføljer',
    PortfoliosManageBtnLabel: 'Administrer porteføljer',
    UrlFieldLabel: 'Nettstedsadresse',
    ProjectListNameFieldLabel: 'Liste for prosjekter',
    ProjectStatusListNameFieldLabel: 'Liste for prosjektstatus',
    ProjectContentColumnsListNameFieldLabel: 'Liste for prosjektinnholdskolonner',
    ViewsListNameFieldLabel: 'Liste for visninger',
    ColumnsListNameFieldLabel: 'Liste for kolonner',
    ColumnConfigListNameFieldLabel: 'Liste for kolonnekonfigurasjon',
    GetPortfolioConfigErrorTitle: 'Ingen konfigurasjon tilgjengelig',
    GetPortfolioConfigErrorText: 'Du er kanskje utenfor en Prosjektportalen-instans? Gå til **Avansert** under _webdelegenskaper_ for å konfigurere porteføljer. Du kan sette opp flere porteføljer og velge hvilken som skal vises som standard i webdelen.',
    AdvancedGroupName: 'Avansert',
    Aria: {
      MenuOverflowCount: '{0} flere elementer',
      MoveDisabled: 'Kan ikke flytte skjult kolonne',
      MoveUp: 'Flytt opp',
      MoveUpDisabled: 'Kan ikke flytte opp, øverste element',
      MoveDown: 'Flytt ned',
      MoveDownDisabled: 'Kan ikke flytte ned, nederste element'
    },
    Placeholder: {
      TextField: 'Angi verdi her',
      Icon: 'Angi et ikon',
      MultiChoiceField: 'Velg ett eller flere alternativer'
    },
    NotSpecifiedText: 'Ikke angitt',
    Idea: {
      MenuLabel: 'Registrer ide',
      ModuleTitle: 'Idémodul',
      ModuleLoadingText: 'Laster inn idémodulen',
      OverviewTitle: 'Oversikt over idéer',
      RegistrationSectionTitle: 'Registrering',
      RegisteredIdeasTitle: 'Registrerte idéer',
      ProcessingSectionTitle: 'Behandling',
      ProcessingIdeasTitle: 'Idéer i behandling',
      NewButtonText: 'Ny idé',
      NewButtonDescription: 'Opprett en ny idé',
      EditButtonText: 'Rediger',
      EditButtonDescription: 'Rediger idéen',
      ApproveButtonText: 'Godkjenn',
      ApproveButtonDescription: 'Godkjenn idéen',
      DeleteButtonText: 'Slett',
      DeleteButtonDescription: 'Slett idéen',
      NoRegisteredIdeasText: 'Det for øyeblikket ingen registrerte idéer, idéer som blir registrert vil dukke opp her',
      NoProcessingIdeasText: 'Det for øyeblikket ingen idéer i behandling, idéer i behandling vil dukke opp her',
      RegisteredIdeaTitle: 'Registrert idé',
      NoViewFoundErrorMessage: 'Det ble ikke funnet noen visning. Det kan være at visningen som er spesifisert i adressefeltet ikke eksiterer, prøv å fjerne dette. Eventuelt opprett en ny visning (Datakilde).',
      NoIdeaFoundErrorMessage: 'Det ble ikke funnet noen idé. Det kan være at idéen som er spesifisert i adressefeltet ikke eksiterer, prøv å fjerne dette. Eventuelt opprett en ny idé.',
      ProvisionAreaTitle: 'Bestill område',
      ConfigurationListFieldLabel: 'Konfigurasjonsliste',
      ConfigurationListFieldDescription: 'Navn på Idékonfigurasjonsliste',
      ConfigurationNameFieldLabel: 'Konfigurasjonsnavn',
      ConfigurationNameFieldDescription: 'Navn på konfigurasjonen som skal brukes',
      HiddenRegistrationFieldsLabel: 'Skjulte felter (registrering)',
      HiddenRegistrationFieldsDescription: 'Felt som skal skjules fra idémodulen (Idéregistrering)',
      HiddenProcessingFieldsLabel: 'Skjulte felter (behandling)',
      HiddenProcessingFieldsDescription: 'Felt som skal skjules fra idémodulen (Idébehandling)',
    },
    NoViewFoundTitle: 'Ingen visning funnet',
    AddColumnLabel: 'Legg til en kolonne',
    AllProjectsHeaderText: 'Alle prosjekter/program',
    AllProjectsSearchBoxPlaceholderText: 'Søk i alle {0} prosjekter...',
    BooleanOff: 'Av',
    BooleanOn: 'På',
    BooleanNo: 'Nei',
    BooleanYes: 'Ja',
    CancelButtonLabel: 'Avbryt',
    ColumnCategoryDescription: 'Angi en kategori for kolonnen. Kolonnen vil dukke opp i alle visninger som bruker denne kategorien. Om du ønsker å endre kategorien for alle webdeler og visninger, kan du endre kategorien i listen Prosjektkolonner.',
    ColumnCategoryLabel: 'Kategori for kolonnen',
    ColumnRenderDataTypePropertiesHeaderText: 'Egenskaper for visningsmodus',
    ColumnRenderDescription: 'Velg hvordan kolonnen skal vises. Om det er tekstfelt som skal vises over flere linjer, velg Notat.',
    ColumnRenderLabel: 'Visningsmodus',
    ColumnSettingsDisabledTooltip: 'Kolonneinnstillinger er kun tilgjengelig når siden er i redigeringsmodus.',
    ColumnSettingsLabel: 'Kolonneinnstillinger',
    ColumnVisibilityDescription: 'Angi hvor kolonnen skal vises. Prosjektforside, prosjektstatus-siden, porterføljeoversikten eller alle steder.',
    ColumnVisibilityLabel: 'Synlighet for kolonne',
    CommandBarGroupName: 'Kommandolinje',
    CommentLabel: 'Kommentar',
    CompactViewText: 'Kompakt liste',
    ConfigItemTitleFieldDescription: 'Dersom det er spesifisert et element med tittelen angitt her i tidslinjekonfigurasjon listen så vil dette vises på tidslinjen.',
    ConfigItemTitleFieldLabel: 'Element tittel (konfigurasjon)',
    ConfigurationGroupName: 'Konfigurasjon',
    ConfirmDeleteProjectColumnSubText: 'Denne kolonnen fjernes fra Prosjektkolonner-listen og dermed fra alle visninger som bruker den. Er du sikker på at du vil slette denne kolonnen? Om du kun ønsker å fjerne kolonnen fra denne visningen, kan du bruke \'Vis eller skjul kolonner\'.',
    ConfirmDeleteProjectColumnTitle: 'Vil du slette?',
    ConfirmDeleteProjectContentColumnSubText: 'Denne kolonnen fjernes fra Prosjektinnholdskolonner-listen og dermed fra alle visninger som bruker den. Er du sikker på at du vil slette denne kolonnen? Om du kun ønsker å fjerne kolonnen fra denne visningen, kan du bruke \'Vis eller skjul kolonner\'.',
    ConfirmDeleteProjectContentColumnTitle: 'Vil du slette?',
    ConfirmDeleteResponseAbort: 'Avbryt',
    ConfirmDeleteResponseConfirm: 'Slett',
    CreatedTooltipText: 'Opprettet {0}',
    CustomSortsText: 'Egendefinert sortering',
    DataSourceCategoryDescription: 'Angi en datakildekategori for å kunne velge mellom flere datakilder i webdelen.',
    DataSourceCategoryError: 'Det skjedde en feil under uthenting av datakilder med kategori **{0}**.',
    DataSourceCategoryLabel: 'Kategori for datakilder',
    DataSourceError: 'Det skjedde en feil under uthenting av data fra datakilde med navn **{0}**. Oppdater siden og prøv igjen.',
    DataSourceGroupName: 'Datakilder',
    DataSourceItemNotFound: 'Datakilde ble ikke funnet',
    DataSourceLabel: 'Datakilde',
    DataSourceLevelDescription: 'Angi nivået for datakilden. Dette brukes for å filtrere datakilder i webdelen basert på hvor man henter data fra. Dette kan endres i ettertid i \'Datakilder\'-listen om du ønsker å gjøre spørringen/visningen tilgjengelig andre steder.',
    DataSourceLevelLabel: 'Nivå for datakilde',
    DataSourceNotFound: 'Finner ingen datakilde med navn **{0}**.',
    DefaultDataSourceViewLabel: 'Standardvisning (datakilde)',
    DefaultRenderModeDescription: 'Her kan du velge hvilken visning som skal være standard.',
    DefaultRenderModeLabel: 'Standard visningsmodus',
    DefaultTimeframeEndLabel: 'Standard sluttdato',
    DefaultTimeframeEndValue: '{0} måneder frem i tid',
    DefaultTimeframeStartLabel: 'Standard startdato',
    DefaultTimeframeStartValue: '{0} måneder tilbake i tid',
    DefaultVerticalDescription: 'Her kan du velge hvilken vertikal som skal være standard. Merk! dersom vertikalen "Alle prosjekter" er valgt som standard og brukere ikke har tilgang til "Alle prosjekter" vertikalen, vil standard bli "Mine prosjekter".',
    DefaultVerticalLabel: 'Standardvertikal',
    VerticalConfigLabel: 'Vertikalkonfigurasjon',
    VerticalConfigPanelHeader: 'Administrer vertikaler',
    VerticalConfigManageBtnLabel: 'Administrer vertikaler',
    VerticalConfigKeyTitle: 'Nøkkel',
    VerticalConfigTitleTitle: 'Tittel',
    VerticalConfigIconTitle: 'Ikon',
    VerticalConfigSortOrderTitle: 'Sorteringsrekkefølge',
    VerticalConfigClientFilterTitle: 'Klientfilter (JSON)',
    VerticalConfigFieldFilterTitle: 'Feltfilter (JSON)',
    VerticalConfigVisibilityRuleTitle: 'Synlighetsregel (JSON)',
    VerticalConfigRequiresAccessTitle: 'Krever tilgang',
    VerticalConfigIsDefaultTitle: 'Er standard',
    VerticalConfigSearchBoxPlaceholderTitle: 'Søkeboksplassholder',
    DefaultViewDescription: 'Velg om dette er standardvisningen for Porteføljeoversikten.',
    DefaultViewLabel: 'Standardvisning',
    DefaultViewSetWarningMessage: 'Det er allerede en visning som er satt som standard. Du må først endre denne visningen før du kan sette en ny som standard. Personlige visninger kan ikke settes som standard.',
    DeleteButtonLabel: 'Slett',
    DisplayNameDescription: 'Visningsnavn for denne kolonnen, kun for denne webdelen. Om du ønsker å endre visningsnavnet for alle webdeler, må du endre det i listen Prosjektinnholdskolonner.',
    DisplayNameLabel: 'Visningsnavn',
    DisplayNamePortfolioOverviewDescription: 'Visningsnavn for denne kolonnen.',
    EditColumnHeaderText: 'Rediger kolonne',
    EditColumnLabel: 'Rediger',
    EditProjectListQuickLaunch: 'Rediger hurtigmeny valg',
    EditViewColumnsPanelHeaderText: 'Rediger visningskolonner',
    EditViewColumnsPanelHelpText: 'Velg kolonnene som skal vises for nåværende visning. Hvis du vil endre rekkefølgen, kan du dra og slippe eller bruke opp- og ned-pilen ved siden av hver kolonne.',
    EditViewHeaderText: 'Rediger visning',
    EditViewText: 'Rediger gjeldende visning',
    EmptyMessageDescription: 'Fant ingen nye prosjekter.',
    EndDateLabel: 'Sluttdato',
    ErrorBoundaryFallbackDescription: 'Feildetaljer:',
    ErrorBoundaryFallbackText: 'Det oppstod en feil under lasting av {0}.',
    ErrorFetchingProjectsTitle: 'Det skjedde en feil under uthenting av prosjekter.',
    ErrorTitle: 'Det har oppstått en feil',
    ExcelExportButtonLabel: 'Eksporter til Excel',
    FiltersString: 'Filtre',
    FilterText: 'Filtrer',
    GeneralGroupName: 'Generelt',
    GroupByColumnLabel: 'Grupper etter {0}',
    HideVerticalsLabel: 'Skjul vertikaler',
    HideVerticalsDescription: 'Skjul vertikaler fra vertikal-velgeren.',
    IconNameDescription: 'Navn på ikon fra UI Fabric. Se https://uifabricicons.azurewebsites.net/.',
    IconNameLabel: 'Ikonnavn',
    IncludeViewNameInExcelExportFilenameLabel: 'Inkluder visningsnavn i Excel-filnavn',
    InternalNameDescription: 'Internt feltnavn for denne kolonnen.',
    InternalNameLabel: 'Internt feltnavn',
    IsGroupableDescription: 'Brukere kan gruppere på denne kolonnen.',
    IsGroupableLabel: 'Grupperbar',
    IsRefinableDescription: 'Brukere kan filtrere på denne kolonnen.',
    IsRefinableLabel: 'Presiser',
    IsResizableLabel: 'Justerbar',
    ListLayoutModeJustifiedLabel: 'Juster kolonner etter skjermbredde',
    ListViewGroupName: 'Listevisning',
    ListViewText: 'Liste',
    LoadingText: 'Laster {0}...',
    MaxWidthDescription: 'Maksimum bredde for kolonnen. Kan ikke være mindre enn minimum bredde.',
    MaxWidthLabel: 'Maks bredde',
    MinWidthDescription: 'Minimum bredde for kolonnen. Kan ikke overstige maksimum bredde.',
    MinWidthLabel: 'Minimum bredde',
    MoveLeftLabel: 'Flytt til venstre',
    MoveRightLabel: 'Flytt til høyre',
    MyProjectsHeaderText: 'Mine prosjekter',
    MyProjectsSearchBoxPlaceholderText: 'Søk i {0} prosjekter du er medlem av...',
    NameLabel: 'Navn',
    NewColumnHeaderText: 'Ny kolonne',
    NewLabel: 'Ny',
    NewViewHeaderText: 'Opprett visning',
    NewViewText: 'Opprett ny visning',
    NoAccessMessage: 'Du har ikke tilgang til dette prosjektet',
    NoDefaultViewMessage: 'Det er ikke satt noen standardvisning.',
    NoProjectsFoundMessage: 'Det er ingen prosjekter som har blitt opprettet enda eller har dukket opp i søket.',
    NoProjectsFoundTitle: 'Ingen prosjekter funnet.',
    NotSet: 'Ikke satt',
    OpenInNewTabLabel: 'Åpne prosjektområder i ny fane',
    ParentProjectsHeaderText: 'Overordnede prosjekter',
    ParentProjectsSearchBoxPlaceholderText: 'Søk i {0} overordnede prosjekter...',
    PersonalViewDescription: 'Velg om dette er en personlig visning. Personlige visninger kan kun redigeres av deg.',
    PersonalViewLabel: 'Personlig visning',
    PersonalViewsHeaderText: 'Personlige visninger',
    PhaseLabel: 'Fase',
    PortfolioAggregationNotConfiguredMessage: 'Webdelen må konfigureres med en datakilde. Rediger webdelen, og legg inn navnet på datakilden du vil bruke.',
    PortfolioAggregationViewSearchQueryDescription: 'Søkespørringen for å hente data. DepartmentId refererer til Prosjektportalen-huben og bør ikke endres. ContentTypeId refererer til innholdstypen til dataelementet du vil hente. Gå til Datakilder-listen for å se eksempler.',
    PortfolioOverviewColumnRenderDescription: 'Velg hvordan kolonnen skal vises. Om det er tekstfelt som skal vises over flere linjer, velg Notat.',
    PortfolioOverviewDataFetchError: 'Det skjedde en feil under henting av data for porteføljeoversikten. Vennligst prøv igjen senere.<br/><br/> **Detaljert feilmelding:**<br/> `{0}`',
    PortfolioOverviewDataFetchErrorView: 'Det skjedde en feil under henting av data for porteføljeoversikten for visning **{0}**. Vennligst prøv igjen senere, eller prøv en annen visning.<br/><br/> **Detaljert feilmelding:**<br/> `{1}`',
    PortfolioOverviewShowEditViewColumnsPanelHelpText: 'Velg kolonnene som skal vises for nåværende visning. Hvis du vil endre rekkefølgen, kan du dra og slippe eller bruke opp- og ned-pilen ved siden av hver kolonne. Bruk \'Tilbakestill rekkefølge\'-knappen for å tilbakestille rekkefølgen til standard rekkefølge spesifisert i Prosjektkolonner-listen.',
    PortfolioViewSearchQueryDescription: 'Søkespørringen for å hente prosjekter i porteføljen. DepartmentId refererer til Prosjektportalen-huben og bør ikke endres.',
    ProgramProjectsHeaderText: 'Program',
    ProgramSearchBoxPlaceholderText: 'Søk i {0} program...',
    ProgramsHeaderText: 'Programmer',
    ProjectContentColumnItemNotFound: 'Prosjektinnholdskolonne ble ikke funnet',
    ProjectDeliveriesGroupName: 'Prosjektleveranser (beta)',
    ProjectInformationGroupName: 'Instillinger for Prosjektinformasjonspanel',
    ProjectInformationPanelButton: 'Åpne prosjektinformasjonspanel',
    ProjectListEmptyMessage: 'Søket etter prosjekter ga ingen resultater',
    ProjectListQuickLaunch: 'Hurtigmeny for prosjekt',
    ProjectMetadataFieldLabel: 'Prosjektmetadata',
    ProjectCard: {
      WebPartDescription: 'Prosjektkort',
      ProjectSiteIdFieldLabel: 'Område ID',
      ProjectSiteIdFieldDescription: 'ID for SharePoint-området (Prosjektet)'
    },
    ProjectsAccessHeaderText: 'Tilgang til',
    ProjectsAccessSearchBoxPlaceholderText: 'Søk i {0} prosjekter du har tilgang til...',
    ProjectServiceArea: 'Tjenesteområder',
    ProjectType: 'Prosjekttype',
    RelativeUrl: 'Relativ url',
    RenderModeCompactListText: 'Kompakt liste',
    RenderModeLabel: 'Visningsmodus',
    RenderModeListText: 'Liste',
    RenderModeTilesText: 'Fliser',
    ResourceAllocationGroupName: 'Ressursallokering',
    ResourceAllocationInfoText: 'Ressursallokering eller fravær som gjelder på tvers av prosjekter legges inn i den <a href="../{0}">sentrale ressursallokeringslisten</a>. Disse oppføringene vil vises med blå og rød (fravær) farge i tabellen under. Prosjektallokeringer vises med grønn farge. Fargestyrken til allokeringen baserer seg på allokeringsprosenten.<br/><br/>Merk: Visningen baserer seg på søk, så innholdet i visningen oppdaterer seg ikke umiddelbart etter at endringer er utført.<br/><br/>Tips: For å zoome inn/ut i tidslinje, bruk ALT+Musehjul eller CTRL+Musehjul. For å navigere frem og tilbake i tid kan du bruke SHIFT+Musehjul.',
    ResourceLabel: 'Ressurs',
    ResourceAbsenceLabel: 'Ressurs (fravær)',
    DepartmentLabel: 'Avdeling',
    RevertCustomOrderButtonText: 'Tilbakestill rekkefølge',
    RevertCustomOrderButtonTooltip: 'Tilbakestill rekkefølge til standard rekkefølge for kolonner spesifisert i Prosjektkolonner-listen.',
    RoleLabel: 'Rolle',
    RowLimitLabel: 'Antall prosjekter å vise',
    SaveButtonLabel: 'Lagre',
    SearchBoxGroupName: 'Søkeboks',
    SearchBoxPlaceholderFallbackText: 'Søk...',
    SearchBoxPlaceholderText: 'Søk i {0}...',
    SearchBoxPlaceholderTextDescription: 'Tekst som vises i søkeboksen når den er tom. Om det ikke settes en verdi baseres teksten på valgt datakilde.',
    SearchBoxPlaceholderTextLabel: 'Søkebokstekst',
    SearchPropertyDescription: 'Navnet på den forvaltede egenskapen for denne kolonnen.',
    SearchPropertyFoundMessage: 'Fant en forvaltet egenskap `{0}` som matcher det interne feltnavnet `{1}`.',
    SearchPropertyFoundTitle: 'Forvaltet egenskap funnet',
    SearchPropertyLabel: 'Søkeegenskap',
    SearchPropertyPlaceholder: 'Søk i forvaltede egenskaper...',
    SearchQueryLabel: 'Søkespørring',
    SelectProgramText: 'Velg et programområde',
    ShowCommandBarLabel: 'Vis kommandolinje',
    ShowExcelExportButtonLabel: 'Vis eksport til Excel-knapp',
    ShowFieldFrontpageLabel: 'Prosjektforside',
    ShowFieldPortfolioLabel: 'Porteføljeoversikt',
    ShowFieldProjectStatusLabel: 'Prosjektstatus',
    ShowFiltersLabel: 'Vis filtre',
    ShowHideColumnsLabel: 'Vis eller skjul kolonner',
    ShowProgramViewsLabel: 'Vis programvisninger',
    ShowProjectLogoFieldLabel: 'Vis logo',
    ShowRenderModeSelectorDescription: 'Her kan du velge om visningsvelgeren skal vises eller ikke.',
    ShowRenderModeSelectorLabel: 'Vis visningsvelger',
    ShowSearchBoxDescription: 'Her kan du velge om søkeboksen skal vises eller ikke.',
    ShowSearchBoxLabel: 'Vis søkeboks',
    ShowClosedProjectsLabel: 'Vis avsluttede prosjekter',
    ShowClosedProjectsDescription: 'Tar med prosjekter med livssyklusstatus Avsluttet. Disse er utelatt som standard. Når innstillingen er på, avgjør filtrene på hver vertikal om de vises \u2014 legg til {"GtProjectLifecycleStatus": {"$ne": "Avsluttet"}} i feltfilteret på fanene som fortsatt skal holdes fri for dem.',
    ShowSortByDescription: 'Her kan du velge om sorteringsknappen skal vises eller ikke.',
    ShowSortByLabel: 'Vis sorteringsknapp',
    ShowViewSelectorLabel: 'Vis visningsvelger',
    SiteTitleLabel: 'Prosjekt',
    SortAscLabel: 'Å til A',
    SortByFieldDescription: 'Internt feltnavn som brukes til sortering av prosjektene',
    SortByFieldLabel: 'Sorteringsegenskap',
    SortCardsByLabel: 'Sorter flisene etter: {0}',
    SortDescLabel: 'A til Å',
    SortOrderDescription: 'Sorteringsrekkefølgen bestemmer hvilken rekkefølge visningene vises i. Lavest verdi vises først.',
    SortOrderLabel: 'Sorteringsrekkefølge',
    StartDateLabel: 'Startdato',
    StatusReportsCountLabel: 'Antall rapporter å vise',
    TileViewGroupName: 'Flisevisning',
    TitleLabel: 'Tittel',
    TitleDescription: 'Tittel for visningen.',
    ToggleColumnFormPanelLabel: 'Legg til kolonne',
    UseChangesButtonText: 'Bruk',
    UseDynamicColorsDescription: 'Her kan du velge om kortvisningen skal ta i bruk dynamiske farger for logodelen, dette kan medføre lengre innlastningstid og anbefales for mindre porteføljer (krever at "Vis logo" er på).',
    UseDynamicColorsLabel: 'Bruk dynamiske farger',
    ViewLessText: 'Vis færre',
    ViewMoreText: 'Vis flere',
    ViewNotFoundMessage: 'Finner ikke angitt visning.',
    ViewNotFoundMessage_WebPartProperty: 'Finner ikke angitt visning **{0}**. Vennligst sjekk visningsnavnet i webdelegenskapene og prøv igjen.',
    ViewNotFoundMessage_Id: 'Finner ingen visning med ID **{0}**.',
    ProjectNotFound: 'Prosjekt ikke angitt...',
    PrimaryFieldLabel: 'Primært felt',
    SecondaryFieldLabel: 'Sekundært felt',
    PrimaryUserFieldLabel: 'Primær bruker',
    SecondaryUserFieldLabel: 'Sekundær bruker',
    RefreshRequiredDescription: 'Krever refresh etter endringer',
    LifecycleStatus_Completed: 'Avsluttet',
    LifecycleStatus_Closed: 'Stengt',
    ProjectLevel: 'Prosjektnivå',
    ColumnRenderOptionText: 'Tekst',
    NoProjectData: 'Kan ikke hente alle data fra prosjektområdet. Det kan være at du ikke har tilgang til selve området. Det kan også være at området nylig er opprettet eller at prosjektegenskaper ikke er utfylt.',
    MeasurementSheetTitleKey: 'Måling'
  }
})
