define([], function () {
  return {
    ColumnPersistRenderGloballyFieldDescription: 'Om du ønsker å endre visningsmodus for kolonnene som for alle webdeler og visninger, huk av sjekkboksen over.',
    ColumnRenderOptionTrendShowTrendIconLabel: 'Vis ikon',
    ColumnRenderOptionModalLinkTextLabel: 'Tekst for lenke',
    ColumnRenderOptionTagsValueSeparatorLabel: 'Separator for verdier',
    ColumnRenderOptionTagsValueSeparatorDescription: 'Angi et tegn som skal brukes for å skille verdier i etikettfeltet. Standard er semikolon.',
    ColumnRenderOptionDateIncludeTimeLabel: 'Inkluder tidspunkt',
    ColumnRenderOptionUrlDescriptionDescription: 'Beskrivelse av lenken. Om du ikke angir en verdi, brukes eventuelt beskrivelse fra lenken.',
    ColumnRenderOptionUrlDescriptionLabel: 'Beskrivelse',
    ColumnRenderOptionUrlOpenInNewTabLabel: 'Åpne i ny fane',
    ColumnRenderOptionUrl: 'URL',
    ColumnRenderOptionCurrencyMinimumFractionDigitsLabel: 'Minimum antall desimaler',
    ColumnRenderOptionCurrencyMaximumFractionDigitsLabel: 'Maksimalt antall desimaler',
    ColumnRenderOptionCurrencyFallbackValueLabel: 'Standardverdi',
    ColumnRenderOptionCurrencyPrefixLabel: 'Valutaprefiks',
    ColumnRenderOptionCurrency: 'Valuta',
    ColumnRenderOptionBooleanTrue: 'Verdi for \'Ja\'',
    ColumnRenderOptionBooleanFalse: 'Verdi for \'Nei\'',
    ColumnRenderDataTypePropertiesHeaderText: 'Egenskaper for visningstype',
    CustomSortsText: 'Egendefinert sortering',
    SearchPropertyFoundMessage: 'Fant en forvaltet egenskap `{0}` som matcher det interne feltnavnet `{1}`.',
    SearchPropertyPlaceholder: 'Søk i forvaltede egenskaper...',
    IncludeViewNameInExcelExportFilenameLabel: 'Inkluder visningsnavn i Excel-filnavn',
    DefaultViewSetWarningMessage: 'Det er allerede en visning som er satt som standard. Du må først endre denne visningen før du kan sette en ny som standard. Personlige visninger kan ikke settes som standard.',
    SearchQueryLabel: 'Søkespørring',
    SearchQueryDescription: 'Søkespørringen for å hente data. DepartmentId refererer til Prosjektportalen-huben og bør ikke endres. ContentTypeId refererer til innholdstypen til dataelementet du vil hente. Gå til Datakilder-listen for å se eksempler.',
    PortfolioViewSearchQueryDescription: 'Søkespørringen for å hente prosjekter i porteføljen. DepartmentId refererer til Prosjektportalen-huben og bør ikke endres.',
    IconNameLabel: 'Ikonnavn',
    IconNameDescription: 'Navn på ikon fra UI Fabric. Se https://uifabricicons.azurewebsites.net/.',
    DefaultViewDescription: 'Velg om dette er standardvisningen for Porteføljeoversikten.',
    PersonalViewDescription: 'Velg om dette er en personlig visning. Personlige visninger kan kun redigeres av deg.',
    PersonalViewLabel: 'Personlig visning',
    PortfolioOverviewShowEditViewColumnsPanelHelpText: 'Velg kolonnene som skal vises for nåværende visning. Hvis du vil endre rekkefølgen, kan du dra og slippe eller bruke opp- og ned-pilen ved siden av hver kolonne. Bruk \'Tilbakestill rekkefølge\'-knappen for å tilbakestille rekkefølgen til standard rekkefølge spesifisert i Prosjektkolonner-listen.',
    RevertCustomOrderButtonTooltip: 'Tilbakestill rekkefølge til standard rekkefølge for kolonner spesifisert i Prosjektkolonner-listen.',
    RevertCustomOrderButtonText: 'Tilbakestill rekkefølge',
    ConfirmDeleteProjectColumnTitle: 'Vil du slette?',
    ConfirmDeleteProjectColumnSubText: 'Denne kolonnen fjernes fra Prosjektkolonner-listen og dermed fra alle visninger som bruker den. Er du sikker på at du vil slette denne kolonnen? Om du kun ønsker å fjerne kolonnen fra denne visningen, kan du bruke \'Vis eller skjul kolonner\'.',
    ConfirmDeleteProjectContentColumnTitle: 'Vil du slette?',
    ConfirmDeleteProjectContentColumnSubText: 'Denne kolonnen fjernes fra Prosjektinnholdskolonner-listen og dermed fra alle visninger som bruker den. Er du sikker på at du vil slette denne kolonnen? Om du kun ønsker å fjerne kolonnen fra denne visningen, kan du bruke \'Vis eller skjul kolonner\'.',
    ConfirmDeleteResponseConfirm: 'Slett',
    ConfirmDeleteResponseAbort: 'Avbryt',
    AddToCurrentViewLabel: 'Legg til kolonnen i gjeldende visning',
    PortfolioViewsListName: 'Porteføljevisninger',
    ShowFieldProjectStatusLabel: 'Prosjektstatus',
    ShowFieldFrontpageLabel: 'Prosjektforside',
    ShowFieldPortfolioLabel: 'Porteføljeoversikt',
    EditViewColumnsPanelHeaderText: 'Rediger visningskolonner',
    SearchBoxPlaceholderTextDescription: 'Tekst som vises i søkeboksen når den er tom. Om det ikke settes en verdi baseres teksten på valgt datakilde.',
    DataSourceLevelLabel: 'Nivå for datakilde',
    ShowProgramViewsLabel: 'Vis programvisninger',
    ProgramsHeaderText: 'Programmer',
    SelectProgramText: 'Velg et programområde',
    HideViewsLabel: 'Skjul visninger',
    PortfolioAggregationNotConfiguredMessage: 'Webdelen må konfigureres med en datakilde. Rediger webdelen, og legg inn navnet på datakilden du vil bruke.',
    DataSourceCategoryDescription: 'Angi en datakildekategori for å kunne velge mellom flere datakilder i webdelen.',
    DataSourceDescription: 'Navnet på datakilden du vil bruke. Datakildene finner du i listen Datakilder på Portføljeområdet.',
    DataSourceGroupName: 'Datakilder',
    CommandBarGroupName: 'Søkeboks',
    SearchBoxGroupName: 'Søkeboks',
    DeleteButtonLabel: 'Slett',
    RemoveButtonLabel: 'Fjern',
    ColumnRenderOptionTags: 'Etiketter',
    ColumnRenderOptionList: 'Liste',
    ColumnRenderOptionNumber: 'Tall',
    ColumnRenderOptionText: 'Tekst',
    ColumnRenderOptionNote: 'Notat',
    ColumnRenderOptionDate: 'Dato',
    ColumnRenderOptionDateTime: 'Dato og tidspunkt',
    ColumnRenderOptionUser: 'Person',
    ColumnRenderOptionPercentage: 'Prosent',
    ColumnRenderOptionTrend: 'Trend',
    ColumnRenderOptionTaxonomy: 'Taksonomi',
    ColumnRenderOptionModal: 'Modal',
    ColumnRenderOptionFilename: 'Filnavn',
    ColumnPersistRenderGloballyFieldLabel: 'Oppdater globalt',
    ColumnRenderOptionBoolean: 'Ja/nei',
    ColumnRenderLabel: 'Vis som',
    ColumnRenderDescription: 'Velg hvordan kolonnen skal vises. Om det er tekstfelt som skal vises over flere linjer, velg Notat.',
    PortfolioOverviewColumnRenderDescription: 'Velg hvordan kolonnen skal vises. Om det er tekstfelt som skal vises over flere linjer, velg Notat.',
    EditColumnLabel: 'Rediger',
    MoveRightLabel: 'Flytt til høyre',
    MoveLeftLabel: 'Flytt til venstre',
    IsGroupableLabel: 'Grupperbar',
    IsGroupableDescription: 'Brukere kan gruppere på denne kolonnen.',
    IsRefinableLabel: 'Presiser',
    IsRefinableDescription: 'Brukere kan filtrere på denne kolonnen.',
    ColumnVisibilityLabel: 'Synlighet for kolonne',
    ColumnVisibilityDescription: 'Angi hvor kolonnen skal vises. Prosjektforside, prosjektstatus-siden, porterføljeoversikten eller alle steder.',
    NewColumnHeaderText: 'Ny kolonne',
    EditColumnHeaderText: 'Rediger kolonne',
    ToggleColumnFormPanelLabel: 'Legg til kolonne',
    AddColumnLabel: 'Legg til en kolonne',
    SearchPropertyLabel: 'Søkeegenskap',
    SearchPropertyDescription: 'Navnet på den forvaltede egenskapen for denne kolonnen.',
    InternalNameLabel: 'Internt feltnavn',
    InternalNameDescription: 'Internt feltnavn for denne kolonnen.',
    DisplayNameLabel: 'Visningsnavn',
    DisplayNameDescription: 'Visningsnavn for denne kolonnen, kun for denne webdelen. Om du ønsker å endre visningsnavnet for alle webdeler, må du endre det i listen Prosjektinnholdskolonner.',
    MinWidthLabel: 'Minimum bredde',
    MaxWidthLabel: 'Maks bredde',
    IsMultilineLabel: 'Flere linjer',
    IsResizableLabel: 'Justerbar',
    SaveButtonLabel: 'Lagre',
    CloseButtonLabel: 'Avbryt',
    GroupByLabel: 'Grupper etter',
    GroupByColumnLabel: 'Grupper etter {0}',
    FilterBy: 'Filtrer etter',
    DataSourceCategoryLabel: 'Kategori for datakilder',
    DataSourceLabel: 'Datakilde',
    SortDescLabel: 'A til Å',
    SortAscLabel: 'Å til A',
    ColumSettingsLabel: 'Kolonneinnstillinger',
    ActorsLabel: 'Aktører',
    AdvancedGroupName: 'Avansert',
    BenefitResponsibleLabel: 'Gevinstansvarlig',
    BenefitOwnerLabel: 'Gevinsteier',
    BenefitTitleLabel: 'Gevinst',
    ChartConfigurationListNameLabel: 'Grafkonfigurasjon',
    ChartErrorText: 'Grafen er ugyldig konfigurert.',
    ColumnConfigListNameLabel: 'Kolonnekonfigurasjon',
    LoadingTextLabel: 'Laste-tekst',
    EmptyMessageLabel: 'Tekst ved ingen elementer',
    RowLimitLabel: 'Antal elementer',
    LoadingTextDescription: 'Tekst som vises mens webdelen lastes.',
    EmptyMessageDescription: 'Tekst som vises om det ikke er noen prosjekter.',
    ColumnsListNameLabel: 'Kolonner',
    CommandBarGroupName: 'Kommandolinje',
    ConfigurationGroupName: 'Konfigurasjon',
    ConsequenceLabel: 'Konsekvens (K)',
    ConsequencePostActionLabel: 'K etter tiltak',
    CreatedText: 'Opprettet',
    DataSourceCategoryError: 'Det skjedde en feil under uthenting av datakilder med kategori **{0}**.',
    DataSourceError: 'Det skjedde en feil under uthenting av data fra datakilde med navn **{0}**.',
    DataSourceNotFound: 'Finner ingen datakilde med navn **{0}**.',
    DefaultViewLabel: 'Standardvisning',
    DefaultDataSourceViewLabel: 'Standardvisning (datakilde)',
    DeliveryDescriptionLabel: 'Leveransebeskrivelse',
    DeliveryEndTimeLabel: 'Sluttidspunkt',
    DeliveryStartTimeLabel: 'Starttidspunkt',
    DeliveryStatusCommentLabel: 'Kommentar, leveransestatus',
    DeliveryStatusLabel: 'Leveransestatus',
    DesiredValueLabel: 'Ønsket verdi',
    DescriptionFieldLabel: 'Beskrivelse',
    TagFieldLabel: 'Etikett',
    CategoryFieldLabel: 'Kategori',
    EditViewText: 'Rediger gjeldende visning',
    ErrorText: 'Det skjedde en feil under uthenting av prosjekter.',
    ExcelExportButtonLabel: 'Eksporter til Excel',
    ExcelExportFileNamePrefix: 'Gevinstoversikt',
    FetchDataErrorMessage: 'Det skjedde en feil under uthenting av data.',
    FieldSelectorEmptyMessage: 'Det er ikke konfigurert opp noen felter. Ta kontakt med en administrator.',
    FieldSelectorName: 'Felter',
    FiltersString: 'Filtre',
    FilterText: 'Filtrer',
    GeneralGroupName: 'Generelt',
    GetConfigErrorMessage: 'Det skjedde en feil under uthenting av konfigurasjon.',
    IndicatorLabel: 'Måleindikator',
    LastMeasurementLabel: 'Siste måling',
    LoadingText: 'Laster {0}...',
    ProjectListLoadingText: 'Laster prosjekter...',
    LogDescriptionLabel: 'Loggbeskrivelse',
    MeasuremenentIdicatorLabel: 'Måleindikator',
    MeasurementAchievementLabel: 'Måloppnåelse',
    MeasurementCommentLabel: 'Kommentar til måling',
    MeasurementDateLabel: 'Dato for måling',
    MeasurementValueLabel: 'Målt verdi',
    MissingProperties: 'Prosjektet mangler egenskaper',
    NewViewText: 'Opprett ny visning',
    NoDefaultViewMessage: 'Det er ikke satt noen standardvisning.',
    NoGroupingText: 'Ingen gruppering',
    NoProjectData: 'Kan ikke hente alle data fra prosjektområdet. Det kan være at du ikke har tilgang til selve området. Det kan også være at området nylig er opprettet eller at prosjektegenskaper ikke er utfylt.',
    NoProperties: 'Det er ikke satt noen egenskaper for prosjektet',
    ProjectListEmptyText: 'Søket ga ingen resultater',
    NotSet: 'Ikke satt',
    PhaseLabel: 'Fase',
    ProbabilityLabel: 'Sannsynlighet (S)',
    ProbabilityPostActionLabel: 'S etter tiltak',
    ProjectInformationGroupName: 'Instillinger for Prosjektinformasjon-vindu',
    ProjectLinkText: 'Gå til prosjektområde',
    ProjectManager: 'Prosjektleder',
    ProjectOwner: 'Prosjekteier',
    ProjectStatusLinkText: 'Gå til prosjektstatus',
    RecommendationLabel: 'Anbefaling',
    ResourceAllocationInfoText: 'Ressursallokering eller fravær som gjelder på tvers av prosjekter legges inn i den<A HREF="../Lists/Ressursallokering/AllItems.aspx?Source={0}">sentrale ressursallokeringslisten</A>. Disse oppføringene vil vises med blå og rød (fravær) farge i tabellen under. Prosjektallokeringer vises med grønn farge. Fargestyrken til allokeringen baserer seg på allokeringsprosenten.',
    ResourceAllocationErrorTransformGroupText: 'Det er et problem med en av ressursene i prosjektet {0}. Det kan skyldes av at det ikke er angitt navn for ressursen. vennligst sjekk opp i dette.',
    ResourceLabel: 'Ressurs',
    ResponsibleLabel: 'Ansvarlig',
    RoleLabel: 'Rolle',
    AllocationPercetageLabel: 'Allokeringsprosent',
    AllocationStatusLabel: 'Allokeringsstatus',
    CommentLabel: 'Kommentar',
    ProjectsAccessSearchBoxPlaceholderText: 'Søk i {0} prosjekter du har tilgang til...',
    MyProjectsSearchBoxPlaceholderText: 'Søk i {0} prosjekter du er medlem av...',
    AllProjectsSearchBoxPlaceholderText: 'Søk i alle {0} prosjekter...',
    ParentProjectsSearchBoxPlaceholderText: 'Søk i {0} overordnede prosjekter...',
    ProgramSearchBoxPlaceholderText: 'Søk i {0} program...',
    SearchBoxPlaceholderText: 'Søk i {0}...',
    SearchBoxPlaceholderFallbackText: 'Søk...',
    SearchBoxPlaceholderTextLabel: 'Søkebokstekst',
    ShowAllMeasurementsLinkText: 'Vis alle målinger',
    RenderModeListText: 'Liste',
    RenderModeTilesText: 'Fliser',
    ShowCommandBarLabel: 'Vis kommandolinje',
    ShowExcelExportButtonLabel: 'Vis eksport til Excel-knapp',
    ShowFiltersLabel: 'Vis filtre',
    ShowGroupByLabel: 'Vis grupperingsvalg',
    ShowProjectLogoFieldLabel: 'Vis logo',
    ShowProjectManagerFieldLabel: 'Vis Prosjektleder',
    ShowProjectOwnerFieldLabel: 'Vis Prosjekteier',
    ShowSearchBoxLabel: 'Vis søkeboks',
    ShowViewSelectorLabel: 'Vis visningsvelger',
    SiteTitleLabel: 'Prosjekt',
    SortByFieldLabel: 'Sorteringsegenskap',
    StartValueLabel: 'Startverdi',
    StatusReportsCountLabel: 'Antal rapporter å vise',
    TileViewGroupName: 'Flisevisning',
    TitleLabel: 'Tittel',
    UnitLabel: 'Måleenhet',
    TypeLabel: 'Type',
    ViewNotFoundMessage: 'Finner ikke angitt visning.',
    ViewsListNameLabel: 'Visninger',
    SelectedColumnsLabel: 'Felter',
    ProjectsListName: 'Prosjekter',
    TimelineContentListName: 'Tidslinjeinnhold',
    TimelineConfigurationListName: 'Tidslinjekonfigurasjon',
    DataSourceListName: 'Datakilder',
    ProjectContentColumnsListName: 'Prosjektinnholdskolonner',
    ProjectColumnsListName: 'Prosjektkolonner',
    PortfolioManagerGroupName: 'Porteføljeinnsyn',
    ProjectTimelineItemInfo: '{0} - prosjektets tidsforløp',
    LastPublishedStatusreport: 'Gå til siste statusrapport',
    DiamondLabel: 'Diamant',
    BarLabel: 'Bar',
    TriangleLabel: 'Trekant',
    MilestoneLabel: 'Milepæl',
    ProjectLabel: 'Prosjekt',
    SubPhaseLabel: 'Delfase',
    ProjectDeliveryLabel: 'Prosjektleveranse',
    NameLabel: 'Navn',
    CurrentPhaseLabel: 'Gjeldende fase',
    MilestoneDateLabel: 'Milepælsdato',
    StartDateLabel: 'Startdato',
    EndDateLabel: 'Sluttdato',
    BudgetTotalLabel: 'Totalbudsjett',
    CostsTotalLabel: 'Kostnader påløpt totalt',
    NoProjectsFound: 'Ingen prosjekter funnet.',
    NewLabel: 'Ny',
    DisplayAllProjects: "Vis alle prosjekter",
    ProjectsAccessHeaderText: 'Tilgang til',
    MyProjectsHeaderText: "Mine prosjekter",
    AllProjectsHeaderText: "Alle prosjekter",
    ParentProjectsHeaderText: "Overordnede områder",
    ProgramProjectsHeaderText: "Program",
    NoAccessMessage: "Du har ikke tilgang til dette prosjektet",
    BooleanYes: "Ja",
    BooleanNo: "Nei",
    ProjectDeliveriesGroupName: 'Prosjektleveranser (beta)',
    ShowProjectDeliveriesLabel: 'Vis prosjektleveranser',
    ConfigItemTitleFieldLabel: 'Element tittel (konfigurasjon)',
    ConfigItemTitleFieldDescription: 'Dersom det er spesifisert et element med tittelen angitt her i tidslinjekonfigurasjon listen så vil dette vises på tidslinjen.',
    SortOrderLabel: 'Sorteringsrekkefølge',
    DataSourceItemNotFound: 'Datakilde ble ikke funnet',
    ProjectContentColumnItemNotFound: 'Prosjektinnholdskolonne ble ikke funnet',
    ToggleEditViewColumnsLabel: 'Vis eller skjul kolonner',
    ShowHideColumnsLabel: 'Vis/skjul kolonner',
    EditViewColumnsPanelHelpText: 'Velg kolonnene som skal vises for nåværende visning. Hvis du vil endre rekkefølgen, kan du dra og slippe eller bruke opp- og ned-pilen ved siden av hver kolonne.',
    PortfolioOverviewDataFetchError: 'Det skjedde en feil under henting av data for porteføljeoversikten. Vennligst prøv igjen senere.\n \n \n **Detaljert feilmelding:** `{0}`',
    PortfolioOverviewDataFetchErrorView: 'Det skjedde en feil under henting av data for porteføljeoversikten for visning "{0}". Vennligst prøv igjen senere, eller prøv en annen visning.\n \n \n **Detaljert feilmelding:** `{1}`',
    PersonalViewsHeaderText: 'Personlige visninger',
    ListViewText: 'Liste',
    CompactViewText: 'Kompakt liste',
    DefaultRenderModeLabel: 'Standard visningsmodus',
    UseChangesButtonText: 'Bruk',
    ColumnSettingsLabel: 'Kolonneinnstillinger',
    ColumnSettingsDisabledTooltip: 'Kolonneinnstillinger er kun tilgjengelig når siden er i redigeringsmodus.',
    MinWidthDescription: 'Minimum bredde for kolonnen. Kan ikke overstige maksimum bredde.',
    MaxWidthDescription: 'Maksimum bredde for kolonnen. Kan ikke være mindre enn minimum bredde.',
  }
})
