define([], function () {
  return {
    AddColumnLabel: 'Legg til en kolonne',
    AllocationPercetageLabel: 'Allokeringsprosent',
    AllocationStatusLabel: 'Allokeringsstatus',
    AllProjectsHeaderText: 'Alle prosjekter/program',
    AllProjectsSearchBoxPlaceholderText: 'Søk i alle {0} prosjekter...',
    BarLabel: 'Bar',
    BooleanNo: 'Nei',
    BooleanYes: 'Ja',
    BooleanOff: 'Av',
    BooleanOn: 'På',
    CancelButtonLabel: 'Avbryt',
    ChartConfigurationListNameLabel: 'Grafkonfigurasjon',
    ChartErrorText: 'Grafen er ugyldig konfigurert.',
    ColumnConfigListNameLabel: 'Kolonnekonfigurasjon',
    ColumnPersistRenderGloballyFieldDescription: 'Om du ønsker å endre visningsmodus for kolonnene som for alle webdeler og visninger, huk av sjekkboksen over.',
    ColumnPersistRenderGloballyFieldLabel: 'Oppdater globalt',
    ColumnRenderDataTypePropertiesHeaderText: 'Egenskaper for visningstype',
    ColumnRenderDescription: 'Velg hvordan kolonnen skal vises. Om det er tekstfelt som skal vises over flere linjer, velg Notat.',
    ColumnRenderLabel: 'Vis som',
    ColumnRenderOptionBoolean: 'Ja/nei',
    ColumnRenderOptionBooleanFalse: 'Verdi for \'Nei\'',
    ColumnRenderOptionBooleanTrue: 'Verdi for \'Ja\'',
    ColumnRenderOptionCurrency: 'Valuta',
    ColumnRenderOptionCurrencyFallbackValueLabel: 'Standardverdi',
    ColumnRenderOptionCurrencyMaximumFractionDigitsLabel: 'Maksimalt antall desimaler',
    ColumnRenderOptionCurrencyMinimumFractionDigitsLabel: 'Minimum antall desimaler',
    ColumnRenderOptionCurrencyPrefixLabel: 'Valutaprefiks',
    ColumnRenderOptionDate: 'Dato',
    ColumnRenderOptionDateIncludeTimeLabel: 'Inkluder tidspunkt',
    ColumnRenderOptionFilename: 'Filnavn',
    ColumnRenderOptionModal: 'Modal',
    ColumnRenderOptionModalInfoTextTemplateDescription: 'Mal for infotekst. Bruk {{GtMeasurementOWSCHCS}} for å vise måleindikatoren, {{GtStartValueOWSNMBR}} for å vise startverdien og {{GtDesiredValueOWSNMBR}} for å vise målet. Du kan også bruke andre kolonnenavn fra gevinstarbeidet.',
    ColumnRenderOptionModalInfoTextTemplateLabel: 'Mal for infotekst',
    ColumnRenderOptionModalLinkTextLabel: 'Tekst for lenke',
    ColumnRenderOptionModalShowInfoTextLabel: 'Vis infotekst',
    ColumnRenderOptionNote: 'Notat',
    ColumnRenderOptionNumber: 'Tall',
    ColumnRenderOptionPercentage: 'Prosent',
    ColumnRenderOptionProjectInformationModal: 'Prosjektinformasjon',
    ColumnRenderOptionTags: 'Etiketter',
    ColumnRenderOptionTagsValueSeparatorDescription: 'Angi et tegn som skal brukes for å skille verdier i etikettfeltet. Standard er semikolon.',
    ColumnRenderOptionTagsValueSeparatorLabel: 'Separator for verdier',
    ColumnRenderOptionText: 'Tekst',
    ColumnRenderOptionTrend: 'Trend',
    ColumnRenderOptionTrendShowTrendIconLabel: 'Vis ikon',
    ColumnRenderOptionUrl: 'URL',
    ColumnRenderOptionUrlDescriptionDescription: 'Beskrivelse av lenken. Om du ikke angir en verdi, brukes eventuelt beskrivelse fra lenken.',
    ColumnRenderOptionUrlDescriptionLabel: 'Beskrivelse',
    ColumnRenderOptionUrlOpenInNewTabLabel: 'Åpne i ny fane',
    ColumnRenderOptionUser: 'Person',
    ColumnSettingsDisabledTooltip: 'Kolonneinnstillinger er kun tilgjengelig når siden er i redigeringsmodus.',
    ColumnSettingsLabel: 'Kolonneinnstillinger',
    ColumnsListNameLabel: 'Kolonner',
    ColumnVisibilityDescription: 'Angi hvor kolonnen skal vises. Prosjektforside, prosjektstatus-siden, porterføljeoversikten eller alle steder.',
    ColumnVisibilityLabel: 'Synlighet for kolonne',
    ColumSettingsLabel: 'Kolonneinnstillinger',
    CommandBarGroupName: 'Kommandolinje',
    CommentLabel: 'Kommentar',
    CompactViewText: 'Kompakt liste',
    ConfigItemTitleFieldDescription: 'Dersom det er spesifisert et element med tittelen angitt her i tidslinjekonfigurasjon listen så vil dette vises på tidslinjen.',
    ConfigItemTitleFieldLabel: 'Element tittel (konfigurasjon)',
    ConfigurationGroupName: 'Konfigurasjon',
    ConfirmDeleteProjectColumnSubText: 'Denne kolonnen fjernes fra Prosjektkolonner-listen og dermed fra alle visninger som bruker den. Er du sikker på at du vil slette denne kolonnen? Om du kun ønsker å fjerne kolonnen fra denne visningen, kan du bruke \'Vis eller skjul kolonner\'.',
    ConfirmDeleteProjectColumnTitle: 'Vil du slette?',
    ConfirmDeleteProjectContentColumnSubText: 'Denne kolonnen fjernes fra Prosjektinnholdskolonner-listen og dermed fra alle visninger som bruker den. Er du sikker på at du vil slette denne kolonnen? Om du kun ønsker å fjerne kolonnen fra denne visningen, kan du bruke \'Vis eller skjul kolonner\'.',
    ConfirmDeleteProjectContentColumnTitle: 'Vil du slette?',
    ConfirmDeleteResponseAbort: 'Avbryt',
    ConfirmDeleteResponseConfirm: 'Slett',
    CreatedText: 'Opprettet',
    CustomSortsText: 'Egendefinert sortering',
    DataSourceCategoryDescription: 'Angi en datakildekategori for å kunne velge mellom flere datakilder i webdelen.',
    DataSourceCategoryError: 'Det skjedde en feil under uthenting av datakilder med kategori **{0}**.',
    DataSourceCategoryLabel: 'Kategori for datakilder',
    DataSourceError: 'Det skjedde en feil under uthenting av data fra datakilde med navn **{0}**.',
    DataSourceGroupName: 'Datakilder',
    DataSourceItemNotFound: 'Datakilde ble ikke funnet',
    DataSourceLabel: 'Datakilde',
    DataSourceLevelDescription: 'Angi nivået for datakilden. Dette brukes for å filtrere datakilder i webdelen basert på hvor man henter data fra. Dette kan endres i ettertid i \'Datakilder\'-listen om du ønsker å gjøre spørringen/visningen tilgjengelig andre steder.',
    DataSourceLevelLabel: 'Nivå for datakilde',
    DataSourceLevelPortfolio: 'Portefølje',
    DataSourceLevelProject: 'Prosjekt',
    DataSourceListName: 'Datakilder',
    DataSourceNotFound: 'Finner ingen datakilde med navn **{0}**.',
    DefaultDataSourceViewLabel: 'Standardvisning (datakilde)',
    DefaultRenderModeLabel: 'Standard visningsmodus',
    DefaultVerticalLabel: 'Standardvertikal',
    DefaultViewDescription: 'Velg om dette er standardvisningen for Porteføljeoversikten.',
    DefaultViewLabel: 'Standardvisning',
    DefaultViewSetWarningMessage: 'Det er allerede en visning som er satt som standard. Du må først endre denne visningen før du kan sette en ny som standard. Personlige visninger kan ikke settes som standard.',
    DeleteButtonLabel: 'Slett',
    DisplayNameDescription: 'Visningsnavn for denne kolonnen, kun for denne webdelen. Om du ønsker å endre visningsnavnet for alle webdeler, må du endre det i listen Prosjektinnholdskolonner.',
    DisplayNameLabel: 'Visningsnavn',
    EditColumnHeaderText: 'Rediger kolonne',
    EditColumnLabel: 'Rediger',
    EditViewColumnsPanelHeaderText: 'Rediger visningskolonner',
    EditViewColumnsPanelHelpText: 'Velg kolonnene som skal vises for nåværende visning. Hvis du vil endre rekkefølgen, kan du dra og slippe eller bruke opp- og ned-pilen ved siden av hver kolonne.',
    EditViewHeaderText: 'Rediger visning',
    EditViewText: 'Rediger gjeldende visning',
    EmptyMessageDescription: 'Tekst som vises om det ikke er noen prosjekter.',
    EmptyMessageLabel: 'Tekst ved ingen elementer',
    EndDateLabel: 'Sluttdato',
    ErrorText: 'Det skjedde en feil under uthenting av prosjekter.',
    ExcelExportButtonLabel: 'Eksporter til Excel',
    FiltersString: 'Filtre',
    FilterText: 'Filtrer',
    GeneralGroupName: 'Generelt',
    GroupByColumnLabel: 'Grupper etter {0}',
    HideVerticalsLabel: 'Skjul vertikaler',
    IconNameDescription: 'Navn på ikon fra UI Fabric. Se https://uifabricicons.azurewebsites.net/.',
    IconNameLabel: 'Ikonnavn',
    IncludeViewNameInExcelExportFilenameLabel: 'Inkluder visningsnavn i Excel-filnavn',
    InternalNameDescription: 'Internt feltnavn for denne kolonnen.',
    InternalNameLabel: 'Internt feltnavn',
    IsGroupableDescription: 'Brukere kan gruppere på denne kolonnen.',
    IsGroupableLabel: 'Grupperbar',
    IsRefinableDescription: 'Brukere kan filtrere på denne kolonnen.',
    IsRefinableLabel: 'Presiser',
    IsResizableLabel: 'Justerbar',
    ListLayoutModeJustifiedLabel: 'Juster kolonner etter skjermbredde',
    ListViewGroupName: 'Listevisning',
    ListViewText: 'Liste',
    LoadingText: 'Laster {0}...',
    LoadingTextDescription: 'Tekst som vises mens webdelen lastes.',
    LoadingTextLabel: 'Laste-tekst',
    MaxWidthDescription: 'Maksimum bredde for kolonnen. Kan ikke være mindre enn minimum bredde.',
    MaxWidthLabel: 'Maks bredde',
    MeasurementAchievementLabel: 'Måloppnåelse',
    MeasurementCommentLabel: 'Kommentar til måling',
    MeasurementDateLabel: 'Dato for måling',
    MeasurementValueLabel: 'Målt verdi',
    MinWidthDescription: 'Minimum bredde for kolonnen. Kan ikke overstige maksimum bredde.',
    MinWidthLabel: 'Minimum bredde',
    ModalColumnEmptyListText: 'Ingen elementer funnet.',
    MoveLeftLabel: 'Flytt til venstre',
    MoveRightLabel: 'Flytt til høyre',
    MyProjectsHeaderText: 'Mine prosjekter',
    MyProjectsSearchBoxPlaceholderText: 'Søk i {0} prosjekter du er medlem av...',
    NameLabel: 'Navn',
    NewColumnHeaderText: 'Ny kolonne',
    NewLabel: 'Ny',
    NewViewHeaderText: 'Opprett visning',
    NewViewText: 'Opprett ny visning',
    NoAccessMessage: 'Du har ikke tilgang til dette prosjektet',
    NoDefaultViewMessage: 'Det er ikke satt noen standardvisning.',
    NoProjectData: 'Kan ikke hente alle data fra prosjektområdet. Det kan være at du ikke har tilgang til selve området. Det kan også være at området nylig er opprettet eller at prosjektegenskaper ikke er utfylt.',
    NoProjectsFound: 'Ingen prosjekter funnet.',
    NotSet: 'Ikke satt',
    ParentProjectsHeaderText: 'Overordnede prosjekter',
    ParentProjectsSearchBoxPlaceholderText: 'Søk i {0} overordnede prosjekter...',
    PersonalViewDescription: 'Velg om dette er en personlig visning. Personlige visninger kan kun redigeres av deg.',
    PersonalViewLabel: 'Personlig visning',
    PersonalViewsHeaderText: 'Personlige visninger',
    PhaseLabel: 'Fase',
    PortfolioAggregationNotConfiguredMessage: 'Webdelen må konfigureres med en datakilde. Rediger webdelen, og legg inn navnet på datakilden du vil bruke.',
    PortfolioAggregationViewSearchQueryDescription: 'Søkespørringen for å hente data. DepartmentId refererer til Prosjektportalen-huben og bør ikke endres. ContentTypeId refererer til innholdstypen til dataelementet du vil hente. Gå til Datakilder-listen for å se eksempler.',
    PortfolioManagerGroupName: 'Porteføljeinnsyn',
    PortfolioOverviewColumnRenderDescription: 'Velg hvordan kolonnen skal vises. Om det er tekstfelt som skal vises over flere linjer, velg Notat.',
    PortfolioOverviewDataFetchError: 'Det skjedde en feil under henting av data for porteføljeoversikten. Vennligst prøv igjen senere.<br/><br/> **Detaljert feilmelding:**<br/> `{0}`',
    PortfolioOverviewDataFetchErrorView: 'Det skjedde en feil under henting av data for porteføljeoversikten for visning **{0}**. Vennligst prøv igjen senere, eller prøv en annen visning.<br/><br/> **Detaljert feilmelding:**<br/> `{1}`',
    PortfolioOverviewShowEditViewColumnsPanelHelpText: 'Velg kolonnene som skal vises for nåværende visning. Hvis du vil endre rekkefølgen, kan du dra og slippe eller bruke opp- og ned-pilen ved siden av hver kolonne. Bruk \'Tilbakestill rekkefølge\'-knappen for å tilbakestille rekkefølgen til standard rekkefølge spesifisert i Prosjektkolonner-listen.',
    PortfolioViewSearchQueryDescription: 'Søkespørringen for å hente prosjekter i porteføljen. DepartmentId refererer til Prosjektportalen-huben og bør ikke endres.',
    PortfolioViewsListName: 'Porteføljevisninger',
    ProgramProjectsHeaderText: 'Program',
    ProgramSearchBoxPlaceholderText: 'Søk i {0} program...',
    ProgramsHeaderText: 'Programmer',
    ProjectColumnsListName: 'Prosjektkolonner',
    ProjectContentColumnItemNotFound: 'Prosjektinnholdskolonne ble ikke funnet',
    ProjectContentColumnsListName: 'Prosjektinnholdskolonner',
    ProjectDeliveriesGroupName: 'Prosjektleveranser (beta)',
    ProjectInformationGroupName: 'Instillinger for Prosjektinformasjonspanel',
    ProjectLabel: 'Prosjekt',
    ProjectListEmptyText: 'Søket ga ingen resultater',
    ProjectManager: 'Prosjektleder',
    ProjectOwner: 'Prosjekteier',
    ProjectsAccessHeaderText: 'Tilgang til',
    ProjectsAccessSearchBoxPlaceholderText: 'Søk i {0} prosjekter du har tilgang til...',
    ProjectsListName: 'Prosjekter',
    RenderModeListText: 'Liste',
    RenderModeTilesText: 'Fliser',
    ResourceAllocationInfoText: 'Ressursallokering eller fravær som gjelder på tvers av prosjekter legges inn i den<A HREF="../Lists/Ressursallokering/AllItems.aspx?Source={0}">sentrale ressursallokeringslisten</A>. Disse oppføringene vil vises med blå og rød (fravær) farge i tabellen under. Prosjektallokeringer vises med grønn farge. Fargestyrken til allokeringen baserer seg på allokeringsprosenten.',
    ResourceLabel: 'Ressurs',
    RevertCustomOrderButtonText: 'Tilbakestill rekkefølge',
    RevertCustomOrderButtonTooltip: 'Tilbakestill rekkefølge til standard rekkefølge for kolonner spesifisert i Prosjektkolonner-listen.',
    RoleLabel: 'Rolle',
    RowLimitLabel: 'Antall elementer',
    SaveButtonLabel: 'Lagre',
    SearchBoxGroupName: 'Søkeboks',
    SearchBoxPlaceholderFallbackText: 'Søk...',
    SearchBoxPlaceholderText: 'Søk i {0}...',
    SearchBoxPlaceholderTextDescription: 'Tekst som vises i søkeboksen når den er tom. Om det ikke settes en verdi baseres teksten på valgt datakilde.',
    SearchBoxPlaceholderTextLabel: 'Søkebokstekst',
    SearchPropertyDescription: 'Navnet på den forvaltede egenskapen for denne kolonnen.',
    SearchPropertyFoundMessage: 'Fant en forvaltet egenskap `{0}` som matcher det interne feltnavnet `{1}`.',
    SearchPropertyLabel: 'Søkeegenskap',
    SearchPropertyPlaceholder: 'Søk i forvaltede egenskaper...',
    SearchQueryLabel: 'Søkespørring',
    SelectProgramText: 'Velg et programområde',
    ShowAllMeasurementsLinkText: 'Vis alle målinger',
    ShowCommandBarLabel: 'Vis kommandolinje',
    ShowExcelExportButtonLabel: 'Vis eksport til Excel-knapp',
    ShowFieldFrontpageLabel: 'Prosjektforside',
    ShowFieldPortfolioLabel: 'Porteføljeoversikt',
    ShowFieldProjectStatusLabel: 'Prosjektstatus',
    ShowFiltersLabel: 'Vis filtre',
    ShowGroupByLabel: 'Vis grupperingsvalg',
    ShowHideColumnsLabel: 'Vis/skjul kolonner',
    ShowProgramViewsLabel: 'Vis programvisninger',
    ShowProjectLogoFieldLabel: 'Vis logo',
    ShowProjectManagerFieldLabel: 'Vis Prosjektleder',
    ShowProjectOwnerFieldLabel: 'Vis Prosjekteier',
    ShowRenderModeSelectorLabel: 'Vis visningsvelger',
    ShowSearchBoxLabel: 'Vis søkeboks',
    ShowViewSelectorLabel: 'Vis visningsvelger',
    SiteTitleLabel: 'Prosjekt',
    SortAscLabel: 'Å til A',
    SortByFieldLabel: 'Sorteringsegenskap',
    SortDescLabel: 'A til Å',
    SortOrderDescription: 'Sorteringsrekkefølgen bestemmer hvilken rekkefølge visningene vises i. Lavest verdi vises først.',
    SortOrderLabel: 'Sorteringsrekkefølge',
    StartDateLabel: 'Startdato',
    StatusReportsCountLabel: 'Antall rapporter å vise',
    TileViewGroupName: 'Flisevisning',
    TimelineConfigurationListName: 'Tidslinjekonfigurasjon',
    TimelineContentListName: 'Tidslinjeinnhold',
    TitleLabel: 'Tittel',
    ToggleColumnFormPanelLabel: 'Legg til kolonne',
    ToggleEditViewColumnsLabel: 'Vis eller skjul kolonner',
    UseChangesButtonText: 'Bruk',
    ViewNotFoundMessage: 'Finner ikke angitt visning.',
    ViewsListNameLabel: 'Visninger'
  }
})
