// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'icon': string;
  'isSelected': string;
  'root': string;
  'secondaryText': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
