import { configuredUrl, expect, test } from '../fixtures/pp365'
import {
  expectDialogGridsToFit,
  findDocumentLibrary,
  measureBothScreens,
  openDocumentTemplateDialog
} from '../fixtures/document-template-dialog'
import { localBundleUse, localBundles, openWithLocalBundle } from '../fixtures/local-bundle'

/**
 * The "Hent dokumentmal" dialog measured with the *local* ProjectExtensions bundle. Opt in with
 * E2E_LOCAL_BUNDLE=1 while `npx heft start --nobrowser` serves ProjectExtensions on
 * https://localhost:4321 (its `config/serve.json` is generated by `npm run watch`).
 *
 * Known gap (2026-09-30): with the debug manifests the deployed custom action's command did not
 * render in the command bar, with or without a `customActions` query parameter, so this variant
 * has not passed yet; the deployed smoke test and the timeline's local variant cover the shared
 * grid's fix.
 */
const siteUrl = configuredUrl(process.env.E2E_LOCAL_SITE_URL ?? process.env.E2E_PROJECT_URL)

test.use(localBundleUse)

test.describe('document template dialog, local bundle', () => {
  test.skip(!siteUrl, 'E2E_LOCAL_SITE_URL or E2E_PROJECT_URL must point at a project site')

  for (const viewport of [
    { width: 1280, height: 800 },
    { width: 1600, height: 1000 }
  ]) {
    test(`lists fit the dialog at ${viewport.width}px`, async ({ page }, testInfo) => {
      await page.setViewportSize(viewport)
      await openWithLocalBundle(page, await findDocumentLibrary(page, siteUrl!))
      const dialog = await openDocumentTemplateDialog(page)
      const metrics = await measureBothScreens(page, dialog, testInfo)
      expect(
        (await localBundles(page)).length,
        'the local bundle should be the one loaded'
      ).toBeGreaterThan(0)
      expectDialogGridsToFit(metrics)
    })
  }
})
