define([], function () {
  return {
    ApplyTemplateFiles: "Legger inn filer og webdeler",
    ApplyTemplateLists: "Legger inn lister med felter, innholdstyper og visninger",
    ApplyTemplateNavigation: "Legger inn navigasjon",
    ApplyTemplateWebSettings: "Legger inn webinstillinger",
    ApplyTemplateComposedLook: "Legger på farge og fonter",
    ApplyTemplateSiteFields: "Legger inn felter",
    ApplyTemplateContentTypes: "Legger inn innholdstyper",
    ApplyTemplateClientSidePages: "Legger inn filer og webdeler",
    TemplateSelectTitle: "Velg prosjektmal",
    SettingsTitle: "Innstillinger",
    IncludeStandardFoldersLabel: "Inkluder standardmapper",
    CopyPlannerTasksLabel: "Kopier standardoppgaver til Planner",
    ListContentTitle: "Velg standardinnhold",
    ExtensionsTitle: "Velg prosjekttillegg",
    TemplateSelectModalTitle: "Oppsett av prosjektområde",
    TemplateSelectModalSubmitButtonText: "Sett opp området",
    TemplateSelectModalInfoText: "Oppsettet av prosjektområdet tar omtrent 10 minutter. Ikke lukk nettleservinduet mens området settes opp.",
    ProgressModalTitle: "Setter opp prosjektområdet",
    ProgressModalLabel: "Klargjør prosjektområdet",
    ProgressModalDescription: "Vennligst vent. Ikke lukk nettleservinduet.",
    ErrorModalTitle: "Noe er galt",
    ApplyExtensionText: "Installer prosjekttilegget {0}",
    PlannerConfigurationText: "Oppretter standardoppgaver i Planner for {0}",
    CopyListDataText: "Kopierer listeinnhold fra {0} til {1}",
    EditPropertiesLinkText: "Du kan allerede nå<A HREF=\"{0}\" TARGET=\"_BLANK\">redigere egenskaper</A> for prosjektet (åpnes i ny fane).",
    InvalidLanguageErrorMessage: "Ugyldig språk for området",
    InvalidLanguageErrorStack: "Språket som er satt for området støttes ikke. Området må være opprettet med norsk språk.",
    NoHubSiteErrorMessage: "Området er ikke koblet til en hub",
    NoHubSiteErrorStack: "Området kan ikke settes opp uten å være koblet til en hub. Koble området til ett hubområde, og last siden på nytt.",
    GetSetupDataErrorMessage: "Det skjedde en feil",
    GetSetupDataErrorStack: "Det skjedde en feil under uthenting av data fra hubområdet.",
    SiteFieldsGroupName: "Kolonner for Prosjektportalen (Prosjekt)",
    ApplyTemplateErrorMessage: "Det skjedde en feil under konfigurering av området",
    CopyListDataErrorMessage: "Det skjedde en feil under kopiering av listeinnhold",
    PlannerConfigurationErrorMessage: "Det skjedde en feil under konfigurering av området",
    SetTaxonomyFieldsErrorMessage: "Det skjedde en feil under konfigurering av taksonomifelter",
    SetupProjectInformationErrorMessage: "Det skjedde en feil under initialisering av prosjektinformasjon",
    ProvisionSiteFieldsErrorMessage: "Det skjedde en feil under provisjonering av områdekolonner",
    ProvisionSiteFieldsText: "Opprettet feltet {0} på området",
  }
});