define([], function () {
  return {
    SaveText: 'Save',
    UpdatingProjectPropertiesStatusText: 'Updating project properties ...',
    SynchronizingProjectPropertiesToPortfolioSiteStatusText:
      'Synchronizing project properties to portfolio site ...',
    AdminPageLinkLabel: 'Path to Admin page',
    AdvancedGroupName: 'Advanced',
    BarLabel: 'Bar',
    CalloutTemplateFieldLabel: 'Callout template',
    CancelText: 'Cancel',
    CategoryFieldLabel: 'Category',
    ChangePhaseText: 'Change to this phase',
    ChangingPhaseDescription: 'Changing phase to {0}',
    ChecklistCommentDescription:
      'Comment is mandatory if the checkpoint is to be marked as "Not relevant" or "Still open".',
    ChecklistCommentPlaceholder: 'Enter a comment...',
    CheckpointDoneTooltip: 'Checkpoint completed',
    CheckpointNotRelevantTooltip: 'Checkpoint is not relevant',
    CheckpointNotRelevantTooltipCommentEmpty:
      "You cannot set the checkpoint as 'Not Relevant' without commenting.",
    CheckPointsStatus: '{0} checkpoints marked as **{1}**',
    CheckpointStillOpenTooltip: 'Checkpoint is still open',
    CheckpointStillOpenTooltipCommentEmpty:
      "You cannot set the checkpoint as 'Still open' without posting a comment.",
    ChildProjectAdminLabel: 'Manage childprojects',
    CloseText: 'Close',
    ColorPickerStrings: {
      blue: 'Blue',
      green: 'Green',
      hex: '',
      red: 'Red'
    },
    CommentLabel: 'Comment',
    ConfigItemTitleFieldLabel: 'Element title (configuration)',
    ConfirmChangePhase: 'Do you want to change phase to {0}?',
    ConsequenceFieldNameFieldLabel: 'Field name - Consequence',
    ConsequenceHeaderFieldLabel: 'Consequence {0}',
    ConsequencePostActionFieldNameFieldLabel: 'Field name - Consequence (post action)',
    CreateParentModalSubText:
      'Do you want to turn the site into a parent project? This action is not reversible.',
    CreateParentModalTitle: 'Parent project',
    CreateParentProjectLabel: 'Convert to parent project',
    CurrentPhaseViewNameFieldLabel: 'Display name for current phase',
    DataGroupName: 'Data',
    DefaultAdminPageLink: 'Admin.aspx',
    DefaultGroupByLabel: 'Default grouping',
    DefaultTimeframeEndLabel: 'Default end date',
    DefaultTimeframeEndValue: '{0} months into the future',
    DefaultTimeframeStartLabel: 'Default start date',
    DefaultTimeframeStartValue: '{0} months back in the past',
    DeleteItemLabel: 'Delete',
    DeleteReportButtonText: 'Delete',
    DiamondLabel: 'Diamond',
    DocumentsListName: 'Documents',
    EditItemLabel: 'Edit',
    EditProjectInformationText: 'Edit project information',
    EditReportButtonLabel: 'Edit status',
    EditSiteInformationText: 'Edit site information',
    ExternalUsersConfigInfoMessage:
      'Here fields/columns to be displayed to external users/guests are configured. <br /> <br /> Fields/columns to be displayed to users in the organization are configured in the portfolio site by the administrator.',
    ExternalUsersConfigText: 'Configuration',
    GeneralGroupName: 'General',
    GetSnapshotButtonLabel: 'Open as snapshot',
    GtModerationStatus_Choice_Draft: 'Draft',
    GtModerationStatus_Choice_Published: 'Published',
    HideActionsLabel: 'Hide buttons',
    HideAllActionsLabel: 'Hide all buttons',
    HideParentProjectsLabel: 'Hide parent projects',
    HideStatusReportLabel: 'Hide latest status report',
    HookAuthFieldDescription: 'Authentication for execution of calls when changing phase',
    HookAuthFieldLabel: 'Hook authentication',
    HookUrlFieldDescription: 'Url to be called when changing a phase',
    HookUrlFieldLabel: 'Hook url',
    ListNameFieldLabel: 'Listname',
    ListSectionDataErrorMessage:
      'An error occurred while retrieving data for the section. Is it configured correctly? ',
    LoadingText: 'Loading {0} ...',
    LogListName: 'Log',
    LookAndFeelGroupName: 'Look and feel',
    ManualConfigurationNotFoundOrInvalid:
      'Manual configuration for Risk matrix not found or has invalid format.',
    ManualConfigurationPathLabel: 'Manual configuration',
    MatrixColorScaleConfigLabel: 'Color configuration',
    MatrixFullWidthLabel: 'Use full width',
    MatrixHeader_Critical: 'Critical',
    MatrixHeader_ExtremelyHigh: 'Extremely high',
    MatrixHeader_ExtremelyLarge: 'Extremely large',
    MatrixHeader_ExtremelyLow: 'Extremely Low',
    MatrixHeader_High: 'High',
    MatrixHeader_Insignificant: 'Insignificant',
    MatrixHeader_Large: 'Large',
    MatrixHeader_Low: 'Low',
    MatrixHeader_Medium: 'Medium',
    MatrixHeader_Moderate: 'Moderate',
    MatrixHeader_Serious: 'Serious',
    MatrixHeader_Small: 'Small',
    MatrixHeader_VeryCritical: 'Very Critical',
    MatrixHeader_VeryHigh: 'Very High',
    MatrixHeader_VeryLarge: 'Very Large',
    MatrixHeader_VeryLow: 'Very Low',
    MatrixHeader_VerySmall: 'Very small',
    MatrixSizeLabel: 'Size',
    MilestoneDateLabel: 'Milestone Date',
    MilestoneLabel: 'Milestone',
    MoveOn: 'Go ahead',
    NavigateToSourceUrlText: 'Go back',
    NewItemLabel: 'New item',
    NewStatusReportLabel: 'New Status Report',
    NewStatusReportTitle: 'New Status Report for {0}',
    No: 'No',
    NoLocalPropertiesListWarningMessage:
      'You must synchronize the project properties before you can configure fields / columns to be displayed to external users / guests. <br /> <br /> This is done by clicking the  "Sync project properties \' button.',
    NoPropertiesMessage: 'No project information found.',
    NoStatusReportsMessage:
      'The status of the project is not yet reported. If you are an owner of the site, you can report status by clicking _New Status Report_ in the menu above. ',
    NotPublishedStatusReport: 'Not published',
    OpportunityMatrixGroupName: 'Opportunity matrix',
    OverrideHeadersLabel: 'Override headers for {0}x{0}',
    ParentProjectsGroupName: 'Parent projects',
    ParentProjectsHeaderText: 'Parent projects',
    PhaseChecklistLinkText: 'Go to the phase checklist',
    PhaseChecklistName: 'Phase Checklist',
    PhaseChecklistViewUrl: 'Lists/PhaseChecklist/AllItems.aspx',
    PhaseFieldFieldLabel: 'Phase Field',
    PhaseLabel: 'Phase',
    PhaseSitePageFoundMessage:
      'Changes to this phase will also result in changes to the front page of the project.<br /><br />Page _{0}_ for phase found. This page will be used as the front page for the project. Press **Yes** to continue.',
    PhaseSitePageNotFoundMessage:
      'Dynamic front page is enabled.<br /><br />Page _{0}_ for phase not found, please create. Pressing **Yes** will not change the front page.',
    PleaseWaitText: 'Please wait',
    ProbabilityFieldNameFieldLabel: 'Field name - Probability',
    ProbabilityHeaderFieldLabel: 'Probability {0}',
    ProbabilityPostActionFieldNameFieldLabel: 'Field name - Probability (post action)',
    ProjectDeliveriesGroupName: 'Project deliveries (beta)',
    ProjectInformationDataFetchErrorText: 'An error occurred while retrieving project information.',
    ProjectInformationStatusReportHeaderText: 'Status report published',
    ProjectLabel: 'Project',
    ProjectPhasesChangePhaseError:
      'An error occured while changing the phase. Please try again or contact an administrator',
    ProjectPhasesFetchDataError:
      'You do not have access to view this web part.<br/><br/>You must either have access to the portfolio site, or the project must be exempt from the portfolio site.',
    ProjectPropertiesListName: 'Projectegenskaper',
    ProjectsListName: 'Projects',
    ProjectStatusDataErrorText: 'No access. You are not allowed to view status reports. ',
    ProjectStatusGroupName: 'Project Status',
    ProjectStatusProjectPropertiesGroupName: 'Project properties (Status Sections)',
    ProjectTimelineErrorFetchText:
      'Error when retrieving the projects data.<br><br>Check that the following SiteId is correct with what is in the "Projects" list. <br><br>- SiteId: {0} <br> - Title: {1} <br><br>Error message: {2}',
    ProjectTimelineErrorTransformItemText:
      'Error when linking elements to timeline.<br><br>This may be due to a problem with an element in the "Projects" list (duplicate, deleted project), or that a timeline element does not have a valid connection. <br><br>- SiteId: {0} <br> - Title: {1} <br><br>Error message: {2}',
    ProjecttimelineGroupName: 'Project timeline',
    ProjectTimelineItemInfo: '{0} - the projects time course',
    ProjectTimelineListInfoText:
      'The list items for the project are listed here. Here you can edit and add new elements. This will sync to the list on the hubsite. To zoom in/out in timeline: ALT+Mouse wheel',
    PublishedStatusReport: 'Published',
    PublishReportButtonLabel: 'Publish',
    PublishingReportLabel: 'Please wait while the status report is being published...',
    RedoText: 'Change',
    RevertDefaultColorConfigurationText: 'Use default',
    RiskMatrixConfigurationFolder: 'Risk matrix',
    OpportunityMatrixConfigurationFolder: 'Opportunity matrix',
    RiskMatrixGroupName: 'Risk Matrix',
    SaveColorConfigurationText: 'Save',
    SettingsGroupName: 'Settings',
    ShowAllProjectInformationText: 'View all project information',
    ShowFieldExternalUsers: 'Visible to external users',
    ShowProjectDeliveriesLabel: 'Show project deliveries',
    ShowSubTextFieldLabel: 'Show sub text',
    ShowTimelineLabel: 'Show timeline',
    ShowTimelineListCommandsLabel: 'Show command line for list',
    ShowTimelineListLabel: 'Show list',
    SiteAssetsConfigurationFolder: 'SiteAssets/Konfigurasjon',
    Skip: 'Skip All',
    SkipSyncToHubLabel: "Don't sync to hub",
    StatusClosed: 'Done',
    StatusNotRelevant: 'Not applicable',
    StatusOpen: 'Open',
    StatusReportShowOnlyIconsLabel: 'Show icons only',
    StatusReportTruncateCommentsLabel: 'Truncate comments',
    StatusStillOpen: 'Still open',
    SubTextTruncateLengthFieldLabel: 'Truncate length for sub text',
    SyncProjectPropertiesErrorText:
      'An error occurred while syncing project properties to the portfolio site. For example, it could for instance be an invalid field.',
    SyncProjectPropertiesListProgressDescription: 'Updating Project Properties List',
    SyncProjectPropertiesProgressLabel: 'Synchronizes project properties to the portfolio site',
    SyncProjectPropertiesValuesProgressDescription: 'Please wait...',
    SyncProjectPropertiesValuesProgressLabel: 'Syncing properties',
    SyncPropertiesAfterPhaseChangeFieldLabel: 'Sync propertis after phase change',
    TagFieldLabel: 'Label',
    TasksLinkText: 'Go To Tasks',
    TimelineConfigurationListName: 'Timeline configuration',
    TimelineContentListName: 'Timeline content',
    ToggleUncertaintyPostActionLabel: 'Show before/after measures',
    ToggleUncertaintyPostActionOffText: 'Before measures',
    ToggleUncertaintyPostActionOnText: 'After measures',
    TypeLabel: 'Type',
    UnknownConfigurationName: 'Configuration without name',
    UnpublishedStatusReportInfo:
      'There are unpublished status reports. It is therefore not possible to create a new status report. If you are an owner of the site, you can publish or delete unpublished reports using the buttons above.',
    UseDynamicConfigurationLabel: 'Use dynamic configuration',
    UseDynamicConfigurationOffText: 'No, use manual',
    UseDynamicConfigurationOnText: 'Yes',
    UseDynamicHomepageCalloutText:
      'Here you can choose whether the phase selector should be dynamic and use separate pages for each phase. It requires pages for each phase to be created in advance. The names of the pages must be identical to the names of the phases.',
    UseDynamicHomepageFieldLabel: 'Use dynamic homepage',
    UseFramelessButtonsLabel: 'Frameless buttons',
    UsePhaseHooksCalloutText:
      "Here you can choose whether hooks should be run when changing phases. When changing the phase, a call to the url specified below will be executed. If the call requires authentication, this can be filled in under the url field. The call that is executed sends with the following parameters: 'webUrl' and 'apiKey', both of which are of type 'string'.",
    UsePhaseHooksFieldLabel: 'Use phase selector hooks',
    ViewsGroupName: 'Views',
    ViewVersionHistoryText: 'View version history',
    ViewXmlFieldLabel: 'View XML query',
    WebPartNoAccessMessage:
      'You do not have access to view this web part. <br/> <br/> You must either have access to the portfolio site or the project must be free from the portfolio site.',
    WidthFieldLabel: 'Width (pixels)',
    Yes: 'Yes',
    // Project News Web Part strings
    ProjectNewsWebPartTitle: 'Project News',
    DialogueTitle: 'Create a news article',
    CreatingNewArticleStatus: 'Creating news article...',
    NewsCreatedSuccessfully: 'News article created successfully.',
    NewsTitleLabel: 'Title',
    NewsTitlePlaceholder: 'Enter article title...',
    CreateButtonLabel: 'Create',
    CancelButtonLabel: 'Cancel',
    CreateNewsLinkLabel: '+ Create News',
    NewsCreateError: 'Something went wrong: ',
    NewsTitleRequired: 'Title is required to create a news article.',
    TemplateRequired: 'Please select a template to create the news article.',
    TemplatePlaceholder: 'Select a template',
    TemplateLabel: 'Template',
    RecentNewsTitle: 'Recent News',
    NoRecentNews: 'No recent news found.',
    ShowMoreNews: 'Show more',
    ShowLessNews: 'Show less',
    EditedLabel: 'Edited',
    MaxVisibleNewsLabel: "Number of visible news articles (before 'Show more')",
    MaxVisibleNewsDescription:
      'Set the number of news articles to display in the web part.',
    NewsFolderNameDescription: 'The name of the folder where news articles should be stored.',
    NewsFolderNameDefault: 'Project News',
    NewsFolderNameLabel: 'News Folder Name',
    FileNameRequired: 'File name is required.',
    FileNameTooLong: 'File name is too long.',
    FileNameInvalid: 'File name contains invalid characters.',
    FileNameNoLeadingTrailingSpaces: 'File name cannot have leading or trailing spaces.',
    FileNameReserved: 'File name is reserved.',
    NewsFolderError: "Failed to check or create news folder: ",
    LoadingLabel: 'Loading news articles...',
    GenericErrorMessage: 'Something went wrong. Please try again later or contact support.',
    // End of Project News Web Part strings
  }
})
