define([], function () {
  return {
    ShowSubTextFieldLabel: 'Show sub text',
    SyncPropertiesAfterPhaseChangeFieldLabel: 'Sync propertis after phase change',
    SubTextTruncateLengthFieldLabel: 'Truncate length for sub text',
    ChangePhaseText: 'Change to this phase',
    ChangingPhaseDescription: 'Changes phase to {0}',
    PleaseWaitText: 'Please wait',
    CheckpointDoneTooltip: 'Checkpoint completed',
    CheckpointNotRelevantTooltip: 'Checkpoint is not relevant',
    CheckpointNotRelevantTooltipCommentEmpty: 'You cannot set the checkpoint as \'Not Relevant\' without commenting.',
    CheckPointsMarkedAsText: 'checkpoints marked as',
    CheckpointStillOpenTooltip: 'Checkpoint is still open',
    CheckpointStillOpenTooltipCommentEmpty: 'You cannot set the checkpoint as \'Still open\' without posting a comment.',
    CloseText: 'Close',
    CommentLabel: 'Comment',
    ConfirmChangePhase: 'Do you want to change phase to {0}?',
    ConfirmPhaseDialogSubText: 'Changing the phase to {0} will change this for everyone, will you continue?',
    ConfirmPhaseDialogTitle: 'Change Phase',
    CurrentPhaseViewNameFieldLabel: 'Current phase display name',
    DocumentsListName: 'Documents',
    EditProjectInformationText: 'Edit project information',
    ShowAllProjectInformationText: 'View all project information',
    EditReportButtonText: 'Edit status',
    PublishReportButtonText: 'Publish',
    GetSnapshotButtonText: 'Open as snapshot',
    DeleteReportButtonText: 'Slett',
    EditSiteInformationText: 'Edit site information',
    ErrorText: 'There was an error loading {0}.',
    ListSectionDataErrorMessage: 'An error occurred while retrieving data for the section. Is it configured correctly? ',
    LoadingText: 'Loading {0} ...',
    MissingPropertiesMessage: 'Important project information has not been set. You should set these properties as soon as possible. ',
    MoveOn: 'Go ahead',
    NewStatusReportModalHeaderText: 'New Status Report',
    NewStatusReportTitle: 'New Status Report for {0}',
    UnpublishedStatusReportInfo: 'There are unpublished status reports. It is therefore not possible to create a new status report. If you are an owner of the site, you can publish or delete unpublished reports using the buttons above.',
    No: 'No',
    NoPropertiesMessage: 'No project information found.',
    PageReloadMessage: 'Refresh the page to get updated list views.',
    PersistedPhasePropertyBagKey: 'persisted_phase',
    PhaseChecklistLinkText: 'Go to the phase checklist',
    PhaseChecklistName: 'Phase Checklist',
    PhaseChecklistViewUrl: 'Lists/PhaseChecklist/AllItems.aspx',
    PickReportText: 'Select Report',
    SaveText: 'Save',
    RiskMatrixGroupName: 'Risk Matrix',
    ProjectStatusProjectPropertiesGroupName: 'Project Properties (Status Sections)',
    SettingsGroupName: 'Settings',
    DataGroupName: 'Data',
    LookAndFeelGroupName: 'Look and feel',
    GeneralGroupName: 'General',
    Skip: 'Skip All',
    StatusClosed: 'Done',
    StatusNotRelevant: 'Not applicable',
    StatusOpen: 'Open',
    StatusStillOpen: 'Still open',
    TasksLinkText: 'Go To Tasks',
    UpdateViewsDocumentsFieldLabel: 'Update Documents',
    UpdateViewsRisksFieldLabel: 'Update Uncertainty',
    ViewsGroupName: 'Views',
    ViewVersionHistoryText: 'View version history',
    WebPartNotConfiguredMessage: 'The web part is not configured properly. You need to set web host properties correctly. ',
    Yes: 'Yes',
    StatusReportsHeaderLabel: 'Heading',
    StatusReportsCountLabel: 'Number of reports to view',
    ProjectStatusGroupName: 'Project Status',
    NavigateToSourceUrlText: 'Go back',
    SyncProjectPropertiesText: 'Sync projectdata',
    SyncProjectPropertiesDescription: 'When you synchronize project properties, the project properties will be in the project area instead of in the portfolio area. If you have set properties in the past, you must reset them as they are not copied. ',
    ProjectPropertiesListName: 'Project Properties',
    SyncProjectPropertiesProgressLabel: 'Synchronizes project properties to the portfolio area',
    SyncProjectPropertiesSuccessText: 'Project properties were synchronized to the portfolio area. The page will reload in {0} seconds. ',
    SyncProjectPropertiesErrorText: 'An error occurred while syncing project properties to the portfolio site. For example, it could for instance be an invalid field.',
    SyncProjectPropertiesListProgressDescription: 'Updating Project Properties List',
    SyncProjectPropertiesValuesProgressLabel: 'Syncing properties',
    SyncProjectPropertiesValuesProgressDescription: 'Please wait...',
    ProjectStatusDataErrorText: 'No access. You are not allowed to view status reports. ',
    ShowFieldExternalUsers: 'Visible to external users',
    ExternalUsersConfigText: 'Configuration',
    ExternalUsersConfigInfoText: 'Here fields / columns to be displayed to external users / guests. <br /> <br /> Fields / columns to be displayed to users in the organization are configured in the portfolio area by the administrator.',
    NoLocalPropertiesListWarningText: 'You must synchronize the project properties before you can configure fields / columns to be displayed to external users / guests. <br /> <br /> This is done by clicking the \ "Sync project properties \' button.',
    WebPartNoAccessMessage: 'You do not have access to view this web part. <br/> <br/> You must either have access to the portfolio area or the project must be free from the portfolio area.',
    ProjectsListName: 'Projects',
    NoStatusReportsMessage: 'The status of the project is not yet reported. If you are an owner of the site, you can report status by clicking _New Status Report_ in the menu above. ',
    PublishedStatusReport: 'Published',
    NotPublishedStatusReport: 'Not published',
    SyncNowText: 'Sync now',
    PhaseFieldFieldLabel: 'Phase Field',
    SkipSyncToHubLabel: 'Don\'t sync to hub',
    RiskMatrix_Header_VeryCritical: 'Very Critical',
    RiskMatrix_Header_Critical: 'Critical',
    RiskMatrix_Header_High: 'High',
    RiskMatrix_Header_Insignificant: 'Insignificant',
    RiskMatrix_Header_Low: 'Low',
    RiskMatrix_Header_Medium: 'Resources',
    RiskMatrix_Header_Moderate: 'Moderate',
    RiskMatrix_Header_Serious: 'Serious',
    RiskMatrix_Header_Small: 'Small',
    RiskMatrix_Header_VeryHigh: 'Very High',
    RiskMatrix_Header_VeryLow: 'Very Low',
    RiskMatrix_Header_ExtremelyLow: 'Extremely Low',
    GtModerationStatus_Choice_Published: 'Published',
    GtModerationStatus_Choice_Draft: 'Draft',
    ListNameFieldLabel: 'List name',
    ViewXmlFieldLabel: 'View XML',
    ProbabilityFieldNameFieldLabel: 'Field name - Probability',
    ConsequenceFieldNameFieldLabel: 'Field name - Consequence',
    ProbabilityPostActionFieldNameFieldLabel: 'Field name - Probability (post action)',
    ConsequencePostActionFieldNameFieldLabel: 'Field name - Consequence (post action)',
    WidthFieldLabel: 'Width (pixels)',
    CalloutTemplateFieldLabel: 'Callout template',
    FilterText: 'Filtrer',
    PhaseLabel: 'Fase',
    SiteTitleLabel: 'Prosjekt',
    TypeLabel: 'Type',
    TagFieldLabel: 'Etikett',
    CategoryFieldLabel: 'Kategori',
    DeleteItemLabel: 'Slett',
    ProjecttimelineGroupName: 'Prosjekttidslinje',
    ProjectTimelineInfoText: 'Her listes prosjektets tidslinje med start- og sluttdato. Prosjekttidslinjen støtter også faser, delfaser og milepæler, dette opprettes og vedlikeholdes i listen under. Prosjektet vises med rød farge, faser i blått, delfaser blågrønt, og milepæler i gult. For å zoome inn/ut i tidslinje: ALT+Musehjul',
    ProjectTimelineListInfoText: 'Her listes listeelementene for prosjektet. Her kan du redigere og legge til nye elementer. Dette vil synkroniseres til listen på hubområdet. For å zoome inn/ut i tidslinje: ALT+Musehjul',
    TimelineContentListName: 'Tidslinjeinnhold',
    TimelineConfigurationListName: 'Tidslinjekonfigurasjon',
    NewItemLabel: 'Nytt element',
    EditItemLabel: 'Rediger',
    PortfolioManagerGroupName: 'Porteføljeinnsyn',
    ProjectTimelineItemInfo: '{0} - prosjektets tidsforløp',
    LastPublishedStatusreport: 'Gå til siste statusrapport',
    DiamondLabel: 'Diamant',
    BarLabel: 'Bar',
    TriangleLabel: 'Trekant',
    MilestoneLabel: 'Milepæl',
    ProjectLabel: 'Prosjekt',
    SubPhaseLabel: 'Delfase',
    CurrentPhaseLabel: 'Gjeldende fase',
    MilestoneDateLabel: 'Milepælsdato',
    StartDateLabel: 'Startdato',
    EndDateLabel: 'Sluttdato',
    BudgetTotalLabel: 'Totalbudsjett',
    CostsTotalLabel: 'Kostnader påløpt totalt',
    ShowFilterButtonLabel: 'Vis filterknapp',
    ShowTimelineLabel: 'Vis tidslinje',
    ShowInfoMessageLabel: 'Vis infomelding',
    ShowTimelineListCommandsLabel: 'Vis kommandolinje for liste',
    ShowTimelineListLabel: 'Vis liste',
    AdvancedGroupName: 'Avansert',
    UseDynamicHomepageFieldLabel: 'Bruk dynamisk hjemmeside',
    UseDynamicHomepageCalloutText: 'Her kan du velge om fasevelgeren skal være dynamisk og bruke egne sider for hver fase. Det krever at det er opprettet sider for hver fase på forhånd. Navnene på sidene må være identiske med navnene på fasene.',
    UsePhaseHooksFieldLabel: 'Bruk fasevelger hooks',
    UsePhaseHooksCalloutText: 'Her kan du velge om det skal kjøres hooks ved endring av faser. Ved endring av fase vil det bli eksekvert et kall mot url-en som er spesifisert under. Dersom kallet krever autentisering, kan dette fylles inn under url feltet. Kallet som blir eksekvert sender med følgende parametere:  \'webUrl\' og  \'apiKey\', disse er begge av typen  \'string\'.',
    HookUrlFieldLabel: 'Hook url',
    HookUrlFieldDescription: 'Url som skal kalles ved endring av fase',
    HookAuthFieldLabel: 'Hook autentisering',
    HookAuthFieldDescription: 'Autentisering for å utføre kall ved endring av fase',
    PhaseSitePageFoundDescription: 'Endring til denne fasen vil også medføre endring av forside til prosjektet.<br /><br />Side _{0}_ for fase funnet. Denne siden vil bli brukt som forside for prosjektet. Trykk **Ja** for å fortsette.',
    PhaseSitePageNotFoundDescription: 'Dynamisk forside er aktivert.<br /><br />Side _{0}_ for fase ble ikke funnet, vennligst opprett. Ved trykk på **Ja** vil ikke forside endres.',
    AdminPageLinkLabel: 'Path to Admin page',
    DefaultAdminPageLink: 'Admin.aspx',
    ConfigItemTitleFieldLabel: 'Element tittel (konfigurasjon)',
    ShowProjectDeliveriesLabel: 'Vis prosjektleveranser',
    ProjectDeliveriesGroupName: 'Prosjektleveranser (beta)',
    UseIdeaProcessingFieldLabel: 'Bruk idébehandlingsfunksjonalitet',
    UseIdeaProcessingCalloutText: 'Dersom idébehandlingsfunksjonalitet brukes for synkronisering av prosjektegenskaper, må dette feltet være aktivert for å kunne synkronisere prosjektegenskaper fra \'Prosjektdata\' listen ned til prosjektet. Dersom det ligger et element i \'Prosjektdata\' listen med samme \'Områdeadresse\', vil det dukke opp en knapp for å sykronisere prosjektegenskaper. Dersom dette ikke er tilfellet, vil det ikke dukke opp noen knapp for å synkronisere prosjektegenskaper.',
    IdeaProjectDataTitle: 'Prosjektdata',
    CancelText: 'Avbryt',
    SyncProjectModalTitle: 'Hent prosjektdata fra idé',
    SyncProjectModalSubText: 'Dersom du synkroniserer prosjektdata, vil alle prosjektegenskaper bli erstattet med prosjektegenskaper fra prosjektdata listen. Dette vil også synkroniseres til hubområdet. Dersom du vil fortsette, trykk \'Synkroniser\'.',
    IdeaProcessingTitle: 'Idébehandling',
    IdeaProcessingUrlTitle: 'Idebehandling',
    GroupLevelProject: 'Prosjekt',
    GroupLevelPortfolio: 'Portefølje'
  }
})
