declare interface IProjectWebPartsStrings {
  NewStatusPanelTitle: string
  EditStatusPanelText: string
  Aria: {
    CurrentPhaseText: string
  }
  SaveText: string
  ErrorBoundaryFallbackDescription: string
  ErrorBoundaryFallbackText: string
  UpdatingProjectPropertiesErrorText: string
  SynchronizingProjectPropertiesToPortfolioSiteErrorText: string
  UpdatingProjectPropertiesStatusText: string
  SynchronizingProjectPropertiesToPortfolioSiteStatusText: string
  UnknownConfigurationName: any
  SiteAssetsConfigurationFolder: string
  RiskMatrixConfigurationFolder: string
  ManualConfigurationNotFoundOrInvalid: stringg
  UseDynamicConfigurationOffText: string
  UseDynamicConfigurationOnText: string
  ManualConfigurationPathLabel: string
  UseDynamicConfigurationLabel: string
  PublishReportSpinnerText: string
  PublishStatusReportSectionDataWarning: string
  AdminPageLinkLabel: string
  AdvancedGroupName: string
  BarLabel: string
  CalloutTemplateFieldLabel: string
  CancelText: string
  CategoryFieldLabel: string
  ChangePhaseText: string
  ChangingPhaseDescription: string
  ChecklistCommentDescription: string
  ChecklistCommentPlaceholder: string
  CheckpointDoneTooltip: string
  CheckpointNotRelevantTooltip: string
  CheckpointNotRelevantTooltipCommentEmpty: string
  CheckPointsStatus: string
  CheckpointStillOpenTooltip: string
  CheckpointStillOpenTooltipCommentEmpty: string
  ChildProjectAdminLabel: string
  CloseText: string
  ColorPickerStrings: IColorPickerStrings
  CommentLabel: string
  ConfigItemTitleFieldLabel: string
  ConfirmChangePhase: string
  ConsequenceFieldNameFieldLabel: string
  ConsequenceHeaderFieldLabel: string
  ConsequencePostActionFieldNameFieldLabel: string
  CreateParentModalSubText: string
  CreateParentModalTitle: string
  CreateParentProjectLabel: string
  CurrentPhaseViewNameFieldLabel: string
  DataGroupName: string
  DefaultAdminPageLink: string
  DefaultGroupByLabel: string
  DefaultTimeframeEndLabel: string
  DefaultTimeframeEndValue: string
  DefaultTimeframeStartLabel: string
  DefaultTimeframeStartValue: string
  DeleteItemLabel: string
  DeleteReportButtonText: string
  DiamondLabel: string
  DocumentsListName: string
  EditItemLabel: string
  EditProjectInformationText: string
  EditReportButtonText: string
  EditSiteInformationText: string
  ExternalUsersConfigInfoText: string
  ExternalUsersConfigText: string
  GeneralGroupName: string
  GetSnapshotButtonText: string
  GtModerationStatus_Choice_Draft: string
  GtModerationStatus_Choice_Published: string
  HideActionsLabel: string
  HideAllActionsLabel: string
  HideParentProjectsLabel: string
  HideStatusReportLabel: string
  HookAuthFieldDescription: string
  HookAuthFieldLabel: string
  HookUrlFieldDescription: string
  HookUrlFieldLabel: string
  ListNameFieldLabel: string
  ListSectionDataErrorMessage: string
  LoadingText: string
  LogListName: string
  LookAndFeelGroupName: string
  ManualConfigurationNotFoundOrInvalid: string
  ManualConfigurationPathLabel: string
  MatrixColorScaleConfigLabel: string
  MatrixFullWidthLabel: string
  MatrixHeader_Critical: string
  MatrixHeader_ExtremelyHigh: string
  MatrixHeader_ExtremelyLarge: string
  MatrixHeader_ExtremelyLow: string
  MatrixHeader_High: string
  MatrixHeader_Insignificant: string
  MatrixHeader_Large: string
  MatrixHeader_Low: string
  MatrixHeader_Medium: string
  MatrixHeader_Moderate: string
  MatrixHeader_Serious: string
  MatrixHeader_Small: string
  MatrixHeader_VeryCritical: string
  MatrixHeader_VeryHigh: string
  MatrixHeader_VeryLarge: string
  MatrixHeader_VeryLow: string
  MatrixHeader_VerySmall: string
  MatrixSizeLabel: string
  MilestoneDateLabel: string
  MilestoneLabel: string
  MoveOn: string
  NavigateToSourceUrlText: string
  NewItemLabel: string
  NewStatusReportModalHeaderText: string
  NewStatusReportTitle: string
  No: string
  NoLocalPropertiesListWarningText: string
  NoPropertiesMessage: string
  NoStatusReportsMessage: string
  NotPublishedStatusReport: string
  OpportunityMatrixGroupName: string
  OverrideHeadersLabel: string
  ParentProjectsGroupName: string
  ParentProjectsHeaderDescription: string
  ParentProjectsHeaderText: string
  PhaseChecklistLinkText: string
  PhaseChecklistName: string
  PhaseChecklistViewUrl: string
  PhaseFieldFieldLabel: string
  PhaseLabel: string
  PhaseSitePageFoundDescription: string
  PhaseSitePageNotFoundDescription: string
  PhaseUseStartArrowLabel: string
  PhaseUseEndArrowLabel: string
  PleaseWaitText: string
  ProbabilityFieldNameFieldLabel: string
  ProbabilityHeaderFieldLabel: string
  ProbabilityPostActionFieldNameFieldLabel: string
  ProjectDeliveriesGroupName: string
  ProjectInformationDataFetchErrorText: string
  ProjectInformationStatusReportHeaderText: string
  ProjectInformationStatusReportHeaderDescription: string
  ProjectLabel: string
  ProjectPhasesChangePhaseError: string
  ProjectPhasesFetchDataError: string
  ProjectPropertiesListName: string
  ProjectsListName: string
  ProjectStatusDataErrorText: string
  ProjectStatusGroupName: string
  ProjectStatusProjectPropertiesGroupName: string
  ProjectTimelineErrorFetchText: string
  ProjectTimelineErrorTransformItemText: string
  ProjecttimelineGroupName: string
  ProjectTimelineItemInfo: string
  ProjectTimelineListInfoText: string
  PublishedStatusReport: string
  PublishReportButtonText: string
  PublishReportSpinnerText: string
  RedoText: string
  RevertDefaultColorConfigurationText: string
  RiskMatrixConfigurationFolder: string
  RiskMatrixGroupName: string
  SaveColorConfigurationText: string
  SettingsGroupName: string
  ShowAllProjectInformationText: string
  ShowFieldExternalUsersOffText: string
  ShowFieldExternalUsersOnText: string
  ShowFilterButtonLabel: string
  ShowInfoMessageLabel: string
  ShowProjectDeliveriesLabel: string
  ShowSubTextFieldLabel: string
  ShowTimelineLabel: string
  ShowTimelineListCommandsLabel: string
  ShowTimelineListLabel: string
  SiteAssetsConfigurationFolder: string
  Skip: string
  SkipSyncToHubLabel: string
  StatusClosed: string
  StatusNotRelevant: string
  StatusOpen: string
  StatusReportShowOnlyIconsLabel: string
  StatusReportTruncateCommentsLabel: string
  StatusStillOpen: string
  SubTextTruncateLengthFieldLabel: string
  SyncProjectPropertiesErrorText: string
  SyncProjectPropertiesListProgressDescription: string
  SyncProjectPropertiesProgressLabel: string
  SyncProjectPropertiesValuesProgressDescription: string
  SyncProjectPropertiesValuesProgressLabel: string
  SyncPropertiesAfterPhaseChangeFieldLabel: string
  TagFieldLabel: string
  TasksLinkText: string
  TimelineConfigurationListName: string
  TimelineContentListName: string
  ToggleUncertaintyPostActionLabel: string
  ToggleUncertaintyPostActionOffText: string
  ToggleUncertaintyPostActionOnText: string
  TypeLabel: string
  UnknownConfigurationName: any
  UnpublishedStatusReportInfo: string
  UseDynamicConfigurationLabel: string
  UseDynamicConfigurationOffText: string
  UseDynamicConfigurationOnText: string
  UseDynamicHomepageCalloutText: string
  UseDynamicHomepageFieldLabel: string
  UseFramelessButtonsLabel: string
  UsePhaseHooksCalloutText: string
  UsePhaseHooksFieldLabel: string
  ViewsGroupName: string
  ViewVersionHistoryText: string
  ViewXmlFieldLabel: string
  WebPartNoAccessMessage: string
  WidthFieldLabel: string
  Yes: string
}

declare module 'ProjectWebPartsStrings' {
  const strings: IProjectWebPartsStrings
  export = strings;
}
