declare interface IProjectWebPartsStrings {
  NoLocalPropertiesListWarningText: string;
  NavigateToSourceUrlText: string;
  ProjectStatusGroupName: string;
  StatusReportsHeaderLabel: string;
  StatusReportsCountLabel: string;
  AutomaticReloadFieldLabel: string;
  ChangePhaseText: string;
  ChangingPhaseDescription: string;
  PleaseWaitText: string;
  CheckpointDoneTooltip: string;
  CheckpointNotRelevantTooltip: string;
  CheckpointNotRelevantTooltipCommentEmpty: string;
  CheckPointsMarkedAsText: string;
  CheckpointStillOpenTooltip: string;
  CheckpointStillOpenTooltipCommentEmpty: string;
  CloseText: string;
  CommentLabel: string;
  ConfirmChangePhase: string;
  ConfirmPhaseChangeFieldLabel: string;
  ConfirmPhaseDialogSubText: string;
  ConfirmPhaseDialogTitle: string;
  CurrentPhaseViewNameFieldLabel: string;
  DocumentsListName: string;
  EditPropertiesText: string;
  EditReportButtonText: string;
  EditSiteInformationText: string;
  ErrorText: string;
  ListSectionDataErrorMessage: string;
  LoadingText: string;
  MissingPropertiesMessage: string;
  MoveOn: string;
  NewStatusReportModalHeaderText: string;
  NewStatusReportTitle: string;
  No: string;
  NoPropertiesMessage: string;
  PageReloadMessage: string;
  PersistedPhasePropertyBagKey: string;
  PhaseChecklistLinkText: string;
  PhaseChecklistName: string;
  PhaseChecklistViewUrl: string;
  PickReportText: string;
  ReloadTimeoutFieldLabel: string;
  SaveText: string;
  SettingsGroupName: string;
  Skip: string;
  StatusClosed: string;
  StatusNotRelevant: string;
  StatusOpen: string;
  StatusStillOpen: string;
  TasksLinkText: string;
  UpdateViewsDocumentsFieldLabel: string;
  UpdateViewsRisksFieldLabel: string;
  ViewsGroupName: string;
  ViewVersionHistoryText: string;
  WebPartNotConfiguredMessage: string;
  Yes: string;
  GeneralGroupName: string;
  SyncProjectPropertiesText: string;
  SyncProjectPropertiesDescription: string;
  ProjectPropertiesListName: string;
  SyncProjectPropertiesProgressLabel: string;
  SyncProjectPropertiesSuccessText: string;
  SyncProjectPropertiesErrorText: string;
  SyncProjectPropertiesListProgressDescription: string;
  SyncProjectPropertiesValuesProgressDescription: string;
  ProjectStatusDataErrorText: string;
  ShowFieldExternalUsers: string;
  ExternalUsersConfigText: string;
  ExternalUsersConfigInfoText: string;
  WebPartNoAccessMessage: string;
  ProjectsListName: string;
  NoStatusReportsMessage: string;
  SyncNowText: string;
  
}

declare module 'ProjectWebPartsStrings' {
  const strings: IProjectWebPartsStrings;
  export = strings;
}
