declare interface IProjectWebPartsStrings {
  ProjectStatusGroupName: string;
  ShowStatusReportsLabel: string;
  StatusReportsHeaderLabel: string;
  ReportListNameLabel: string;
  ReportCountLabel: string;
  ReportLinkUrlLabel: string;
  AutomaticReloadFieldLabel: string;
  BoxBackgroundColorLabel: string;
  BoxLayoutLabel: string;
  BoxTypeLabel: string;
  ChangePhaseText: string;
  ChangingPhaseDescription: string;
  ChangingPhaseLabel: string;
  CheckpointDoneTooltip: string;
  CheckpointNotRelevantTooltip: string;
  CheckpointNotRelevantTooltipCommentEmpty: string;
  CheckPointsMarkedAsText: string;
  CheckpointStillOpenTooltip: string;
  CheckpointStillOpenTooltipCommentEmpty: string;
  Close: string;
  CommentLabel: string;
  ConfirmChangePhase: string;
  ConfirmPhaseChangeFieldLabel: string;
  ConfirmPhaseDialogSubText: string;
  ConfirmPhaseDialogTitle: string;
  CurrentPhaseViewNameFieldLabel: string;
  DocumentsListName: string;
  EditPropertiesText: string;
  EditReportButtonText: string;
  EditSiteInformationText: string;
  ErrorText: string;
  ListSectionDataErrorMessage: string;
  LoadingText: string;
  LookAndFeelGroupName: string;
  MissingPropertiesMessage: string;
  MoveOn: string;
  NewStatusReportModalHeaderText: string;
  NewStatusReportTitle: string;
  No: string;
  NoPropertiesMessage: string;
  OverallStatusFieldName: string;
  PageReloadMessage: string;
  PersistedPhasePropertyBagKey: string;
  PhaseChecklistLinkText: string;
  PhaseChecklistName: string;
  PhaseChecklistViewUrl: string;
  PhaseSubTextPropertyFieldLabel: string;
  PickReportText: string;
  ReloadTimeoutFieldLabel: string;
  SaveText: string;
  SettingsGroupName: string;
  Skip: string;
  StatusClosed: string;
  StatusNotRelevant: string;
  StatusOpen: string;
  StatusStillOpen: string;
  TasksLinkText: string;
  UpdateViewsDocumentsFieldLabel: string;
  UpdateViewsRisksFieldLabel: string;
  ViewsGroupName: string;
  ViewVersionHistoryText: string;
  WebPartNotConfiguredMessage: string;
  Yes: string;
  GeneralGroupName: string;
}

declare module 'ProjectWebPartsStrings' {
  const strings: IProjectWebPartsStrings;
  export = strings;
}
