define([], function () {
  return {
    ErrorBoundaryFallbackText: 'Det oppstod en feil under lasting av {0}.',
    ErrorBoundaryFallbackDescription: 'Feildetaljer:',
    UpdatingProjectPropertiesErrorText: 'Det oppstod en feil under lagring av prosjektegenskaper. Vennligst prøv igjen senere.',
    SynchronizingProjectPropertiesToPortfolioSiteErrorText: 'Det oppstod en feil under synkronisering av prosjektegenskaper til porteføljeområdet. Vennligst prøv igjen senere.',
    UpdatingProjectPropertiesStatusText: 'Lagrer prosjektegenskaper...',
    SynchronizingProjectPropertiesToPortfolioSiteStatusText: 'Synkroniserer prosjektegenskaper til porteføljeområdet...',
    UrlFieldUrlPlaceholder: 'Angi en nettadresse',
    UrlFieldDescriptionPlaceholder: 'Alternativ tekst',
    UnknownConfigurationName: 'Konfigurasjon uten navn',
    ManualConfigurationNotFoundOrInvalid: 'Manuell konfigurasjon for Risikomatrise ikke funnet eller har ugyldig format.',
    RiskMatrixManualConfigurationPathDefaltValue: 'standard-konfigurasjon.json',
    RiskMatrixConfigurationFolder: 'Risikomatrise',
    SiteAssetsConfigurationFolder: 'SiteAssets/Konfigurasjon',
    UseDynamicConfigurationOffText: 'Nei, bruk manuell',
    UseDynamicConfigurationOnText: 'Ja',
    ManualConfigurationPathLabel: 'Manuell konfigurasjon',
    UseDynamicConfigurationLabel: 'Bruk dynamisk konfigurasjon',
    AdminPageLinkLabel: 'Lenke til administrasjonssiden',
    AdvancedGroupName: 'Avansert',
    BarLabel: 'Bar',
    CalloutTemplateFieldLabel: 'Mal for callout',
    CancelText: 'Avbryt',
    CategoryFieldLabel: 'Kategori',
    ChangePhaseText: 'Endre til denne fasen',
    ChangingPhaseDescription: 'Endrer fase til {0}',
    ChecklistCommentDescription: 'Kommentar er obligatorisk om sjekkpunktet skal markeres som "Ikke relevant" eller "Fortsatt åpen".',
    ChecklistCommentPlaceholder: 'Skriv inn en kommentar...',
    CheckpointDoneTooltip: 'Sjekkpunktet er utført',
    CheckpointNotRelevantTooltip: 'Sjekkpunktet er ikke relevant',
    CheckpointNotRelevantTooltipCommentEmpty: 'Du kan ikke sette sjekkpunktet som \'Ikke relevant\' uten å legge inn en kommentar.',
    CheckPointsStatus: '{0} sjekkpunkter markert som **{1}**',
    CheckpointStillOpenTooltip: 'Sjekkpunktet er fortsatt åpent',
    CheckpointStillOpenTooltipCommentEmpty: 'Du kan ikke sette sjekkpunktet som \'Fortsatt åpen\' uten å legge inn en kommentar.',
    ChildProjectAdminLabel: 'Administrer underområder',
    CloseText: 'Lukk',
    ColorPickerStrings: {
      blue: 'Blå',
      green: 'Grønn',
      hex: '',
      red: 'Rød',
    },
    CommentLabel: 'Kommentar',
    ConfigItemTitleFieldLabel: 'Elementtittel (konfigurasjon)',
    ConfirmChangePhase: 'Vil du endre fase til {0}?',
    ConsequenceFieldNameFieldLabel: 'Feltnavn - Konsekvens',
    ConsequenceHeaderFieldLabel: 'Konsekvens {0}',
    ConsequencePostActionFieldNameFieldLabel: 'Feltnavn - Konsekvens (etter tiltak)',
    CreateParentModalSubText: 'Ønsker du å gjøre om området til et overordnet område? Denne handlingen er ikke reversibel.',
    CreateParentModalTitle: 'Overordnet område',
    CreateParentProjectLabel: 'Gjør om til overordnet område',
    CurrentPhaseViewNameFieldLabel: 'Visningsnavn for gjeldende fase',
    DataGroupName: 'Data',
    DefaultAdminPageLink: 'Admin.aspx',
    DefaultGroupByLabel: 'Standard gruppering',
    DefaultTimeframeEndLabel: 'Standard sluttdato',
    DefaultTimeframeEndValue: '{0} måneder frem i tid',
    DefaultTimeframeStartLabel: 'Standard startdato',
    DefaultTimeframeStartValue: '{0} måneder tilbake i tid',
    DeleteItemLabel: 'Slett',
    DeleteReportButtonText: 'Slett',
    DiamondLabel: 'Diamant',
    DocumentsListName: 'Dokumenter',
    EditItemLabel: 'Rediger',
    EditProjectInformationText: 'Rediger prosjektinformasjon',
    EditReportButtonText: 'Rediger status',
    EditSiteInformationText: 'Rediger områdeinformasjon',
    ExternalUsersConfigInfoText: 'Her konfigueres felter/kolonner som skal vises for eksterne brukere/gjester.<br /><br />Felter/kolonner som skal vises for brukere i organisasjonen konfigureres på porteføljeområdet av administrator.',
    ExternalUsersConfigText: 'Konfigurasjon',
    GeneralGroupName: 'Generelt',
    GetSnapshotButtonText: 'Åpne som øyeblikksbilde',
    GtModerationStatus_Choice_Draft: 'Kladd',
    GtModerationStatus_Choice_Published: 'Publisert',
    HideActionsLabel: 'Skjul knapper',
    HideAllActionsLabel: 'Skjul alle knapper',
    HideParentProjectsLabel: 'Skjul overordnede prosjekter',
    HideStatusReportLabel: 'Skjul siste statusrapport',
    HookAuthFieldDescription: 'Autentisering for å utføre kall ved endring av fase',
    HookAuthFieldLabel: 'Hook autentisering',
    HookUrlFieldDescription: 'URL som skal kalles ved endring av fase',
    HookUrlFieldLabel: 'Hook URL',
    IdeaConfigurationDescription: 'Hvilken konfigurasjon skal brukes for synkronisering av ideer?',
    IdeaConfigurationTitle: 'Idekonfigurasjon',
    IdeaProjectDataTitle: 'Prosjektdata',
    ListNameFieldLabel: 'Listenavn',
    ListSectionDataErrorMessage: 'Det oppsto en feil under uthenting av data for seksjonen. Er den riktig konfigurert?',
    LoadingText: 'Laster {0}...',
    LogListName: 'Logg',
    LookAndFeelGroupName: 'Utseende og funksjonalitet',
    ManualConfigurationNotFoundOrInvalid: 'Manuell konfigurasjon for Risikomatrise ble ikke funnet eller har ugyldig format.',
    ManualConfigurationPathLabel: 'Manuell konfigurasjon',
    MatrixColorScaleConfigLabel: 'Fargekonfigurasjon',
    MatrixFullWidthLabel: 'Bruk full bredde',
    MatrixHeader_Critical: 'Kritisk',
    MatrixHeader_ExtremelyHigh: 'Ekstremt høy',
    MatrixHeader_ExtremelyLarge: 'Ekstremt stor',
    MatrixHeader_ExtremelyLow: 'Ekstremt lav',
    MatrixHeader_High: 'Høy',
    MatrixHeader_Insignificant: 'Ubetydelig',
    MatrixHeader_Large: 'Stor',
    MatrixHeader_Low: 'Lav',
    MatrixHeader_Medium: 'Middels',
    MatrixHeader_Moderate: 'Moderat',
    MatrixHeader_Serious: 'Alvorlig',
    MatrixHeader_Small: 'Liten',
    MatrixHeader_VeryCritical: 'Veldig kritisk',
    MatrixHeader_VeryHigh: 'Svært høy',
    MatrixHeader_VeryLarge: 'Veldig stor',
    MatrixHeader_VeryLow: 'Svært lav',
    MatrixHeader_VerySmall: 'Veldig liten',
    MatrixSizeLabel: 'Størrelse',
    MilestoneDateLabel: 'Milepælsdato',
    MilestoneLabel: 'Milepæl',
    MoveOn: 'Gå videre',
    NavigateToSourceUrlText: 'Gå tilbake',
    NewItemLabel: 'Nytt element',
    NewStatusReportModalHeaderText: 'Ny statusrapport',
    NewStatusReportTitle: 'Ny statusrapport for {0}',
    No: 'Nei',
    NoLocalPropertiesListWarningText: 'Du må synkronisere prosjektegenskapene før du kan konfigurere felter/kolonner som skal vises for eksterne brukere/gjester.<br /><br />Dette gjøres ved å klikke på knappen \'Synkroniser prosjektegenskaper\'.',
    NoPropertiesMessage: 'Finner ingen informasjon om prosjektet.',
    NoStatusReportsMessage: 'Det er ennå ikke rapportert status for prosjektet. Hvis du er eier av området, kan du rapportere status ved å klikke på _Ny statusrapport_ i menyen over.',
    NotPublishedStatusReport: 'Ikke publisert',
    OpportunityMatrixGroupName: 'Mulighetsmatrise',
    OverrideHeadersLabel: 'Overstyr overskrifter for {0}x{0}',
    ParentProjectsGroupName: 'Overordnede prosjekter',
    ParentProjectsHeaderText: 'Overordnede prosjekter',
    PhaseChecklistLinkText: 'Gå til fasesjekklisten',
    PhaseChecklistName: 'Fasesjekkliste',
    PhaseChecklistViewUrl: 'Lists/Fasesjekkliste/AllItems.aspx',
    PhaseFieldFieldLabel: 'Fasefelt',
    PhaseLabel: 'Fase',
    PhaseSitePageFoundDescription: 'Å endre til denne fasen vil også endre forsiden til prosjektet.<br /><br />Side _{0}_ for fase funnet. Denne siden vil bli brukt som forside for prosjektet. Trykk **Ja** for å fortsette.',
    PhaseSitePageNotFoundDescription: 'Dynamisk forside er aktivert.<br /><br />Side _{0}_ for fase ble ikke funnet, vennligst opprett. Ved trykk på **Ja** vil ikke forside endres.',
    PleaseWaitText: 'Vennligst vent',
    ProbabilityFieldNameFieldLabel: 'Feltnavn - Sannsynlighet',
    ProbabilityHeaderFieldLabel: 'Sannsynlighet {0}',
    ProbabilityPostActionFieldNameFieldLabel: 'Feltnavn - Sannsynlighet (etter tiltak)',
    ProjectDeliveriesGroupName: 'Prosjektleveranser (beta)',
    ProjectInformationDataFetchErrorText: 'En feil oppsto under henting av prosjektinformasjon.',
    ProjectInformationStatusReportHeaderText: 'Statusrapport publisert',
    ProjectLabel: 'Prosjekt',
    ProjectPhasesChangePhaseError: 'En feil oppsto under endring av fase. Vennligst prøv igjen eller kontakt en administrator.',
    ProjectPhasesFetchDataError: 'Du har ikke tilgang til å se denne webdelen.<br/><br/>Du må enten ha tilgang til porteføljeområdet, eller så må prosjektet være fristilt fra porteføljeområdet.',
    ProjectPropertiesListName: 'Prosjektegenskaper',
    ProjectsListName: 'Prosjekter',
    ProjectStatusDataErrorText: 'Ingen tilgang. Du har ikke tillatelse til å se statusrapporter.',
    ProjectStatusGroupName: 'Prosjektstatus',
    ProjectStatusProjectPropertiesGroupName: 'Prosjektegenskaper (Statusseksjoner)',
    ProjectTimelineErrorFetchText: 'Feil ved henting av prosjektets data.<br><br>Sjekk at følgende SiteId er riktig med hva som ligger i "Prosjekter" listen. <br><br>- SiteId: {0} <br> - Tittel: {1} <br><br>Feilmelding: {2}',
    ProjectTimelineErrorTransformItemText: 'Feil ved knytning av elementer til tidslinje.<br><br>Dette kan være grunnet problem med et element i "Prosjekter" listen (duplikat, slettet prosjekt), eller at et tidslinjeelement ikke har gyldig tilknytning. <br><br>- SiteId: {0} <br> - Tittel: {1} <br><br>Feilmelding: {2}',
    ProjecttimelineGroupName: 'Prosjekttidslinje',
    ProjectTimelineItemInfo: '{0} - prosjektets tidsforløp',
    ProjectTimelineListInfoText: 'Her listes listeelementene for prosjektet. Her kan du redigere og legge til nye elementer. Dette vil synkroniseres til listen på hubområdet. For å zoome inn/ut i tidslinje: ALT+Musehjul',
    PublishedStatusReport: 'Publisert',
    PublishReportButtonText: 'Publiser',
    PublishReportSpinnerText: 'Vennligst vent mens statusrapporten publiseres...',
    RedoText: 'Gjør om',
    RevertDefaultColorConfigurationText: 'Bruk standard',
    RiskMatrixConfigurationFolder: 'Risikomatrise',
    RiskMatrixGroupName: 'Risikomatrise',
    RiskMatrixManualConfigurationPathDefaltValue: 'standard-konfigurasjon.json',
    SaveColorConfigurationText: 'Lagre',
    SettingsGroupName: 'Innstillinger',
    ShowAllProjectInformationText: 'Vis all prosjektinformasjon',
    ShowFieldExternalUsersOnText: 'Synlig for eksterne brukere',
    ShowFieldExternalUsersOffText: 'Ikke synlig for eksterne brukere',
    ShowFilterButtonLabel: 'Vis filterknapp',
    ShowInfoMessageLabel: 'Vis infomelding',
    ShowProjectDeliveriesLabel: 'Vis prosjektleveranser',
    ShowSubTextFieldLabel: 'Vis fasetekst',
    ShowTimelineLabel: 'Vis tidslinje',
    ShowTimelineListCommandsLabel: 'Vis kommandolinje for liste',
    ShowTimelineListLabel: 'Vis liste',
    SiteAssetsConfigurationFolder: 'SiteAssets/Konfigurasjon',
    Skip: 'Hopp over alle',
    SkipSyncToHubLabel: 'Ikke synkroniser til hub',
    StatusClosed: 'Utført',
    StatusNotRelevant: 'Ikke relevant',
    StatusOpen: 'Åpen',
    StatusReportShowOnlyIconsLabel: 'Vis kun ikoner',
    StatusReportTruncateCommentsLabel: 'Avkort kommentarer',
    StatusStillOpen: 'Fortsatt åpen',
    SubTextTruncateLengthFieldLabel: 'Max lengde fasetekst',
    SyncProjectModalSubText: 'Dersom du synkroniserer prosjektdata, vil alle prosjektegenskaper bli erstattet med prosjektegenskaper fra prosjektdata listen. Dette vil også synkroniseres til hubområdet. Dersom du vil fortsette, trykk \'Synkroniser\'.',
    SyncProjectModalTitle: 'Hent prosjektdata fra idé',
    SyncProjectPropertiesErrorText: 'Det skjedde feil under synkronisering av prosjektegenskaper til porteføljeområdet. Det kan for eksempel være et ugyldig felt.',
    SyncProjectPropertiesListProgressDescription: 'Oppdaterer Prosjektegenskaper-listen',
    SyncProjectPropertiesProgressLabel: 'Synkroniserer prosjektegenskaper til porteføljeområdet',
    SyncProjectPropertiesText: 'Hent prosjektdata',
    SyncProjectPropertiesValuesProgressDescription: 'Vennligst vent...',
    SyncProjectPropertiesValuesProgressLabel: 'Synkroniserer egenskaper',
    SyncPropertiesAfterPhaseChangeFieldLabel: 'Synkroniser prosjektegenskaper etter faseendring',
    TagFieldLabel: 'Etikett',
    TasksLinkText: 'Gå til oppgaver',
    TimelineConfigurationListName: 'Tidslinjekonfigurasjon',
    TimelineContentListName: 'Tidslinjeinnhold',
    ToggleUncertaintyPostActionLabel: 'Vis før/etter tiltak',
    ToggleUncertaintyPostActionOffText: 'Før tiltak',
    ToggleUncertaintyPostActionOnText: 'Etter tiltak',
    TypeLabel: 'Type',
    UnknownConfigurationName: 'Konfigurasjon uten navn',
    UnpublishedStatusReportInfo: 'Det eksisterer upubliserte statusrapporter. Det er dermed ikke mulig å opprette ny statusrapport. Om du er eier på området, kan du publisere eller slette upubliserte rapporter ved å bruke knappene over etter valgt statusrapport.',
    UseDynamicConfigurationLabel: 'Bruk dynamisk konfigurasjon',
    UseDynamicConfigurationOffText: 'Nei, bruk manuell',
    UseDynamicConfigurationOnText: 'Ja',
    UseDynamicHomepageCalloutText: 'Her kan du velge om fasevelgeren skal være dynamisk og bruke egne sider for hver fase. Det krever at det er opprettet sider for hver fase på forhånd. Navnene på sidene må være identiske med navnene på fasene.',
    UseDynamicHomepageFieldLabel: 'Bruk dynamisk hjemmeside',
    UseFramelessButtonsLabel: 'Rammeløse knapper',
    UseIdeaProcessingCalloutText: 'Dersom idébehandlingsfunksjonalitet brukes for synkronisering av prosjektegenskaper, må dette feltet være aktivert for å kunne synkronisere prosjektegenskaper fra \'Prosjektdata\' listen ned til prosjektet. Dersom det ligger et element i \'Prosjektdata\' listen med samme \'Områdeadresse\', vil det dukke opp en knapp for å sykronisere prosjektegenskaper. Dersom dette ikke er tilfellet, vil det ikke dukke opp noen knapp for å synkronisere prosjektegenskaper.',
    UseIdeaProcessingFieldLabel: 'Bruk idébehandlingsfunksjonalitet',
    UsePhaseHooksCalloutText: 'Her kan du velge om det skal kjøres hooks ved endring av faser. Ved endring av fase vil det bli eksekvert et kall mot url-en som er spesifisert under. Dersom kallet krever autentisering, kan dette fylles inn under url feltet. Kallet som blir eksekvert sender med følgende parametere:  \'webUrl\' og  \'apiKey\', disse er begge av typen  \'string\'.',
    UsePhaseHooksFieldLabel: 'Bruk fasevelger hooks',
    ViewsGroupName: 'Visninger',
    ViewVersionHistoryText: 'Vis versjonshistorikk',
    ViewXmlFieldLabel: 'Vis XML spørring',
    WebPartNoAccessMessage: 'Du har ikke tilgang til å se denne webdelen.<br/><br/>Du må enten ha tilgang til porteføljeområdet, eller så må prosjektet være fristilt fra porteføljeområdet.',
    WidthFieldLabel: 'Bredde (piksler)',
    Yes: 'Ja'
  }
})
