define([], function () {
  return {
    AdminPageLinkLabel: 'Lenke til Administrasjonssiden (Etter /SitePages/)',
    AdvancedGroupName: 'Avansert',
    BarLabel: 'Bar',
    BudgetTotalLabel: 'Totalbudsjett',
    CalloutTemplateFieldLabel: 'Mal for callout',
    CancelText: 'Avbryt',
    CategoryFieldLabel: 'Kategori',
    ChangePhaseText: 'Endre til denne fasen',
    ChangingPhaseDescription: 'Endrer fase til {0}',
    ChecklistCommentDescription: 'Kommentar er obligatorisk om sjekkpunktet skal markeres som "Ikke relevant" eller "Fortsatt åpen".',
    ChecklistCommentPlaceholder: 'Skriv inn en kommentar...',
    CheckpointDoneTooltip: 'Sjekkpunktet er utført',
    CheckpointNotRelevantTooltip: 'Sjekkpunktet er ikke relevant',
    CheckpointNotRelevantTooltipCommentEmpty: 'Du kan ikke sette sjekkpunktet som \'Ikke relevant\' uten å legge inn enn kommentar.',
    CheckPointsStatus: '{0} sjekkpunkter markert som **{1}**',
    CheckpointStillOpenTooltip: 'Sjekkpunktet er forsatt åpent',
    CheckpointStillOpenTooltipCommentEmpty: 'Du kan ikke sette sjekkpunktet som \'Fortsatt åpen\' uten å legge inn enn kommentar.',
    ChildProjectAdminLabel: 'Administrer underområder',
    CloseText: 'Lukk',
    ColorPickerStrings: {
      hex: '',
      red: 'Rød',
      green: 'Grønn',
      blue: 'Blå'
    },
    CommentLabel: 'Kommentar',
    ConfigItemTitleFieldLabel: 'Element tittel (konfigurasjon)',
    ConfirmChangePhase: 'Vil du endre fase til {0}?',
    ConfirmPhaseDialogSubText: 'Endring av fasen til {0} vil endre dette for alle, vil du fortsette?',
    ConfirmPhaseDialogTitle: 'Endre fase',
    ConsequenceFieldNameFieldLabel: 'Feltnavn - Konsekvens',
    ConsequenceHeaderFieldLabel: 'Konsekvens {0}',
    ConsequencePostActionFieldNameFieldLabel: 'Feltnavn - Konsekvens (etter tiltak)',
    CostsTotalLabel: 'Kostnader påløpt totalt',
    CreateParentModalSubText: 'Ønsker du å gjøre om området til et overordnet område? Denne handlingen er ikke reversibel.',
    CreateParentModalTitle: 'Overordnet område',
    CreateParentProjectLabel: 'Gjør om til overordnet område',
    CurrentPhaseLabel: 'Gjeldende fase',
    CurrentPhaseViewNameFieldLabel: 'Visningsnavn for gjeldende fase',
    DataGroupName: 'Data',
    DefaultAdminPageLink: 'Admin.aspx',
    DefaultGroupByLabel: 'Standard gruppering',
    DefaultTimeframeEndLabel: 'Standard sluttdato',
    DefaultTimeframeEndValue: '{0} måneder frem i tid',
    DefaultTimeframeStartLabel: 'Standard starttdato',
    DefaultTimeframeStartValue: '{0} måneder tilbake i tid',
    DeleteItemLabel: 'Slett',
    DeleteReportButtonText: 'Slett',
    DiamondLabel: 'Diamant',
    DocumentsListName: 'Dokumenter',
    EditItemLabel: 'Rediger',
    EditProjectInformationText: 'Rediger prosjektinformasjon',
    EditReportButtonText: 'Rediger status',
    EditSiteInformationText: 'Rediger områdeinformasjon',
    EndDateLabel: 'Sluttdato',
    ErrorText: 'Det skjedde en feil under lasting av {0}.',
    ExternalUsersConfigInfoText: 'Her konfigueres felter/kolonner som skal vises for eksterne brukere/gjester.<br /><br />Felter/kolonner som skal vises for brukere i organisasjonen konfigureres på porteføljeområdet av administrator.',
    ExternalUsersConfigText: 'Konfigurasjon',
    FilterText: 'Filtrer',
    GeneralGroupName: 'Generelt',
    GetSnapshotButtonText: 'Åpne som øyeblikksbilde',
    GroupLevelPortfolio: 'Portefølje',
    GroupLevelProject: 'Prosjekt',
    GtModerationStatus_Choice_Draft: 'Kladd',
    GtModerationStatus_Choice_Published: 'Publisert',
    HideActionsLabel: 'Skjul knapper',
    HideAllActionsLabel: 'Skjul alle knapper',
    HideParentProjectsLabel: 'Skjul overordnede prosjekter',
    HideStatusReportLabel: 'Skjul siste statusrapport',
    HookAuthFieldDescription: 'Autentisering for å utføre kall ved endring av fase',
    HookAuthFieldLabel: 'Hook autentisering',
    HookUrlFieldDescription: 'Url som skal kalles ved endring av fase',
    HookUrlFieldLabel: 'Hook url',
    IdeaProcessingTitle: 'Idébehandling',
    IdeaProcessingUrlTitle: 'Idebehandling',
    IdeaProjectDataTitle: 'Prosjektdata',
    IdeaConfigurationTitle: 'Idékonfigurasjon',
    IdeaConfigurationDescription: 'Hvilken konfigurasjon skal brukes for synkroniser av idéer?',
    LastPublishedStatusreport: 'Gå til siste statusrapport',
    ListNameFieldLabel: 'Listenavn',
    ListSectionDataErrorMessage: 'Det skjedde en feil under uthenting av data for seksjonen. Er den riktig konfigurert?',
    LoadingText: 'Laster {0}...',
    LogListName: 'Logg',
    LookAndFeelGroupName: 'Utseende og funksjonalitet',
    MatrixColorScaleConfigLabel: 'Fargekonfigurasjon',
    MatrixFullWidthLabel: 'Bruk full bredde',
    MatrixHeader_Critical: 'Kritisk',
    MatrixHeader_ExtremelyHigh: 'Ekstremt høy',
    MatrixHeader_ExtremelyLarge: 'Ekstremt stor',
    MatrixHeader_ExtremelyLow: 'Ekstremt lav',
    MatrixHeader_High: 'Høy',
    MatrixHeader_Insignificant: 'Ubetydelig',
    MatrixHeader_Large: 'Stor',
    MatrixHeader_Low: 'Lav',
    MatrixHeader_Medium: 'Middels',
    MatrixHeader_Moderate: 'Moderat',
    MatrixHeader_Serious: 'Alvorlig',
    MatrixHeader_Small: 'Liten',
    MatrixHeader_VeryCritical: 'Veldig kritisk',
    MatrixHeader_VeryHigh: 'Svært høy',
    MatrixHeader_VeryLarge: 'Veldig stor',
    MatrixHeader_VeryLow: 'Svært lav',
    MatrixHeader_VerySmall: 'Veldig liten',
    MatrixSizeLabel: 'Størrelse',
    MilestoneDateLabel: 'Milepælsdato',
    MilestoneLabel: 'Milepæl',
    MissingPropertiesMessage: 'Viktig informasjon om prosjektet er ikke satt. Du bør sette disse egenskapene snarest.',
    MoveOn: 'Gå videre',
    NavigateToSourceUrlText: 'Gå tilbake',
    NewItemLabel: 'Nytt element',
    NewStatusReportModalHeaderText: 'Ny statusrapport',
    NewStatusReportTitle: 'Ny statusrapport for {0}',
    No: 'Nei',
    NoLocalPropertiesListWarningText: 'Du må synkronisere prosjektegenskapene før du kan konfigurere felter/kolonner som skal vises for eksterne brukere/gjester.<br /><br />Det gjøres ved å klikke på knappen \'Synkroniser prosjektegenskaper\'.',
    NoPropertiesMessage: 'Finner ingen informasjon om prosjektet.',
    NoStatusReportsMessage: 'Det er ikke rapportert status for prosjektet enda. Om du er eier på området, kan du rapportere status ved å klikke på _Ny statusrapport_ i menyen over.',
    NotPublishedStatusReport: 'Ikke publisert',
    OpportunityMatrixGroupName: 'Mulighetsmatrise',
    OverrideHeadersLabel: 'Overstyr overskrifter for {0}x{0}',
    PageReloadMessage: 'Oppdater siden for å få oppdaterte listevisninger.',
    ParentProjectsGroupName: 'Overordnede prosjekter',
    ParentProjectsHeaderText: 'Overordnede prosjekter',
    PersistedPhasePropertyBagKey: 'persisted_phase',
    PhaseChecklistLinkText: 'Gå til fasesjekklisten',
    PhaseChecklistName: 'Fasesjekkliste',
    PhaseChecklistViewUrl: 'Lists/Fasesjekkliste/AllItems.aspx',
    PhaseFieldFieldLabel: 'Fasefelt',
    PhaseLabel: 'Fase',
    PhaseSitePageFoundDescription: 'Endring til denne fasen vil også medføre endring av forside til prosjektet.<br /><br />Side _{0}_ for fase funnet. Denne siden vil bli brukt som forside for prosjektet. Trykk **Ja** for å fortsette.',
    PhaseSitePageNotFoundDescription: 'Dynamisk forside er aktivert.<br /><br />Side _{0}_ for fase ble ikke funnet, vennligst opprett. Ved trykk på **Ja** vil ikke forside endres.',
    PickReportText: 'Velg rapport',
    PleaseWaitText: 'Vennligst vent',
    PortfolioManagerGroupName: 'Porteføljeinnsyn',
    ProbabilityFieldNameFieldLabel: 'Feltnavn - Sannsynlighet',
    ProbabilityHeaderFieldLabel: 'Sannsynlighet {0}',
    ProbabilityPostActionFieldNameFieldLabel: 'Feltnavn - Sannsynlighet (etter tiltak)',
    ProjectDeliveriesGroupName: 'Prosjektleveranser (beta)',
    ProjectInformationDataFetchErrorText: 'Det skjedde en feil under uthenting av prosjektinformasjon.',
    ProjectInformationStatusReportHeaderText: 'Statusrapport publisert',
    ProjectLabel: 'Prosjekt',
    ProjectPhasesChangePhaseError: 'Det skjedde en feil under endring av fase. Vennligst prøv igjen, eller kontakt en administrator.',
    ProjectPhasesFetchDataError: 'Du har ikke tilgang til å se denne webdelen.<br/><br/>Du må enten ha tilgang til porteføljeområdet, eller så må prosjektet være fristilt fra porteføljeområdet.',
    ProjectPropertiesListName: 'Prosjektegenskaper',
    ProjectsListName: 'Prosjekter',
    ProjectStatusDataErrorText: 'Ingen tilgang. Du har ikke tillatelse til å se statusrapporter.',
    ProjectStatusGroupName: 'Prosjektstatus',
    ProjectStatusProjectPropertiesGroupName: 'Prosjektegenskaper (Statusseksjoner)',
    ProjectTimelineErrorFetchText: 'Feil ved henting av prosjektets data.<br><br>Sjekk at følgende SiteId er riktig med hva som ligger i "Prosjekter" listen. <br><br>- SiteId: {0} <br> - Tittel: {1} <br><br>Feilmelding: {2}',
    ProjectTimelineErrorTransformItemText: 'Feil ved knytning av elementer til tidslinje.<br><br>Dette kan være grunnet problem med et element i "Prosjekter" listen (duplikat, slettet prosjekt), eller at et tidslinjeelement ikke har gyldig tilknytning. <br><br>- SiteId: {0} <br> - Tittel: {1} <br><br>Feilmelding: {2}',
    ProjecttimelineGroupName: 'Prosjekttidslinje',
    ProjectTimelineInfoText: 'Her listes prosjektets tidslinje med start- og sluttdato. Prosjekttidslinjen støtter også faser, delfaser og milepæler, dette opprettes og vedlikeholdes i listen under. Prosjektet vises med rød farge, faser i blått, delfaser blågrønt, og milepæler i gult. For å zoome inn/ut i tidslinje: ALT+Musehjul',
    ProjectTimelineItemInfo: '{0} - prosjektets tidsforløp',
    ProjectTimelineListInfoText: 'Her listes listeelementene for prosjektet. Her kan du redigere og legge til nye elementer. Dette vil synkroniseres til listen på hubområdet. For å zoome inn/ut i tidslinje: ALT+Musehjul',
    PublishedStatusReport: 'Publisert',
    PublishReportButtonText: 'Publiser',
    RedoText: 'Gjør om',
    RevertDefaultColorConfigurationText: 'Bruk standard',
    RiskMatrixGroupName: 'Risikomatrise',
    SaveColorConfigurationText: 'Lagre',
    SaveText: 'Lagre',
    SettingsGroupName: 'Innstillinger',
    ShowAllProjectInformationText: 'Vis all prosjektinformasjon',
    ShowFieldExternalUsers: 'Synlig for eksterne brukere',
    ShowFilterButtonLabel: 'Vis filterknapp',
    ShowInfoMessageLabel: 'Vis infomelding',
    ShowProjectDeliveriesLabel: 'Vis prosjektleveranser',
    ShowSubTextFieldLabel: 'Vis fasetekst',
    ShowTimelineLabel: 'Vis tidslinje',
    ShowTimelineListCommandsLabel: 'Vis kommandolinje for liste',
    ShowTimelineListLabel: 'Vis liste',
    SiteTitleLabel: 'Prosjekt',
    Skip: 'Hopp over alle',
    SkipSyncToHubLabel: 'Ikke synkroniser til hub',
    StartDateLabel: 'Startdato',
    StatusClosed: 'Utført',
    StatusNotRelevant: 'Ikke relevant',
    StatusOpen: 'Åpen',
    StatusReportsHeaderLabel: 'Overskrift',
    StatusReportShowOnlyIconsLabel: 'Vis kun ikoner',
    StatusReportTruncateCommentsLabel: 'Avkort kommentarer',
    StatusStillOpen: 'Forsatt åpen',
    SubPhaseLabel: 'Delfase',
    SubTextTruncateLengthFieldLabel: 'Max lengde fasetekst',
    SyncNowText: 'Synkroniser nå',
    SyncProjectModalSubText: 'Dersom du synkroniserer prosjektdata, vil alle prosjektegenskaper bli erstattet med prosjektegenskaper fra prosjektdata listen. Dette vil også synkroniseres til hubområdet. Dersom du vil fortsette, trykk \'Synkroniser\'.',
    SyncProjectModalTitle: 'Hent prosjektdata fra idé',
    SyncProjectPropertiesDescription: 'Når du synkroniserer prosjektegenskaper vil prosjektegenskapene ligge på prosjektområdet istedenfor på porteføljeområdet. Om du har satt egenskaper tidligere, må du sette disse på nytt da disse ikke kopieres over.',
    SyncProjectPropertiesErrorText: 'Det skjedde feil under synkronisering av prosjektegenskaper til porteføljeområdet. Det kan for eksempel være et ugyldig felt.',
    SyncProjectPropertiesListProgressDescription: 'Oppdaterer Prosjektegenskaper-listen',
    SyncProjectPropertiesProgressLabel: 'Synkroniserer prosjektegenskaper til porteføljeområdet',
    SyncProjectPropertiesSuccessText: 'Prosjektegenskaper ble synkronisert til porteføljeområdet. Siden lastes på nytt om {0} sekunder.',
    SyncProjectPropertiesText: 'Hent prosjektdata',
    SyncProjectPropertiesValuesProgressDescription: 'Vennligst vent...',
    SyncProjectPropertiesValuesProgressLabel: 'Synkroniserer egenskaper',
    SyncPropertiesAfterPhaseChangeFieldLabel: 'Synkroniser prosjektegenskaper etter faseendring',
    TagFieldLabel: 'Etikett',
    TasksLinkText: 'Gå til oppgaver',
    TimelineConfigurationListName: 'Tidslinjekonfigurasjon',
    TimelineContentListName: 'Tidslinjeinnhold',
    ToggleUncertaintyPostActionLabel: 'Vis før/etter tiltak',
    ToggleUncertaintyPostActionOffText: 'Før tiltak',
    ToggleUncertaintyPostActionOnText: 'Etter tiltak',
    TriangleLabel: 'Trekant',
    TypeLabel: 'Type',
    UnpublishedStatusReportInfo: 'Det eksisterer upubliserte statusrapporter. Det er dermed ikke mulig å opprette ny statusrapport. Om du er eier på området, kan du publisere eller slette upubliserte rapporter ved å bruke knappene over etter valgt statusrapport.',
    UpdateViewsDocumentsFieldLabel: 'Opppdater Dokumenter',
    UpdateViewsRisksFieldLabel: 'Oppdater Usikkerhet',
    UseDynamicHomepageCalloutText: 'Her kan du velge om fasevelgeren skal være dynamisk og bruke egne sider for hver fase. Det krever at det er opprettet sider for hver fase på forhånd. Navnene på sidene må være identiske med navnene på fasene.',
    UseDynamicHomepageFieldLabel: 'Bruk dynamisk hjemmeside',
    UseFramelessButtonsLabel: 'Rammeløse knapper',
    UseIdeaProcessingCalloutText: 'Dersom idébehandlingsfunksjonalitet brukes for synkronisering av prosjektegenskaper, må dette feltet være aktivert for å kunne synkronisere prosjektegenskaper fra \'Prosjektdata\' listen ned til prosjektet. Dersom det ligger et element i \'Prosjektdata\' listen med samme \'Områdeadresse\', vil det dukke opp en knapp for å sykronisere prosjektegenskaper. Dersom dette ikke er tilfellet, vil det ikke dukke opp noen knapp for å synkronisere prosjektegenskaper.',
    UseIdeaProcessingFieldLabel: 'Bruk idébehandlingsfunksjonalitet',
    UsePhaseHooksCalloutText: 'Her kan du velge om det skal kjøres hooks ved endring av faser. Ved endring av fase vil det bli eksekvert et kall mot url-en som er spesifisert under. Dersom kallet krever autentisering, kan dette fylles inn under url feltet. Kallet som blir eksekvert sender med følgende parametere:  \'webUrl\' og  \'apiKey\', disse er begge av typen  \'string\'.',
    UsePhaseHooksFieldLabel: 'Bruk fasevelger hooks',
    ViewsGroupName: 'Visninger',
    ViewVersionHistoryText: 'Vis versjonshistorikk',
    ViewXmlFieldLabel: 'Spørring',
    WebPartNoAccessMessage: 'Du har ikke tilgang til å se denne webdelen.<br/><br/>Du må enten ha tilgang til porteføljeområdet, eller så må prosjektet være fristilt fra porteføljeområdet.',
    WebPartNotConfiguredMessage: 'Webdelen er ikke konfigurert riktig. Du må angi webpartegenskaper riktig.',
    WidthFieldLabel: 'Bredde (piksler)',
    Yes: 'Ja',
    PublishStatusReportSectionDataWarning: 'Prosjektstatusen ble publisert, men uten å persistere listedata. Dette kan føre til feil ved visning av statusrapporten.',
    PublishReportSpinnerText: 'Vennligst vent mens statusrapporten publiseres...'
  }
})
