define([], function () {
  return {
    DefaultGroupByLabel:'Standard gruppering',
    DefaultTimeframeStartLabel: 'Standard starttdato',
    DefaultTimeframeStartValue: '{0} måneder tilbake i tid',
    DefaultTimeframeEndLabel: 'Standard sluttdato',
    DefaultTimeframeEndValue: '{0} måneder frem i tid',
    CreateParentModalTitle: 'Overordnet område',
    CreateParentModalSubText: 'Ønsker du å gjøre om området til et overordnet område? Denne handlingen er ikke reversibel.',
    UseFramelessButtonsLabel: 'Rammeløse knapper',
    HideParentProjectsLabel: 'Skjul overordnede prosjekter',
    HideStatusReportLabel: 'Skjul siste statusrapport',
    HideActionsLabel: 'Skjul knapper',
    HideAllActionsLabel: 'Skjul alle knapper',
    ShowSubTextFieldLabel: 'Vis fasetekst',
    SyncPropertiesAfterPhaseChangeFieldLabel: 'Synkroniser prosjektegenskaper etter faseendring',
    SubTextTruncateLengthFieldLabel: 'Max lengde fasetekst',
    ChangePhaseText: 'Endre til denne fasen',
    ChangingPhaseDescription: 'Endrer fase til {0}',
    PleaseWaitText: 'Vennligst vent',
    CheckpointDoneTooltip: 'Sjekkpunktet er utført',
    CheckpointNotRelevantTooltip: 'Sjekkpunktet er ikke relevant',
    CheckpointNotRelevantTooltipCommentEmpty: 'Du kan ikke sette sjekkpunktet som \'Ikke relevant\' uten å legge inn enn kommentar.',
    CheckPointsMarkedAsText: 'sjekkpunkter markert som',
    CheckpointStillOpenTooltip: 'Sjekkpunktet er forsatt åpent',
    CheckpointStillOpenTooltipCommentEmpty: 'Du kan ikke sette sjekkpunktet som \'Fortsatt åpen\' uten å legge inn enn kommentar.',
    CloseText: 'Lukk',
    CommentLabel: 'Kommentar',
    ConfirmChangePhase: 'Vil du endre fase til {0}?',
    ConfirmPhaseDialogSubText: 'Endring av fasen til {0} vil endre dette for alle, vil du fortsette?',
    ConfirmPhaseDialogTitle: 'Endre fase',
    CurrentPhaseViewNameFieldLabel: 'Visningsnavn for gjeldende fase',
    DocumentsListName: 'Dokumenter',
    EditProjectInformationText: 'Rediger prosjektinformasjon',
    ShowAllProjectInformationText: 'Vis all prosjektinformasjon',
    ProjectInformationStatusReportHeaderText: 'Statusrapport publisert',
    EditReportButtonText: 'Rediger status',
    PublishReportButtonText: 'Publiser',
    GetSnapshotButtonText: 'Åpne som øyeblikksbilde',
    DeleteReportButtonText: 'Slett',
    EditSiteInformationText: 'Rediger områdeinformasjon',
    ErrorText: 'Det skjedde en feil under lasting av {0}.',
    ListSectionDataErrorMessage: 'Det skjedde en feil under uthenting av data for seksjonen. Er den riktig konfigurert?',
    LoadingText: 'Laster {0}...',
    MissingPropertiesMessage: 'Viktig informasjon om prosjektet er ikke satt. Du bør sette disse egenskapene snarest.',
    MoveOn: 'Gå videre',
    NewStatusReportModalHeaderText: 'Ny statusrapport',
    NewStatusReportTitle: 'Ny statusrapport for {0}',
    UnpublishedStatusReportInfo: 'Det eksisterer upubliserte statusrapporter. Det er dermed ikke mulig å opprette ny statusrapport. Om du er eier på området, kan du publisere eller slette upubliserte rapporter ved å bruke knappene over etter valgt statusrapport.',
    No: 'Nei',
    NoPropertiesMessage: 'Finner ingen informasjon om prosjektet.',
    PageReloadMessage: 'Oppdater siden for å få oppdaterte listevisninger.',
    PersistedPhasePropertyBagKey: 'persisted_phase',
    PhaseChecklistLinkText: 'Gå til fasesjekklisten',
    PhaseChecklistName: 'Fasesjekkliste',
    PhaseChecklistViewUrl: 'Lists/Fasesjekkliste/AllItems.aspx',
    PickReportText: 'Velg rapport',
    SaveText: 'Lagre',
    RiskMatrixGroupName: 'Risikomatrise',
    ProjectStatusProjectPropertiesGroupName: 'Prosjektegenskaper (Statusseksjoner)',
    SettingsGroupName: 'Innstillinger',
    DataGroupName: 'Data',
    LookAndFeelGroupName: 'Utseende og funksjonalitet',
    GeneralGroupName: 'Generelt',
    Skip: 'Hopp over alle',
    StatusClosed: 'Utført',
    StatusNotRelevant: 'Ikke relevant',
    StatusOpen: 'Åpen',
    StatusStillOpen: 'Forsatt åpen',
    TasksLinkText: 'Gå til oppgaver',
    UpdateViewsDocumentsFieldLabel: 'Opppdater Dokumenter',
    UpdateViewsRisksFieldLabel: 'Oppdater Usikkerhet',
    ViewsGroupName: 'Visninger',
    ViewVersionHistoryText: 'Vis versjonshistorikk',
    WebPartNotConfiguredMessage: 'Webdelen er ikke konfigurert riktig. Du må angi webpartegenskaper riktig.',
    Yes: 'Ja',
    StatusReportsHeaderLabel: 'Overskrift',
    StatusReportsCountLabel: 'Antal rapporter å vise',
    ProjectStatusGroupName: 'Prosjektstatus',
    NavigateToSourceUrlText: 'Gå tilbake',
    SyncProjectPropertiesText: 'Hent prosjektdata',
    SyncProjectPropertiesDescription: 'Når du synkroniserer prosjektegenskaper vil prosjektegenskapene ligge på prosjektområdet istedenfor på porteføljeområdet. Om du har satt egenskaper tidligere, må du sette disse på nytt da disse ikke kopieres over.',
    ProjectPropertiesListName: 'Prosjektegenskaper',
    SyncProjectPropertiesProgressLabel: 'Synkroniserer prosjektegenskaper til porteføljeområdet',
    SyncProjectPropertiesSuccessText: 'Prosjektegenskaper ble synkronisert til porteføljeområdet. Siden lastes på nytt om {0} sekunder.',
    SyncProjectPropertiesErrorText: 'Det skjedde feil under synkronisering av prosjektegenskaper til porteføljeområdet. Det kan for eksempel være et ugyldig felt.',
    SyncProjectPropertiesListProgressDescription: 'Oppdaterer Prosjektegenskaper-listen',
    SyncProjectPropertiesValuesProgressLabel: 'Synkroniserer egenskaper',
    SyncProjectPropertiesValuesProgressDescription: 'Vennligst vent...',
    ProjectStatusDataErrorText: 'Ingen tilgang. Du har ikke tillatelse til å se statusrapporter.',
    ShowFieldExternalUsers: 'Synlig for eksterne brukere',
    ExternalUsersConfigText: 'Konfigurasjon',
    ExternalUsersConfigInfoText: 'Her konfigueres felter/kolonner som skal vises for eksterne brukere/gjester.<br /><br />Felter/kolonner som skal vises for brukere i organisasjonen konfigureres på porteføljeområdet av administrator.',
    NoLocalPropertiesListWarningText: 'Du må synkronisere prosjektegenskapene før du kan konfigurere felter/kolonner som skal vises for eksterne brukere/gjester.<br /><br />Det gjøres ved å klikke på knappen \'Synkroniser prosjektegenskaper\'.',
    WebPartNoAccessMessage: 'Du har ikke tilgang til å se denne webdelen.<br/><br/>Du må enten ha tilgang til porteføljeområdet, eller så må prosjektet være fristilt fra porteføljeområdet.',
    ProjectsListName: 'Prosjekter',
    NoStatusReportsMessage: 'Det er ikke rapportert status for prosjektet enda. Om du er eier på området, kan du rapportere status ved å klikke på _Ny statusrapport_ i menyen over.',
    PublishedStatusReport: 'Publisert',
    NotPublishedStatusReport: 'Ikke publisert',
    SyncNowText: 'Synkroniser nå',
    PhaseFieldFieldLabel: 'Fasefelt',
    SkipSyncToHubLabel: 'Ikke synkroniser til hub',
    RiskMatrix_Header_Critical: 'Kritisk',
    RiskMatrix_Header_High: 'Høy',
    RiskMatrix_Header_Insignificant: 'Ubetydelig',
    RiskMatrix_Header_Low: 'Lav',
    RiskMatrix_Header_Medium: 'Middels',
    RiskMatrix_Header_Moderate: 'Moderat',
    RiskMatrix_Header_Serious: 'Alvorlig',
    RiskMatrix_Header_Small: 'Liten',
    RiskMatrix_Header_VeryHigh: 'Svært høy',
    RiskMatrix_Header_VeryLow: 'Svart lav',
    RiskMatrix_ViewSelectorLabel: 'Velg en visning',
    RiskMatrix_EmptyMessage: 'Det finnes ingen Risiko-elementer i den angitte visningen.',
    RiskMatrix_LoadingText: 'Laster risikomatrise...',
    RiskMatrix_ToggleElements: 'Vis før/etter tiltak',
    GtModerationStatus_Choice_Published: 'Publisert',
    GtModerationStatus_Choice_Draft: 'Kladd',
    ListNameFieldLabel: 'Listenavn',
    ViewXmlFieldLabel: 'Spørring',
    ProbabilityFieldNameFieldLabel: 'Feltnavn - Sannsynlighet',
    ConsequenceFieldNameFieldLabel: 'Feltnavn - Konsekvens',
    ProbabilityPostActionFieldNameFieldLabel: 'Feltnavn - Sannsynlighet (etter tiltak)',
    ConsequencePostActionFieldNameFieldLabel: 'Feltnavn - Konsekvens (etter tiltak)',
    WidthFieldLabel: 'Bredde (piksler)',
    HeightFieldLabel: 'Høyde (piksler)',
    CalloutTemplateFieldLabel: 'Mal for callout',
    FilterText: 'Filtrer',
    PhaseLabel: 'Fase',
    SiteTitleLabel: 'Prosjekt',
    TypeLabel: 'Type',
    TagFieldLabel: 'Etikett',
    CategoryFieldLabel: 'Kategori',
    DeleteItemLabel: 'Slett',
    ProjecttimelineGroupName: 'Prosjekttidslinje',
    ProjectTimelineInfoText: 'Her listes prosjektets tidslinje med start- og sluttdato. Prosjekttidslinjen støtter også faser, delfaser og milepæler, dette opprettes og vedlikeholdes i listen under. Prosjektet vises med rød farge, faser i blått, delfaser blågrønt, og milepæler i gult. For å zoome inn/ut i tidslinje: ALT+Musehjul',
    ProjectTimelineErrorTransformItemText: 'Feil ved knytning av elementer til tidslinje.<br><br>Dette kan være grunnet problem med et element i "Prosjekter" listen (duplikat, slettet prosjekt), eller at et tidslinjeelement ikke har gyldig tilknytning. <br><br>- SiteId: {0} <br> - Tittel: {1} <br><br>Feilmelding: {2}',
    ProjectTimelineErrorFetchText: 'Feil ved henting av prosjektets data.<br><br>Sjekk at følgende SiteId er riktig med hva som ligger i "Prosjekter" listen. <br><br>- SiteId: {0} <br> - Tittel: {1} <br><br>Feilmelding: {2}',
    ProjectTimelineListInfoText: 'Her listes listeelementene for prosjektet. Her kan du redigere og legge til nye elementer. Dette vil synkroniseres til listen på hubområdet. For å zoome inn/ut i tidslinje: ALT+Musehjul',
    TimelineContentListName: 'Tidslinjeinnhold',
    TimelineConfigurationListName: 'Tidslinjekonfigurasjon',
    NewItemLabel: 'Nytt element',
    EditItemLabel: 'Rediger',
    PortfolioManagerGroupName: 'Porteføljeinnsyn',
    ProjectTimelineItemInfo: '{0} - prosjektets tidsforløp',
    LastPublishedStatusreport: 'Gå til siste statusrapport',
    DiamondLabel: 'Diamant',
    BarLabel: 'Bar',
    TriangleLabel: 'Trekant',
    MilestoneLabel: 'Milepæl',
    ProjectLabel: 'Prosjekt',
    SubPhaseLabel: 'Delfase',
    CurrentPhaseLabel: 'Gjeldende fase',
    MilestoneDateLabel: 'Milepælsdato',
    StartDateLabel: 'Startdato',
    EndDateLabel: 'Sluttdato',
    BudgetTotalLabel: 'Totalbudsjett',
    CostsTotalLabel: 'Kostnader påløpt totalt',
    ShowFilterButtonLabel: 'Vis filterknapp',
    ShowTimelineLabel: 'Vis tidslinje',
    ShowInfoMessageLabel: 'Vis infomelding',
    ShowTimelineListCommandsLabel: 'Vis kommandolinje for liste',
    ShowTimelineListLabel: 'Vis liste',
    AdvancedGroupName: 'Avansert',
    UseDynamicHomepageFieldLabel: 'Bruk dynamisk hjemmeside',
    UseDynamicHomepageCalloutText: 'Her kan du velge om fasevelgeren skal være dynamisk og bruke egne sider for hver fase. Det krever at det er opprettet sider for hver fase på forhånd. Navnene på sidene må være identiske med navnene på fasene.',
    UsePhaseHooksFieldLabel: 'Bruk fasevelger hooks',
    UsePhaseHooksCalloutText: 'Her kan du velge om det skal kjøres hooks ved endring av faser. Ved endring av fase vil det bli eksekvert et kall mot url-en som er spesifisert under. Dersom kallet krever autentisering, kan dette fylles inn under url feltet. Kallet som blir eksekvert sender med følgende parametere:  \'webUrl\' og  \'apiKey\', disse er begge av typen  \'string\'.',
    HookUrlFieldLabel: 'Hook url',
    HookUrlFieldDescription: 'Url som skal kalles ved endring av fase',
    HookAuthFieldLabel: 'Hook autentisering',
    HookAuthFieldDescription: 'Autentisering for å utføre kall ved endring av fase',
    PhaseSitePageFoundDescription: 'Endring til denne fasen vil også medføre endring av forside til prosjektet.<br /><br />Side _{0}_ for fase funnet. Denne siden vil bli brukt som forside for prosjektet. Trykk **Ja** for å fortsette.',
    PhaseSitePageNotFoundDescription: 'Dynamisk forside er aktivert.<br /><br />Side _{0}_ for fase ble ikke funnet, vennligst opprett. Ved trykk på **Ja** vil ikke forside endres.',
    AdminPageLinkLabel: 'Lenke til Administrasjonssiden (Etter /SitePages/)',
    CreateParentProjectLabel: 'Gjør om til overordnet område',
    ChildProjectAdminLabel: 'Administrer underområder',
    DefaultAdminPageLink: 'Admin.aspx',
    ConfigItemTitleFieldLabel: 'Element tittel (konfigurasjon)',
    ShowProjectDeliveriesLabel: 'Vis prosjektleveranser',
    ProjectDeliveriesGroupName: 'Prosjektleveranser (beta)',
    UseIdeaProcessingFieldLabel: 'Bruk idébehandlingsfunksjonalitet',
    UseIdeaProcessingCalloutText: 'Dersom idébehandlingsfunksjonalitet brukes for synkronisering av prosjektegenskaper, må dette feltet være aktivert for å kunne synkronisere prosjektegenskaper fra \'Prosjektdata\' listen ned til prosjektet. Dersom det ligger et element i \'Prosjektdata\' listen med samme \'Områdeadresse\', vil det dukke opp en knapp for å sykronisere prosjektegenskaper. Dersom dette ikke er tilfellet, vil det ikke dukke opp noen knapp for å synkronisere prosjektegenskaper.',
    IdeaProjectDataTitle: 'Prosjektdata',
    CancelText: 'Avbryt',
    RedoText:'Gjør om',
    SyncProjectModalTitle: 'Hent prosjektdata fra idé',
    SyncProjectModalSubText: 'Dersom du synkroniserer prosjektdata, vil alle prosjektegenskaper bli erstattet med prosjektegenskaper fra prosjektdata listen. Dette vil også synkroniseres til hubområdet. Dersom du vil fortsette, trykk \'Synkroniser\'.',
    IdeaProcessingTitle: 'Idébehandling',
    IdeaProcessingUrlTitle: 'Idebehandling',
    GroupLevelProject: 'Prosjekt',
    GroupLevelPortfolio: 'Portefølje',
    ParentProjectsHeaderText: 'Overordnede prosjekter'
  }
})
