Set-PnPList -Identity Prosjektstatus -EnableContentTypes:$false
Set-PnPList -Identity Prosjekter -EnableContentTypes:$false
Set-PnPList -Identity Prosjektkolonnekonfigurasjon -EnableContentTypes:$false
Set-PnPList -Identity Fasesjekkliste -EnableContentTypes:$false
Set-PnPList -Identity Konfigurasjon -EnableContentTypes:$false
Set-PnPList -Identity Listeinnhold -EnableContentTypes:$false
Set-PnPList -Identity Porteføljevisninger -EnableContentTypes:$false
Set-PnPList -Identity Prosjektkolonner -EnableContentTypes:$false
Set-PnPList -Identity Ressursallokering -EnableContentTypes:$false
Set-PnPList -Identity Statusseksjoner -EnableContentTypes:$false