define([], function () {
  return {
    AdministratorLabel: 'Administrator',
    ApprovedSyncText: 'Approved and synchronized',
    HelpContentAvailableDescription: 'Open help dialog for this page',
    HelpContentAvailableLabel: 'Help available',
    HelpContentUnavailableDescription: 'This page has no help content, if you think there should be help content here, please contact your administrator',
    HelpContentUnavailableLabel: 'Help unavailable',
    IdeaProcessingListErrorMessage: 'Could not find an idea processing list, please check the idea configuration or contact the administrator.',
    IdeaProjectDataDialogBlockedTitle: 'Project data item found',
    IdeaProjectDataDialogNotApprovedMessage: 'This idea is not approved, so you cannot create project data for the idea. Wait until the idea is approved before creating project data.',
    IdeaProjectDataDialogInfoTitle: 'Linking of project data',
    LastInstallDescription: 'Here is an overview of the last installation of Prosjektportalen. At the very bottom you will find information about the latest release from GitHub.',
    LinksListDescription: 'Links to useful pages. The links can be configured here: ',
    LinksListLabel: 'Useful links',
    SiteContentsLabel: 'Site contents',
    SiteSettingsDescription: 'View all site settings for the Portfolio site',
    SiteSettingsLabel: 'Site settings',
    ActionLabel: 'Action',
    ActionLabelPlaceholder: 'Please select action...',
    AssistantButtonLabel: 'Assistant',
    AssistantDrawerTitle: 'Project Portal Assistant',
    AssistantIframeTitle: 'Assistant for Project Portal 365',
    AssistantLoadingText: 'Loading assistant...',
    AssistantSettingsTooltip: 'Settings',
    AssistantTooltipAvailable: 'Open the assistant to use artificial intelligence in Project Portal 365.',
    AssistantTooltipUnavailable: 'The assistant is not available.',
    CancelLabel: 'Cancel',
    CloseLabel: 'Close',
    CommentLabel: 'Comment',
    CommentLabelPlaceholder: 'Comment on choice...',
    ConfigurationLinkText: 'Configuration of the Prosjektportalen',
    ConfigurationDescription: 'Go to the configuration page for Prosjektportalen',
    ConfigurationLabel: 'Configuration of Prosjektportalen',
    CreateLabel: 'Create',
    HelpContentLinkText: 'Help available',
    IdeaAlreadyApproved: 'This idea has already been approved',
    IdeaProjectDataDialogBlockedMessage: 'Project data for this idea has already been created and associated.',
    IdeaProjectDataDialogTitle: 'Create project data for the idea',
    InstallChannelLabel: 'Installation channel',
    InstalledDateLabel: 'Installation date',
    InstallVersionLabel: 'Version',
    LastInstallHeaderText: 'Last installation',
    LatestGitHubReleaseDownloadButtonText: 'Download the latest release from GitHub',
    LatestGitHubReleaseIsNewerText: 'A newer version is available on GitHub',
    LatestGitHubReleaseIsOlderText: 'The version installed is newer than the latest release from GitHub',
    LatestGitHubReleaseIsSameText: 'The version installed is the latest release from GitHub',
    LatestGitHubReleaseLabel: 'Latest release from GitHub',
    LatestGitHubReleaseLinkTitle: 'See the latest release notes on GitHub',
    LatestGitHubReleaseHighlightsLabel: 'What\'s new in this version',
    LinksListText: 'Useful links',
    SeeAllInstallationsLinkText: 'See all installations',
    SetRecommendationSubtitle: 'Select recommendation for: {0}. \n\n{1}',
    SetRecommendationTitle: 'Set recommendation',
    SiteSettingsLinkText: 'Site settings',
    SubmitLabel: 'Submit',
    IdeaRegistrationIncludeString: 'Registration',
    AssistantGroupName: 'Assistant users',
    IdeaProcessingCommandTitle: 'Set recommendation',
    IdeaProcessingLinkTitle: 'Go to processing',
    IdeaRegistrationCommandTitle: 'Set recommendation',
    IdeaProjectDataCommandTitle: 'Create project data',
    FavoriteProjectsLabel: 'My favorite projects',
    FavoriteProjectsDescription: 'Quick access to projects you follow in current portfolio',
    FavoriteProjectsNoItemsMessage: 'You are not following any projects yet, go to a project and click the star "follow" to add it to favorites',
    TemplatePackageCatalogCommandTitle: 'Template package catalog',
    CatalogDrawerTitle: 'Template package catalog',
    CatalogSubtitle: 'Browse template packages from the central template store. Copy to your installation or make available as a cloud template.',
    CatalogUserGuideLinkText: 'See user guide',
    CatalogCloseAria: 'Close',
    CatalogLoadingText: 'Loading catalog...',
    CatalogSearchPlaceholder: 'Search the template package catalog',
    CatalogFilterTypeLabel: 'Type',
    CatalogFilterCategoryLabel: 'Category',
    CatalogFilterStatusLabel: 'Status',
    CatalogFilterAllOption: 'All',
    CatalogClearFiltersText: 'Clear filters',
    CatalogResultCount: '{0} packages',
    CatalogSortLabel: 'Sorted by',
    CatalogSortNewest: 'Newest',
    CatalogSortName: 'Name (A-Z)',
    CatalogViewGrid: 'Grid view',
    CatalogViewList: 'List view',
    CatalogTypeTemplate: 'Template',
    CatalogTypeExtension: 'Extension',
    CatalogTypeContent: 'Content',
    CatalogStatusLocal: 'Local',
    CatalogStatusImported: 'Imported',
    CatalogStatusCentral: 'Central',
    CatalogStatusUpdate: 'Update available',
    CatalogBadgeImported: 'Imported',
    CatalogBadgeCentral: 'Central',
    CatalogBadgeUpdate: 'Update!',
    CatalogCardByAuthor: 'By {0}',
    CatalogCardPublished: 'Published {0}',
    CatalogEmptyTitle: 'No packages found',
    CatalogEmptyDescription: 'Try adjusting your search or filters.',
    CatalogPaginationText: 'Showing {0}-{1} of {2}',
    CatalogPaginationPrevious: 'Previous',
    CatalogPaginationNext: 'Next',
    CatalogDetailsEmptyText: 'Select a package to see details.',
    CatalogContentSummaryTitle: 'Package content',
    CatalogContentSummaryUnavailable: 'No content information is available for this package.',
    CatalogScreenshotsHeading: 'Screenshots',
    CatalogScreenshotCounter: '{0} / {1}',
    CatalogScreenshotPrevious: 'Previous',
    CatalogScreenshotNext: 'Next',
    CatalogScreenshotZoom: 'Open full size',
    CatalogScreenshotClose: 'Close',
    CatalogScreenshotAlt: 'Screenshot {0} of {1}',
    CatalogScreenshotError: 'Could not load the screenshot.',
    CatalogContentStandardContent: 'Standard content',
    CatalogContentLists: 'Lists',
    CatalogContentContentTypes: 'Content types',
    CatalogContentSiteFields: 'Site columns',
    CatalogContentFieldFallback: 'Field',
    CatalogContentTaxonomy: 'Taxonomy',
    CatalogContentTermSets: 'Term sets',
    CatalogContentExtensions: 'Project extensions',
    CatalogContentFiles: 'Files',
    CatalogShowDetails: 'Show details',
    CatalogHideDetails: 'Hide details',
    CatalogHistoryTitle: 'History',
    CatalogHistoryUnavailable: 'No version history available.',
    CatalogChangelogLinkText: 'See changelog',
    CatalogBackToListText: 'Back to list',
    CatalogActionImport: 'Copy to my installation',
    CatalogActionPublishCentral: 'Make available as cloud template',
    CatalogActionUpdate: 'Update to v{0}',
    CatalogActionRemove: 'Remove',
    CatalogStepDownload: 'Downloading .pppkg',
    CatalogStepUnzip: 'Extracting package',
    CatalogStepValidateManifest: 'Validating manifest',
    CatalogStepCheckVersion: 'Checking version',
    CatalogStepProvisionHub: 'Provisioning hub',
    CatalogStepTaxonomy: 'Provisioning taxonomy',
    CatalogStepStoreProjectTemplate: 'Storing project template',
    CatalogStepExtensions: 'Adding to Project Extensions',
    CatalogStepContent: 'Standard content',
    CatalogStepListContent: 'Adding to List Content',
    CatalogStepListContentDetail: '{0} list content config(s) added',
    CatalogStepUpdateTemplateOptions: 'Updating template options',
    CatalogStepSkippedFeatureFlag: 'Skipped (feature flag off)',
    CatalogInstallSuccessTitle: 'Package imported',
    CatalogInstallSuccessText: 'The template is now available in the setup wizard.',
    CatalogInstallErrorTitle: 'Import failed',
    CatalogPublishSuccessText: 'The cloud template is now available in the setup wizard.',
    CatalogPublishErrorText: 'Could not make the cloud template available.',
    CatalogRemoveSuccessText: 'The template was removed.',
    CatalogRemoveErrorText: 'Could not remove the template.',
    CatalogLoadErrorTitle: 'Could not load the catalog',
    CatalogLoadErrorText: 'Check your network connection and try again.',
    CatalogRetryText: 'Try again',
    CatalogHistoryError: 'Could not load version history.',
    CatalogContentSummaryError: 'Could not load content overview.',
    CatalogInstallErrorPartialNote: 'Some changes may already have been applied. See the steps above for what completed.',
    CatalogFilterLanguageLabel: 'Language',
    CatalogFilterLanguageTooltip: 'Filter by available language',
    CatalogFilterCompatibleOnly: 'Compatible only',
    CatalogFilterCompatibleOnlyTooltip: 'Show only packages compatible with your Prosjektportalen version',
    CatalogNoResultsTitle: 'No matches',
    CatalogNoResultsDescription: 'No packages match your filters. Adjust or clear them.',
    CatalogClearFiltersCount: 'Clear filters ({0})',
    CatalogMinVersionError: 'This template package requires Prosjektportalen {0}. Upgrade Prosjektportalen before importing this template.',
    CatalogPermissionError: 'You do not have permission to provision to the hub site.',
    CatalogTaxonomyPermissionBlocked: 'This template package provisions taxonomy (term sets), which requires write access to the term store. You do not have that access, so the installation was stopped to avoid a partial result.',
    CatalogCloseTooltip: 'Close the catalog',
    CatalogFilterTypeTooltip: 'Filter by package type',
    CatalogFilterCategoryTooltip: 'Filter by category (derived from tags)',
    CatalogFilterStatusTooltip: 'Filter by installation status',
    CatalogSortTooltip: 'Change sort order',
    CatalogClearFiltersTooltip: 'Reset search and all filters',
    CatalogBadgeImportedTooltip: 'Copied to your installation',
    CatalogBadgeCentralTooltip: 'Published as a cloud template',
    CatalogBadgeUpdateTooltip: 'A newer version is available',
    CatalogActionImportTooltip: 'Download, provision to the hub site and add to Template Options',
    CatalogActionUpdateTooltip: 'Fetch and install the latest version',
    CatalogActionPublishCentralTooltip: 'Register as a cloud template without local provisioning',
    CatalogActionRemoveTooltip: 'Remove this template package from Template Options',
    CatalogRemoveConfirmTitle: 'Remove the template?',
    CatalogRemoveConfirmText:
      'Remove "{0}" from Template Options? It will disappear from the setup wizard. Content already provisioned on the hub is left untouched, and you can add the template again from the catalog later.',
    CatalogRemoveConfirmButton: 'Remove',
    CatalogTagFilterTooltip: 'Show all tagged "{0}"',
    CatalogContentCountTooltip: '{0} item(s)',
    CatalogStepStatusRunning: 'In progress',
    CatalogStepStatusDone: 'Completed',
    CatalogStepStatusError: 'Failed',
    CatalogStepStatusSkipped: 'Skipped',
    CatalogStepStatusPending: 'Pending',
    CatalogActionAddExtension: 'Add as project extension',
    CatalogActionUpdateExtension: 'Update extension to v{0}',
    CatalogActionAddExtensionTooltip:
      'Download the extension and add it to the Project Extensions library on the hub',
    CatalogExtensionInfo:
      'The extension is added to the Project Extensions library. Nothing is created in Template Options — you can later link the extension to a template there yourself.',
    CatalogStepExtensionsDetail: '{0} extension(s) added',
    CatalogInstallSuccessTitleExtension: 'Extension added',
    CatalogInstallSuccessTextExtension:
      'The extension was added to the Project Extensions library and can be selected in the setup wizard.',
    CatalogPreviewTooltip: 'Preview content',
    CatalogPreviewError: 'Could not load the content.',
    CatalogPreviewCopy: 'Copy',
    CatalogPreviewCopied: 'Copied!',
    CatalogRequiresVersion: 'Requires Prosjektportalen {0}',
    CatalogRequiresPP: 'Prosjektportalen {0}+',
    CatalogRequiresPPTooltip: 'This template targets Prosjektportalen {0} or later.',
    CatalogRequiresBestillingsportalen: 'Bestillingsportalen',
    CatalogRequiresBestillingsportalenTooltip:
      'Requires Bestillingsportalen to be installed for full use of the template.',
    CatalogRequiresEntra: 'Microsoft Azure',
    CatalogRequiresEntraTooltip:
      'Requires Microsoft Azure resources (e.g. app registrations and permissions) to be set up for full use of the template.',
    CatalogIncompatibleTitle: 'Not compatible with your version',
    CatalogIncompatibleText:
      'This template package requires Prosjektportalen {0}, but you have {1}. Upgrade Prosjektportalen to use it.',
    CatalogBadgeLocal: 'Exists locally',
    CatalogBadgeLocalTooltip:
      'This extension already exists in your installation but was not installed from the catalog.',
    CatalogActionReplaceExtension: 'Replace with catalog version',
    CatalogReplaceConfirmTitle: 'Replace existing extension?',
    CatalogReplaceConfirmText:
      'The extension "{0}" already exists in the Project Extensions library and was not installed from the catalog. If you continue, it will be replaced with the catalog version (v{1}) and any local customizations will be lost.',
    CatalogReplaceConfirmButton: 'Replace',
    CatalogPublishCloudWarningTitle: 'Make available as cloud template?',
    CatalogPublishCloudWarningText:
      'The template "{0}" requires hub content (e.g. a content type bound to the Projects list) that cannot be set up from a cloud template. Extensions and list content will work, but the hub content is skipped when the template is used as a cloud template. Continue anyway?',
    CatalogPublishCloudWarningConfirm: 'Make available anyway',
    CatalogStepCheckCompatibility: 'Checking compatibility',
    CatalogStepCheckCompatibilityDetail: '{0} conflict(s) found',
    CatalogImportCancelled: 'The import was cancelled',
    CatalogCompatibilityTitle: 'Compatibility check',
    CatalogCompatibilityIntro:
      'The following conflicts were found against what already exists in your installation. You can cancel and fix them manually, or continue — items will be overwritten or skipped (when overwrite is not possible).',
    CatalogCompatibilityContinue: 'Continue anyway',
    CatalogResolutionOverwrite: 'Overwritten',
    CatalogResolutionSkip: 'Skipped',
    CatalogResolutionBlocked: 'Blocked',
    CatalogConflictContentType:
      'The content type "{0}" uses an ID already owned by "{1}". It is skipped so the existing one is left unchanged.',
    CatalogConflictFieldRef:
      'The content type "{0}" references the field "{1}" which does not exist on the hub. The content type is skipped.',
    CatalogConflictSiteField:
      'The site column "{0}" already exists with a different ID. Its properties are updated, but the ID is kept.',
    CatalogConflictSiteFieldType:
      'The site column "{0}" already exists with a different type ({1}). Updating it may fail.',
    CatalogConflictSiteFieldReused:
      'The field ID of "{0}" is already used by the column "{1}". The column cannot be added and is skipped.',
    CatalogConflictListField:
      'The list column "{0}" in the list "{1}" has an ID that already exists. It would be deleted and recreated (data may be lost), so it is skipped.',
    CatalogConflictListView: 'The view "{0}" in the list "{1}" already exists and will be overwritten.',
    CatalogConflictList: 'The list "{0}" will have its existing content types removed.',
    CatalogConflictExtension: 'The project extension "{0}" already exists and will be overwritten.',
    CatalogConflictTaxonomy:
      'The term set "{0}" already exists in the term store with the name "{1}". The existing one is kept.',
    CatalogLanguagesTooltip: 'Available languages',
    CatalogLanguageNorwegian: 'Norwegian',
    CatalogLanguageEnglish: 'English',
  }
})
