define([], function () {
  return {
    AdministratorLabel: 'Administrator',
    ApprovedSyncText: 'Approved and synchronized',
    HelpContentAvailableDescription: 'Open help dialog for this page',
    HelpContentAvailableLabel: 'Help available',
    HelpContentUnavailableDescription: 'This page has no help content, if you think there should be help content here, please contact your administrator',
    HelpContentUnavailableLabel: 'Help unavailable',
    IdeaProcessingListErrorMessage: 'Could not find an idea processing list, please check the idea configuration or contact the administrator.',
    IdeaProjectDataDialogBlockedTitle: 'Project data item found',
    IdeaProjectDataDialogNotApprovedMessage: 'This idea is not approved, so you cannot create project data for the idea. Wait until the idea is approved before creating project data.',
    IdeaProjectDataDialogInfoTitle: 'Linking of project data',
    LastInstallDescription: 'Here is an overview of the last installation of Prosjektportalen. At the very bottom you will find information about the latest release from GitHub.',
    LinksListDescription: 'Links to useful pages. The links can be configured here: ',
    LinksListLabel: 'Useful links',
    SiteSettingsDescription: 'View all site settings for the Portfolio site',
    SiteSettingsLabel: 'Site settings',
    ActionLabel: 'Action',
    ActionLabelPlaceholder: 'Please select action...',
    AssistantButtonLabel: 'Assistant',
    AssistantDrawerTitle: 'Project Portal Assistant',
    AssistantIframeTitle: 'Assistant for Project Portal 365',
    AssistantLoadingText: 'Loading assistant...',
    AssistantSettingsTooltip: 'Settings',
    AssistantTooltipAvailable: 'Open the assistant to use artificial intelligence in Project Portal 365.',
    AssistantTooltipUnavailable: 'The assistant is not available.',
    CancelLabel: 'Cancel',
    CloseLabel: 'Close',
    CommentLabel: 'Comment',
    CommentLabelPlaceholder: 'Comment on choice...',
    ConfigurationLinkText: 'Configuration of the Prosjektportalen',
    ConfigurationDescription: 'Go to the configuration page for Prosjektportalen',
    ConfigurationLabel: 'Configuration of Prosjektportalen',
    CreateLabel: 'Create',
    HelpContentLinkText: 'Help available',
    HelpContentListName: 'Hjelpeinnhold',
    IdeaAlreadyApproved: 'This idea has already been approved',
    IdeaConfigurationTitle: 'Idékonfigurasjon',
    IdeaProcessorsSiteGroup: 'Idebehandlere',
    IdeaProjectDataDialogBlockedMessage: 'Project data for this idea has already been created and associated.',
    IdeaProjectDataDialogTitle: 'Create project data for the idea',
    IdeaProjectDataTitle: 'Prosjektdata',
    InstallChannelLabel: 'Installation channel',
    InstalledDateLabel: 'Installation date',
    InstallVersionLabel: 'Version',
    LastInstallHeaderText: 'Last installation',
    LatestGitHubReleaseDownloadButtonText: 'Download the latest release from GitHub',
    LatestGitHubReleaseIsNewerText: 'A newer version is available on GitHub',
    LatestGitHubReleaseIsOlderText: 'The version installed is newer than the latest release from GitHub',
    LatestGitHubReleaseIsSameText: 'The version installed is the latest release from GitHub',
    LatestGitHubReleaseLabel: 'Latest release from GitHub',
    LatestGitHubReleaseLinkTitle: 'See the latest release on GitHub',
    LinksListText: 'Useful links',
    SeeAllInstallationsLinkText: 'See all installations',
    SetRecommendationSubtitle: 'Select recommendation for: {0}. \n\n{1}',
    SetRecommendationTitle: 'Set recommendation',
    SiteSettingsLinkText: 'Site settings',
    SubmitLabel: 'Submit'
  }
})
