declare interface IPortfolioExtensionsStrings {
  ActionLabel: string
  ActionLabelPlaceholder: string
  AdministratorLabel: string
  ApprovedSyncText: string
  AssistantButtonLabel: string
  AssistantDrawerTitle: string
  AssistantIframeTitle: string
  AssistantLoadingText: string
  AssistantSettingsTooltip: string
  AssistantTooltipAvailable: string
  AssistantTooltipUnavailable: string
  AssistantGroupName: string
  CancelLabel: string
  CloseLabel: string
  CommentLabel: string
  CommentLabelPlaceholder: string
  ConfigurationDescription: string
  ConfigurationLabel: string
  CreateLabel: string
  HelpContentAvailableDescription: string
  HelpContentAvailableLabel: string
  HelpContentUnavailableDescription: string
  HelpContentUnavailableLabel: string
  IdeaAlreadyApproved: string
  IdeaProcessingListErrorMessage: string
  IdeaProjectDataDialogBlockedTitle: string
  IdeaProjectDataDialogBlockedMessage: string
  IdeaProjectDataDialogNotApprovedMessage: string
  IdeaProjectDataDialogInfoTitle: string
  IdeaProjectDataDialogTitle: string
  InstallChannelLabel: string
  InstalledDateLabel: string
  InstallVersionLabel: string
  LastInstallHeaderText: string
  LastInstallDescription: string
  LatestGitHubReleaseDownloadButtonText: string
  LatestGitHubReleaseIsNewerText: string
  LatestGitHubReleaseIsOlderText: string
  LatestGitHubReleaseIsSameText: string
  LatestGitHubReleaseLabel: string
  LatestGitHubReleaseLinkTitle: string
  LatestGitHubReleaseHighlightsLabel: string
  LinksListDescription: string
  LinksListLabel: string
  SeeAllInstallationsLinkText: string
  SetRecommendationSubtitle: string
  SetRecommendationTitle: string
  SiteContentsLabel: string
  SiteSettingsDescription: string
  SiteSettingsLabel: string
  SubmitLabel: string
  IdeaRegistrationIncludeString: string
  IdeaProcessingCommandTitle: string
  IdeaProcessingLinkTitle: string
  IdeaRegistrationCommandTitle: string
  IdeaProjectDataCommandTitle: string
  FavoriteProjectsLabel: string
  FavoriteProjectsDescription: string
  FavoriteProjectsNoItemsMessage: string
  TemplatePackageCatalogCommandTitle: string
  CatalogDrawerTitle: string
  CatalogSubtitle: string
  CatalogUserGuideLinkText: string
  CatalogCloseAria: string
  CatalogLoadingText: string
  CatalogSearchPlaceholder: string
  CatalogFilterTypeLabel: string
  CatalogFilterCategoryLabel: string
  CatalogFilterStatusLabel: string
  CatalogFilterAllOption: string
  CatalogClearFiltersText: string
  CatalogResultCount: string
  CatalogSortLabel: string
  CatalogSortNewest: string
  CatalogSortName: string
  CatalogViewGrid: string
  CatalogViewList: string
  CatalogTypeTemplate: string
  CatalogTypeExtension: string
  CatalogTypeContent: string
  CatalogStatusLocal: string
  CatalogStatusImported: string
  CatalogStatusCentral: string
  CatalogStatusUpdate: string
  CatalogBadgeImported: string
  CatalogBadgeCentral: string
  CatalogBadgeUpdate: string
  CatalogCardByAuthor: string
  CatalogCardPublished: string
  CatalogEmptyTitle: string
  CatalogEmptyDescription: string
  CatalogPaginationText: string
  CatalogPaginationPrevious: string
  CatalogPaginationNext: string
  CatalogDetailsEmptyText: string
  CatalogContentSummaryTitle: string
  CatalogContentSummaryUnavailable: string
  CatalogScreenshotsHeading: string
  CatalogScreenshotCounter: string
  CatalogScreenshotPrevious: string
  CatalogScreenshotNext: string
  CatalogScreenshotZoom: string
  CatalogScreenshotClose: string
  CatalogScreenshotAlt: string
  CatalogScreenshotError: string
  CatalogContentStandardContent: string
  CatalogContentLists: string
  CatalogContentContentTypes: string
  CatalogContentSiteFields: string
  CatalogContentFieldFallback: string
  CatalogContentTaxonomy: string
  CatalogContentTermSets: string
  CatalogContentExtensions: string
  CatalogContentFiles: string
  CatalogShowDetails: string
  CatalogHideDetails: string
  CatalogHistoryTitle: string
  CatalogHistoryUnavailable: string
  CatalogChangelogLinkText: string
  CatalogBackToListText: string
  CatalogActionImport: string
  CatalogActionPublishCentral: string
  CatalogActionUpdate: string
  CatalogActionRemove: string
  CatalogStepDownload: string
  CatalogStepUnzip: string
  CatalogStepValidateManifest: string
  CatalogStepCheckVersion: string
  CatalogStepProvisionHub: string
  CatalogStepTaxonomy: string
  CatalogStepStoreProjectTemplate: string
  CatalogStepExtensions: string
  CatalogStepContent: string
  CatalogStepListContent: string
  CatalogStepListContentDetail: string
  CatalogStepUpdateTemplateOptions: string
  CatalogStepSkippedFeatureFlag: string
  CatalogInstallSuccessTitle: string
  CatalogInstallSuccessText: string
  CatalogInstallErrorTitle: string
  CatalogPublishSuccessText: string
  CatalogPublishErrorText: string
  CatalogRemoveSuccessText: string
  CatalogRemoveErrorText: string
  CatalogLoadErrorTitle: string
  CatalogLoadErrorText: string
  CatalogRetryText: string
  CatalogHistoryError: string
  CatalogContentSummaryError: string
  CatalogInstallErrorPartialNote: string
  CatalogFilterLanguageLabel: string
  CatalogFilterLanguageTooltip: string
  CatalogFilterCompatibleOnly: string
  CatalogFilterCompatibleOnlyTooltip: string
  CatalogNoResultsTitle: string
  CatalogNoResultsDescription: string
  CatalogClearFiltersCount: string
  CatalogMinVersionError: string
  CatalogPermissionError: string
  CatalogTaxonomyPermissionBlocked: string
  CatalogCloseTooltip: string
  CatalogFilterTypeTooltip: string
  CatalogFilterCategoryTooltip: string
  CatalogFilterStatusTooltip: string
  CatalogSortTooltip: string
  CatalogClearFiltersTooltip: string
  CatalogBadgeImportedTooltip: string
  CatalogBadgeCentralTooltip: string
  CatalogBadgeUpdateTooltip: string
  CatalogActionImportTooltip: string
  CatalogActionUpdateTooltip: string
  CatalogActionPublishCentralTooltip: string
  CatalogActionRemoveTooltip: string
  CatalogRemoveConfirmTitle: string
  CatalogRemoveConfirmText: string
  CatalogRemoveConfirmButton: string
  CatalogTagFilterTooltip: string
  CatalogContentCountTooltip: string
  CatalogStepStatusRunning: string
  CatalogStepStatusDone: string
  CatalogStepStatusError: string
  CatalogStepStatusSkipped: string
  CatalogStepStatusPending: string
  CatalogActionAddExtension: string
  CatalogActionUpdateExtension: string
  CatalogActionAddExtensionTooltip: string
  CatalogExtensionInfo: string
  CatalogStepExtensionsDetail: string
  CatalogInstallSuccessTitleExtension: string
  CatalogInstallSuccessTextExtension: string
  CatalogPreviewTooltip: string
  CatalogPreviewError: string
  CatalogPreviewCopy: string
  CatalogPreviewCopied: string
  CatalogRequiresVersion: string
  CatalogRequiresPP: string
  CatalogRequiresPPTooltip: string
  CatalogRequiresBestillingsportalen: string
  CatalogRequiresBestillingsportalenTooltip: string
  CatalogRequiresEntra: string
  CatalogRequiresEntraTooltip: string
  CatalogIncompatibleTitle: string
  CatalogIncompatibleText: string
  CatalogBadgeLocal: string
  CatalogBadgeLocalTooltip: string
  CatalogActionReplaceExtension: string
  CatalogReplaceConfirmTitle: string
  CatalogReplaceConfirmText: string
  CatalogReplaceConfirmButton: string
  CatalogPublishCloudWarningTitle: string
  CatalogPublishCloudWarningText: string
  CatalogPublishCloudWarningConfirm: string
  CatalogStepCheckCompatibility: string
  CatalogStepCheckCompatibilityDetail: string
  CatalogImportCancelled: string
  CatalogCompatibilityTitle: string
  CatalogCompatibilityIntro: string
  CatalogCompatibilityContinue: string
  CatalogResolutionOverwrite: string
  CatalogResolutionSkip: string
  CatalogResolutionBlocked: string
  CatalogConflictContentType: string
  CatalogConflictFieldRef: string
  CatalogConflictSiteField: string
  CatalogConflictSiteFieldType: string
  CatalogConflictSiteFieldReused: string
  CatalogConflictListField: string
  CatalogConflictListView: string
  CatalogConflictList: string
  CatalogConflictExtension: string
  CatalogConflictTaxonomy: string
  CatalogLanguagesTooltip: string
  CatalogLanguageNorwegian: string
  CatalogLanguageEnglish: string
}

declare module 'PortfolioExtensionsStrings' {
  const strings: IPortfolioExtensionsStrings;
  export = strings;
}
