define([], function () {
  return {
    ActionLabel: 'Handling',
    ActionLabelPlaceholder: 'Vennligst velg en handling...',
    AdministratorLabel: 'Administrator',
    ApprovedSyncText: 'Godkjent og synkronisert',
    CancelLabel: 'Avbryt',
    CloseLabel: 'Lukk',
    CommentLabel: 'Kommentar',
    CommentLabelPlaceholder: 'Kommentar til valg...',
    ConfigurationDescription: 'Gå til konfigurasjonssiden for Prosjektportalen',
    ConfigurationLabel: 'Konfigurasjon av Prosjektportalen',
    CreateLabel: 'Opprett',
    HelpContentAvailableDescription: 'Åpne hjelpedialog for denne siden',
    HelpContentAvailableLabel: 'Hjelp tilgjengelig',
    HelpContentUnavailableDescription: 'Denne siden har ingen hjelpeinnhold, dersom du mener det burde vært hjelpeinnhold her, vennligst kontakt din administrator',
    HelpContentUnavailableLabel: 'Hjelp utilgjengelig',
    HelpContentListName: 'Hjelpeinnhold',
    IdeaAlreadyApproved: 'Denne ideen er allerede godkjent',
    IdeaConfigurationTitle: 'Idékonfigurasjon',
    IdeaProcessingListErrorMessage: 'Fant ikke en idébehandlingsliste, vennligst sjekk idékonfigurasjonen eller kontakt administrator.',
    IdeaProcessorsSiteGroup: 'Idebehandlere',
    IdeaProjectDataDialogBlockedTitle: 'Prosjektdata element funnet',
    IdeaProjectDataDialogBlockedMessage: 'Det er allerede opprettet og tilknyttet prosjektdata for denne ideen.',
    IdeaProjectDataDialogNotApprovedMessage: 'Denne ideen er ikke godkjent, du kan dermed ikke opprette prosjektdata for ideen. Vent til ideen er godkjent før du oppretter prosjektdata.',
    IdeaProjectDataDialogInfoTitle: 'Tilknytning av prosjektdata',
    IdeaProjectDataDialogTitle: 'Opprett prosjektdata for ideen',
    IdeaProjectDataTitle: 'Prosjektdata',
    InstallationLogListName: 'Installasjonslogg',
    InstallChannelLabel: 'Installasjonskanal',
    InstalledDateLabel: 'Installasjonsdato',
    InstallVersionLabel: 'Versjon',
    LastInstallHeaderText: 'Siste installasjon',
    LastInstallDescription: 'Her er en oversikt over siste installasjon av Prosjektportalen. Helt nederst finner du informasjon om siste release fra GitHub.',
    LatestGitHubReleaseDownloadButtonText: 'Last ned siste release fra GitHub',
    LatestGitHubReleaseIsNewerText: 'En nyere versjon er tilgjengelig på GitHub',
    LatestGitHubReleaseIsOlderText: 'Versjonen som er installert er nyere enn siste release fra GitHub',
    LatestGitHubReleaseIsSameText: 'Versjonen som er installert er siste release fra GitHub',
    LatestGitHubReleaseLabel: 'Siste release fra GitHub',
    LatestGitHubReleaseLinkTitle: 'Se siste release på GitHub',
    LinksListName: 'Lenker',
    LinksListDescription: 'Lenker til nyttige sider. Lenkene kan konfigureres her: ',
    LinksListLabel: 'Nyttige lenker',
    SeeAllInstallationsLinkText: 'Se alle installasjoner',
    SetRecommendationSubtitle: 'Velg anbefaling for: {0}',
    SetRecommendationTitle: 'Sett anbefaling',
    SiteSettingsDescription: 'Vis alle områdeinnstillinger for Porteføljeområdet',
    SiteSettingsLabel: 'Områdeinnstillinger',
    SubmitLabel: 'Send'
  }
})
