define([], function () {
  return {
    ActionLabel: 'Handling',
    ActionLabelPlaceholder: 'Vennligst velg en handling...',
    ApproveChoice: 'Godkjenn',
    ApprovedSyncText: 'Godkjent og synkronisert',
    CancelLabel: 'Avbryt',
    CloseLabel: 'Lukk',
    CommentLabel: 'Kommentar',
    CommentLabelPlaceholder: 'Kommentar til valg...',
    ConfigurationDescription: 'Gå til konfigurasjonssiden for Prosjektportalen',
    ConfigurationLabel: 'Konfigurasjon av Prosjektportalen',
    ConsiderationChoice: 'Under vurdering',
    CreateLabel: 'Opprett',
    HelpContentAvailableDescription: 'Åpne hjelpedialog for denne siden',
    HelpContentAvailableLabel: 'Hjelp tilgjengelig',
    HelpContentUnavailableDescription: 'Denne siden har ingen hjelpeinnhold, dersom du mener det burde vært hjelpeinnhold her, vennligst kontakt din administrator',
    HelpContentUnavailableLabel: 'Hjelp utilgjengelig',
    HelpContentListName: 'Hjelpeinnhold',
    IdeaAlreadyApproved: 'Denne ideen er allerede godkjent',
    IdeaConfigurationTitle: 'Idékonfigurasjon',
    IdeaProcessorsSiteGroup: 'Idebehandlere',
    IdeaProjectDataDialogBlockedTitle: 'Prosjektdata element funnet',
    IdeaProjectDataDialogBlockedText: 'Det er allerede opprettet og tilknyttet prosjektdata for denne ideen.',
    IdeaProjectDataDialogInfoTitle: 'Tilknytning av prosjektdata',
    IdeaProjectDataDialogTitle: 'Opprett prosjektdata for ideen',
    IdeaProjectDataTitle: 'Prosjektdata',
    InstallationLogListName: 'Installasjonslogg',
    InstallChannelLabel: 'Installasjonskanal',
    InstalledDateLabel: 'Installasjonsdato',
    InstallVersionLabel: 'Versjon',
    LastInstallHeaderText: 'Siste installasjon',
    LastInstallDescription: 'Her er en oversikt over siste installasjon av Prosjektportalen. Helt nederst finner du informasjon om siste release fra GitHub.',
    LatestGitHubReleaseDownloadButtonText: 'Last ned siste release fra GitHub',
    LatestGitHubReleaseIsNewerText: 'En nyere versjon er tilgjengelig på GitHub',
    LatestGitHubReleaseIsOlderText: 'Versjonen som er installert er nyere enn siste release fra GitHub',
    LatestGitHubReleaseIsSameText: 'Versjonen som er installert er siste release fra GitHub',
    LatestGitHubReleaseLabel: 'Siste release fra GitHub',
    LatestGitHubReleaseLinkTitle: 'Se siste release på GitHub',
    LinksListName: 'Lenker',
    LinksListDescription: 'Lenker til nyttige sider. Lenkene kan konfigureres her: ',
    LinksListLabel: 'Nyttige lenker',
    RejectChoice: 'Avvis',
    SeeAllInstallationsLinkText: 'Se alle installasjoner',
    SetRecommendationDefaultDescription: 'Dersom ideen blir godkjent, vil det bli opprettet en detaljert idé-side for ideen og et element i <a href="../Idebehandling/AllItems.aspx" target="_blank">Idébehandlingslisten</a>.;Dersom ideen blir godkjent, vil det være mulig å opprette prosjektdata som kan bli brukt for provisjonering av området.;Tilknytt prosjektdata til ideen for å synkronisere data til et prosjekt senere. Når prosjektdata er opprettet, er det viktig å fylle ut ønsket metadata, deretter legge inn url for prosjektet, dette gjør at metadata synkroniseres til prosjektet ved provisjonering. Url til prosjektet kan enten fylles inn manuelt etter at et prosjekt har fått URL eller via en bestillingsløsning.',
    SetRecommendationSubtitle: 'Velg anbefaling for: {0}',
    SetRecommendationTitle: 'Sett anbefaling',
    SiteSettingsDescription: 'Vis alle områdeinnstillinger for Porteføljeområdet',
    SiteSettingsLabel: 'Områdeinnstillinger',
    SubmitLabel: 'Send'
  }
})
