define([], function () {
    return {
        MeasurementCommentLabel: 'Measurement Comment',
        MeasurementDateLabel: 'Measurement Date',
        MeasurementValueLabel: 'Measured Value',
        MinWidthDescription: 'Minimum width for the column. Cannot exceed maximum width.',
        MinWidthLabel: 'Minimum Width',
        MoveLeftLabel: 'Move Left',
        MoveRightLabel: 'Move Right',
        NewColumnHeaderText: 'New Column',
        NewViewHeaderText: 'Create View',
        NewViewText: 'Create New View',
        PersonalViewDescription: 'Select if this is a personal view. Personal views can only be edited by you.',
        PersonalViewLabel: 'Personal View',
        PersonalViewsHeaderText: 'Personal Views',
        PortfolioAggregationViewSearchQueryDescription: 'The search query to retrieve data. DepartmentId refers to the Project Portal hub and should not be changed. ContentTypeId refers to the content type of the data item you want to retrieve. Go to the Data Sources list to see examples.',
        PortfolioViewSearchQueryDescription: 'The search query to retrieve projects in the portfolio. DepartmentId refers to the Project Portal hub and should not be changed.',
        ProgramAdministrationAddChildsButtonDescription: 'Here you can add subordinate areas.',
        ProgramAdministrationEmptyTitle: 'No areas are connected to the program.',
        ProgramRemoveChildsButtonDescription: 'Remove one or more subordinate areas.',
        ProgramRemoveChildsDeletingLabel: 'Removing subordinate areas...',
        ProjectInformationPanelButton: 'Open Project Information Panel',
        ProjectPropertiesHeader: 'Project Information',
        SaveButtonLabel: 'Save',
        SearchPropertyDescription: 'The name of the managed property for this column.',
        SearchPropertyFoundMessage: 'Found a managed property `{0}` that matches the internal field name `{1}`.',
        SearchPropertyFoundTitle: 'Managed Property Found',
        SearchPropertyLabel: 'Search Property',
        SearchPropertyPlaceholder: 'Search managed properties...',
        SearchQueryLabel: 'Search Query',
        ShowAllMeasurementsLinkText: 'Show All Measurements',
        ShowInstrumentLinkText: '{0} (show instrument)',
        ShowFieldFrontpageLabel: 'Project Front Page',
        ShowFieldPortfolioLabel: 'Portfolio Overview',
        ShowFieldProjectStatusLabel: 'Project Status',
        ShowHideColumnsLabel: 'Show or Hide Columns',
        SortAscLabel: 'A to Z',
        SortDescLabel: 'Z to A',
        SortOrderDescription: 'The sort order determines the sequence in which views are displayed. Lowest value is shown first.',
        SortOrderLabel: 'Sort Order',
        TitleLabel: 'Title',
        ToggleColumnFormPanelLabel: 'Add Column',
        UseChangesButtonText: 'Apply',
        ViewNotFoundMessage: 'The specified view could not be found.',
        DataSourceItemNotFound: 'Data source not found',
        DataSourceListName: 'Data Sources',
        ProjectContentColumnItemNotFound: 'Project content column not found',
        Aria: {
            MenuOverflowCount: '{0} more items',
            MoveDisabled: 'Cannot move hidden column',
            MoveUp: 'Move up',
            MoveUpDisabled: 'Cannot move up, top item',
            MoveDown: 'Move down',
            MoveDownDisabled: 'Cannot move down, bottom item'
        },
        Placeholder: {
            TextField: 'Enter value here',
            Icon: 'Enter an icon',
            ChoiceField: 'Select an option',
            MultiChoiceField: 'Select one or more options'
        },
        AddColumnLabel: 'Add a column',
        BooleanNo: 'No',
        BooleanOff: 'Off',
        BooleanOn: 'On',
        BooleanYes: 'Yes',
        CancelButtonLabel: 'Cancel',
        ChildrenRemoveToastMessage: 'Subareas removal completed.',
        ChildrenRemoveToastTitle: 'Subareas removed',
        ColumnCategoryDescription: 'Specify a category for the column. The column will appear in all views using this category. To change the category for all web parts and views, modify the category in the Project Columns list.',
        ColumnCategoryLabel: 'Column category',
        ColumnPersistRenderGloballyFieldDescription: 'If you want to change the display mode for the column globally, for all web parts and views, check the box above. (This applies only to display mode)',
        ColumnPersistRenderGloballyFieldLabel: 'Update display mode globally',
        ColumnRenderDataTypePropertiesHeaderText: 'Display mode properties',
        ColumnRenderDescription: 'Choose how the column should be displayed. If it is a text field to be displayed over multiple lines, select Note.',
        ColumnRenderLabel: 'Display mode',
        ColumnRenderOptionBoolean: 'Yes/No',
        ColumnRenderOptionBooleanFalse: 'Value for "No"',
        ColumnRenderOptionBooleanTrue: 'Value for "Yes"',
        ColumnRenderOptionCurrency: 'Currency',
        ColumnRenderOptionCurrencyFallbackValueLabel: 'Default value',
        ColumnRenderOptionCurrencyMaximumFractionDigitsLabel: 'Maximum number of decimals',
        ColumnRenderOptionCurrencyMinimumFractionDigitsLabel: 'Minimum number of decimals',
        ColumnRenderOptionCurrencyPrefixLabel: 'Currency prefix',
        ColumnRenderOptionDate: 'Date',
        ColumnRenderOptionDateIncludeTimeLabel: 'Include time',
        ColumnRenderOptionInstrument: 'Instrument',
        ColumnRenderOptionDialog: 'Modal',
        ColumnRenderOptionDialogInfoTextTemplateDescription: 'Template for info text. Use {{GtMeasurementOWSCHCS}} to display the measurement indicator, {{GtStartValueOWSNMBR}} for the start value, and {{GtDesiredValueOWSNMBR}} for the goal. You can also use other column names from the benefit work.',
        ColumnRenderOptionDialogInfoTextTemplateLabel: 'Info text template',
        ColumnRenderOptionDialogLinkTextLabel: 'Link text',
        ColumnRenderOptionDialogShowInfoTextLabel: 'Show info text',
        ColumnRenderOptionFilename: 'Filename',
        ColumnRenderOptionNote: 'Note',
        ColumnRenderOptionNumber: 'Number',
        ColumnRenderOptionPercentage: 'Percentage',
        ColumnRenderOptionProjectInfo: 'Project information',
        ColumnRenderOptionTags: 'Tags',
        ColumnRenderOptionTagsValueSeparatorDescription: 'Specify a character to separate values in the tag field. The default is a semicolon.',
        ColumnRenderOptionTagsValueSeparatorLabel: 'Value separator',
        ColumnRenderOptionText: 'Text',
        ColumnRenderOptionTrend: 'Trend',
        ColumnRenderOptionTrendShowTrendIconLabel: 'Show icon',
        ColumnRenderOptionUrl: 'URL',
        ColumnRenderOptionUrlDescriptionDescription: 'Description of the link. If you do not specify a value, the description from the link is used.',
        ColumnRenderOptionUrlDescriptionLabel: 'Description',
        ColumnRenderOptionUrlOpenInNewTabLabel: 'Open in new tab',
        ColumnRenderOptionUser: 'Person',
        ColumnSettingsDisabledTooltip: 'Column settings are only available when the page is in edit mode.',
        ColumnSettingsLabel: 'Column settings',
        ColumnsListNameLabel: 'Columns',
        ColumnVisibilityDescription: 'Specify where the column should be displayed. Project front page, project status page, portfolio overview, or all locations.',
        ColumnVisibilityLabel: 'Column visibility',
        CompactViewText: 'Compact list',
        ConfirmDeleteProjectColumnSubText: 'This column will be removed from the Project Columns list and thus from all views using it. Are you sure you want to delete this column? If you only want to remove the column from this view, you can use "Show or hide columns".',
        ConfirmDeleteProjectColumnTitle: 'Do you want to delete?',
        ConfirmDeleteProjectContentColumnSubText: 'This column will be removed from the Project Content Columns list and thus from all views using it. Are you sure you want to delete this column? If you only want to remove the column from this view, you can use "Show or hide columns".',
        ConfirmDeleteProjectContentColumnTitle: 'Do you want to delete?',
        ConfirmDeleteResponseAbort: 'Cancel',
        ConfirmDeleteResponseConfirm: 'Delete',
        CustomSortsText: 'Custom sorting',
        DefaultViewDescription: 'Choose whether this is the default view for the Portfolio Overview.',
        DefaultViewSetWarningMessage: 'There is already a view set as default. You must first change this view before setting a new one as default. Personal views cannot be set as default.',
        DeleteButtonLabel: 'Delete',
        DisplayNameDescription: 'Display name for this column, only for this web part. To change the display name for all web parts, you must change it in the Project Content Columns list.',
        DisplayNameLabel: 'Display name',
        DisplayNamePortfolioOverviewDescription: 'Display name for this column.',
        EditColumnLabel: 'Edit',
        EditViewColumnsPanelHeaderText: 'Edit view columns',
        EditViewColumnsPanelHelpText: 'Select the columns to be displayed for the current view. To change the order, you can drag and drop or use the up and down arrows next to each column.',
        EditViewHeaderText: 'Edit view',
        EditViewText: 'Edit current view',
        ErrorTitle: 'An error has occurred',
        ExcelExportButtonLabel: 'Export to Excel',
        FilterText: 'Filter',
        GroupByColumnLabel: 'Group by {0}',
        IconNameDescription: 'Name of icon from UI Fabric. See overview at https://uifabricicons.azurewebsites.net/.',
        IconNameLabel: 'Icon name',
        InternalNameDescription: 'Internal field name for this column.',
        InternalNameLabel: 'Internal field name',
        IsGroupableDescription: 'Users can group by this column.',
        IsGroupableLabel: 'Groupable',
        IsRefinableDescription: 'Users can filter by this column.',
        IsRefinableLabel: 'Refinable',
        IsResizableLabel: 'Resizable',
        ListViewText: 'List',
        MaxWidthDescription: 'Maximum width for the column. Cannot be less than the minimum width.',
        MaxWidthLabel: 'Max width',
        MeasurementAchievementLabel: 'Goal achievement',
        Add: 'Add',
        AddProjectDialogSearchBoxPlaceholder: 'Search projects...',
        BarLabel: 'Bar',
        Cancel: 'Cancel',
        CmdSelectionCountText: '{0} is marked',
        CmdSelectionCountTooltipText: 'The following projects have been selected:',
        CommandBarGroupName: 'Commandline',
        ConfigItemTitleFieldDescription: 'If an element with the title specified here is specified in the timeline configuration list, this will be displayed on the timeline.',
        ConfigItemTitleFieldLabel: 'Element title (configuration)',
        DataSourceCategoryDescription: 'Enter a data source category to be able to choose between multiple data sources in the web part.',
        DataSourceCategoryError: 'An error occurred while retrieving data sources with category **{0}**.',
        DataSourceCategoryLabel: 'Category for data sources',
        DataSourceError: 'An error occurred while retrieving data from the data source named **{0}**.',
        DataSourceGroupName: 'Data sources',
        DataSourceLabel: 'Data source',
        DataSourceLevelDescription: 'Select level for the data source. Only data sources with this level will be available in the web part.',
        DataSourceLevelLabel: 'Data source level',
        DataSourceNotFound: 'Cannot find any data source with name **{0}**.',
        DefaultDataSourceViewLabel: 'Default view (data source)',
        DefaultViewLabel: 'Default view',
        GeneralGroupName: 'General',
        PortfolioManagerGroupName: 'Portfolio insight',
        ProgramAdministrationAddChildsButtonLabel: 'Add projects',
        ProgramAdministrationEmptyMessage: 'No sites are connected to the program.',
        ProgramAdministrationHeader: 'Administration of child projects',
        ProgramAdministrationInfoMessage: 'Select one or more projects you want to associate to the site. The site will appear as a parent for the projects that have been selected under Project Information.',
        ProgramAdministrationSearchBoxPlaceholder: 'Search the program site...',
        ProgramRemoveChildsButtonLabel: 'Remove child projects',
        ProgramTimelineInfoText: 'All the projects with start and end dates associated with the site are listed here. To zoom in/out in timeline: ALT+Mouse wheel.',
        ProjectContentColumnsListName: 'Prosjektinnholdskolonner',
        ProjectDeliveriesGroupName: 'Project deliveries (beta)',
        ProjectLabel: 'Project',
        ProjectsListName: 'Prosjekter',
        SearchBoxGroupName: 'Search box',
        SearchBoxPlaceholderText: 'Search {0}...',
        SearchBoxPlaceholderTextDescription: 'Text that appears in the search box when it is empty. If no value is set, the text is based on the selected data source.',
        SearchBoxPlaceholderTextLabel: 'Search box text',
        ShowCommandBarLabel: 'Show commandline',
        ShowExcelExportButtonLabel: 'Show export to Excel button',
        ShowFiltersLabel: 'Show filters',
        ShowGroupByLabel: 'Show grouping options',
        ShowSearchBoxLabel: 'Show search box',
        ShowViewSelectorLabel: 'Show view selector',
        TimelineConfigurationListName: 'Tidslinjekonfigurasjon',
        TimelineContentListName: 'Tidslinjeinnhold',
    }
})
