declare interface IProgramWebPartsStrings {
  EditColumnHeaderText: string
  PortfolioAggregationNotConfiguredMessage: string
  DataSourceCategoryDescription: string
  DataSourceDescription: string
  ColumnRenderOptionTags: string
  ColumnRenderOptionList: string
  ColumnRenderOptionInt: string
  SearchPropertyDescription: string
  DataSourceGroupName: string
  CommandBarGroupName: string
  SearchBoxGroupName: string
  DeleteButtonLabel: string
  ColumnRenderOptionText: string
  ColumnRenderOptionDate: string
  ColumnRenderOptionDateTime: string
  ColumnRenderLabel: string
  ProjectPropertiesListName: string
  EditColumnLabel: any
  MoveRightLabel: string
  MoveLeftLabel: string
  IsGroupableLabel: string
  NewColumnHeaderText: string
  AddColumnText: string
  SearchPropertyLabel: string
  DisplayNameLabel: string
  MinWidthLabel: string
  MaxWidthLabel: string
  IsMultilineLabel: string
  IsResizableLabel: string
  SaveButtonLabel: string
  CloseButtonLabel: string
  GroupByColumnLabel: string
  FilterBy: string
  DataSourceCategoryLabel: string
  DataSourceLabel: string
  SelectedColumnsLabel: string
  SortDescLabel: string
  SortAscLabel: string
  ColumSettingsLabel: string
  AdvancedGroupName: string
  DeliveriesDatasource: string
  DeliveriesTitle: string
  WebPartTitleLabel: string
  SettingsLabel: string
  ActorsLabel: string
  BenefitResponsibleLabel: string
  BenefitOwnerLabel: string
  BenefitTitleLabel: string
  BenefitDataSource: string
  BenefitsTitle: string
  ChartConfigurationListNameLabel: string
  ChartErrorText: string
  ColumnConfigListNameLabel: string
  ColumnsListNameLabel: string
  LoadingTextLabel: string
  EmptyMessageLabel: string
  RowLimitLabel: string
  LoadingTextDescription: string
  EmptyMessageDescription: string
  CommandBarGroupName: string
  ConfigurationGroupName: string
  ConsequenceLabel: string
  ConsequencePostActionLabel: string
  CreatedText: string
  DataSourceError: string
  DataSourceCategoryError: string
  DataSourceNotFound: string
  DefaultViewLabel: string
  DeliveryDescriptionLabel: string
  DeliveryEndTimeLabel: string
  DeliveryStartTimeLabel: string
  DeliveryStatusCommentLabel: string
  DeliveryStatusLabel: string
  DescriptionFieldLabel: string
  DesiredValueLabel: string
  EditViewText: string
  ErrorText: string
  ExcelExportButtonLabel: string
  ExcelExportFileNamePrefix: string
  FetchDataErrorMessage: string
  FieldSelectorEmptyMessage: string
  FieldSelectorName: string
  FiltersString: string
  FilterText: string
  GeneralGroupName: string
  GetConfigErrorMessage: string
  IndicatorLabel: string
  LastMeasurementLabel: string
  LoadingText: string
  LogDescriptionLabel: string
  MeasuremenentIdicatorLabel: string
  MeasurementAchievementLabel: string
  MeasurementCommentLabel: string
  MeasurementDateLabel: string
  MeasurementValueLabel: string
  MissingProperties: string
  NewViewText: string
  NoDefaultViewMessage: string
  NoGroupingText: string
  NoProperties: string
  NoSearchResults: string
  NotSet: string
  PhaseLabel: string
  ProbabilityLabel: string
  ProbabilityPostActionLabel: string
  ProjectInformationGroupName: string
  StatusReportsCountLabel: string
  ProjectLinkText: string
  ProjectManager: string
  ProjectOwner: string
  ProjectStatusLinkText: string
  PropertyPaneDescription: string
  RecommendationLabel: string
  ProjectTimelineInfoText: string
  ResourceAllocationInfoText: string
  ResourceLabel: string
  ResponsibleLabel: string
  RoleLabel: string
  AllocationPercetageLabel: string
  AllocationStatusLabel: string
  CommentLabel: string
  SaveViewAsText: string
  SearchBoxPlaceholderText: string
  SearchBoxPlaceholderTextLabel: string
  ShowAllMeasurementsLinkText: string
  ShowAsListText: string
  ShowAsTilesLabel: string
  ShowAsTilesText: string
  ShowCommandBarLabel: string
  ShowExcelExportButtonLabel: string
  ShowFiltersLabel: string
  ShowGroupByLabel: string
  ShowProjectLogoFieldLabel: string
  ShowProjectManagerFieldLabel: string
  ShowProjectOwnerFieldLabel: string
  ShowSearchBoxLabel: string
  ShowViewSelectorLabel: string
  SiteTitleLabel: string
  SortByFieldLabel: string
  StartValueLabel: string
  TileViewGroupName: string
  TitleLabel: string
  UnitLabel: string
  TypeLabel: string
  ViewNotFoundMessage: string
  ViewsListNameLabel: string
  ProjectsListName: string
  TimelineContentListName: string
  TimelineConfigurationListName: string
  PortfolioManagerGroupName: string
  ProjectTimelineItemInfo: string
  LastPublishedStatusreport: string
  DiamondLabel: string
  BarLabel: string
  TriangleLabel: string
  MilestoneLabel: string
  ProjectLabel: string
  SubPhaseLabel: string
  CurrentPhaseLabel: string
  MilestoneDateLabel: string
  StartDateLabel: string
  EndDateLabel: string
  BudgetTotalLabel: string
  CostsTotalLabel: string
  NoProjectsFound: string
  NewLabel: string
  ReadOnlyGroupName: string
  DisplayAllProjects: string
  MyProjectsLabel: string
  AllProjectsLabel: string
  NoAccessMessage: string
  ProgramProjectsTimelineSync_LogListHeader: string
  ProgramProjectsTimelineSync_DeleteLog: string
  ProgramProjectsTimelineSync_EmptyLog: string
  ProgramProjectsTimelineSync_RemoveFromProgram: string
  ProgramProjectsTimelineSync_SyncToTimeline: string
  ProgramProjectsTimelineSync_SyncingToTimeline: string
  ProgramProjectsTimelineSync_SyncAllToTimeline: string
  ProgramProjectsTimelineSync_SyncingAllToTimeline: string
  ProgramProjectsTimelineSync_AddToTimelineAutomatically: string
  ProgramProjectsTimelineSync_IncludeExpiredProjects: string
  ProgramProjectsTimelineSync_StoredProjectsListHeader: string
  ProgramProjectsTimelineSync_LoadingText: string
  ProgramProjectsTimelineSync_ProjectRemoved: string
  ProgramProjectsTimelineSync_ProjectDoesNotExist: string
  ProgramProjectsTimelineSync_TimelineItemUpdated: string
  ProgramProjectsTimelineSync_TimelineItemUpdateError: string
  ProgramProjectsTimelineSync_TimelineItemAdded: string
  ProgramProjectsTimelineSync_TimelineItemAddedToTimeline: string
  ProgramProjectsTimelineSync_TimelineItemExpired: string
  ProgramProjectsTimelineSync_TimelineItemNoDates: string
  ProgramProjectsTimelineSync_PagingStatusText: string
  ProgramProjectsTimelineSync_CountText: string
  ProgramProjectStatus_LoadingText: string
  ProgramProjectStatus_LoadingTextDescription: string
  ProgramProjectStatus_LoadingFailedMessage: string
  ProgramAddProject_AddingProjectToProgram: string
  ProgramAddProject_AddingProjectToProgramDescription: string
  ProgramAddProject_ProjectWasAddedToProgram: string
  ProgramAddProject_ProjectsWasAddedToProgram: string
  ProgramAddProject_AddProjectToProgram: string
  ProgramAddProject: string
  ProgramAddProject_ProjectAlreadyInProgram: string
  ProgramAddProject_ProjectsAlreadyInProgram: string
  ProgramAddProject_AddAllProjectsToProgram: string
  ProgramAddProject_EmptyMessage: string
  ProgramAddProject_SearchBoxLabelText: string
  ProgramAdministration_EmptyMessage: string
  RiskWebPartTitle: string
  RiskDataSource: string
  Lists_StoredProjects_MaxLimitError: string
  Lists_StoredProjects_DoesNotExist: string
  Lists_ProjectsTimeline_DoesNotExist: string
  ProgramPortfolio_LoadingText: string
  ProgramPortfolio_SearchBoxLabelText: string
  ProgramPortfolio_ShowCountText: string
  ProgramTimelineHeader: string
  ProgramAdministrationHeader: string
  ProgramAddProjectButtonText: string
  ProgramRemoveChildButtonText: string
  ProgramSearchProjectsText: string
  Add: string
  Cancel: string
  Yes: string
  No: string
  PreviousPage: string
  NextPage: string
  ProjectTimelineSync_RemoveFromProject: string
  ProjectsTimelineSync_StoredProjectsListHeader: string
  ProjectsTimelineSync_LoadingText: string
  ProjectsTimelineSync_ProjectRemoved: string
  ProjectsTimelineSync_CountText: string
  ProjectStatus_LoadingText: string
  ProjectAddProject_AddingProjectToProject: string
  ProjectAddProject_AddingProjectToProjectDescription: string
  ProjectAddProject_ProjectWasAddedToProject: string
  ProjectAddProject_ProjectsWasAddedToProject: string
  ProjectAddProject_AddProjectToProject: string
  ProjectAddProject_ProjectAlreadyExist: string
  ProjectAddProject_ProjectsAlreadyExist: string
  ProjectAddProject_AddAllProjects: string
  ProjectLists_StoredProjects_MaxLimitError: string
  ProjectLists_StoredProjects_DoesNotExist: string
  ProjectPortfolio_LoadingText: string
  ProjectPortfolio_SearchBoxLabelText: string
  ProjectPortfolio_ShowCountText: string
  ProgramStatus_ViewIdLabel: string
}

declare module 'ProgramWebPartsStrings' {
  const strings: IProgramWebPartsStrings
  export = strings
}
