declare interface IProgramWebPartsStrings {
  Aria: {
    MenuOverflowCount: string
    MoveDisabled: string
    MoveUp: string
    MoveUpDisabled: string
    MoveDown: string
    MoveDownDisabled: string
  },
  Placeholder: {
    TextField: string
    Icon: string
    ChoiceField: string
    MultiChoiceField: string
  }
  Add: string
  AddColumnLabel: string
  AddColumnLabel: string
  AddProjectDialogSearchBoxPlaceholder: string
  BarLabel: string
  BooleanNo: string
  BooleanOff: string
  BooleanOn: string
  BooleanYes: string
  Cancel: string
  CancelButtonLabel: string
  ChildrenRemoveToastMessage: string
  ChildrenRemoveToastTitle: string
  CmdSelectionCountText: string
  CmdSelectionCountTooltipText: string
  ColumnCategoryDescription: string
  ColumnCategoryLabel: string
  ColumnPersistRenderGloballyFieldDescription: string
  ColumnPersistRenderGloballyFieldLabel: string
  ColumnRenderDataTypePropertiesHeaderText: string
  ColumnRenderDescription: string
  ColumnRenderLabel: string
  ColumnRenderOptionBoolean: string
  ColumnRenderOptionBooleanFalse: string
  ColumnRenderOptionBooleanTrue: string
  ColumnRenderOptionCurrency: string
  ColumnRenderOptionCurrencyFallbackValueLabel: string
  ColumnRenderOptionCurrencyMaximumFractionDigitsLabel: string
  ColumnRenderOptionCurrencyMinimumFractionDigitsLabel: string
  ColumnRenderOptionCurrencyPrefixLabel: string
  ColumnRenderOptionDate: string
  ColumnRenderOptionDateIncludeTimeLabel: string
  ColumnRenderOptionInstrument: string
  ColumnRenderOptionDialog: string
  ColumnRenderOptionDialogInfoTextTemplateDescription: string
  ColumnRenderOptionDialogInfoTextTemplateLabel: string
  ColumnRenderOptionDialogLinkTextLabel: string
  ColumnRenderOptionDialogShowInfoTextLabel: string
  ColumnRenderOptionFilename: string
  ColumnRenderOptionNote: string
  ColumnRenderOptionNumber: string
  ColumnRenderOptionPercentage: string
  ColumnRenderOptionProjectInfo: string
  ColumnRenderOptionTags: string
  ColumnRenderOptionTagsValueSeparatorDescription: string
  ColumnRenderOptionTagsValueSeparatorLabel: string
  ColumnRenderOptionText: string
  ColumnRenderOptionTrend: string
  ColumnRenderOptionTrendShowTrendIconLabel: string
  ColumnRenderOptionUrl: string
  ColumnRenderOptionUrlDescriptionDescription: string
  ColumnRenderOptionUrlDescriptionLabel: string
  ColumnRenderOptionUrlOpenInNewTabLabel: string
  ColumnRenderOptionUser: string
  ColumnSettingsDisabledTooltip: string
  ColumnSettingsLabel: string
  ColumnsListNameLabel: string
  ColumnVisibilityDescription: string
  ColumnVisibilityLabel: string
  CommandBarGroupName: string
  CompactViewText: string
  ConfigItemTitleFieldDescription: string
  ConfigItemTitleFieldLabel: string
  ConfirmDeleteProjectColumnSubText: string
  ConfirmDeleteProjectColumnTitle: string
  ConfirmDeleteProjectContentColumnSubText: string
  ConfirmDeleteProjectContentColumnTitle: string
  ConfirmDeleteResponseAbort: string
  ConfirmDeleteResponseConfirm: string
  CustomSortsText: string
  DataSourceCategoryDescription: string
  DataSourceCategoryError: string
  DataSourceCategoryLabel: string
  DataSourceError: string
  DataSourceGroupName: string
  DataSourceLabel: string
  DataSourceLevelDescription: string
  DataSourceLevelLabel: string
  DataSourceNotFound: string
  DefaultDataSourceViewLabel: string
  DefaultViewDescription: string
  DefaultViewLabel: string
  DefaultViewSetWarningMessage: string
  DeleteButtonLabel: string
  DisplayNameDescription: string
  DisplayNameLabel: string
  DisplayNamePortfolioOverviewDescription: string
  EditColumnLabel: string
  EditViewColumnsPanelHeaderText: string
  EditViewColumnsPanelHelpText: string
  EditViewHeaderText: string
  EditViewText: string
  ErrorTitle: string
  ExcelExportButtonLabel: string
  FilterText: string
  GeneralGroupName: string
  GroupByColumnLabel: string
  IconNameDescription: string
  IconNameLabel: string
  InternalNameDescription: string
  InternalNameLabel: string
  IsGroupableDescription: string
  IsGroupableLabel: string
  IsRefinableDescription: string
  IsRefinableLabel: string
  IsResizableLabel: string
  ListViewText: string
  MaxWidthDescription: string
  MaxWidthLabel: string
  MeasurementAchievementLabel: string
  MeasurementCommentLabel: string
  MeasurementDateLabel: string
  MeasurementValueLabel: string
  MinWidthDescription: string
  MinWidthLabel: string
  MoveLeftLabel: string
  MoveRightLabel: string
  NewColumnHeaderText: string
  NewViewHeaderText: string
  NewViewText: string
  PersonalViewDescription: string
  PersonalViewLabel: string
  PersonalViewsHeaderText: string
  PortfolioAggregationViewSearchQueryDescription: string
  PortfolioManagerGroupName: string
  PortfolioViewSearchQueryDescription: string
  ProgramAdministrationAddChildsButtonDescription: string
  ProgramAdministrationAddChildsButtonLabel: string
  ProgramAdministrationEmptyMessage: string
  ProgramAdministrationEmptyTitle: string
  ProgramAdministrationHeader: string
  ProgramAdministrationInfoMessage: string
  ProgramAdministrationSearchBoxPlaceholder: string
  ProgramRemoveChildsButtonDescription: string
  ProgramRemoveChildsButtonLabel: string
  ProgramRemoveChildsDeletingLabel: string
  ProgramTimelineInfoText: string
  ProjectContentColumnsListName: string
  ProjectDeliveriesGroupName: string
  ProjectLabel: string
  ProjectPropertiesHeader: string
  ProjectPropertiesListName: string
  ProjectsListName: string
  SaveButtonLabel: string
  SearchBoxGroupName: string
  SearchBoxPlaceholderText: string
  SearchBoxPlaceholderTextDescription: string
  SearchBoxPlaceholderTextLabel: string
  SearchPropertyDescription: string
  SearchPropertyFoundMessage: string
  SearchPropertyFoundTitle: string
  SearchPropertyLabel: string
  SearchPropertyPlaceholder: string
  SearchQueryLabel: string
  ShowAllMeasurementsLinkText: string
  ShowInstrumentLinkText: string
  ShowCommandBarLabel: string
  ShowExcelExportButtonLabel: string
  ShowFieldFrontpageLabel: string
  ShowFieldPortfolioLabel: string
  ShowFieldProjectStatusLabel: string
  ShowFiltersLabel: string
  ShowGroupByLabel: string
  ShowHideColumnsLabel: string
  ShowSearchBoxLabel: string
  ShowViewSelectorLabel: string
  SortAscLabel: string
  SortDescLabel: string
  SortOrderDescription: string
  SortOrderLabel: string
  TimelineConfigurationListName: string
  TimelineContentListName: string
  TitleLabel: string
  ToggleColumnFormPanelLabel: string
  UseChangesButtonText: string
  ViewNotFoundMessage: string
  DataSourceItemNotFound: string
  DataSourceListName: string
  ProjectContentColumnItemNotFound: string
}

declare module 'ProgramWebPartsStrings' {
  const strings: IProgramWebPartsStrings
  export = strings
}
