declare interface IProgramWebPartsStrings {
  CmdSelectionCountText: string
  ProgramAdministrationInfoMessage: string
  EditColumnHeaderText: string
  DataSourceCategoryDescription: string
  DataSourceDescription: string
  ColumnRenderOptionTags: string
  ColumnRenderOptionList: string
  ColumnRenderOptionInt: string
  SearchPropertyDescription: string
  DataSourceGroupName: string
  CommandBarGroupName: string
  SearchBoxGroupName: string
  DeleteButtonLabel: string
  ColumnRenderOptionText: string
  ColumnRenderOptionDate: string
  ColumnRenderOptionDateTime: string
  ColumnRenderLabel: string
  ProjectPropertiesListName: string
  EditColumnLabel: any
  MoveRightLabel: string
  MoveLeftLabel: string
  IsGroupableLabel: string
  NewColumnHeaderText: string
  AddColumnText: string
  SearchPropertyLabel: string
  DisplayNameLabel: string
  MinWidthLabel: string
  MaxWidthLabel: string
  IsMultilineLabel: string
  IsResizableLabel: string
  SaveButtonLabel: string
  CloseButtonLabel: string
  GroupByColumnLabel: string
  FilterBy: string
  DataSourceCategoryLabel: string
  DataSourceLabel: string
  SelectedColumnsLabel: string
  SortDescLabel: string
  SortAscLabel: string
  ColumSettingsLabel: string
  AdvancedGroupName: string
  DeliveriesDatasource: string
  DeliveriesTitle: string
  WebPartTitleLabel: string
  SettingsLabel: string
  ActorsLabel: string
  BenefitResponsibleLabel: string
  BenefitOwnerLabel: string
  BenefitTitleLabel: string
  BenefitDataSource: string
  BenefitsTitle: string
  ChartConfigurationListNameLabel: string
  ChartErrorText: string
  ColumnConfigListNameLabel: string
  ColumnsListNameLabel: string
  LoadingTextLabel: string
  EmptyMessageLabel: string
  RowLimitLabel: string
  LoadingTextDescription: string
  EmptyMessageDescription: string
  CommandBarGroupName: string
  ConfigurationGroupName: string
  ConsequenceLabel: string
  ConsequencePostActionLabel: string
  CreatedText: string
  DataSourceError: string
  DataSourceCategoryError: string
  DataSourceNotFound: string
  DefaultViewLabel: string
  DeliveryDescriptionLabel: string
  DeliveryEndTimeLabel: string
  DeliveryStartTimeLabel: string
  DeliveryStatusCommentLabel: string
  DeliveryStatusLabel: string
  DescriptionFieldLabel: string
  DesiredValueLabel: string
  EditViewText: string
  ErrorText: string
  ExcelExportButtonLabel: string
  ExcelExportFileNamePrefix: string
  FetchDataErrorMessage: string
  FieldSelectorEmptyMessage: string
  FieldSelectorName: string
  FiltersString: string
  FilterText: string
  GeneralGroupName: string
  GetConfigErrorMessage: string
  IndicatorLabel: string
  LastMeasurementLabel: string
  LoadingText: string
  LogDescriptionLabel: string
  MeasuremenentIdicatorLabel: string
  MeasurementAchievementLabel: string
  MeasurementCommentLabel: string
  MeasurementDateLabel: string
  MeasurementValueLabel: string
  MissingProperties: string
  NewViewText: string
  NoDefaultViewMessage: string
  NoGroupingText: string
  NoProperties: string
  NoSearchResults: string
  NotSet: string
  PhaseLabel: string
  ProbabilityLabel: string
  ProbabilityPostActionLabel: string
  ProjectInformationGroupName: string
  StatusReportsCountLabel: string
  ProjectLinkText: string
  ProjectManager: string
  ProjectOwner: string
  ProjectStatusLinkText: string
  PropertyPaneDescription: string
  RecommendationLabel: string
  ProjectTimelineInfoText: string
  ResourceAllocationInfoText: string
  ResourceLabel: string
  ResponsibleLabel: string
  RoleLabel: string
  AllocationPercetageLabel: string
  AllocationStatusLabel: string
  CommentLabel: string
  SaveViewAsText: string
  SearchBoxPlaceholderText: string
  SearchBoxPlaceholderTextLabel: string
  ShowAllMeasurementsLinkText: string
  ShowAsListText: string
  ShowAsTilesLabel: string
  ShowAsTilesText: string
  ShowCommandBarLabel: string
  ShowExcelExportButtonLabel: string
  ShowFiltersLabel: string
  ShowGroupByLabel: string
  ShowProjectLogoFieldLabel: string
  ShowProjectManagerFieldLabel: string
  ShowProjectOwnerFieldLabel: string
  ShowSearchBoxLabel: string
  ShowViewSelectorLabel: string
  SiteTitleLabel: string
  SortByFieldLabel: string
  StartValueLabel: string
  TileViewGroupName: string
  TitleLabel: string
  UnitLabel: string
  TypeLabel: string
  ViewNotFoundMessage: string
  ViewsListNameLabel: string
  ProjectsListName: string
  TimelineContentListName: string
  TimelineConfigurationListName: string
  PortfolioManagerGroupName: string
  ProjectTimelineItemInfo: string
  LastPublishedStatusreport: string
  DiamondLabel: string
  BarLabel: string
  TriangleLabel: string
  MilestoneLabel: string
  ProjectLabel: string
  SubPhaseLabel: string
  CurrentPhaseLabel: string
  MilestoneDateLabel: string
  NameLabel: string
  StartDateLabel: string
  EndDateLabel: string
  BudgetTotalLabel: string
  CostsTotalLabel: string
  NoProjectsFound: string
  NewLabel: string
  DisplayAllProjects: string
  MyProjectsLabel: string
  AllProjectsLabel: string
  NoAccessMessage: string
  ProgramAdministrationEmptyMessage: string
  ProgramAdministrationAddChildsButtonText: string
  RiskDataSource: string
  ProgramAdministrationSearchBoxPlaceholder: string
  ProgramTimelineHeader: string
  ProgramAdministrationHeader: string
  ProgramRemoveChildsButtonText: string
  AddProjectDialogSearchBoxPlaceholder: string
  Add: string
  Cancel: string
  Yes: string
  No: string
  PreviousPage: string
  NextPage: string
  ProjectDeliveriesGroupName: string
  ShowProjectDeliveriesLabel: string
  ConfigItemTitleFieldLabel: string
  ConfigItemTitleFieldDescription: string
  ProjectContentColumnsListName: string
}

declare module 'ProgramWebPartsStrings' {
  const strings: IProgramWebPartsStrings
  export = strings
}
