define([], function () {
  return {
    Placeholder: {
      TextField: 'Angi verdi her',
      Icon: 'Angi et ikon',
      ChoiceField: 'Velg et alternativ',
      MultiChoiceField: 'Velg ett eller flere alternativer',
    },
    Add: 'Legg til',
    AddColumnLabel: 'Legg til en kolonne',
    AddProjectDialogSearchBoxPlaceholder: 'Søk i prosjekter...',
    BarLabel: 'Bar',
    Cancel: 'Avbryt',
    ChildrenRemoveToastMessage: 'Fjerning av underområder er fullført.',
    ChildrenRemoveToastTitle: 'Underområder fjernet',
    CmdSelectionCountText: '{0} er merket',
    CmdSelectionCountTooltipText: 'Følgende prosjekter er valgt:',
    ColumnSettingsLabel: 'Kolonneinnstillinger',
    CommandBarGroupName: 'Kommandolinje',
    CompactViewText: 'Kompakt liste',
    ConfigItemTitleFieldDescription: 'Dersom det er spesifisert et element med tittelen angitt her i tidslinjekonfigurasjon listen så vil dette vises på tidslinjen.',
    ConfigItemTitleFieldLabel: 'Element tittel (konfigurasjon)',
    CustomSortsText: 'Egendefinert sortering',
    DataSourceCategoryDescription: 'Angi en datakildekategori for å kunne velge mellom flere datakilder i webdelen.',
    DataSourceCategoryError: 'Det skjedde en feil under uthenting av datakilder med kategori **{0}**.',
    DataSourceCategoryLabel: 'Kategori for datakilder',
    DataSourceError: 'Det skjedde en feil under uthenting av data fra datakilde med navn **{0}**.',
    DataSourceGroupName: 'Datakilder',
    DataSourceLabel: 'Datakilde',
    DataSourceLevelDescription: 'Velg nivå for datakilde. Kun datakilder med dette nivået vil være tilgjengelig i webdelen.',
    DataSourceLevelLabel: 'Nivå for datakilde',
    DataSourceNotFound: 'Finner ingen datakilde med navn **{0}**.',
    DefaultDataSourceViewLabel: 'Standardvisning (datakilde)',
    DefaultViewLabel: 'Standardvisning',
    EditColumnLabel: 'Rediger',
    EditViewText: 'Rediger gjeldende visning',
    ErrorTitle: 'Det har oppstått en feil',
    ExcelExportButtonLabel: 'Eksporter til Excel',
    FilterText: 'Filtrer',
    GeneralGroupName: 'Generelt',
    GroupByColumnLabel: 'Grupper etter {0}',
    ListViewText: 'Liste',
    NewViewText: 'Opprett ny visning',
    PersonalViewsHeaderText: 'Personlige visninger',
    PortfolioManagerGroupName: 'Porteføljeinnsyn',
    ProgramAdministrationAddChildsButtonDescription: 'Her kan du legge til underordnede områder.',
    ProgramAdministrationAddChildsButtonLabel: 'Legg til underområder',
    ProgramAdministrationEmptyMessage: 'Det er ingen områder som er koblet til programmet. For å koble til områder, klikk på knappen _Legg til prosjekter_ over.',
    ProgramAdministrationEmptyTitle: 'Ingen områder er koblet til programmet.',
    ProgramAdministrationHeader: 'Administrasjon av underområder',
    ProgramAdministrationInfoMessage: 'Her får du muligheten til å legge til underordnede områder. Disse vil dukke opp i aggregerte oversikter og tidslinje inne på området. Området vil dukke opp som forelder for prosjektene som er valgt under Prosjektinformasjon.',
    ProgramAdministrationSearchBoxPlaceholder: 'Søk i underområder...',
    ProgramRemoveChildsButtonDescription: 'Fjern ett eller flere underordnede områder.',
    ProgramRemoveChildsButtonLabel: 'Fjern underområder',
    ProgramRemoveChildsDeletingLabel: 'Fjerner underområder...',
    ProgramTimelineInfoText: "Her listes alle prosjektene med start- og sluttdato som er tilknyttet området. For å zoome inn/ut i tidslinje: ALT+Musehjul",
    ProjectContentColumnsListName: 'Prosjektinnholdskolonner',
    ProjectDeliveriesGroupName: 'Prosjektleveranser (beta)',
    ProjectLabel: 'Prosjekt',
    ProjectPropertiesListName: 'Prosjektegenskaper',
    ProjectsListName: 'Prosjekter',
    SearchBoxGroupName: 'Søkeboks',
    SearchBoxPlaceholderText: 'Søk i {0}...',
    SearchBoxPlaceholderTextDescription: 'Tekst som vises i søkeboksen når den er tom. Om det ikke settes en verdi baseres teksten på valgt datakilde.',
    SearchBoxPlaceholderTextLabel: 'Søkebokstekst',
    ShowCommandBarLabel: 'Vis kommandolinje',
    ShowExcelExportButtonLabel: 'Vis eksport til Excel-knapp',
    ShowFiltersLabel: 'Vis filtre',
    ShowGroupByLabel: 'Vis grupperingsvalg',
    ShowSearchBoxLabel: 'Vis søkeboks',
    ShowViewSelectorLabel: 'Vis visningsvelger',
    SortAscLabel: 'Å til A',
    SortDescLabel: 'A til Å',
    TimelineConfigurationListName: 'Tidslinjekonfigurasjon',
    TimelineContentListName: 'Tidslinjeinnhold',
    TitleLabel: 'Tittel'
  }
})
