define([], function () {
    return {
        DataSourceListName: 'Datakilder',
        DataSourceItemNotFound: 'Datakilde ble ikke funnet',
        ListViewText: 'Liste',
        CompactViewText: 'Kompakt liste',
        CmdSelectionCountTooltipText: 'Følgende prosjekter er valgt:',
        DefaultViewLabel: 'Standardvisning',
        DefaultDataSourceViewLabel: 'Standardvisning (datakilde)',
        DataSourceLevelLabel: 'Nivå for datakilde',
        DataSourceLevelDescription: 'Velg nivå for datakilde. Kun datakilder med dette nivået vil være tilgjengelig i webdelen.',
        SearchBoxPlaceholderTextDescription: 'Tekst som vises i søkeboksen når den er tom. Om det ikke settes en verdi baseres teksten på valgt datakilde.',
        ProgramTimelineInfoText: "Her listes alle prosjektene med start- og sluttdato som er tilknyttet området. For å zoome inn/ut i tidslinje: ALT+Musehjul",
        CmdSelectionCountText: '{0} er merket',
        DataSourceCategoryDescription: 'Angi en datakildekategori for å kunne velge mellom flere datakilder i webdelen.',
        DataSourceDescription: 'Navnet på datakilden du vil bruke. Datakildene finner du i listen Datakilder på Portføljeområdet.',
        SearchPropertyDescription: 'Navnet på den forvaltede egenskapen for denne kolonnen.',
        DataSourceGroupName: 'Datakilder',
        CommandBarGroupName: 'Søkeboks',
        SearchBoxGroupName: 'Søkeboks',
        DeleteButtonLabel: 'Slett',
        ColumnRenderOptionTags: 'Etiketter',
        ColumnRenderOptionList: 'Liste',
        ColumnRenderOptionInt: 'Tall',
        ColumnRenderOptionText: 'Tekst',
        ColumnRenderOptionDate: 'Dato',
        ColumnRenderOptionDateTime: 'Dato og tidspunkt',
        ColumnRenderLabel: 'Vis som',
        EditColumnLabel: 'Rediger',
        MoveRightLabel: 'Flytt til høyre',
        MoveLeftLabel: 'Flytt til venstre',
        IsGroupableLabel: 'Grupperbar',
        NewColumnHeaderText: 'Ny kolonne',
        EditColumnHeaderText: 'Rediger kolonne',
        ToggleColumnFormPanelLabel: 'Legg til kolonne',
        ToggleEditViewColumnsLabel: 'Vis eller skjul kolonner',
        ShowHideColumnsLabel: 'Vis/skjul kolonner',
        EditViewColumnsPanelHeaderText: 'Rediger visningskolonner',
        ShowEditViewColumnsPanelHelpText: 'Velg kolonnene som skal vises for nåværende visning. Hvis du vil endre rekkefølgen, kan du dra og slippe eller bruke opp- og ned-pilen ved siden av hver kolonne.',  
        SearchPropertyLabel: 'Søkeegenskap',
        DisplayNameLabel: 'Visningsnavn',
        MinWidthLabel: 'Minimum bredde',
        MaxWidthLabel: 'Maks bredde',
        IsMultilineLabel: 'Flere linjer',
        IsResizableLabel: 'Justerbar',
        SaveButtonLabel: 'Lagre',
        CloseButtonLabel: 'Lukk',
        GroupByColumnLabel: 'Grupper etter {0}',
        FilterBy: 'Filtrer etter',
        DataSourceCategoryLabel: 'Kategori for datakilder',
        DataSourceLabel: 'Datakilde',
        SortDescLabel: 'A til Å',
        SortAscLabel: 'Å til A',
        ColumSettingsLabel: 'Kolonneinnstillinger',
        ActorsLabel: 'Aktører',
        AdvancedGroupName: 'Avansert',
        BenefitResponsibleLabel: 'Gevinstansvarlig',
        BenefitOwnerLabel: 'Gevinsteier',
        BenefitTitleLabel: 'Gevinst',
        BenefitsTitle: 'Gevinster',
        BenefitDataSource: 'Gevinstoversikt',
        ChartConfigurationListNameLabel: 'Grafkonfigurasjon',
        ChartErrorText: 'Grafen er ugyldig konfigurert.',
        ColumnConfigListNameLabel: 'Kolonnekonfigurasjon',
        LoadingTextLabel: 'Laste-tekst',
        EmptyMessageLabel: 'Tekst ved ingen elementer',
        RowLimitLabel: 'Antal elementer',
        LoadingTextDescription: 'Tekst som vises mens webdelen lastes.',
        EmptyMessageDescription: 'Tekst som vises om det ikke er noen prosjekter.',
        ColumnsListNameLabel: 'Kolonner',
        CommandBarGroupName: 'Kommandolinje',
        ConfigurationGroupName: 'Konfigurasjon',
        ConsequenceLabel: 'Konsekvens (K)',
        ConsequencePostActionLabel: 'K etter tiltak',
        CreatedText: 'Opprettet',
        DataSourceCategoryError: 'Det skjedde en feil under uthenting av datakilder med kategori **{0}**.',
        DataSourceError: 'Det skjedde en feil under uthenting av data fra datakilde med navn **{0}**.',
        DataSourceNotFound: 'Finner ingen datakilde med navn **{0}**.',
        DefaultViewLabel: 'Standardvisning',
        DeliveryDescriptionLabel: 'Leveransebeskrivelse',
        DeliveryEndTimeLabel: 'Sluttidspunkt',
        DeliveryStartTimeLabel: 'Starttidspunkt',
        DeliveryStatusCommentLabel: 'Kommentar, leveransestatus',
        DeliveryStatusLabel: 'Leveransestatus',
        DeliveriesTitle: 'Leveranser',
        DesiredValueLabel: 'Ønsket verdi',
        DescriptionFieldLabel: 'Beskrivelse',
        DeliveriesDatasource: 'Alle prosjektleveranser',
        WebPartTitleLabel: 'Navn på webpart',
        SettingsLabel: 'Innstillinger',
        EditViewText: 'Rediger gjeldende visning',
        ErrorText: 'Det skjedde en feil under uthenting av prosjekter.',
        ExcelExportButtonLabel: 'Eksporter til Excel',
        ExcelExportFileNamePrefix: 'Gevinstoversikt',
        FetchDataErrorMessage: 'Det skjedde en feil under uthenting av data.',
        FieldSelectorEmptyMessage: 'Det er ikke konfigurert opp noen felter. Ta kontakt med en administrator.',
        FieldSelectorName: 'Felter',
        FiltersString: 'Filtre',
        FilterText: 'Filtrer',
        GeneralGroupName: 'Generelt',
        GetConfigErrorMessage: 'Det skjedde en feil under uthenting av konfigurasjon.',
        IndicatorLabel: 'Måleindikator',
        LastMeasurementLabel: 'Siste måling',
        LoadingText: 'Laster {0}...',
        LogDescriptionLabel: 'Loggbeskrivelse',
        MeasuremenentIdicatorLabel: 'Måleindikator',
        MeasurementAchievementLabel: 'Måloppnåelse',
        MeasurementCommentLabel: 'Kommentar til måling',
        MeasurementDateLabel: 'Dato for måling',
        MeasurementValueLabel: 'Målt verdi',
        MissingProperties: 'Prosjektet mangler egenskaper',
        NewViewText: 'Opprett ny visning',
        NoDefaultViewMessage: 'Det er ikke satt noen standardvisning.',
        NoGroupingText: 'Ingen gruppering',
        NoProperties: 'Det er ikke satt noen egenskaper for prosjektet',
        NoSearchResults: 'Søket ga ingen resultater',
        NotSet: 'Ikke satt',
        PhaseLabel: 'Fase',
        ProbabilityLabel: 'Sannsynlighet (S)',
        ProbabilityPostActionLabel: 'S etter tiltak',
        ProjectInformationGroupName: 'Instillinger for Prosjektinformasjon-vindu',
        ProjectLinkText: 'Gå til prosjektområde',
        ProjectManager: 'Prosjektleder',
        ProjectOwner: 'Prosjekteier',
        ProjectStatusLinkText: 'Gå til prosjektstatus',
        RecommendationLabel: 'Anbefaling',
        ProjectTimelineInfoText: 'Her listes alle prosjektene med start- og sluttdato. Prosjekttidslinjen støtter også faser, delfaser og milepæler, dette opprettes i den<A HREF="../Lists/Tidslinjeinnhold/AllItems.aspx?Source={0}">sentrale tidslinjeinnhold listen</A>. Prosjekter vises med rød farge, faser i blått, delfaser blågrønt, og milepæler i gult. For å zoome inn/ut i tidslinje: ALT+Musehjul',
        ResourceAllocationInfoText: 'Ressursallokering eller fravær som gjelder på tvers av prosjekter legges inn i den<A HREF="../Lists/Ressursallokering/AllItems.aspx?Source={0}">sentrale ressursallokeringslisten</A>. Disse oppføringene vil vises med blå og rød (fravær) farge i tabellen under. Prosjektallokeringer vises med grønn farge. Fargestyrken til allokeringen baserer seg på allokeringsprosenten.',
        ResourceLabel: 'Ressurs',
        ResponsibleLabel: 'Ansvarlig',
        RoleLabel: 'Rolle',
        AllocationPercetageLabel: 'Allokeringsprosent',
        AllocationStatusLabel: 'Allokeringsstatus',
        CommentLabel: 'Kommentar',
        SaveViewAsText: 'Lagre visning som',
        SearchBoxPlaceholderText: 'Søk i {0}...',
        SearchBoxPlaceholderTextLabel: 'Søkebokstekst',
        ShowAllMeasurementsLinkText: 'Vis alle målinger',
        ShowAsListText: 'Vis som liste',
        ShowAsTilesLabel: 'Vis som fliser',
        ShowAsTilesText: 'Vis som fliser',
        ShowCommandBarLabel: 'Vis kommandolinje',
        ShowExcelExportButtonLabel: 'Vis eksport til Excel-knapp',
        ShowFiltersLabel: 'Vis filtre',
        ShowGroupByLabel: 'Vis grupperingsvalg',
        ShowProjectLogoFieldLabel: 'Vis logo',
        ShowProjectManagerFieldLabel: 'Vis Prosjektleder',
        ShowProjectOwnerFieldLabel: 'Vis Prosjekteier',
        ShowSearchBoxLabel: 'Vis søkeboks',
        ShowViewSelectorLabel: 'Vis visningsvelger',
        SiteTitleLabel: 'Prosjekt',
        SortByFieldLabel: 'Sorteringsegenskap',
        StartValueLabel: 'Startverdi',
        StatusReportsCountLabel: 'Antal rapporter å vise',
        TileViewGroupName: 'Flisevisning',
        TitleLabel: 'Tittel',
        UnitLabel: 'Måleenhet',
        TypeLabel: 'Type',
        ViewNotFoundMessage: 'Finner ikke angitt visning.',
        ViewsListNameLabel: 'Visninger',
        SelectedColumnsLabel: 'Felter',
        ProjectsListName: 'Prosjekter',
        TimelineContentListName: 'Tidslinjeinnhold',
        TimelineConfigurationListName: 'Tidslinjekonfigurasjon',
        PortfolioManagerGroupName: 'Porteføljeinnsyn',
        ProjectTimelineItemInfo: '{0} - prosjektets tidsforløp',
        LastPublishedStatusreport: 'Gå til siste statusrapport',
        DiamondLabel: 'Diamant',
        BarLabel: 'Bar',
        TriangleLabel: 'Trekant',
        MilestoneLabel: 'Milepæl',
        ProjectLabel: 'Prosjekt',
        SubPhaseLabel: 'Delfase',
        CurrentPhaseLabel: 'Gjeldende fase',
        MilestoneDateLabel: 'Milepælsdato',
        NameLabel: 'Navn',
        StartDateLabel: 'Startdato',
        EndDateLabel: 'Sluttdato',
        BudgetTotalLabel: 'Totalbudsjett',
        CostsTotalLabel: 'Kostnader påløpt totalt',
        NoProjectsFound: 'Ingen prosjekter funnet.',
        NewLabel: 'Ny',
        DisplayAllProjects: 'Vis alle prosjekter',
        MyProjectsLabel: 'Mine prosjekter',
        AllProjectsLabel: 'Alle prosjekter',
        NoAccessMessage: 'Du har ikke tilgang til dette prosjektet',
        ProgramAdministrationEmptyMessage: 'Ingen områder er koblet til programmet.',
        ProgramTimelineHeader: 'Tidslinje',
        ProgramAdministrationAddChildsButtonText: 'Legg til prosjekter',
        ProgramAdministrationHeader: 'Administrasjon av underordnede områder',
        ProgramAdministrationInfoMessage: 'Velg en eller flere prosjekter du ønsker å knytte til området. Området vil dukke opp som forelder, for prosjektene som er valgt, under Prosjektinformasjon.',
        ProgramRemoveChildsButtonText: 'Fjern underordnede områder',
        RiskDataSource: 'Programrisiko',
        Add: 'Legg til',
        Cancel: 'Avbryt',
        AddProjectDialogSearchBoxPlaceholder: 'Søk i prosjekter...',
        ProgramAdministrationSearchBoxPlaceholder: 'Søk i programmets områder...',
        Yes: 'Ja',
        No: 'Nei',
        PreviousPage: 'Forrige side',
        NextPage: 'Neste side',
        ProjectDeliveriesGroupName: 'Prosjektleveranser (beta)',
        ShowProjectDeliveriesLabel: 'Vis prosjektleveranser',
        ConfigItemTitleFieldLabel: 'Element tittel (konfigurasjon)',
        ConfigItemTitleFieldDescription: 'Dersom det er spesifisert et element med tittelen angitt her i tidslinjekonfigurasjon listen så vil dette vises på tidslinjen.',
        ProjectContentColumnsListName: 'Prosjektinnholdskolonner',
        UseChangesButtonText: 'Bruk',
        ColumnSettingsLabel: 'Kolonneinnstillinger'
    }
})
