define([], function () {
  return {
    ResultsCountLabel: 'Viser {0} av {1} prosjekter',
    Aria: {
      MenuOverflowCount: '{0} flere elementer',
      MoveDisabled: 'Kan ikke flytte skjult kolonne',
      MoveUp: 'Flytt opp',
      MoveUpDisabled: 'Kan ikke flytte opp, øverste element',
      MoveDown: 'Flytt ned',
      MoveDownDisabled: 'Kan ikke flytte ned, nederste element',
    },
    Placeholder: {
      TextField: 'Angi verdi her',
      Icon: 'Angi et ikon',
      ChoiceField: 'Velg et alternativ',
      MultiChoiceField: 'Velg ett eller flere alternativer',
    },
    Add: 'Legg til',
    AddColumnLabel: 'Legg til en kolonne',
    AddColumnLabel: 'Legg til en kolonne',
    AddProjectDialogSearchBoxPlaceholder: 'Søk i prosjekter...',
    BarLabel: 'Bar',
    BooleanNo: 'Nei',
    BooleanOff: 'Av',
    BooleanOn: 'På',
    BooleanYes: 'Ja',
    Cancel: 'Avbryt',
    CancelButtonLabel: 'Avbryt',
    ChildrenRemoveToastMessage: 'Fjerning av underområder er fullført.',
    ChildrenRemoveToastTitle: 'Underområder fjernet',
    CmdSelectionCountText: '{0} er merket',
    CmdSelectionCountTooltipText: 'Følgende prosjekter er valgt:',
    ColumnCategoryDescription: 'Angi en kategori for kolonnen. Kolonnen vil dukke opp i alle visninger som bruker denne kategorien. Om du ønsker å endre kategorien for alle webdeler og visninger, kan du endre kategorien i listen Prosjektkolonner.',
    ColumnCategoryLabel: 'Kategori for kolonnen',
    ColumnPersistRenderGloballyFieldDescription: 'Om du ønsker å endre visningsmodus for kolonnen globaly, for alle webdeler og visninger, huk av sjekkboksen over. (Dette gjelder kun visningsmodus)',
    ColumnPersistRenderGloballyFieldLabel: 'Oppdater visningsmodus globalt',
    ColumnRenderDataTypePropertiesHeaderText: 'Egenskaper for visningsmodus',
    ColumnRenderDescription: 'Velg hvordan kolonnen skal vises. Om det er tekstfelt som skal vises over flere linjer, velg Notat.',
    ColumnRenderLabel: 'Visningsmodus',
    ColumnRenderOptionBoolean: 'Ja/nei',
    ColumnRenderOptionBooleanFalse: 'Verdi for \'Nei\'',
    ColumnRenderOptionBooleanTrue: 'Verdi for \'Ja\'',
    ColumnRenderOptionCurrency: 'Valuta',
    ColumnRenderOptionCurrencyFallbackValueLabel: 'Standardverdi',
    ColumnRenderOptionCurrencyMaximumFractionDigitsLabel: 'Maksimalt antall desimaler',
    ColumnRenderOptionCurrencyMinimumFractionDigitsLabel: 'Minimum antall desimaler',
    ColumnRenderOptionCurrencyPrefixLabel: 'Valutaprefiks',
    ColumnRenderOptionDate: 'Dato',
    ColumnRenderOptionDateIncludeTimeLabel: 'Inkluder tidspunkt',
    ColumnRenderOptionInstrument: 'Instrument',
    ColumnRenderOptionDialog: 'Modal',
    ColumnRenderOptionDialogInfoTextTemplateDescription: 'Mal for infotekst. Bruk {{GtMeasurementOWSCHCS}} for å vise måleindikatoren, {{GtStartValueOWSNMBR}} for å vise startverdien og {{GtDesiredValueOWSNMBR}} for å vise målet. Du kan også bruke andre kolonnenavn fra gevinstarbeidet.',
    ColumnRenderOptionDialogInfoTextTemplateLabel: 'Mal for infotekst',
    ColumnRenderOptionDialogLinkTextLabel: 'Tekst for lenke',
    ColumnRenderOptionDialogShowInfoTextLabel: 'Vis infotekst',
    ColumnRenderOptionFilename: 'Filnavn',
    ColumnRenderOptionNote: 'Notat',
    ColumnRenderOptionNumber: 'Tall',
    ColumnRenderOptionPercentage: 'Prosent',
    ColumnRenderOptionProjectInfo: 'Prosjektinformasjon',
    ColumnRenderOptionTags: 'Etiketter',
    ColumnRenderOptionTagsValueSeparatorDescription: 'Angi et tegn som skal brukes for å skille verdier i etikettfeltet. Standard er semikolon.',
    ColumnRenderOptionTagsValueSeparatorLabel: 'Separator for verdier',
    ColumnRenderOptionText: 'Tekst',
    ColumnRenderOptionTrend: 'Trend',
    ColumnRenderOptionTrendShowTrendIconLabel: 'Vis ikon',
    ColumnRenderOptionUrl: 'URL',
    ColumnRenderOptionUrlDescriptionDescription: 'Beskrivelse av lenken. Om du ikke angir en verdi, brukes eventuelt beskrivelse fra lenken.',
    ColumnRenderOptionUrlDescriptionLabel: 'Beskrivelse',
    ColumnRenderOptionUrlOpenInNewTabLabel: 'Åpne i ny fane',
    ColumnRenderOptionUser: 'Person',
    ColumnSettingsDisabledTooltip: 'Kolonneinnstillinger er kun tilgjengelig når siden er i redigeringsmodus.',
    ColumnSettingsLabel: 'Kolonneinnstillinger',
    ColumnsListNameLabel: 'Kolonner',
    ColumnVisibilityDescription: 'Angi hvor kolonnen skal vises. Prosjektforside, prosjektstatus-siden, porterføljeoversikten eller alle steder.',
    ColumnVisibilityLabel: 'Synlighet for kolonne',
    CommandBarGroupName: 'Kommandolinje',
    CompactViewText: 'Kompakt liste',
    ConfigItemTitleFieldDescription: 'Dersom det er spesifisert et element med tittelen angitt her i tidslinjekonfigurasjon listen så vil dette vises på tidslinjen.',
    ConfigItemTitleFieldLabel: 'Element tittel (konfigurasjon)',
    ConfirmDeleteProjectColumnSubText: 'Denne kolonnen fjernes fra Prosjektkolonner-listen og dermed fra alle visninger som bruker den. Er du sikker på at du vil slette denne kolonnen? Om du kun ønsker å fjerne kolonnen fra denne visningen, kan du bruke \'Vis eller skjul kolonner\'.',
    ConfirmDeleteProjectColumnTitle: 'Vil du slette?',
    ConfirmDeleteProjectContentColumnSubText: 'Denne kolonnen fjernes fra Prosjektinnholdskolonner-listen og dermed fra alle visninger som bruker den. Er du sikker på at du vil slette denne kolonnen? Om du kun ønsker å fjerne kolonnen fra denne visningen, kan du bruke \'Vis eller skjul kolonner\'.',
    ConfirmDeleteProjectContentColumnTitle: 'Vil du slette?',
    ConfirmDeleteResponseAbort: 'Avbryt',
    ConfirmDeleteResponseConfirm: 'Slett',
    CustomSortsText: 'Egendefinert sortering',
    DataSourceCategoryDescription: 'Angi en datakildekategori for å kunne velge mellom flere datakilder i webdelen.',
    DataSourceCategoryError: 'Det skjedde en feil under uthenting av datakilder med kategori **{0}**.',
    DataSourceCategoryLabel: 'Kategori for datakilder',
    DataSourceError: 'Det skjedde en feil under uthenting av data fra datakilde med navn **{0}**. Oppdater siden og prøv igjen.',
    DataSourceGroupName: 'Datakilder',
    DataSourceLabel: 'Datakilde',
    DataSourceLevelDescription: 'Velg nivå for datakilde. Kun datakilder med dette nivået vil være tilgjengelig i webdelen.',
    DataSourceLevelLabel: 'Nivå for datakilde',
    DataSourceNotFound: 'Finner ingen datakilde med navn **{0}**.',
    DefaultDataSourceViewLabel: 'Standardvisning (datakilde)',
    DefaultViewDescription: 'Velg om dette er standardvisningen for Porteføljeoversikten.',
    DefaultViewLabel: 'Standardvisning',
    DefaultViewSetWarningMessage: 'Det er allerede en visning som er satt som standard. Du må først endre denne visningen før du kan sette en ny som standard. Personlige visninger kan ikke settes som standard.',
    DeleteButtonLabel: 'Slett',
    DisplayNameDescription: 'Visningsnavn for denne kolonnen, kun for denne webdelen. Om du ønsker å endre visningsnavnet for alle webdeler, må du endre det i listen Prosjektinnholdskolonner.',
    DisplayNameLabel: 'Visningsnavn',
    DisplayNamePortfolioOverviewDescription: 'Visningsnavn for denne kolonnen.',
    EditColumnLabel: 'Rediger',
    EditViewColumnsPanelHeaderText: 'Rediger visningskolonner',
    EditViewColumnsPanelHelpText: 'Velg kolonnene som skal vises for nåværende visning. Hvis du vil endre rekkefølgen, kan du dra og slippe eller bruke opp- og ned-pilen ved siden av hver kolonne.',
    EditViewHeaderText: 'Rediger visning',
    EditViewText: 'Rediger gjeldende visning',
    ErrorTitle: 'Det har oppstått en feil',
    ExcelExportButtonLabel: 'Eksporter til Excel',
    FilterText: 'Filtrer',
    GeneralGroupName: 'Generelt',
    GroupByColumnLabel: 'Grupper etter {0}',
    IconNameDescription: 'Navn på ikon fra UI Fabric. Se oversikt på https://uifabricicons.azurewebsites.net/.',
    IconNameLabel: 'Ikonnavn',
    InternalNameDescription: 'Internt feltnavn for denne kolonnen.',
    InternalNameLabel: 'Internt feltnavn',
    IsGroupableDescription: 'Brukere kan gruppere på denne kolonnen.',
    IsGroupableLabel: 'Grupperbar',
    IsRefinableDescription: 'Brukere kan filtrere på denne kolonnen.',
    IsRefinableLabel: 'Presiser',
    IsResizableLabel: 'Justerbar',
    ListViewText: 'Liste',
    MaxWidthDescription: 'Maksimum bredde for kolonnen. Kan ikke være mindre enn minimum bredde.',
    MaxWidthLabel: 'Maks bredde',
    MeasurementAchievementLabel: 'Måloppnåelse',
    MeasurementCommentLabel: 'Kommentar til måling',
    MeasurementDateLabel: 'Dato for måling',
    MeasurementValueLabel: 'Målt verdi',
    MinWidthDescription: 'Minimum bredde for kolonnen. Kan ikke overstige maksimum bredde.',
    MinWidthLabel: 'Minimum bredde',
    MoveLeftLabel: 'Flytt til venstre',
    MoveRightLabel: 'Flytt til høyre',
    NewColumnHeaderText: 'Ny kolonne',
    NewViewHeaderText: 'Opprett visning',
    NewViewText: 'Opprett ny visning',
    PersonalViewDescription: 'Velg om dette er en personlig visning. Personlige visninger kan kun redigeres av deg.',
    PersonalViewLabel: 'Personlig visning',
    PersonalViewsHeaderText: 'Personlige visninger',
    PortfolioAggregationViewSearchQueryDescription: 'Søkespørringen for å hente data. DepartmentId refererer til Prosjektportalen-huben og bør ikke endres. ContentTypeId refererer til innholdstypen til dataelementet du vil hente. Gå til Datakilder-listen for å se eksempler.',
    PortfolioManagerGroupName: 'Porteføljeinnsyn',
    PortfolioViewSearchQueryDescription: 'Søkespørringen for å hente prosjekter i porteføljen. DepartmentId refererer til Prosjektportalen-huben og bør ikke endres.',
    ProgramAdministrationAddChildsButtonDescription: 'Her kan du legge til underordnede områder.',
    ProgramAdministrationAddChildsButtonLabel: 'Legg til underområder',
    ProgramAdministrationEmptyMessage: 'Det er ingen områder som er koblet til programmet. For å koble til områder, klikk på knappen _Legg til prosjekter_ over.',
    ProgramAdministrationEmptyTitle: 'Ingen områder er koblet til programmet.',
    ProgramAdministrationHeader: 'Administrasjon av underområder',
    ProgramAdministrationInfoMessage: 'Her får du muligheten til å legge til underordnede områder. Disse vil dukke opp i aggregerte oversikter og tidslinje inne på området. Området vil dukke opp som forelder for prosjektene som er valgt under Prosjektinformasjon.',
    ProgramAdministrationSearchBoxPlaceholder: 'Søk i underområder...',
    ProgramRemoveChildsButtonDescription: 'Fjern ett eller flere underordnede områder.',
    ProgramRemoveChildsButtonLabel: 'Fjern underområder',
    ProgramRemoveChildsDeletingLabel: 'Fjerner underområder...',
    ProgramTimelineInfoText: "Her listes alle prosjektene med start- og sluttdato som er tilknyttet området. For å zoome inn/ut i tidslinje: ALT+Musehjul",
    ProjectContentColumnsListName: 'Prosjektinnholdskolonner',
    ProjectDeliveriesGroupName: 'Prosjektleveranser (beta)',
    ProjectInformationPanelButton: 'Åpne prosjektinformasjonspanel',
    ProjectLabel: 'Prosjekt',
    ProjectPropertiesHeader: 'Prosjektinformasjon',
    ProjectsListName: 'Prosjekter',
    SaveButtonLabel: 'Lagre',
    SearchBoxGroupName: 'Søkeboks',
    SearchBoxPlaceholderText: 'Søk i {0}...',
    SearchBoxPlaceholderTextDescription: 'Tekst som vises i søkeboksen når den er tom. Om det ikke settes en verdi baseres teksten på valgt datakilde.',
    SearchBoxPlaceholderTextLabel: 'Søkebokstekst',
    SearchPropertyDescription: 'Navnet på den forvaltede egenskapen for denne kolonnen.',
    SearchPropertyFoundMessage: 'Fant en forvaltet egenskap `{0}` som matcher det interne feltnavnet `{1}`.',
    SearchPropertyFoundTitle: 'Forvaltet egenskap funnet',
    SearchPropertyLabel: 'Søkeegenskap',
    SearchPropertyPlaceholder: 'Søk i forvaltede egenskaper...',
    SearchQueryLabel: 'Søkespørring',
    ShowAllMeasurementsLinkText: 'Vis alle målinger',
    ShowInstrumentLinkText: '{0} (vis instrument)',
    ShowCommandBarLabel: 'Vis kommandolinje',
    ShowExcelExportButtonLabel: 'Vis eksport til Excel-knapp',
    ShowFieldFrontpageLabel: 'Prosjektforside',
    ShowFieldPortfolioLabel: 'Porteføljeoversikt',
    ShowFieldProjectStatusLabel: 'Prosjektstatus',
    ShowFiltersLabel: 'Vis filtre',
    ShowGroupByLabel: 'Vis grupperingsvalg',
    ShowHideColumnsLabel: 'Vis eller skjul kolonner',
    ShowSearchBoxLabel: 'Vis søkeboks',
    ShowViewSelectorLabel: 'Vis visningsvelger',
    SortAscLabel: 'Å til A',
    SortDescLabel: 'A til Å',
    SortOrderDescription: 'Sorteringsrekkefølgen bestemmer hvilken rekkefølge visningene vises i. Lavest verdi vises først.',
    SortOrderLabel: 'Sorteringsrekkefølge',
    TitleDescription: 'Tittel for visningen.',
    TitleLabel: 'Tittel',
    ToggleColumnFormPanelLabel: 'Legg til kolonne',
    UseChangesButtonText: 'Bruk',
    ViewNotFoundMessage: 'Finner ikke angitt visning.',
    DataSourceItemNotFound: 'Datakilde ble ikke funnet',
    DataSourceListName: 'Datakilder',
    ProjectContentColumnItemNotFound: 'Prosjektinnholdskolonne ble ikke funnet',
  }
})
