name: CI - Build and install (feature/flexible-portfolio-aggregation-views-webparts-394)

on:
  push:
    branches: [feature/flexible-portfolio-aggregation-views-webparts-394]

env:
  TARGET_URL: 'https://puzzlepart.sharepoint.com/sites/pp365'

jobs:
   build-release:
    runs-on: windows-latest
    
    steps:      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Run Install/Build-Release.ps1 in CI mode
      run: Install/Build-Release.ps1 -CI
      shell: powershell
      
    - uses: actions/upload-artifact@v1
      with:
        name: release-package
        path: release
        
   install-script:
    needs: build-release
    runs-on: windows-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: release-package

    - name: Upgrade
      run: release-package/Install.ps1 -Url ${{ env.TARGET_URL }} -Upgrade -CI ${{ secrets.CI_DEV_CREDENTIALS }}
      shell: powershell

    - name: Install
      run: release-package/Install.ps1 -Url "${{ env.TARGET_URL }}_${{ github.run_id }}" -Title "Prosjektportalen 365 ${{ github.run_id }}" -CI ${{ secrets.CI_DEV_CREDENTIALS }} -SkipAppPackages -SkipSiteDesign -SkipTaxonomy
      shell: powershell