name: Build release (main)

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-release:
    name: Build release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Install/Build-Release.ps1 in CI mode
        run: Install/Build-Release.ps1 -CI -SkipBuildSharePointFramework
        shell: powershell
      
      - uses: actions/upload-artifact@v1
        with:
          name: release-package
          path: release

  create-release:
    name: Create release
    runs-on: ubuntu-18.04
    needs: [build-release]
    env:
      SHA8: ${GITHUB_SHA::8}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-package
          path: release-package

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release-package.zip'
          path: release-package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false

      - name: Read package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-package.zip
          asset_name: "pp365-${{ steps.package-node-version.outputs.version }}.zip"
          asset_content_type: application/zip
