name: CI - Build and install

on:
  push:
    branches: [dev]

env:
  TARGET_URL: 'https://puzzlepart.sharepoint.com/sites/pp365_ci'
  
jobs:
   build:
    runs-on: windows-latest
    
    steps:      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
      
    - name: Run build release script Install/Build-Release.ps1 in CI mode
      run: Install/Build-Release.ps1 -CI
      shell: powershell
      
    - uses: actions/upload-artifact@v1
      with:
        name: release-package
        path: release
        
   install:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: release-package
    - name: Install to ${{ env.TARGET_URL }}
      run: release-package/Install.ps1 -Url ${{ env.TARGET_URL }} -Upgrade -CI ${{ secrets.CI_CREDENTIALS }}
      shell: powershell
      
    - uses: actions/upload-artifact@v1
      with:
        name: installation-log
        path: release-package/Install_Log.txt

