name: CI - Build and install (cache)

on:
  push:
    branches: [dev]

env:
  TARGET_URL: 'https://puzzlepart.sharepoint.com/sites/pp365_ci'
  
jobs:
   build:
    runs-on: windows-latest
    
    steps:      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: (@Shared) Cache node modules
      id: shared_node_modules_cache
      uses: actions/cache@v2
      with:
       path: SharePointFramework/@Shared/node_modules
       key: node-modules-${{ hashFiles('SharePointFramework/@Shared/package.json') }}

    - name: (PortfolioWebParts) Cache node modules
      id: portfolio_webparts_node_modules_cache
      uses: actions/cache@v2
      with:
        path: SharePointFramework/PortfolioWebParts/node_modules
        key: node-modules-${{ hashFiles('SharePointFramework/PortfolioWebParts/package.json') }}

    - name: (ProjectExtensions) Cache node modules
      id: project_extensions_node_modules_cache
      uses: actions/cache@v2
      with:
        path: SharePointFramework/ProjectExtensions/node_modules
        key: node-modules-${{ hashFiles('SharePointFramework/ProjectExtensions/package.json') }}

    - name: (ProjectWebParts) Cache node modules
      id: project_webparts_node_modules_cache
      uses: actions/cache@v2
      with:
        path: SharePointFramework/ProjectWebParts/node_modules
        key: node-modules-${{ hashFiles('SharePointFramework/ProjectWebParts/package.json') }}

    - name: (@Shared) NPM install npm packages
      if: steps.shared_node_modules_cache.outputs.cache-hit != 'true'
      working-directory: SharePointFramework/@Shared
      run: npm install

    - name: (PortfolioWebParts) NPM install npm packages
      if: steps.portfolio_webparts_node_modules_cache.outputs.cache-hit != 'true'
      working-directory: SharePointFramework/PortfolioWebParts
      run: npm install

    - name: (ProjectExtensions) NPM install npm packages
      if: steps.project_extensions_node_modules_cache.outputs.cache-hit != 'true'
      working-directory: SharePointFramework/ProjectExtensions
      run: npm install

    - name: (ProjectWebParts) NPM install npm packages
      if: steps.project_webparts_node_modules_cache.outputs.cache-hit != 'true'
      working-directory: SharePointFramework/ProjectWebParts
      run: npm install

    - name: Run Install/Build-Release.ps1 in CI mode
      run: Install/Build-Release.ps1 -CI
      shell: powershell
      
    - uses: actions/upload-artifact@v1
      with:
        name: release-package
        path: release
        
   install:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: release-package
    - name: Install to ${{ env.TARGET_URL }}
      run: release-package/Install.ps1 -Url ${{ env.TARGET_URL }} -Upgrade -CI ${{ secrets.CI_CREDENTIALS }}
      shell: powershell
