name: CI - Build and install 

on:
  push:
    branches: [master]

jobs:
   build-release:
    runs-on: windows-latest
    
    steps:      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Run Install/Build-Release.ps1 in CI mode
      run: Install/Build-Release.ps1 -CI
      shell: powershell
      
    - uses: actions/upload-artifact@v1
      with:
        name: release-package
        path: release
        
   install-script:
    needs: build-release
    runs-on: windows-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: release-package

    - name: Install to CI_MASTER_TARGET_URL
      run: release-package/Install.ps1 -Url ${{ secrets.CI_MASTER_TARGET_URL }} -Upgrade -CI ${{ secrets.CI_MASTER_CREDENTIALS }}
      shell: powershell