name: CI (channels)

on:
  push:
    branches:
      - feat/channel-support
    paths:
      - "SharePointFramework/**"
      - "Install/**"
      - "Templates/**"

env:
  SP_URL: "https://puzzlepart.sharepoint.com/sites/pp365_channel_test"
  CI_CREDENTIALS: ${{ secrets.CI_DEV_CREDENTIALS }}

jobs:
  build_release_package:
    name: Build release package for test channel
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set sha_short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Setup Node.js 16.18.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0

      - name: Run Install/Build-Release.ps1 in CI mode for channel test
        run: Install/Build-Release.ps1 -CI -SkipBundle -Channel test
        shell: pwsh

      - uses: actions/upload-artifact@v3
        with:
          name: release-package
          path: release
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

  install:
    needs: [build_release_package]
    name: Install (test)
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip-install]')"
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-package
          path: release

      - name: Install
        run: release/Install.ps1 -Url "${{ env.SP_URL }}" -Title "Prosjektportalen 365 (test)" -CI ${{ env.CI_CREDENTIALS }} -SkipTaxonomy -SkipSearchConfiguration
        shell: powershell