name: CI (channels/test)

on:
  push:
    branches:
      - releases/1.11
      - main
    paths:
      - 'SharePointFramework/**'
      - 'Install/**'
      - 'Templates/**'
      - .github/workflows/ci-channel-test.yml

env:
  CI_CERT_BASE64: ${{ secrets.CI_CERT_BASE64 }}
  CI_TENANT: ${{ secrets.CI_TENANT }}
  CI_CLIENT_ID: ${{ secrets.CI_CLIENT_ID }}

jobs:
  build_release_package_test:
    name: Build release package (test channel)
    runs-on: macos-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') && !contains(github.event.head_commit.message, '[packages-only]') }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set sha_short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Run Install/Build-Release.ps1 in CI mode for channel test
        run: Install/Build-Release.ps1 -CI -SkipBundle -Channel test
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: release-package-test
          path: release
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

  upgrade_channel_test:
    needs: [build_release_package_test]
    name: Upgrade (test channel)
    runs-on: macos-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-upgrade]') }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-package-test
          path: release

      - name: Upgrade
        run: release/Install.ps1 -Url "${{ vars.SP_URL_TEST }}" -Upgrade -CI -Tenant ${{ env.CI_TENANT }} -CertificateBase64Encoded ${{ env.CI_CERT_BASE64 }} -ClientId ${{ env.CI_CLIENT_ID }}
        shell: powershell

  upgrade_all_sites_to_latest:
    needs: [build_release_package_test, upgrade_channel_test]
    name: Upgrade all sites to latest (test channel)
    runs-on: macos-latest
    if: ${{ contains(github.event.head_commit.message, '[upgrade-all-sites-to-latest]') }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-package-test
          path: release

      - name: Run script UpgradeAllSitesToLatest.ps1 in CI mode
        run: release/Scripts/UpgradeAllSitesToLatest.ps1 -Url ${{ vars.SP_URL_TEST }} -CI -Tenant ${{ env.CI_TENANT }} -CertificateBase64Encoded ${{ env.CI_CERT_BASE64 }} -ClientId ${{ env.CI_CLIENT_ID }}
        shell: powershell

  build_release_package_test_packages_only:
    name: Build release package - packages only (test channel)
    runs-on: macos-latest
    if: ${{ contains(github.event.head_commit.message, '[packages-only]')}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set sha_short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Run Install/Build-Release.ps1 in CI mode for channel test
        run: Install/Build-Release.ps1 -CI -SkipBundle -SkipBuildPnPTemplates -Channel test
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: release-package-test
          path: release
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

  upgrade_channel_test_packages_only:
    needs: [build_release_package_test_packages_only]
    name: Upgrade packages only (test channel)
    runs-on: macos-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-upgrade]') }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-package-test
          path: release

      - name: Upgrade
        run: release/Install.ps1 -Url "${{ vars.SP_URL_TEST }}" -Upgrade -CI -Tenant ${{ env.CI_TENANT }} -CertificateBase64Encoded ${{ env.CI_CERT_BASE64 }} -ClientId ${{ env.CI_CLIENT_ID }} -SkipTemplate
        shell: powershell
