name: CI (channels/arkiv)

on:
  push:
    branches:
      - feat/archive
    paths:
      - 'SharePointFramework/**'
      - 'Install/**'
      - 'Templates/**'
      - .github/workflows/ci-channel-arkiv.yml

env:
  CI_CERT_BASE64: ${{ secrets.CI_CERT_BASE64 }}
  CI_TENANT: ${{ secrets.CI_TENANT }}
  CI_CLIENT_ID: ${{ secrets.CI_CLIENT_ID }}
  SP_URL_ARKIV: https://puzzlepart.sharepoint.com/sites/pp365-arkiv

jobs:
  build_release_package_arkiv:
    name: Build release package (arkiv channel)
    runs-on: macos-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') && !contains(github.event.head_commit.message, '[apps-only]') }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Run Install/Build-Release.ps1 in CI mode for channel arkiv
        run: Install/Build-Release.ps1 -CI -SkipBundle -Channel arkiv
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: release-package-arkiv
          path: release

  upgrade_channel_arkiv:
    needs: [build_release_package_arkiv]
    name: Upgrade (arkiv channel)
    runs-on: macos-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-upgrade]') }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-package-arkiv
          path: release

      - name: Upgrade
        run: release/Install.ps1 -Url "${{ env.SP_URL_ARKIV }}" -Upgrade -CI -Tenant ${{ env.CI_TENANT }} -CertificateBase64Encoded ${{ env.CI_CERT_BASE64 }} -ClientId ${{ env.CI_CLIENT_ID }}
        shell: powershell

  upgrade_all_sites_to_latest:
    needs: [build_release_package_arkiv, upgrade_channel_arkiv]
    name: Upgrade all sites to latest (arkiv channel)
    runs-on: macos-latest
    if: ${{ contains(github.event.head_commit.message, '[upgrade-all-sites-to-latest]') }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-package-arkiv
          path: release

      - name: Run script UpgradeAllSitesToLatest.ps1 in CI mode
        run: release/Scripts/UpgradeAllSitesToLatest.ps1 -Url ${{ env.SP_URL_ARKIV }} -CI -Tenant ${{ env.CI_TENANT }} -CertificateBase64Encoded ${{ env.CI_CERT_BASE64 }} -ClientId ${{ env.CI_CLIENT_ID }}
        shell: powershell

  build_release_package_arkiv_packages_only:
    name: Build release package - packages only (arkiv channel)
    runs-on: macos-latest
    if: ${{ contains(github.event.head_commit.message, '[apps-only]') }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Run Install/Build-Release.ps1 in CI mode for channel arkiv
        run: Install/Build-Release.ps1 -CI -SkipBundle -SkipBuildPnPTemplates -Channel arkiv
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: release-package-arkiv
          path: release

  upgrade_channel_arkiv_packages_only:
    needs: [build_release_package_arkiv_packages_only]
    name: Upgrade packages only (arkiv channel)
    runs-on: macos-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-upgrade]') }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-package-arkiv
          path: release

      - name: Upgrade
        run: release/Install.ps1 -Url "${{ env.SP_URL_ARKIV }}" -Upgrade -CI -Tenant ${{ env.CI_TENANT }} -CertificateBase64Encoded ${{ env.CI_CERT_BASE64 }} -ClientId ${{ env.CI_CLIENT_ID }} -SkipTemplate
        shell: powershell
