name: CI (dev)

on:
  push:
    branches: [feat/upgrade-install-script]
    paths:
      - "SharePointFramework/**"
      - "Install/**"
      - "Templates/**"
      - package.json

env:
  SP_URL: "https://puzzlepart.sharepoint.com/sites/pp365"

jobs:
  build_release_package:
    name: Build release package
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set sha_short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Setup Node.js 16.18.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0

      - name: Run Install/Build-Release.ps1 in CI mode
        run: Install/Build-Release.ps1 -CI -SkipBundle
        shell: pwsh

      - uses: actions/upload-artifact@v3
        with:
          name: release-package
          path: release
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

  upgrade:
    needs: build_release_package
    name: Upgrade
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-package
          path: release

      - name: Upgrade
        run: release/Install.ps1 -Url ${{ env.SP_URL }} -Upgrade -CI ${{ secrets.CI_DEV_CREDENTIALS }}
        shell: powershell

  install:
    needs: [build_release_package, upgrade]
    name: Install
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-package
          path: release

      - name: Install
        run: release/Install.ps1 -Url "${{ env.SP_URL }}_${{ needs.build_release_package.outputs.sha_short }}" -Title "Prosjektportalen 365 ${{ needs.build_release_package.outputs.sha_short }}" -CI ${{ secrets.CI_DEV_CREDENTIALS }} -SkipAppPackages -SkipSiteDesign -SkipTaxonomy -SkipSearchConfiguration
        shell: powershell