name: CI (dev)

on:
  push:
    branches: [dev]
    paths:
      - "SharePointFramework/**"
      - "Install/**"
      - "Templates/**"
      - package.json

env:
  SP_URL: "https://puzzlepart.sharepoint.com/sites/pp365"

jobs:
  build_release_package:
    name: Build release package
    runs-on: windows-latest
    steps:
      - name: Checkout Puzzlepart/prosjektportalen365.git
        run: |
          mkdir C:/prosjektportalen365
          git clone --branch dev https://github.com/Puzzlepart/prosjektportalen365.git C:/prosjektportalen365

      - name: Checkout current SHA
        working-directory: C:/prosjektportalen365
        run: git checkout $GITHUB_SHA

      - name: Set sha_short
        id: vars
        working-directory: C:/prosjektportalen365
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - run: Get-PSDrive

      - name: Setup Node.js 12.19.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.0

      - name: Run Install/Build-Release.ps1 in CI mode
        run: C:/prosjektportalen365/Install/Build-Release.ps1 -CI
        shell: powershell

      - uses: actions/upload-artifact@v3
        with:
          name: release-package
          path: C:/prosjektportalen365/release
          retention-days: 3
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

  upgrade:
    needs: build_release_package
    name: Upgrade
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-package
          path: release

      - name: Upgrade
        run: release/Install.ps1 -Url ${{ env.SP_URL }} -Upgrade -CI ${{ secrets.CI_DEV_CREDENTIALS }}
        shell: powershell

  install:
    needs: [build_release_package, upgrade]
    name: Install
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-package
          path: release

      - name: Install
        run: release/Install.ps1 -Url "${{ env.SP_URL }}_${{ needs.build_release_package.outputs.sha_short }}" -Title "Prosjektportalen 365 ${{ needs.build_release_package.outputs.sha_short }}" -CI ${{ secrets.CI_DEV_CREDENTIALS }} -SkipAppPackages -SkipSiteDesign -SkipTaxonomy -SkipSearchConfiguration
        shell: powershell