name: CI (dev)

on:
  push:
    branches: [dev]
    paths:
      - "SharePointFramework/**"
      - "Install/**"
      - "Templates/**"
      - package.json

env:
  SP_URL: "https://puzzlepart.sharepoint.com/sites/pp365"
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - name: Checkout Puzzlepart/prosjektportalen365.git
        run: |
          mkdir C:/prosjektportalen365
          git clone https://github.com/Puzzlepart/prosjektportalen365.git C:/prosjektportalen365 --depth 1
        
      - run: Get-PSDrive

      - name: Setup Node.js 12.19.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.0

      - name: Run Install/Build-Release.ps1 in CI mode
        run: Install/Build-Release.ps1 -CI
        shell: powershell
        working-directory: C:/prosjektportalen365

      - uses: actions/upload-artifact@v3
        working-directory: C:/prosjektportalen365
        with:
          name: release-package
          path: release
          retention-days: 3

  upgrade:
    needs: build-release
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: release-package

      - name: Upgrade
        run: release-package/Install.ps1 -Url ${{ env.SP_URL }} -Upgrade -CI ${{ secrets.CI_DEV_CREDENTIALS }}
        shell: powershell

      - name: Slack notify
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'action-slack',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} succeeded in ${process.env.AS_TOOK}. ${{ env.SP_URL }} have been upgraded with the latest goodies from the dev branch.`,
              }]
            }

  install:
    needs: [build-release, upgrade]
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: release-package

      - name: Install
        run: release-package/Install.ps1 -Url "${{ env.SP_URL }}_${{ github.run_id }}" -Title "Prosjektportalen 365 ${{ github.run_id }}" -CI ${{ secrets.CI_DEV_CREDENTIALS }} -SkipAppPackages -SkipSiteDesign -SkipTaxonomy -SkipSearchConfiguration
        shell: powershell

      - name: Slack notify
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'action-slack',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} succeeded in ${process.env.AS_TOOK}. A fresh install of Prosjektportalen 365 is ready at ${{ env.SP_URL }}_${{ github.run_id }}.`,
              }]
            }
