name: Package SharePoint Framework
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - releases/*
    paths:
      - SharePointFramework/**
      - .github/workflows/pr-package-spfx-dev.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose --production