name: Package SharePoint Framework
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - dev
jobs:
  build_shared:
    name: Build @Shared
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}_build_shared
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Install npm packages
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm ci --no-audit --no-fund --loglevel=error

      - name: Run npm run-script build
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm run-script build

      - name: Run npm run-script lint
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm run-script lint
  
  package_portfolioextensions:
    name: Package PortfolioExtensions
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}_package_portfolioextensions
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Install npm packages
        working-directory: ./SharePointFramework/PortfolioExtensions
        run: |
          npm ci --no-audit --no-fund --loglevel=error

      - name: Run npm run-script package:ci
        working-directory: ./SharePointFramework/PortfolioExtensions
        run: |
          npm run package:ci

      - name: Run npm run-script lint
        working-directory: ./SharePointFramework/PortfolioExtensions
        run: |
          npm run-script lint

  package_portfoliowebparts:
    name: Package PortfolioWebParts
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}_package_portfoliowebparts
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Install npm packages
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm ci --no-audit --no-fund --loglevel=error

      - name: Run npm run-script package:ci
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm run-script package:ci

      - name: Run npm run-script lint
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm run-script lint

  package_programwebparts:
    name: Package ProgramWebParts
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}_package_programwebparts
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Install npm packages
        working-directory: ./SharePointFramework/ProgramWebParts
        run: |
          npm ci --no-audit --no-fund --loglevel=error

      - name: Run npm run-script package:ci
        working-directory: ./SharePointFramework/ProgramWebParts
        run: |
          npm run-script package:ci

      - name: Run npm run-script lint
        working-directory: ./SharePointFramework/ProgramWebParts
        run: |
          npm run-script lint

  package_projectextensions:
    name: Package ProjectExtensions
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}_package_projectextensions
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Install npm packages
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm ci --no-audit --no-fund --loglevel=error

      - name: Run npm run-script package:ci
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm run package:ci

      - name: Run npm run-script lint
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm run-script lint

  package_projectwebparts:
    name: Package ProjectWebParts
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}_package_projectwebparts
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Install npm packages
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm ci --no-audit --no-fund --loglevel=error

      - name: Run npm run-script package:ci
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm run-script package:ci

      - name: Run npm run-script lint
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm run-script lint
