name: Package SharePoint Framework
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - releases/1.11
    paths:
      - SharePointFramework/**
      - .github/workflows/pr-package-spfx-dev.yml
jobs:
  build:
    name: Rush Install and Rebuild
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}_rush_rebuild
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush Lint
        run: node common/scripts/install-run-rush.js lint
      - name: Rush Rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose