name: Package SharePoint Framework
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - dev
jobs:
  spfx-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
          
      - name: (@Shared) NPM CI
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm ci

      - name: (@Shared) Run npm script build
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm run build

      - name: (@Shared) Run npm script lint
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm run lint     

      - name: (ProjectWebParts) NPM CI
        if: steps.project_webparts_node_modules_cache.outputs.cache-hit != 'true'
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm ci

      - name: (ProjectWebParts) Run npm script package:ci
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm run package:ci

      - name: (ProjectWebParts) Run npm script lint
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm run lint

      - name: (PortfolioWebParts) NPM CI
        if: steps.portfolio_webparts_node_modules_cache.outputs.cache-hit != 'true'
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm ci

      - name: (PortfolioWebParts) Run npm script package:ci
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm run package:ci

      - name: (PortfolioWebParts) Run npm script lint
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm run lint

      - name: (ProjectExtensions) NPM CI
        if: steps.project_extensions_node_modules_cache.outputs.cache-hit != 'true'
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm ci

      - name: (ProjectExtensions) Run npm script package:ci
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm run package:ci

      - name: (ProjectExtensions) Run npm script lint
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm run lint