name: Package SharePoint Framework
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - dev
jobs:
  build-shared:
    name: Build @Shared
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 12.22.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.0

      - name: Install npm packages
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm ci

      - name: Run npm run-script build
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm run-script build

      - name: Run npm run-script lint
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm run-script lint
  
  package-portfolioextensions:
    name: Package PortfolioExtensions
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 12.22.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.0

      - name: Install npm packages
        working-directory: ./SharePointFramework/PortfolioExtensions
        run: |
          npm ci

      - name: Run npm run-script package:ci
        working-directory: ./SharePointFramework/PortfolioExtensions
        run: |
          npm run package:ci

      - name: Run npm run-script lint
        working-directory: ./SharePointFramework/PortfolioExtensions
        run: |
          npm run-script lint

  package-portfoliowebparts:
    name: Package PortfolioWebParts
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 12.22.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.0

      - name: Install npm packages
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm ci

      - name: Run npm run-script package:ci
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm run-script package:ci

      - name: Run npm run-script lint
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm run-script lint

  package-programwebparts:
    name: Package ProgramWebParts
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 12.22.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.0

      - name: Install npm packages
        working-directory: ./SharePointFramework/ProgramWebParts
        run: |
          npm ci

      - name: Run npm run-script package:ci
        working-directory: ./SharePointFramework/ProgramWebParts
        run: |
          npm run-script package:ci

      - name: Run npm run-script lint
        working-directory: ./SharePointFramework/ProgramWebParts
        run: |
          npm run-script lint

  package-projectextensions:
    name: Package ProjectExtensions
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 12.22.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.0

      - name: Install npm packages
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm ci

      - name: Run npm run-script package:ci
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm run package:ci

      - name: Run npm run-script lint
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm run-script lint

  package-projectwebparts:
    name: Package ProjectWebParts
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 12.22.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.0

      - name: Install npm packages
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm ci

      - name: Run npm run-script package:ci
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm run-script package:ci

      - name: Run npm run-script lint
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm run-script lint
