name: Package SharePoint Framework
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - dev
jobs:
  spfx-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js 12.19.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.0

      - name: (@Shared) Install npm packages
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm ci

      - name: (@Shared) Run npm script build
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm run build

      - name: (@Shared) Run npm script lint
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm run lint

      - name: (PortfolioExtensions) Install npm packages
        working-directory: ./SharePointFramework/PortfolioExtensions
        run: |
          npm ci

      - name: (PortfolioExtensions) Run npm script package:ci
        working-directory: ./SharePointFramework/PortfolioExtensions
        run: |
          npm run package:ci

      - name: (PortfolioExtensions) Run npm script lint
        working-directory: ./SharePointFramework/PortfolioExtensions
        run: |
          npm run lint

      - name: (PortfolioWebParts) Install npm packages
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm ci

      - name: (PortfolioWebParts) Run npm script package:ci
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm run package:ci

      - name: (PortfolioWebParts) Run npm script lint
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm run lint

      - name: (ProgramWebParts) Install npm packages
        working-directory: ./SharePointFramework/ProgramWebParts
        run: |
          npm ci

      - name: (ProgramWebParts) Run npm script package:ci
        working-directory: ./SharePointFramework/ProgramWebParts
        run: |
          npm run package:ci

      - name: (ProgramWebParts) Run npm script lint
        working-directory: ./SharePointFramework/ProgramWebParts
        run: |
          npm run lint

      - name: (ProjectExtensions) Install npm packages
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm ci

      - name: (ProjectExtensions) Run npm script package:ci
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm run package:ci

      - name: (ProjectExtensions) Run npm script lint
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm run lint

      - name: (ProjectWebParts) Install npm packages
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm ci

      - name: (ProjectWebParts) Run npm script package:ci
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm run package:ci

      - name: (ProjectWebParts) Run npm script lint
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm run lint
