name: "[Test] Build release"
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - dev
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm packages
        run: |
          npm install --no-progress --loglevel silent --no-shrinkwrap --no-fund
      - name: Build release package
        run: |
          npm run buildReleasePackage
