name: SPFx CICD with CLI for Microsoft 365
on:
  pull_request:
    types: [synchronize]
    branches:
      - dev

jobs:
  spfx-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.22.0]
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: (@Shared) Install npm packages
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm install --no-progress --loglevel silent --no-shrinkwrap --no-fund

      - name: (@Shared) Run npm script build
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm run build

      - name: (@Shared) Run npm script lint
        working-directory: ./SharePointFramework/@Shared
        run: |
          npm run lint
        


      - name: (ProjectWebParts) Install npm packages
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm install --no-progress --loglevel silent --no-shrinkwrap --no-fund

      - name: (ProjectWebParts) Run npm script package
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm run package

      - name: (ProjectWebParts) Run npm script lint
        working-directory: ./SharePointFramework/ProjectWebParts
        run: |
          npm run lint

      - name: (PortfolioWebParts) Install npm packages
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm install --no-progress --loglevel silent --no-shrinkwrap --no-fund

      - name: (PortfolioWebParts) Run npm script package
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm run package

      - name: (PortfolioWebParts) Run npm script lint
        working-directory: ./SharePointFramework/PortfolioWebParts
        run: |
          npm run lint


      - name: (ProjectExtensions) Install npm packages
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm install --no-progress --loglevel silent --no-shrinkwrap --no-fund

      - name: (ProjectExtensions) Run npm script package
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm run package

      - name: (ProjectExtensions) Run npm script lint
        working-directory: ./SharePointFramework/ProjectExtensions
        run: |
          npm run lint
        
  spfx-deploy:
    needs: spfx-package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.22.0]
    
    steps:
    - name: Login to tenant
      uses: pnp/action-cli-login@v2.0.0
      with:
        ADMIN_USERNAME:  ${{ secrets.CI_USERNAME }}
        ADMIN_PASSWORD:  ${{ secrets.CI_PASSWORD }}

    - name: Option 1 - Deploy app to tenant
      uses: pnp/action-cli-deploy@v2.0.0
      with:
        APP_FILE_PATH: SharePointFramework/ProjectWebParts/sharepoint/solution/pp-project-web-parts.sppkg
        SKIP_FEATURE_DEPLOYMENT: true
        OVERWRITE: true